#!/usr/bin/env python3
"""Replace placeholder questions in physics/11 weeks 42-52 (Revision + Mixed Practice).

11 weeks × 25 MCQs = 275 NCERT-aligned revision questions covering the full Class 11 syllabus.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = ROOT / "src" / "data" / "physics-quizzes.json"

QS = {}

# ============ Week 42: Revision – Kinematics (Straight Line + Plane) ============
QS[42] = [
    ("Displacement is a:",
     ["Vector quantity", "Scalar quantity", "Dimensionless", "Always positive"],
     "Vector quantity"),
    ("Distance is always:",
     ["Non-negative scalar", "Vector", "Negative", "Zero"],
     "Non-negative scalar"),
    ("Slope of position-time graph gives:",
     ["Velocity", "Acceleration", "Displacement", "Time"],
     "Velocity"),
    ("Slope of velocity-time graph gives:",
     ["Acceleration", "Displacement", "Velocity", "Momentum"],
     "Acceleration"),
    ("Area under v-t graph gives:",
     ["Displacement", "Acceleration", "Speed", "Time"],
     "Displacement"),
    ("For uniform motion, a-t graph is:",
     ["Horizontal line at zero", "Straight sloped line", "Parabola", "Vertical line"],
     "Horizontal line at zero"),
    ("First equation of motion: v = :",
     ["u + at", "u² + 2as", "s + ut", "at²"],
     "u + at"),
    ("Second equation of motion: s = :",
     ["ut + ½at²", "u + at", "v² - u²", "a/t"],
     "ut + ½at²"),
    ("Third equation of motion: v² = :",
     ["u² + 2as", "u + at", "ut + ½at²", "2as"],
     "u² + 2as"),
    ("A ball dropped from rest falls with acceleration (ignore air resistance):",
     ["g downward", "g upward", "Zero", "Variable"],
     "g downward"),
    ("Time of flight for vertical projection upward with speed u:",
     ["2u/g", "u/g", "u²/g", "u/2g"],
     "2u/g"),
    ("Maximum height of vertical projection: H = :",
     ["u²/(2g)", "u/(2g)", "2u/g", "ug"],
     "u²/(2g)"),
    ("Range of projectile (level ground): R = :",
     ["u² sin(2θ)/g", "u² sinθ/g", "u sin(2θ)/g", "u/g"],
     "u² sin(2θ)/g"),
    ("Maximum range of projectile is achieved at angle:",
     ["45°", "30°", "60°", "90°"],
     "45°"),
    ("Time of flight of projectile: T = :",
     ["2u sinθ/g", "u sinθ/g", "u cosθ/g", "2u cosθ/g"],
     "2u sinθ/g"),
    ("Maximum height of projectile: H = :",
     ["u² sin²θ/(2g)", "u² cos²θ/(2g)", "u sinθ/g", "u²/g"],
     "u² sin²θ/(2g)"),
    ("A projectile's horizontal component of velocity (no air resistance):",
     ["Stays constant", "Increases", "Decreases", "Oscillates"],
     "Stays constant"),
    ("In 2D motion, motion along x and y can be analyzed:",
     ["Independently", "Only together", "Only on straight line", "Randomly"],
     "Independently"),
    ("Relative velocity of A w.r.t. B = v_A - v_B; if both in same direction:",
     ["Subtract magnitudes", "Add magnitudes", "Multiply", "Divide"],
     "Subtract magnitudes"),
    ("A train moving at 20 m/s is passed by a car at 30 m/s same direction. Relative velocity =",
     ["10 m/s", "50 m/s", "30 m/s", "600 m/s"],
     "10 m/s"),
    ("In uniform circular motion, speed:",
     ["Constant, velocity changes", "Changes", "Zero", "Negative"],
     "Constant, velocity changes"),
    ("Centripetal acceleration: a_c = :",
     ["v²/r", "v/r", "vr", "r/v²"],
     "v²/r"),
    ("Instantaneous velocity = limit of:",
     ["Δr/Δt as Δt → 0", "Δr × Δt", "r/t", "average velocity"],
     "Δr/Δt as Δt → 0"),
    ("Dimensions of velocity:",
     ["[LT⁻¹]", "[LT⁻²]", "[L]", "[T]"],
     "[LT⁻¹]"),
    ("A stone is thrown horizontally from a cliff; it reaches ground in time independent of:",
     ["Initial horizontal speed", "Height", "g", "Mass"],
     "Initial horizontal speed"),
]

# ============ Week 43: Revision – Laws of Motion & Friction ============
QS[43] = [
    ("Newton's first law is also called:",
     ["Law of inertia", "Law of momentum", "Law of action-reaction", "Gravitation"],
     "Law of inertia"),
    ("Newton's second law: F = :",
     ["dp/dt", "mv", "ma only at low v", "p/t"],
     "dp/dt"),
    ("Newton's third law is:",
     ["Action-reaction pair equal and opposite", "Inertia principle", "Force = ma", "Gravity"],
     "Action-reaction pair equal and opposite"),
    ("Linear momentum is defined as:",
     ["mv", "ma", "F/m", "mv²"],
     "mv"),
    ("Conservation of momentum holds when:",
     ["Net external force is zero", "System is accelerating", "Friction is present", "Any time"],
     "Net external force is zero"),
    ("A body in equilibrium has:",
     ["Zero net force", "Maximum force", "Variable force", "Zero mass"],
     "Zero net force"),
    ("Coefficient of static friction μ_s vs kinetic friction μ_k:",
     ["μ_s > μ_k", "μ_s < μ_k", "Equal", "Always zero"],
     "μ_s > μ_k"),
    ("Kinetic friction force is:",
     ["μ_k × Normal force", "mg only", "Weight/2", "Zero"],
     "μ_k × Normal force"),
    ("Friction acts:",
     ["Opposite to relative motion or tendency", "Along motion", "Perpendicular to motion only", "Zero always"],
     "Opposite to relative motion or tendency"),
    ("On a horizontal surface with friction, a block moves with constant velocity, so net force is:",
     ["Zero", "Maximum", "Gravity", "Negative"],
     "Zero"),
    ("The angle of friction θ satisfies:",
     ["tanθ = μ", "sinθ = μ", "cosθ = μ", "μ = 1"],
     "tanθ = μ"),
    ("Angle of repose for a block on incline, with μ_s:",
     ["tan⁻¹(μ_s)", "sin⁻¹(μ_s)", "90°", "0°"],
     "tan⁻¹(μ_s)"),
    ("Tension in light string connecting two masses is:",
     ["Same throughout", "Greater on heavier side", "Zero", "Variable"],
     "Same throughout"),
    ("On an incline of angle θ, component of weight along incline is:",
     ["mg sinθ", "mg cosθ", "mg", "mg tanθ"],
     "mg sinθ"),
    ("Normal reaction on incline of angle θ is:",
     ["mg cosθ", "mg sinθ", "mg", "mg/cosθ"],
     "mg cosθ"),
    ("Banking of roads is done to:",
     ["Provide centripetal force without relying on friction", "Reduce speed", "Increase friction", "Protect from wind"],
     "Provide centripetal force without relying on friction"),
    ("On a banked curve (frictionless), v² = :",
     ["rg tanθ", "rg sinθ", "rg/cosθ", "r/g"],
     "rg tanθ"),
    ("A block on rough horizontal surface pulled by 20 N, μ_k = 0.2, m = 5 kg. If a = ? (g=10):",
     ["2 m/s²", "4 m/s²", "6 m/s²", "1 m/s²"],
     "2 m/s²"),
    ("Free body diagram shows:",
     ["All forces on a body", "Only gravity", "Only friction", "Velocity"],
     "All forces on a body"),
    ("Impulse = :",
     ["Change in momentum (F·Δt)", "Force/time", "Mass×velocity²", "Energy"],
     "Change in momentum (F·Δt)"),
    ("SI unit of impulse:",
     ["N·s", "N/s", "J", "W"],
     "N·s"),
    ("Rolling friction is generally:",
     ["Smaller than kinetic friction", "Larger", "Same", "Zero"],
     "Smaller than kinetic friction"),
    ("Friction can be reduced by:",
     ["Polishing and lubrication", "Heating", "Increasing load", "Increasing area"],
     "Polishing and lubrication"),
    ("In a frictionless system, pulling a block needs:",
     ["Net force", "No force to keep it moving", "Unlimited force", "Variable"],
     "No force to keep it moving"),
    ("A bullet of mass 0.01 kg moving at 200 m/s embeds in block of 0.99 kg. Common velocity:",
     ["2 m/s", "20 m/s", "200 m/s", "0.2 m/s"],
     "2 m/s"),
]

# ============ Week 44: Revision – Work, Energy, Power & Collisions ============
QS[44] = [
    ("Work done by constant force F over displacement d (angle θ):",
     ["Fd cosθ", "Fd sinθ", "Fd", "F/d"],
     "Fd cosθ"),
    ("SI unit of work:",
     ["Joule", "Watt", "Newton", "Pascal"],
     "Joule"),
    ("Kinetic energy = :",
     ["½mv²", "mv", "mgh", "ma"],
     "½mv²"),
    ("Work-energy theorem: W_net = :",
     ["ΔKE", "ΔPE", "PE + KE", "F × t"],
     "ΔKE"),
    ("Gravitational PE near Earth's surface:",
     ["mgh", "mh", "½mgh²", "Fg"],
     "mgh"),
    ("Mechanical energy is conserved when:",
     ["Only conservative forces do work", "Friction is present", "External forces act", "Always"],
     "Only conservative forces do work"),
    ("Power = :",
     ["Work/time", "Work × time", "Energy × time", "Force/time"],
     "Work/time"),
    ("SI unit of power:",
     ["Watt", "Joule", "Newton", "Hertz"],
     "Watt"),
    ("1 horsepower ≈ :",
     ["746 W", "1000 W", "100 W", "10000 W"],
     "746 W"),
    ("1 kWh = :",
     ["3.6 × 10⁶ J", "3600 J", "1000 J", "10⁶ J"],
     "3.6 × 10⁶ J"),
    ("Power can be written as P = F·v when:",
     ["Force is along velocity", "Perpendicular", "Zero", "Random"],
     "Force is along velocity"),
    ("Elastic PE stored in a spring: U = :",
     ["½kx²", "kx", "kx²", "mgh"],
     "½kx²"),
    ("An elastic collision conserves:",
     ["Both KE and momentum", "Momentum only", "KE only", "Neither"],
     "Both KE and momentum"),
    ("In a perfectly inelastic collision:",
     ["Objects stick together, momentum conserved", "Separate, KE conserved", "Both conserved", "Nothing conserved"],
     "Objects stick together, momentum conserved"),
    ("For 1D elastic collision between equal masses with one at rest:",
     ["They exchange velocities", "Both stop", "Both continue", "They stick"],
     "They exchange velocities"),
    ("Coefficient of restitution e for elastic collision:",
     ["1", "0", "0.5", "Negative"],
     "1"),
    ("For perfectly inelastic collision, e = :",
     ["0", "1", "0.5", "Infinity"],
     "0"),
    ("A conservative force satisfies:",
     ["Work done in closed loop = 0", "Work always positive", "Depends on path", "Always zero"],
     "Work done in closed loop = 0"),
    ("Friction is a:",
     ["Non-conservative force", "Conservative force", "Gravitational", "Electrical"],
     "Non-conservative force"),
    ("The area under F-x graph gives:",
     ["Work done", "Power", "Energy density", "Impulse"],
     "Work done"),
    ("Power developed by a horse pulling 200 N at 5 m/s steady:",
     ["1000 W", "100 W", "40 W", "10000 W"],
     "1000 W"),
    ("A body of mass 2 kg falls 5 m. KE just before impact (g=10):",
     ["100 J", "50 J", "10 J", "1000 J"],
     "100 J"),
    ("When a ball bounces back with lower speed, the collision is:",
     ["Partially elastic", "Perfectly elastic", "Perfectly inelastic", "None"],
     "Partially elastic"),
    ("In explosion, fragments fly apart. Momentum is conserved if:",
     ["No external force", "External force present", "Always", "Never"],
     "No external force"),
    ("Internal forces between parts of a system can change:",
     ["KE, not total momentum", "Momentum, not KE", "Both", "Neither"],
     "KE, not total momentum"),
]

# ============ Week 45: Revision – Rotational Motion & Gravitation ============
QS[45] = [
    ("Moment of inertia depends on:",
     ["Mass and distribution relative to axis", "Only mass", "Only velocity", "Only force"],
     "Mass and distribution relative to axis"),
    ("MOI of uniform solid sphere about diameter:",
     ["(2/5)MR²", "(2/3)MR²", "MR²", "(1/2)MR²"],
     "(2/5)MR²"),
    ("MOI of thin uniform ring about its axis:",
     ["MR²", "½MR²", "(2/5)MR²", "(1/3)MR²"],
     "MR²"),
    ("MOI of solid disc about its axis:",
     ["½MR²", "MR²", "(2/5)MR²", "(1/3)MR²"],
     "½MR²"),
    ("Rotational KE = :",
     ["½Iω²", "½mv²", "Iω", "mω²"],
     "½Iω²"),
    ("Torque τ = :",
     ["r × F", "F·v", "m·a", "p/t"],
     "r × F"),
    ("Angular momentum L = :",
     ["Iω", "mv", "mω", "F × r"],
     "Iω"),
    ("Conservation of angular momentum holds when:",
     ["Net external torque is zero", "Mass changes", "Friction present", "Always"],
     "Net external torque is zero"),
    ("An ice skater pulls in arms → angular velocity:",
     ["Increases (MOI decreases)", "Decreases", "Unchanged", "Zero"],
     "Increases (MOI decreases)"),
    ("Work done by torque W = :",
     ["τ·θ", "τ/θ", "F·d", "I·ω"],
     "τ·θ"),
    ("Power in rotation P = :",
     ["τω", "τ/ω", "Iω²", "Fω"],
     "τω"),
    ("Rolling without slipping: v_cm = :",
     ["Rω", "R/ω", "R + ω", "Rω²"],
     "Rω"),
    ("Universal law of gravitation: F = :",
     ["Gm₁m₂/r²", "Gm₁m₂/r", "Gm₁m₂·r²", "Gm₁+m₂"],
     "Gm₁m₂/r²"),
    ("Value of G ≈ :",
     ["6.67 × 10⁻¹¹ N·m²/kg²", "9.8", "3 × 10⁸", "1.6 × 10⁻¹⁹"],
     "6.67 × 10⁻¹¹ N·m²/kg²"),
    ("Acceleration due to gravity at Earth's surface ≈ :",
     ["9.8 m/s²", "10 m/s² always exact", "1.6 m/s²", "0"],
     "9.8 m/s²"),
    ("At height h above Earth's surface, g' = :",
     ["g(R/(R+h))²", "g(R+h)/R", "g/h", "g·h"],
     "g(R/(R+h))²"),
    ("Escape velocity from Earth ≈ :",
     ["11.2 km/s", "7.9 km/s", "3×10⁸ m/s", "100 m/s"],
     "11.2 km/s"),
    ("Orbital velocity at Earth's surface ≈ :",
     ["7.9 km/s", "11.2 km/s", "1 km/s", "100 km/s"],
     "7.9 km/s"),
    ("Kepler's 3rd law: T² ∝ :",
     ["a³ (semi-major axis cubed)", "a", "a²", "1/a"],
     "a³ (semi-major axis cubed)"),
    ("A geostationary satellite has period:",
     ["24 hours", "12 hours", "1 hour", "48 hours"],
     "24 hours"),
    ("Gravitational PE between two masses: U = :",
     ["-Gm₁m₂/r", "Gm₁m₂/r", "Gm₁m₂r", "-Gm₁m₂r²"],
     "-Gm₁m₂/r"),
    ("Inside a uniform spherical shell, gravitational field is:",
     ["Zero", "Constant non-zero", "Varies with r", "Infinite"],
     "Zero"),
    ("At the center of Earth, effective g is:",
     ["Zero", "Maximum", "9.8 m/s²", "6.67×10⁻¹¹"],
     "Zero"),
    ("Newton's shell theorem says external gravity of a sphere acts as if mass is at:",
     ["Center", "Surface", "Rim", "Equator"],
     "Center"),
    ("If radius of planet doubles (mass same), g becomes:",
     ["g/4", "2g", "g/2", "4g"],
     "g/4"),
]

# ============ Week 46: Revision – Properties of Solids & Fluids ============
QS[46] = [
    ("Stress has same dimensions as:",
     ["Pressure", "Force", "Energy", "Momentum"],
     "Pressure"),
    ("Strain is:",
     ["Dimensionless", "Pascal", "Newton", "Joule"],
     "Dimensionless"),
    ("Young's modulus Y = :",
     ["Longitudinal stress / longitudinal strain", "Shear stress / shear strain", "Volume stress / volume strain", "Stress × strain"],
     "Longitudinal stress / longitudinal strain"),
    ("SI unit of Y:",
     ["Pa (N/m²)", "N", "m²", "J"],
     "Pa (N/m²)"),
    ("Hooke's law: Stress ∝ :",
     ["Strain (within elastic limit)", "Any strain", "Plastic strain", "Time"],
     "Strain (within elastic limit)"),
    ("Steel is more elastic than rubber because:",
     ["Larger Y for steel → resists deformation more", "Rubber is inelastic", "Steel deforms more", "Rubber has no strain"],
     "Larger Y for steel → resists deformation more"),
    ("Bulk modulus B = :",
     ["-V(dP/dV)", "Y/shear", "F/A", "ρg"],
     "-V(dP/dV)"),
    ("Compressibility = :",
     ["1/B", "B", "B²", "B⁻²"],
     "1/B"),
    ("Poisson's ratio σ = :",
     ["lateral strain / longitudinal strain (both magnitudes)", "shear/volume", "stress/strain", "1 always"],
     "lateral strain / longitudinal strain (both magnitudes)"),
    ("Pressure at depth h in fluid: P = P₀ + :",
     ["ρgh", "ρ/h", "ρh²", "g/h"],
     "ρgh"),
    ("Pascal's law states that pressure applied to enclosed fluid:",
     ["Is transmitted undiminished", "Doubles downward", "Vanishes", "Halves"],
     "Is transmitted undiminished"),
    ("Hydraulic lift uses:",
     ["Pascal's law", "Archimedes", "Bernoulli", "Stokes"],
     "Pascal's law"),
    ("Archimedes' principle: Buoyant force = :",
     ["Weight of displaced fluid", "Weight of object", "Density × g", "Pressure × area"],
     "Weight of displaced fluid"),
    ("An object floats when:",
     ["Density < fluid density", "Density > fluid density", "Equal masses", "Any"],
     "Density < fluid density"),
    ("Viscosity SI unit:",
     ["Pa·s", "N/m", "m²/s", "kg/m³"],
     "Pa·s"),
    ("Bernoulli's equation: P + ½ρv² + ρgh = :",
     ["Constant (along streamline)", "Zero", "ρg", "Infinite"],
     "Constant (along streamline)"),
    ("Venturi meter measures:",
     ["Flow rate of fluid", "Viscosity", "Density", "Temperature"],
     "Flow rate of fluid"),
    ("Lift on aircraft wing is due to:",
     ["Pressure difference from Bernoulli", "Gravity", "Buoyancy", "Friction"],
     "Pressure difference from Bernoulli"),
    ("Stokes' law for sphere in viscous fluid: F = :",
     ["6πηrv", "4πr²", "ρgV", "ηA"],
     "6πηrv"),
    ("Terminal velocity depends on:",
     ["Size, density of sphere and fluid, η", "Time only", "Height only", "Mass only"],
     "Size, density of sphere and fluid, η"),
    ("Surface tension SI unit:",
     ["N/m", "N·m", "Pa", "J/s"],
     "N/m"),
    ("Capillary rise: h = :",
     ["2T cosθ/(ρgr)", "T/(ρg)", "T·ρ·g·r", "2T/ρg"],
     "2T cosθ/(ρgr)"),
    ("Water rises in a capillary because:",
     ["It wets glass (contact angle < 90°)", "It doesn't wet glass", "High viscosity", "High density"],
     "It wets glass (contact angle < 90°)"),
    ("Mercury in a capillary:",
     ["Depresses below reservoir", "Rises above", "Remains same", "Boils"],
     "Depresses below reservoir"),
    ("Reynolds number determines:",
     ["Laminar vs turbulent flow", "Viscosity only", "Buoyancy", "Pressure"],
     "Laminar vs turbulent flow"),
]

# ============ Week 47: Revision – Thermal Properties & Thermodynamics ============
QS[47] = [
    ("Temperature scales: C, F, K relation: T(K) = :",
     ["°C + 273.15", "°C - 273.15", "5/9(°F - 32)", "°F + 32"],
     "°C + 273.15"),
    ("Normal human body temp ≈ :",
     ["37°C", "50°C", "25°C", "100°C"],
     "37°C"),
    ("Coefficient of linear expansion α has units:",
     ["K⁻¹", "K", "m/K", "m²"],
     "K⁻¹"),
    ("Linear expansion: ΔL = :",
     ["L₀ α ΔT", "L₀ ΔT", "αΔT", "L₀/α"],
     "L₀ α ΔT"),
    ("Volume expansion coefficient γ ≈ :",
     ["3α (isotropic)", "α", "α/3", "2α"],
     "3α (isotropic)"),
    ("Water anomaly: max density at:",
     ["4°C", "0°C", "100°C", "-4°C"],
     "4°C"),
    ("Heat required: Q = :",
     ["mcΔT", "m/cΔT", "c/mΔT", "ΔT/(mc)"],
     "mcΔT"),
    ("Specific heat SI unit:",
     ["J/(kg·K)", "kcal", "cal·°C", "J/K"],
     "J/(kg·K)"),
    ("Latent heat of fusion of ice ≈ :",
     ["334 kJ/kg", "540 kJ/kg", "100 kJ/kg", "4.18 J/g"],
     "334 kJ/kg"),
    ("Latent heat of vaporization of water ≈ :",
     ["2260 kJ/kg", "334 kJ/kg", "100 kJ/kg", "4.18 kJ/kg"],
     "2260 kJ/kg"),
    ("Thermal conduction rate: Q/t = :",
     ["kAΔT/L", "kΔT", "A/L", "kAL"],
     "kAΔT/L"),
    ("Radiation rate per unit area (Stefan):",
     ["σT⁴", "σT", "σ/T", "σT²"],
     "σT⁴"),
    ("Wien's law: λ_max·T = :",
     ["Constant b ≈ 2.9×10⁻³ m·K", "Variable", "Zero", "T²"],
     "Constant b ≈ 2.9×10⁻³ m·K"),
    ("A perfect blackbody has emissivity:",
     ["1", "0", "0.5", "Negative"],
     "1"),
    ("Zeroth law of thermodynamics concerns:",
     ["Thermal equilibrium", "Energy conservation", "Entropy", "Temperature scale"],
     "Thermal equilibrium"),
    ("First law of thermodynamics: ΔU = :",
     ["Q - W", "Q + W", "W - Q", "Q/W"],
     "Q - W"),
    ("Isothermal process: ΔT = :",
     ["0", "Variable", "Constant Q", "Constant W"],
     "0"),
    ("Adiabatic process has Q = :",
     ["0", "Variable", "Max", "Constant"],
     "0"),
    ("Second law of thermodynamics states:",
     ["Heat flows spontaneously hot → cold", "Energy is not conserved", "Entropy decreases", "Work creates heat"],
     "Heat flows spontaneously hot → cold"),
    ("Carnot engine efficiency η = :",
     ["1 - T_cold/T_hot", "T_cold/T_hot", "T_hot/T_cold", "1 - T_hot/T_cold"],
     "1 - T_cold/T_hot"),
    ("Carnot cycle consists of:",
     ["2 isothermal + 2 adiabatic", "4 isothermal", "2 isobaric + 2 isochoric", "4 adiabatic"],
     "2 isothermal + 2 adiabatic"),
    ("Entropy change of reversible process: ΔS = :",
     ["Q_rev/T", "Q × T", "T/Q", "Q + T"],
     "Q_rev/T"),
    ("Entropy of universe in irreversible process:",
     ["Increases", "Decreases", "Constant", "Zero"],
     "Increases"),
    ("No engine can be more efficient than:",
     ["Carnot", "Otto", "Diesel", "Rankine"],
     "Carnot"),
    ("Refrigerator coefficient of performance = :",
     ["Q_cold/W", "W/Q_cold", "Q_hot/W", "W/Q_hot"],
     "Q_cold/W"),
]

# ============ Week 48: Revision – Kinetic Theory & Oscillations ============
QS[48] = [
    ("Ideal gas equation: PV = :",
     ["nRT", "nkT", "RT", "RT/n"],
     "nRT"),
    ("R (gas constant) ≈ :",
     ["8.314 J/(mol·K)", "1.38×10⁻²³", "6.02×10²³", "9.8"],
     "8.314 J/(mol·K)"),
    ("Boltzmann constant k = R/N_A ≈ :",
     ["1.38×10⁻²³ J/K", "8.314 J/K", "6.67×10⁻¹¹", "9.8"],
     "1.38×10⁻²³ J/K"),
    ("Avogadro's number N_A ≈ :",
     ["6.02×10²³", "1.38×10⁻²³", "8.314", "9.1×10⁻³¹"],
     "6.02×10²³"),
    ("Average translational KE per molecule = :",
     ["(3/2)kT", "kT", "RT", "(1/2)kT"],
     "(3/2)kT"),
    ("RMS speed of gas molecules = :",
     ["√(3RT/M)", "√(3kT/m)", "Both A and B", "kT/m"],
     "Both A and B"),
    ("DOF for monatomic ideal gas:",
     ["3", "5", "7", "1"],
     "3"),
    ("DOF for diatomic gas at room T:",
     ["5", "3", "7", "2"],
     "5"),
    ("Cv for monatomic gas = :",
     ["(3/2)R", "(5/2)R", "(7/2)R", "R"],
     "(3/2)R"),
    ("Cp - Cv = :",
     ["R (ideal gas)", "2R", "kT", "0"],
     "R (ideal gas)"),
    ("γ = Cp/Cv for monatomic ideal gas = :",
     ["5/3", "7/5", "9/7", "1"],
     "5/3"),
    ("Mean free path λ = :",
     ["1/(√2 n π d²)", "kT/P", "Both expressions (equivalent)", "v/t"],
     "Both expressions (equivalent)"),
    ("SHM acceleration: a = :",
     ["-ω²x", "ω²x", "-ωx", "Constant"],
     "-ω²x"),
    ("Spring-mass time period: T = :",
     ["2π√(m/k)", "2π√(k/m)", "√(m/k)", "π m/k"],
     "2π√(m/k)"),
    ("Simple pendulum period: T = :",
     ["2π√(L/g)", "2π√(g/L)", "L/g", "√L"],
     "2π√(L/g)"),
    ("Total energy of SHM: E = :",
     ["½mω²A²", "½mω²x²", "mω²A", "½kA"],
     "½mω²A²"),
    ("In SHM, KE at displacement x = :",
     ["½mω²(A² - x²)", "½mω²x²", "½mω²A²", "Zero"],
     "½mω²(A² - x²)"),
    ("In SHM, max velocity = :",
     ["ωA", "ω²A", "ωA²", "A/ω"],
     "ωA"),
    ("Damped oscillation amplitude decays:",
     ["Exponentially", "Linearly", "Quadratically", "Doesn't decay"],
     "Exponentially"),
    ("Resonance condition:",
     ["Driving freq ≈ natural freq", "Driving = 0", "Amplitude = 0", "Damping = ∞"],
     "Driving freq ≈ natural freq"),
    ("Forced oscillation steady frequency:",
     ["Driving frequency", "Natural frequency", "Average", "Zero"],
     "Driving frequency"),
    ("Shock absorbers are designed to be:",
     ["Critically damped", "Underdamped", "Overdamped", "Undamped"],
     "Critically damped"),
    ("If two SHMs are in phase, resultant amplitude (equal A each):",
     ["2A", "A", "0", "A√2"],
     "2A"),
    ("Phase difference π between same-A SHMs gives amplitude:",
     ["0", "2A", "A", "A/2"],
     "0"),
    ("For a seconds pendulum, T = :",
     ["2 s", "1 s", "4 s", "0.5 s"],
     "2 s"),
]

# ============ Week 49: Revision – Waves & Sound ============
QS[49] = [
    ("Wave carries:",
     ["Energy and momentum, not matter", "Matter alone", "Momentum only", "Neither"],
     "Energy and momentum, not matter"),
    ("Sound is:",
     ["Longitudinal mechanical wave", "Transverse", "EM", "Gravity wave"],
     "Longitudinal mechanical wave"),
    ("Speed of sound in solid > gas because:",
     ["Higher elasticity dominates", "Higher density dominates", "Lower pressure", "Lower friction"],
     "Higher elasticity dominates"),
    ("Laplace formula: v = :",
     ["√(γP/ρ)", "√(P/ρ)", "√(ρ/P)", "γ/Pρ"],
     "√(γP/ρ)"),
    ("v, f, λ relation:",
     ["v = fλ", "v = f + λ", "v = f/λ", "v = f·λ²"],
     "v = fλ"),
    ("String fixed at both ends, fundamental = :",
     ["v/(2L)", "v/L", "v/(4L)", "2v/L"],
     "v/(2L)"),
    ("Closed organ pipe fundamental = :",
     ["v/(4L)", "v/(2L)", "v/L", "4v/L"],
     "v/(4L)"),
    ("Open organ pipe fundamental = :",
     ["v/(2L)", "v/(4L)", "v/L", "2v/L"],
     "v/(2L)"),
    ("Closed pipe has only:",
     ["Odd harmonics", "Even harmonics", "All", "None"],
     "Odd harmonics"),
    ("Open pipe has:",
     ["All harmonics", "Only odd", "Only even", "None"],
     "All harmonics"),
    ("Node is point of:",
     ["Zero displacement", "Max displacement", "Max velocity", "Random"],
     "Zero displacement"),
    ("Antinode is point of:",
     ["Max displacement", "Zero displacement", "Zero velocity", "Zero KE"],
     "Max displacement"),
    ("Distance between adjacent nodes:",
     ["λ/2", "λ", "λ/4", "2λ"],
     "λ/2"),
    ("Beats frequency = :",
     ["|f₁ - f₂|", "f₁ + f₂", "f₁ × f₂", "f₁/f₂"],
     "|f₁ - f₂|"),
    ("Doppler for approaching source:",
     ["f' > f", "f' < f", "f' = f", "f' = 0"],
     "f' > f"),
    ("Doppler for receding source:",
     ["f' < f", "f' > f", "f' = f", "f' = ∞"],
     "f' < f"),
    ("Red-shift in astronomy indicates:",
     ["Source moving away", "Source approaching", "Stationary", "Source heating"],
     "Source moving away"),
    ("Speed of sound in air at 0°C:",
     ["331 m/s", "1500 m/s", "3×10⁸ m/s", "100 m/s"],
     "331 m/s"),
    ("Audible range humans:",
     ["20 Hz - 20 kHz", "0 - 100 Hz", "1 kHz - 100 kHz", "> 100 kHz"],
     "20 Hz - 20 kHz"),
    ("Ultrasonic uses include:",
     ["Medical imaging and cleaning", "X-ray imaging", "FM radio", "GPS"],
     "Medical imaging and cleaning"),
    ("Intensity of sound ∝ :",
     ["Amplitude squared", "Amplitude", "Frequency only", "Phase"],
     "Amplitude squared"),
    ("Sound level (dB) = :",
     ["10 log₁₀(I/I₀)", "ln(I/I₀)", "I × I₀", "I/I₀"],
     "10 log₁₀(I/I₀)"),
    ("Increase in intensity by 10× corresponds to:",
     ["+10 dB", "+1 dB", "+100 dB", "0 dB"],
     "+10 dB"),
    ("Pitch depends on:",
     ["Frequency", "Amplitude", "Loudness", "Phase"],
     "Frequency"),
    ("Quality (timbre) depends on:",
     ["Harmonic content", "Amplitude only", "Pitch only", "Speed"],
     "Harmonic content"),
]

# ============ Week 50: Mixed Practice – Numerical Problems (Mechanics) ============
QS[50] = [
    ("A car accelerates from rest at 2 m/s² for 5 s. Final velocity:",
     ["10 m/s", "5 m/s", "25 m/s", "2 m/s"],
     "10 m/s"),
    ("A body at rest accelerates at 3 m/s² for 4 s. Distance travelled:",
     ["24 m", "12 m", "48 m", "6 m"],
     "24 m"),
    ("A stone dropped reaches ground in 3 s. Height (g=10):",
     ["45 m", "30 m", "90 m", "15 m"],
     "45 m"),
    ("Projectile launched at 30° with 20 m/s. Time of flight (g=10):",
     ["2 s", "4 s", "1 s", "3 s"],
     "2 s"),
    ("Projectile at 45°, 20 m/s. Range (g=10):",
     ["40 m", "20 m", "80 m", "10 m"],
     "40 m"),
    ("Projectile at 45°, 20 m/s. Max height (g=10):",
     ["10 m", "20 m", "5 m", "40 m"],
     "10 m"),
    ("5 kg at 4 m/s has momentum:",
     ["20 kg·m/s", "9 kg·m/s", "40 kg·m/s", "1 kg·m/s"],
     "20 kg·m/s"),
    ("Force 10 N on 2 kg causes acceleration:",
     ["5 m/s²", "2 m/s²", "20 m/s²", "0.2 m/s²"],
     "5 m/s²"),
    ("Block m=4 kg on rough surface μ=0.25 (g=10). Friction force:",
     ["10 N", "4 N", "40 N", "1 N"],
     "10 N"),
    ("Incline 30°, m=10 kg (g=10). Component along incline:",
     ["50 N", "100 N", "86.6 N", "25 N"],
     "50 N"),
    ("Work done by 10 N force moving 5 m (parallel):",
     ["50 J", "2 J", "15 J", "5 J"],
     "50 J"),
    ("1 kg body at 10 m/s. KE:",
     ["50 J", "10 J", "100 J", "5 J"],
     "50 J"),
    ("Power to lift 20 kg by 5 m in 10 s (g=10):",
     ["100 W", "10 W", "1000 W", "50 W"],
     "100 W"),
    ("Spring k=200 N/m compressed 0.1 m. PE:",
     ["1 J", "20 J", "0.1 J", "10 J"],
     "1 J"),
    ("Ball 2 kg at 5 m/s collides with 3 kg at rest; stick together. Common v:",
     ["2 m/s", "5 m/s", "10 m/s", "0.5 m/s"],
     "2 m/s"),
    ("Solid sphere m=5 kg, R=0.2 m. MOI about diameter:",
     ["0.08 kg·m²", "0.2 kg·m²", "1 kg·m²", "0.02 kg·m²"],
     "0.08 kg·m²"),
    ("Ring of m=2 kg, R=0.5 m. MOI about axis:",
     ["0.5 kg·m²", "1 kg·m²", "0.25 kg·m²", "0.125 kg·m²"],
     "0.5 kg·m²"),
    ("Torque 10 N·m applied 5 s; initial ω=0, I=2 kg·m². Final ω:",
     ["25 rad/s", "2 rad/s", "50 rad/s", "10 rad/s"],
     "25 rad/s"),
    ("Satellite at Earth's radius (g=10, R=6.4×10⁶). Orbital v ≈ :",
     ["8 km/s", "11.2 km/s", "3 km/s", "100 km/s"],
     "8 km/s"),
    ("Escape v from Earth ≈ :",
     ["11.2 km/s", "8 km/s", "3×10⁸ m/s", "5 km/s"],
     "11.2 km/s"),
    ("Pendulum L=1 m (g=10). Period ≈ :",
     ["2π/√10 s", "2π s", "1 s", "10 s"],
     "2π/√10 s"),
    ("Car goes around a banked curve (tanθ = 0.5, r=20 m, g=10). Speed:",
     ["10 m/s", "5 m/s", "20 m/s", "100 m/s"],
     "10 m/s"),
    ("Two 1 kg masses, separated 1 m. Gravitational force:",
     ["6.67×10⁻¹¹ N", "9.8 N", "10⁻⁵ N", "1 N"],
     "6.67×10⁻¹¹ N"),
    ("A 50 kg body on Moon (g_m = 1.6). Weight:",
     ["80 N", "490 N", "50 N", "800 N"],
     "80 N"),
    ("Centripetal force on 2 kg mass at r=1 m, v=5 m/s:",
     ["50 N", "10 N", "5 N", "25 N"],
     "50 N"),
]

# ============ Week 51: Mixed Practice – Numerical Problems (Thermodynamics & Waves) ============
QS[51] = [
    ("A rod of length 1 m heated from 20 to 120°C, α = 10⁻⁵ /K. ΔL = :",
     ["1 mm", "10 cm", "0.1 m", "1 cm"],
     "1 mm"),
    ("Heat to raise 2 kg water from 20 to 70°C (c=4186 J/kg·K):",
     ["4.186×10⁵ J", "1000 J", "10⁶ J", "4186 J"],
     "4.186×10⁵ J"),
    ("Heat to melt 1 kg ice at 0°C (L_f = 334 kJ/kg):",
     ["334 kJ", "100 kJ", "1000 kJ", "4.18 kJ"],
     "334 kJ"),
    ("Carnot engine T_hot=500 K, T_cold=300 K. Efficiency:",
     ["40%", "60%", "100%", "20%"],
     "40%"),
    ("Carnot engine with η=50%, T_cold=300 K. T_hot:",
     ["600 K", "300 K", "450 K", "150 K"],
     "600 K"),
    ("Ideal gas PV=nRT. 1 mol at 300 K, P=10⁵ Pa. V:",
     ["0.025 m³ (≈24.9 L)", "10 m³", "0.1 m³", "1 m³"],
     "0.025 m³ (≈24.9 L)"),
    ("Isothermal compression halves V. Work done on gas (nRT ln2):",
     ["nRT ln2", "-nRT", "nR/T", "Zero"],
     "nRT ln2"),
    ("Monatomic ideal gas, n=1 mol at 300 K. U = (3/2)RT:",
     ["3741 J (≈3.74 kJ)", "1000 J", "8.314 J", "10 kJ"],
     "3741 J (≈3.74 kJ)"),
    ("Cp of monatomic ideal = (5/2)R ≈ :",
     ["20.8 J/(mol·K)", "12.47 J/(mol·K)", "8.314 J/(mol·K)", "30 J/(mol·K)"],
     "20.8 J/(mol·K)"),
    ("Entropy change when 1 kg ice melts at 0°C (L=334 kJ/kg, T=273 K):",
     ["≈1223 J/K", "334 J/K", "273 J/K", "10⁶ J/K"],
     "≈1223 J/K"),
    ("Sound in air at 27°C, γ=1.4, M=28.8 g/mol. v ≈ :",
     ["348 m/s", "331 m/s", "400 m/s", "100 m/s"],
     "348 m/s"),
    ("String L=1 m, tension 100 N, μ=0.01 kg/m. Fundamental:",
     ["50 Hz", "100 Hz", "25 Hz", "10 Hz"],
     "50 Hz"),
    ("Open pipe length 0.5 m, v_sound=340 m/s. Fundamental:",
     ["340 Hz", "170 Hz", "680 Hz", "100 Hz"],
     "340 Hz"),
    ("Closed pipe 0.5 m, v=340. Fundamental:",
     ["170 Hz", "340 Hz", "680 Hz", "100 Hz"],
     "170 Hz"),
    ("Two forks 256 Hz and 260 Hz. Beats/s:",
     ["4", "2", "8", "1"],
     "4"),
    ("Source 500 Hz moving 34 m/s toward stationary observer, v=340. f'=:",
     ["555.6 Hz", "500 Hz", "450 Hz", "340 Hz"],
     "555.6 Hz"),
    ("Source stationary, observer moves 34 m/s toward it. Heard f (source=500, v=340):",
     ["550 Hz", "500 Hz", "450 Hz", "340 Hz"],
     "550 Hz"),
    ("A wave y = 2 sin(4πx - 400πt). Wavelength:",
     ["0.5 m", "4 m", "2π m", "100 m"],
     "0.5 m"),
    ("Same wave: frequency:",
     ["200 Hz", "400 Hz", "π Hz", "2 Hz"],
     "200 Hz"),
    ("Same wave: speed:",
     ["100 m/s", "400 m/s", "2 m/s", "10 m/s"],
     "100 m/s"),
    ("SHM amplitude 5 cm, f=2 Hz. v_max:",
     ["20π cm/s", "10 cm/s", "5π cm/s", "2π cm/s"],
     "20π cm/s"),
    ("Spring k=100 N/m, mass 1 kg. T:",
     ["2π/10 s ≈ 0.628 s", "2π s", "1 s", "0.1 s"],
     "2π/10 s ≈ 0.628 s"),
    ("Seconds pendulum length on Earth (g=9.8):",
     ["≈0.994 m", "1 m exactly", "2 m", "0.5 m"],
     "≈0.994 m"),
    ("Intensity quadrupled → sound level increases by:",
     ["≈6 dB", "2 dB", "10 dB", "1 dB"],
     "≈6 dB"),
    ("Wien's law: λ_max for T=1000 K (b=2.9×10⁻³ m·K):",
     ["2.9 µm", "290 nm", "2.9 mm", "29 nm"],
     "2.9 µm"),
]

# ============ Week 52: Comprehensive Revision – Full Syllabus ============
QS[52] = [
    ("Fundamental SI unit of length:",
     ["metre", "cm", "inch", "foot"],
     "metre"),
    ("Dimensions of force:",
     ["[MLT⁻²]", "[MLT⁻¹]", "[ML²T⁻²]", "[L]"],
     "[MLT⁻²]"),
    ("Significant figures in 0.0024:",
     ["2", "3", "4", "5"],
     "2"),
    ("Instantaneous velocity is:",
     ["dx/dt", "Δx/Δt", "average velocity", "x/t"],
     "dx/dt"),
    ("Uniform circular motion has:",
     ["Centripetal acceleration only", "Tangential acceleration", "Zero acceleration", "Both positive and negative"],
     "Centripetal acceleration only"),
    ("Inertia depends on:",
     ["Mass", "Velocity", "Acceleration", "Force"],
     "Mass"),
    ("Angular momentum: L = Iω conserved if:",
     ["External torque is zero", "Force is zero", "Mass changes", "Never"],
     "External torque is zero"),
    ("Gravitational force is:",
     ["Always attractive", "Repulsive", "Zero at surface", "Constant everywhere"],
     "Always attractive"),
    ("Young's modulus measures:",
     ["Longitudinal elasticity", "Volumetric elasticity", "Shear elasticity", "Density"],
     "Longitudinal elasticity"),
    ("Bernoulli's principle is based on:",
     ["Energy conservation along streamline", "Momentum conservation", "Mass conservation only", "Viscosity"],
     "Energy conservation along streamline"),
    ("First law of thermodynamics is:",
     ["Energy conservation", "Entropy increase", "Zeroth law alternative", "Heat flows from hot to cold"],
     "Energy conservation"),
    ("Second law of thermodynamics implies:",
     ["Heat does not spontaneously flow cold to hot", "Energy is not conserved", "Heat equals work", "Entropy decreases"],
     "Heat does not spontaneously flow cold to hot"),
    ("Ideal gas law: PV = nRT applies to:",
     ["Ideal (low pressure, high T) gases", "All gases exactly", "Solids", "Liquids"],
     "Ideal (low pressure, high T) gases"),
    ("Mean KE ∝ T for ideal gas:",
     ["True (3/2 kT)", "False", "Only at 0 K", "Only for solids"],
     "True (3/2 kT)"),
    ("SHM is motion in which restoring force is:",
     ["Proportional to displacement and oppositely directed", "Constant", "Random", "Zero"],
     "Proportional to displacement and oppositely directed"),
    ("Pendulum's period depends on:",
     ["Length and g", "Mass", "Amplitude (small)", "Colour"],
     "Length and g"),
    ("Sound is a:",
     ["Longitudinal mechanical wave", "Transverse wave", "EM wave", "Gravity wave"],
     "Longitudinal mechanical wave"),
    ("Doppler effect:",
     ["Frequency changes with relative motion", "Frequency unchanged", "Light only", "Mass changes"],
     "Frequency changes with relative motion"),
    ("Resonance in organ pipe:",
     ["Produces maximum amplitude sound", "Destroys sound", "Irrelevant", "Cools the pipe"],
     "Produces maximum amplitude sound"),
    ("Work-energy theorem: W = ΔKE, valid for:",
     ["Any force", "Only conservative", "Only friction", "Never"],
     "Any force"),
    ("Momentum is conserved in:",
     ["Collisions (any type, if no external force)", "Only elastic", "Only inelastic", "Never"],
     "Collisions (any type, if no external force)"),
    ("KE is conserved in:",
     ["Elastic collisions only", "All collisions", "No collisions", "Random"],
     "Elastic collisions only"),
    ("Kepler's second law implies constant:",
     ["Areal velocity", "Speed", "Angular speed", "Tangential velocity"],
     "Areal velocity"),
    ("Geostationary satellite orbit radius (from Earth center):",
     ["≈42,000 km", "6400 km", "1000 km", "400 km"],
     "≈42,000 km"),
    ("Physics is fundamentally about:",
     ["Explaining nature using mathematical laws", "Memorizing facts", "Only experiments", "Only theory"],
     "Explaining nature using mathematical laws"),
]

# ============ validation ============
for wk, qlist in QS.items():
    assert len(qlist) == 25, f"Week {wk}: expected 25, got {len(qlist)}"
    for (q, opts, ans) in qlist:
        assert len(opts) == 4, f"Week {wk} Q='{q}': needs 4 options"
        assert ans in opts, f"Week {wk} Q='{q}': answer '{ans}' not in options {opts}"

# ============ apply to JSON ============
d = json.loads(JSON_PATH.read_text())
grade_11 = d["11"]

replaced = 0
for wk_entry in grade_11:
    wk_num = wk_entry["week"]
    if wk_num in QS:
        new_qs = []
        for i, (q, opts, ans) in enumerate(QS[wk_num], start=1):
            new_qs.append({
                "id": f"p11-w{wk_num}-q{i}",
                "question": q,
                "options": opts,
                "answer": ans,
            })
        wk_entry["questions"] = new_qs
        replaced += len(new_qs)

JSON_PATH.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
print(f"Replaced {replaced} physics/11 placeholder questions across {len(QS)} weeks: {sorted(QS.keys())}")
