"""Batch 3: physics/11 wk24-34 — Solids, Fluids, Thermal, Thermodynamics, KTG. 275 real NCERT MCQs."""
import json
from pathlib import Path

DATA = Path("src/data/physics-quizzes.json")

QS = {
    24: [  # Mechanical Properties of Solids
        ("Stress is defined as:", ["Force per unit area", "Force times area", "Force per unit length", "Change in length"], "Force per unit area"),
        ("SI unit of stress:", ["Pascal (N/m²)", "Newton", "kg/m²", "N·m"], "Pascal (N/m²)"),
        ("Strain is:", ["Change in dimension / original dimension", "Force / area", "Stress / elasticity", "Change in length"], "Change in dimension / original dimension"),
        ("Strain has units of:", ["None (dimensionless)", "Pascal", "Newton", "m/m"], "None (dimensionless)"),
        ("Hooke's law states:", ["Stress is proportional to strain within elastic limit", "F=ma", "PV=constant", "Stress = strain²"], "Stress is proportional to strain within elastic limit"),
        ("Young's modulus is:", ["Longitudinal stress / longitudinal strain", "Shear stress / shear strain", "Volume stress / volume strain", "Force/area"], "Longitudinal stress / longitudinal strain"),
        ("SI unit of Young's modulus:", ["Pascal", "Newton", "kg/m", "N·m"], "Pascal"),
        ("Bulk modulus relates:", ["Pressure change to fractional volume change", "Force to area", "Stress to strain always", "Shear stress to angle"], "Pressure change to fractional volume change"),
        ("Modulus of rigidity (shear modulus) is defined for:", ["Shear strain", "Volumetric strain", "Linear strain", "Torsional"], "Shear strain"),
        ("Poisson's ratio σ lies between:", ["-1 and 0.5", "0 and 1", "-0.5 and 1", "1 and 2"], "-1 and 0.5"),
        ("Material with largest Young's modulus among: steel, copper, rubber:", ["Steel", "Copper", "Rubber", "All same"], "Steel"),
        ("Elastic limit is:", ["Max stress beyond which permanent deformation occurs", "Max force", "Max length", "Breaking point"], "Max stress beyond which permanent deformation occurs"),
        ("Breaking stress depends on:", ["Material only", "Length only", "Area only", "Material and temperature"], "Material and temperature"),
        ("Dimensional formula of stress:", ["[ML⁻¹T⁻²]", "[MLT⁻²]", "[M⁰L⁰T⁰]", "[ML²T⁻²]"], "[ML⁻¹T⁻²]"),
        ("Strain energy per unit volume = :", ["½ × stress × strain", "stress × strain", "½ × F × x", "stress/strain"], "½ × stress × strain"),
        ("A wire of length L, area A, stretched by force F. Extension x = :", ["FL/(AY)", "FA/(LY)", "LY/(FA)", "F/(AYL)"], "FL/(AY)"),
        ("Two wires of same material, one thicker. Same force. Extension:", ["Less in thicker", "More in thicker", "Same", "Zero in thicker"], "Less in thicker"),
        ("Elastic potential energy in stretched wire:", ["½ × stress × strain × volume", "stress × strain × volume", "Force × length", "stress × volume"], "½ × stress × strain × volume"),
        ("Ratio Y:B:η for typical solid:", ["Y > B > η usually", "All equal", "η > B > Y", "Depends"], "Y > B > η usually"),
        ("Compressibility = :", ["1/Bulk modulus", "Bulk modulus", "Young's modulus", "Shear modulus"], "1/Bulk modulus"),
        ("A rubber band is:", ["Less elastic than steel", "More elastic than steel", "Equally elastic", "Not elastic"], "Less elastic than steel"),
        ("Stress-strain curve: yield point lies between:", ["Elastic limit and ultimate stress", "Origin and proportional limit", "Ultimate stress and breaking", "After breaking"], "Elastic limit and ultimate stress"),
        ("Proportional limit is:", ["Max stress where Hooke's law holds", "Breaking stress", "Yield stress", "Ultimate stress"], "Max stress where Hooke's law holds"),
        ("A steel wire (Y=2×10¹¹ Pa), length 2 m, area 10⁻⁶ m², stretched by 0.1 mm. Force:", ["10 N", "100 N", "1 N", "1000 N"], "10 N"),
        ("Young's modulus of a perfectly rigid body is:", ["Infinite", "Zero", "1", "Negative"], "Infinite"),
    ],
    25: [  # Fluids – Pressure, Pascal, Bernoulli
        ("Pressure at depth h in a fluid of density ρ:", ["ρgh", "ρg/h", "ρ/gh", "g·h"], "ρgh"),
        ("SI unit of pressure:", ["Pascal", "Newton", "Torr", "Bar"], "Pascal"),
        ("1 atmosphere equals approximately:", ["1.013 × 10⁵ Pa", "10⁵ Pa", "1000 Pa", "10⁷ Pa"], "1.013 × 10⁵ Pa"),
        ("Pascal's law states:", ["Pressure applied at one point in enclosed fluid transmits equally everywhere", "P = ρgh", "Density is constant", "Flow is laminar"], "Pressure applied at one point in enclosed fluid transmits equally everywhere"),
        ("Hydraulic lift works on:", ["Pascal's law", "Bernoulli's principle", "Archimedes' principle", "Stokes' law"], "Pascal's law"),
        ("Bernoulli's equation:", ["P + ½ρv² + ρgh = const", "P = ρgh", "PV = nRT", "F = ma"], "P + ½ρv² + ρgh = const"),
        ("Bernoulli's principle is based on conservation of:", ["Energy", "Momentum", "Mass", "Pressure"], "Energy"),
        ("In a venturi meter, increased velocity implies:", ["Reduced pressure", "Increased pressure", "Same pressure", "Zero pressure"], "Reduced pressure"),
        ("Aerofoil generates lift because:", ["Faster airflow on top reduces pressure", "Slower airflow on top", "Equal airflow", "No relation to pressure"], "Faster airflow on top reduces pressure"),
        ("Equation of continuity: A₁v₁ = :", ["A₂v₂", "A₂/v₂", "v₂·A₂²", "constant/A₂"], "A₂v₂"),
        ("Equation of continuity is based on:", ["Conservation of mass", "Conservation of energy", "Newton's law", "Stokes' law"], "Conservation of mass"),
        ("Archimedes' principle: buoyant force = :", ["Weight of displaced fluid", "Weight of body", "Density × volume", "Pressure × area"], "Weight of displaced fluid"),
        ("Body floats when:", ["Weight = buoyant force (average density ≤ fluid density)", "Weight > buoyant force", "Weight < 0", "Density same as ground"], "Weight = buoyant force (average density ≤ fluid density)"),
        ("A body weighs 50 N in air and 30 N in water. Upthrust:", ["20 N", "80 N", "50 N", "30 N"], "20 N"),
        ("Pressure of gas in open manometer depends on:", ["Height difference of liquid", "Area of tube", "Length of tube only", "Gravity only"], "Height difference of liquid"),
        ("Gauge pressure is:", ["Absolute - atmospheric", "Atmospheric - absolute", "ρgh only", "Zero always"], "Absolute - atmospheric"),
        ("Pressure of 1 atm in mm of Hg:", ["760 mm", "75 mm", "1000 mm", "100 mm"], "760 mm"),
        ("In a siphon, fluid flows from:", ["Higher to lower level", "Lower to higher", "Both ways", "Not at all"], "Higher to lower level"),
        ("Specific gravity of a body is ratio to:", ["Density of water at 4°C", "Mass of water", "Volume of water", "Weight of air"], "Density of water at 4°C"),
        ("Buoyancy decreases when fluid density:", ["Decreases", "Increases", "Stays same", "No effect"], "Decreases"),
        ("Pressure increases with depth because:", ["Weight of fluid column above increases", "Fluid is denser at depth", "Temperature decreases", "Surface tension"], "Weight of fluid column above increases"),
        ("Torricelli's theorem: v = :", ["√(2gh)", "√(gh)", "2gh", "gh"], "√(2gh)"),
        ("A small hole at depth h has efflux speed:", ["√(2gh)", "2gh", "gh", "√(gh/2)"], "√(2gh)"),
        ("Pressure at depth 10 m in water (ρ=1000, g=10):", ["10⁵ Pa", "10⁴ Pa", "10³ Pa", "10⁶ Pa"], "10⁵ Pa"),
        ("Atmospheric pressure decreases with altitude because:", ["Less air column above", "More gravity", "Less humidity", "Temperature rises"], "Less air column above"),
    ],
    26: [  # Fluids – Viscosity, Stokes, Surface Tension
        ("Viscosity is the property of fluid by which it:", ["Opposes relative motion between layers", "Flows faster", "Transmits pressure", "Floats objects"], "Opposes relative motion between layers"),
        ("SI unit of coefficient of viscosity:", ["Pa·s (or N·s/m²)", "N·m", "kg/m", "m²/s"], "Pa·s (or N·s/m²)"),
        ("CGS unit of viscosity:", ["Poise", "Stokes", "Pascal", "Newton"], "Poise"),
        ("Stokes' law: viscous force on sphere F = :", ["6πηrv", "πηrv", "4πηrv", "2πηrv"], "6πηrv"),
        ("Terminal velocity of sphere: v_t = :", ["(2r²(ρ-σ)g)/(9η)", "(r²ρg)/(9η)", "(2rρg)/η", "η/(r²g)"], "(2r²(ρ-σ)g)/(9η)"),
        ("Reynolds number Re = :", ["ρvD/η", "η/(ρvD)", "ρD/(vη)", "v²D/(ρη)"], "ρvD/η"),
        ("Flow becomes turbulent typically for Re:", ["> ~2000-3000", "< 100", "< 500", "Any value"], "> ~2000-3000"),
        ("Surface tension is due to:", ["Cohesive forces between molecules", "Gravity", "Pressure", "Viscosity"], "Cohesive forces between molecules"),
        ("SI unit of surface tension:", ["N/m", "N·m", "Pa", "J"], "N/m"),
        ("Surface tension of water decreases with:", ["Increased temperature", "Decreased temperature", "Increased pressure", "Any change"], "Increased temperature"),
        ("Capillary rise h = :", ["2T cosθ / (ρgr)", "2T / (ρgr)", "T cosθ / (ρg)", "T/(rρg)"], "2T cosθ / (ρgr)"),
        ("Water rises in capillary because:", ["Adhesion > cohesion, angle of contact acute", "Cohesion > adhesion", "Gravity pushes up", "Pressure is low"], "Adhesion > cohesion, angle of contact acute"),
        ("Mercury in capillary:", ["Depresses (angle > 90°)", "Rises", "Remains same", "Boils"], "Depresses (angle > 90°)"),
        ("Excess pressure inside a soap bubble:", ["4T/r", "2T/r", "T/r", "8T/r"], "4T/r"),
        ("Excess pressure inside a liquid drop:", ["2T/r", "4T/r", "T/r", "8T/r"], "2T/r"),
        ("Surface energy per unit area equals:", ["Surface tension", "Pressure", "Half of pressure", "Twice pressure"], "Surface tension"),
        ("Two drops of radius r combine. New radius:", ["r·2^(1/3)", "2r", "r/2", "r"], "r·2^(1/3)"),
        ("Velocity gradient has units:", ["s⁻¹", "m/s", "m/s²", "s"], "s⁻¹"),
        ("Streamline flow is:", ["Orderly, non-mixing layers", "Turbulent", "Random", "Rotational always"], "Orderly, non-mixing layers"),
        ("Critical velocity is:", ["Speed at which flow becomes turbulent", "Max speed in pipe", "Escape speed", "Zero velocity"], "Speed at which flow becomes turbulent"),
        ("Coefficient of viscosity of honey vs water:", ["Honey higher", "Water higher", "Equal", "Both zero"], "Honey higher"),
        ("A sphere falls in viscous liquid. Initially it accelerates, then:", ["Attains terminal velocity", "Keeps accelerating", "Stops", "Oscillates"], "Attains terminal velocity"),
        ("Rain drops achieve constant velocity due to:", ["Viscous drag balancing gravity", "No gravity", "Buoyancy only", "Electromagnetic force"], "Viscous drag balancing gravity"),
        ("Angle of contact for water-glass is:", ["≈ 0° (acute)", "90°", ">90°", "180°"], "≈ 0° (acute)"),
        ("Soap reduces surface tension of water, hence:", ["Cleans better by wetting fabric", "Increases capillary rise", "Increases tension", "Heats water"], "Cleans better by wetting fabric"),
    ],
    27: [  # Thermal — Temperature, Heat, Expansion
        ("Temperature is measure of:", ["Average KE of molecules", "Total energy", "Pressure", "Mass"], "Average KE of molecules"),
        ("SI unit of temperature:", ["Kelvin", "Celsius", "Fahrenheit", "Rankine"], "Kelvin"),
        ("Absolute zero is:", ["0 K = -273.15°C", "0°C", "0°F", "-100°C"], "0 K = -273.15°C"),
        ("Conversion: °C to K:", ["K = °C + 273.15", "K = °C - 273.15", "K = °C/273", "K = °C × 273"], "K = °C + 273.15"),
        ("°F to °C: C = :", ["(F-32) × 5/9", "(F+32) × 5/9", "F × 9/5 + 32", "F - 32"], "(F-32) × 5/9"),
        ("Heat is a form of:", ["Energy", "Force", "Mass", "Temperature"], "Energy"),
        ("1 calorie equals approximately:", ["4.186 J", "1 J", "10 J", "0.1 J"], "4.186 J"),
        ("Linear expansion coefficient α is defined as:", ["(ΔL/L)/ΔT", "ΔL × ΔT", "L/T", "1/L"], "(ΔL/L)/ΔT"),
        ("Area expansion coefficient β = :", ["2α", "α", "3α", "α²"], "2α"),
        ("Volume expansion coefficient γ = :", ["3α", "α", "2α", "α/3"], "3α"),
        ("Unit of α:", ["K⁻¹ or °C⁻¹", "m/K", "K", "m"], "K⁻¹ or °C⁻¹"),
        ("Anomalous expansion of water: max density at:", ["4°C", "0°C", "100°C", "-4°C"], "4°C"),
        ("A bimetallic strip uses different:", ["Expansion coefficients", "Densities", "Colours", "Weights"], "Expansion coefficients"),
        ("Thermal expansion of solids is generally:", ["Less than liquids and gases", "More than gases", "Same", "Zero"], "Less than liquids and gases"),
        ("Steel bridge has expansion joints for:", ["Thermal expansion/contraction", "Support", "Weight", "Decoration"], "Thermal expansion/contraction"),
        ("Length of rod at T₁ is L₁, at T₂ is L₂ = L₁(1 + α(T₂-T₁)). This assumes:", ["Small ΔT", "Only metals", "T₁ > T₂", "Large strain"], "Small ΔT"),
        ("A metal rod of 1 m expands 1 mm when heated 100°C. α = :", ["10⁻⁵ /°C", "10⁻³ /°C", "10⁻⁴ /°C", "10⁻⁶ /°C"], "10⁻⁵ /°C"),
        ("Thermometer using gas is based on:", ["Variation of pressure or volume with T", "Variation of length", "Color", "Density"], "Variation of pressure or volume with T"),
        ("Celsius and Fahrenheit scales are equal at:", ["-40°", "0°", "100°", "40°"], "-40°"),
        ("Which has higher α: brass or invar?", ["Brass (higher)", "Invar (higher)", "Equal", "Zero both"], "Brass (higher)"),
        ("Mercury is used in thermometers because:", ["Uniform expansion, doesn't wet glass", "Cheap", "Solid", "Red color"], "Uniform expansion, doesn't wet glass"),
        ("Heat absorbed Q = :", ["mcΔT", "mΔT", "cΔT", "m/c"], "mcΔT"),
        ("Heat is transferred from:", ["Hot to cold", "Cold to hot naturally", "Both ways equally", "No direction"], "Hot to cold"),
        ("Celsius and Kelvin differ by:", ["273.15", "100", "32", "0"], "273.15"),
        ("Thermocouple thermometer uses:", ["Seebeck effect", "Peltier effect", "Joule effect", "Ohm's law"], "Seebeck effect"),
    ],
    28: [  # Specific Heat, Calorimetry, Change of State
        ("Specific heat capacity is:", ["Heat to raise 1 kg by 1 K", "Heat to melt 1 kg", "Heat per mole", "Heat per volume"], "Heat to raise 1 kg by 1 K"),
        ("SI unit of specific heat:", ["J/(kg·K)", "J/K", "cal/g", "J"], "J/(kg·K)"),
        ("Specific heat of water (approx):", ["4186 J/(kg·K)", "1000 J/(kg·K)", "100 cal/g·°C", "1 J/(kg·K)"], "4186 J/(kg·K)"),
        ("Molar specific heat is heat for:", ["1 mole by 1 K", "1 gram by 1 K", "1 kg by 1°C", "1 atom"], "1 mole by 1 K"),
        ("Latent heat of fusion is heat to:", ["Change solid to liquid at constant T", "Raise temperature", "Change phase of any material", "Evaporate"], "Change solid to liquid at constant T"),
        ("Latent heat of vaporization of water at 100°C:", ["~2260 J/g", "~336 J/g", "~1 J/g", "~2260 kJ/kg"], "~2260 J/g"),
        ("Latent heat of fusion of ice:", ["~336 J/g", "~2260 J/g", "~100 J/g", "~1000 J/g"], "~336 J/g"),
        ("Principle of calorimetry:", ["Heat lost = heat gained", "Heat is created", "Temperature is constant", "Mass is constant"], "Heat lost = heat gained"),
        ("During change of state, temperature:", ["Remains constant", "Rises", "Falls", "Oscillates"], "Remains constant"),
        ("Heat supplied during melting is used to:", ["Overcome intermolecular forces", "Raise temperature", "Compress", "Ionize"], "Overcome intermolecular forces"),
        ("Triple point of water:", ["273.16 K, 611 Pa", "0°C, 1 atm", "100°C, 1 atm", "0 K, 0 Pa"], "273.16 K, 611 Pa"),
        ("Water has highest specific heat among common substances making it:", ["Good coolant", "Poor coolant", "Good insulator", "Poor heat carrier"], "Good coolant"),
        ("Dulong-Petit law: molar specific heat of solids ≈ :", ["3R", "R", "2R", "3R/2"], "3R"),
        ("When 1 g ice at 0°C mixes with 1 g water at 80°C, final state:", ["All water near 0°C", "Ice remains", "All ice", "Gas"], "All water near 0°C"),
        ("Sublimation is:", ["Solid directly to gas", "Solid to liquid", "Liquid to gas", "Gas to liquid"], "Solid directly to gas"),
        ("Boiling point of water at 1 atm:", ["100°C", "0°C", "4°C", "273 K"], "100°C"),
        ("Freezing point of water at 1 atm:", ["0°C", "100°C", "273 K (same as 0°C)", "Both a and c"], "Both a and c"),
        ("Pressure cooker cooks faster because:", ["Higher pressure raises boiling point", "Lower pressure", "Greater heat capacity", "Lower density"], "Higher pressure raises boiling point"),
        ("100 g water at 20°C needs heat to reach 100°C (c=4200 J/kg·K):", ["33.6 kJ", "336 kJ", "3.36 kJ", "420 J"], "33.6 kJ"),
        ("Critical temperature is T above which gas:", ["Cannot be liquefied by pressure alone", "Boils", "Freezes", "Sublimates"], "Cannot be liquefied by pressure alone"),
        ("Regelation refers to:", ["Ice melting under pressure and refreezing", "Ice sublimation", "Water freezing", "Water boiling"], "Ice melting under pressure and refreezing"),
        ("During evaporation, temperature of remaining liquid:", ["Decreases", "Increases", "Unchanged", "Doubles"], "Decreases"),
        ("Heat capacity depends on:", ["Mass and specific heat", "Density", "Temperature only", "Volume"], "Mass and specific heat"),
        ("Water equivalent of body is:", ["Mass of water with same heat capacity", "Water content", "Density", "Volume of water"], "Mass of water with same heat capacity"),
        ("Two substances of equal mass & same specific heat, heated with same Q:", ["Same ΔT", "Different ΔT", "Depends on colour", "Impossible"], "Same ΔT"),
    ],
    29: [  # Heat Transfer
        ("Conduction occurs mainly in:", ["Solids", "Gases", "Vacuum", "Plasmas only"], "Solids"),
        ("Fourier's law: Q/t = :", ["-kA(dT/dx)", "kA(dT/dt)", "kA/dx", "-dT/dx"], "-kA(dT/dx)"),
        ("k in Fourier's law is:", ["Thermal conductivity", "Specific heat", "Stefan constant", "Boltzmann constant"], "Thermal conductivity"),
        ("Unit of thermal conductivity:", ["W/(m·K)", "J/K", "W/m", "K/m"], "W/(m·K)"),
        ("Convection occurs in:", ["Fluids (liquids and gases)", "Solids only", "Vacuum", "None"], "Fluids (liquids and gases)"),
        ("Convection involves:", ["Bulk motion of fluid", "Random molecular motion", "EM waves", "Particle oscillation"], "Bulk motion of fluid"),
        ("Radiation occurs in:", ["All media including vacuum", "Solids only", "Fluids only", "Plasma only"], "All media including vacuum"),
        ("Stefan-Boltzmann law: P = :", ["σAT⁴", "σAT", "σAT²", "σAT³"], "σAT⁴"),
        ("Stefan-Boltzmann constant σ:", ["5.67 × 10⁻⁸ W/(m²K⁴)", "6.67 × 10⁻¹¹", "1.38 × 10⁻²³", "3 × 10⁸"], "5.67 × 10⁻⁸ W/(m²K⁴)"),
        ("A black body is:", ["Perfect absorber and emitter", "White", "Transparent", "Reflector"], "Perfect absorber and emitter"),
        ("Emissivity e of black body:", ["1", "0", "0.5", "Infinite"], "1"),
        ("Wien's displacement law: λ_max × T = :", ["Constant (2.9×10⁻³ m·K)", "T², variable", "Stefan constant", "Boltzmann const"], "Constant (2.9×10⁻³ m·K)"),
        ("Newton's law of cooling: rate ∝ :", ["Temperature difference", "Temperature", "T⁴", "T²"], "Temperature difference"),
        ("Good conductors are usually:", ["Metals", "Plastics", "Wood", "Ceramics"], "Metals"),
        ("Silver is the best:", ["Thermal conductor", "Insulator", "Radiator", "None"], "Thermal conductor"),
        ("Vacuum flask (thermos) reduces heat loss by:", ["Conduction, convection, and radiation", "Only conduction", "Only radiation", "None"], "Conduction, convection, and radiation"),
        ("Silvered walls in thermos reduce:", ["Radiation", "Conduction", "Convection", "Nothing"], "Radiation"),
        ("Wall of thermos is vacuum to reduce:", ["Conduction and convection", "Radiation only", "Nothing", "Convection only"], "Conduction and convection"),
        ("Heat transfer in a pan on stove is primarily by:", ["Conduction", "Convection", "Radiation", "Sublimation"], "Conduction"),
        ("Heat from Sun reaches Earth by:", ["Radiation", "Conduction", "Convection", "All three"], "Radiation"),
        ("Kirchhoff's law: good absorbers are:", ["Good emitters", "Poor emitters", "Transparent", "Reflective"], "Good emitters"),
        ("A body at 300 K emits maximum power at λ_max ~ :", ["~10 μm (infrared)", "~500 nm (visible)", "~100 nm (UV)", "~1 pm"], "~10 μm (infrared)"),
        ("Greenhouse effect involves:", ["Trapping of IR radiation by atmospheric gases", "Reflection of UV", "Blue light absorption", "Neutron emission"], "Trapping of IR radiation by atmospheric gases"),
        ("Rate of radiation depends on T as:", ["T⁴", "T", "T²", "T³"], "T⁴"),
        ("Convection is absent in:", ["Solids and vacuum", "Liquids", "Gases", "Plasma"], "Solids and vacuum"),
    ],
    30: [  # Thermodynamics — Zeroth, First Law, U, W
        ("Zeroth law of thermodynamics:", ["If A and B each in equilibrium with C, then A and B in equilibrium", "Energy conservation", "Entropy increases", "PV=nRT"], "If A and B each in equilibrium with C, then A and B in equilibrium"),
        ("Zeroth law defines:", ["Temperature", "Entropy", "Enthalpy", "Work"], "Temperature"),
        ("First law of thermodynamics:", ["ΔU = Q - W", "PV = nRT", "ΔS ≥ 0", "F=ma"], "ΔU = Q - W"),
        ("In first law, sign convention: Q positive when:", ["Heat added to system", "Heat leaves system", "System does work", "System compressed"], "Heat added to system"),
        ("W positive (in ΔU=Q-W) when:", ["System does work on surroundings", "Work done on system", "Heat added", "No change"], "System does work on surroundings"),
        ("Internal energy U depends on:", ["State of system", "Path", "Time", "Phase only"], "State of system"),
        ("U is a function of state; Q and W are:", ["Path-dependent", "State-functions too", "Constants", "Zero"], "Path-dependent"),
        ("Work done by gas in isobaric process:", ["PΔV", "ΔU", "nRT", "Zero"], "PΔV"),
        ("Work done in isochoric process:", ["Zero", "PΔV", "nRT ln(V₂/V₁)", "ΔU"], "Zero"),
        ("First law for adiabatic process:", ["ΔU = -W", "ΔU = Q", "Q=0 and ΔU=-W", "W=0"], "Q=0 and ΔU=-W"),
        ("For ideal gas, U depends only on:", ["Temperature", "Pressure", "Volume", "Both P and V"], "Temperature"),
        ("Heat capacity at constant volume C_v = :", ["(dU/dT)_V", "(dQ/dT)_P", "(dU/dV)", "PV"], "(dU/dT)_V"),
        ("Heat capacity at constant pressure C_p = :", ["(dQ/dT)_P = C_v + R", "C_v - R", "C_v", "R"], "(dQ/dT)_P = C_v + R"),
        ("Relation: C_p - C_v = :", ["R (for ideal gas)", "0", "2R", "R/2"], "R (for ideal gas)"),
        ("Specific heat ratio γ = :", ["C_p/C_v", "C_v/C_p", "C_p·C_v", "R"], "C_p/C_v"),
        ("γ for monatomic ideal gas:", ["5/3", "7/5", "4/3", "2"], "5/3"),
        ("γ for diatomic ideal gas:", ["7/5", "5/3", "4/3", "2"], "7/5"),
        ("Unit of internal energy:", ["Joule", "Watt", "Pascal", "Kelvin"], "Joule"),
        ("Perpetual motion machine of first kind violates:", ["First law", "Second law", "Zeroth law", "None"], "First law"),
        ("In isothermal process, ΔU for ideal gas:", ["Zero", "nRT", "PV", "Positive"], "Zero"),
        ("Q in isothermal process equals:", ["W", "ΔU", "0", "U"], "W"),
        ("Work done by ideal gas in isothermal expansion from V₁ to V₂:", ["nRT ln(V₂/V₁)", "PΔV", "nRΔT", "PV"], "nRT ln(V₂/V₁)"),
        ("Extensive properties include:", ["Volume, energy, mass", "Temperature, pressure", "Density", "Temperature only"], "Volume, energy, mass"),
        ("Intensive properties include:", ["Temperature, pressure, density", "Mass, volume", "Energy only", "Entropy"], "Temperature, pressure, density"),
        ("A gas absorbs 200 J heat and does 50 J work. ΔU:", ["150 J", "250 J", "50 J", "200 J"], "150 J"),
    ],
    31: [  # Thermodynamic Processes
        ("Isothermal process: T is constant means:", ["ΔU = 0 (for ideal gas), Q = W", "Q = 0", "W = 0", "P is constant"], "ΔU = 0 (for ideal gas), Q = W"),
        ("Adiabatic process: Q = 0 means:", ["ΔU = -W", "ΔU = Q", "W = 0", "T is constant"], "ΔU = -W"),
        ("Isochoric process: V constant means:", ["W = 0, Q = ΔU", "Q = 0", "T = constant", "P = constant"], "W = 0, Q = ΔU"),
        ("Isobaric process: P constant means:", ["W = PΔV", "V = constant", "Q = 0", "ΔU = 0"], "W = PΔV"),
        ("Adiabatic equation: PV^γ = :", ["Constant", "nRT", "Zero", "Linear in V"], "Constant"),
        ("Isothermal equation: PV = :", ["nRT (constant at const T)", "constant·V²", "nRT²", "γR"], "nRT (constant at const T)"),
        ("In adiabatic expansion, temperature:", ["Decreases", "Increases", "Same", "Oscillates"], "Decreases"),
        ("In adiabatic compression, temperature:", ["Increases", "Decreases", "Same", "Zero"], "Increases"),
        ("Relation TV^(γ-1) = constant applies to:", ["Adiabatic process", "Isothermal", "Isobaric", "Isochoric"], "Adiabatic process"),
        ("Relation T·P^((1-γ)/γ) = constant applies to:", ["Adiabatic", "Isothermal", "Isobaric", "Isochoric"], "Adiabatic"),
        ("Slope of P-V curve: isothermal vs adiabatic:", ["Adiabatic steeper", "Isothermal steeper", "Same", "Adiabatic flat"], "Adiabatic steeper"),
        ("Cyclic process: ΔU = :", ["0", "Q", "W", "nRT"], "0"),
        ("In cyclic process, Q = :", ["W", "ΔU", "0", "nRT"], "W"),
        ("Quasi-static process is:", ["Carried out slowly through equilibrium states", "Fast", "Instantaneous", "Irreversible"], "Carried out slowly through equilibrium states"),
        ("Reversible process requires:", ["Quasi-static, no friction/dissipation", "Fast change", "Irreversibility", "Entropy decrease"], "Quasi-static, no friction/dissipation"),
        ("In free expansion of ideal gas:", ["W=0, Q=0, ΔU=0, T unchanged", "T changes", "PV increases", "All values change"], "W=0, Q=0, ΔU=0, T unchanged"),
        ("For ideal gas in adiabatic: W = :", ["(P₁V₁ - P₂V₂)/(γ-1)", "nRT ln(V₂/V₁)", "PΔV", "nRΔT"], "(P₁V₁ - P₂V₂)/(γ-1)"),
        ("Isothermal process of ideal gas: Work = :", ["nRT ln(V₂/V₁)", "CvΔT", "PV", "ΔU"], "nRT ln(V₂/V₁)"),
        ("Most rapid real gas compressions approximate:", ["Adiabatic", "Isothermal", "Isochoric", "Isobaric"], "Adiabatic"),
        ("In isobaric heating, ΔU = :", ["nC_v ΔT", "nC_p ΔT", "nRΔT", "0"], "nC_v ΔT"),
        ("In isobaric heating, Q = :", ["nC_p ΔT", "nC_v ΔT", "0", "PV"], "nC_p ΔT"),
        ("PV diagram area enclosed in cycle = :", ["Net work done", "Heat added", "ΔU", "Entropy"], "Net work done"),
        ("If cycle runs clockwise on PV diagram:", ["Engine (positive work)", "Refrigerator", "Both", "Neither"], "Engine (positive work)"),
        ("Polytropic process: PV^n = constant where n:", ["Any constant value", "Always γ", "Always 1", "Always 0"], "Any constant value"),
        ("Isothermal: n = ; Adiabatic: n = ; Isobaric: n = ; Isochoric: n = :", ["1; γ; 0; ∞", "0; 1; γ; ∞", "γ; 1; 0; ∞", "1; ∞; 0; γ"], "1; γ; 0; ∞"),
    ],
    32: [  # Second Law, Heat Engines, Carnot
        ("Second law of thermodynamics (Kelvin-Planck):", ["No engine converts 100% heat into work", "Heat flows from hot to cold", "Both a and b", "Energy is conserved"], "Both a and b"),
        ("Clausius statement:", ["Heat cannot flow from cold to hot without external work", "Q=mcΔT", "PV=nRT", "No 100% efficient engine"], "Heat cannot flow from cold to hot without external work"),
        ("Efficiency of heat engine η = :", ["W/Q_hot = 1 - Q_cold/Q_hot", "Q_hot/W", "Q_cold/Q_hot", "W/Q_cold"], "W/Q_hot = 1 - Q_cold/Q_hot"),
        ("Carnot engine efficiency η_Carnot = :", ["1 - T_cold/T_hot", "T_hot/T_cold", "T_cold/T_hot", "T_hot - T_cold"], "1 - T_cold/T_hot"),
        ("Carnot engine operates between two temperatures with:", ["Two isotherms and two adiabatics", "Three isotherms", "Only adiabats", "Only isochoric"], "Two isotherms and two adiabatics"),
        ("Max possible efficiency of engine between T₁ and T₂ (T₂<T₁):", ["(T₁-T₂)/T₁", "T₂/T₁", "T₁/T₂", "100%"], "(T₁-T₂)/T₁"),
        ("A heat engine working between 500 K and 300 K has max efficiency:", ["40%", "60%", "100%", "30%"], "40%"),
        ("Refrigerator COP β = :", ["Q_cold/W", "W/Q_cold", "Q_hot/W", "T_hot/T_cold"], "Q_cold/W"),
        ("Carnot refrigerator COP:", ["T_cold/(T_hot - T_cold)", "T_hot/(T_hot - T_cold)", "(T_hot-T_cold)/T_hot", "T_cold/T_hot"], "T_cold/(T_hot - T_cold)"),
        ("Heat pump COP:", ["T_hot/(T_hot-T_cold)", "T_cold/T_hot", "1-T_cold/T_hot", "W/Q_cold"], "T_hot/(T_hot-T_cold)"),
        ("Perpetual motion machine of second kind violates:", ["Second law", "First law", "Zeroth law", "Newton's laws"], "Second law"),
        ("Entropy change for reversible process ΔS = :", ["∫dQ/T", "Q/T", "Q·T", "dU/dV"], "∫dQ/T"),
        ("In all spontaneous processes, total entropy:", ["Increases", "Decreases", "Constant", "Zero"], "Increases"),
        ("SI unit of entropy:", ["J/K", "K/J", "W/K", "J·K"], "J/K"),
        ("Entropy is a measure of:", ["Disorder", "Energy", "Temperature", "Pressure"], "Disorder"),
        ("Efficiency of actual heat engine compared to Carnot:", ["Less", "More", "Equal", "Double"], "Less"),
        ("Carnot's theorem: all reversible engines between same temperatures have:", ["Same efficiency", "Different efficiencies", "Zero efficiency", "100% efficiency"], "Same efficiency"),
        ("In a reversible cycle, ΔS_universe = :", ["0", "Positive", "Negative", "Infinite"], "0"),
        ("For cyclic process, ΔS_system = :", ["0", "Q/T", "Positive", "Negative"], "0"),
        ("A heat engine takes 1000 J from hot and rejects 600 J to cold. W = :", ["400 J", "600 J", "1000 J", "1600 J"], "400 J"),
        ("η of that engine:", ["40%", "60%", "100%", "25%"], "40%"),
        ("Impossibility of 100% efficient engine is due to:", ["Second law", "First law", "Zeroth law", "Conservation of energy"], "Second law"),
        ("A Carnot engine's working substance can be any:", ["Ideal or real gas (result is universal)", "Only ideal gas", "Only real gas", "Only water"], "Ideal or real gas (result is universal)"),
        ("If T_cold = T_hot, Carnot efficiency:", ["Zero", "1", "0.5", "100%"], "Zero"),
        ("Otto cycle is used in:", ["Petrol engines", "Diesel engines", "Refrigerators", "Steam engines"], "Petrol engines"),
    ],
    33: [  # KTG — Ideal Gas Eq, Gas Laws
        ("Ideal gas equation:", ["PV = nRT", "PV = RT", "P/V = nRT", "PV² = nRT"], "PV = nRT"),
        ("Universal gas constant R value:", ["8.314 J/(mol·K)", "1.38 × 10⁻²³", "6.67 × 10⁻¹¹", "3 × 10⁸"], "8.314 J/(mol·K)"),
        ("Boltzmann constant k_B:", ["1.38 × 10⁻²³ J/K", "6.022 × 10²³", "8.314 J/(mol·K)", "9.8"], "1.38 × 10⁻²³ J/K"),
        ("Avogadro's number N_A:", ["6.022 × 10²³", "8.314", "1.38 × 10⁻²³", "3 × 10⁸"], "6.022 × 10²³"),
        ("R = :", ["N_A · k_B", "N_A / k_B", "k_B / N_A", "1/(N_A·k_B)"], "N_A · k_B"),
        ("Boyle's law: at constant T:", ["PV = constant", "V/T = constant", "P/T = constant", "V = constant"], "PV = constant"),
        ("Charles's law: at constant P:", ["V/T = constant", "PV = constant", "P/T = constant", "V·P = T"], "V/T = constant"),
        ("Gay-Lussac's law: at constant V:", ["P/T = constant", "PV = constant", "V/T = constant", "PT = constant"], "P/T = constant"),
        ("Avogadro's law: at same P and T, equal volumes of gases contain:", ["Equal number of molecules", "Equal mass", "Equal atoms", "Equal density"], "Equal number of molecules"),
        ("Dalton's law of partial pressures:", ["Total P = sum of partial pressures", "P is constant", "P = 1 atm", "P varies linearly"], "Total P = sum of partial pressures"),
        ("At STP, 1 mole of ideal gas occupies:", ["22.4 L", "1 L", "11.2 L", "24 L"], "22.4 L"),
        ("At STP, T and P are:", ["273.15 K and 1 atm", "0 K and 1 atm", "300 K and 1 atm", "273 K and 0.1 atm"], "273.15 K and 1 atm"),
        ("PV = nRT, T is in:", ["Kelvin", "Celsius", "Fahrenheit", "Any unit"], "Kelvin"),
        ("For real gases, ideal gas law holds best at:", ["Low pressure and high temperature", "High pressure and low temperature", "All conditions", "Neither"], "Low pressure and high temperature"),
        ("Van der Waals equation corrects for:", ["Molecular size and intermolecular forces", "Temperature", "Pressure only", "Volume only"], "Molecular size and intermolecular forces"),
        ("Van der Waals equation: (P + a/V²)(V - b) = :", ["nRT (per mole: RT)", "nR", "PV", "constant"], "nRT (per mole: RT)"),
        ("Gas at constant V: if T doubles, P:", ["Doubles", "Halves", "Same", "Quadruples"], "Doubles"),
        ("Gas at constant P: if T doubles, V:", ["Doubles", "Halves", "Same", "Quadruples"], "Doubles"),
        ("Gas at constant T: if V doubles, P:", ["Halves", "Doubles", "Same", "Quadruples"], "Halves"),
        ("n in PV=nRT stands for:", ["Number of moles", "Number of molecules", "Molar mass", "Avogadro's number"], "Number of moles"),
        ("PV = Nk_B T where N is:", ["Number of molecules", "Number of moles", "Molar mass", "Mass"], "Number of molecules"),
        ("Number density n = N/V; then P = :", ["nk_B T", "NT", "V/N", "k_B/T"], "nk_B T"),
        ("Ideal gas molecules exert no force on each other except during:", ["Collisions (instantaneous)", "Free flight", "Always", "Never"], "Collisions (instantaneous)"),
        ("Gas laws imply that at T=0 K:", ["Pressure or volume would be zero (linear extrapolation)", "Gas becomes liquid", "Nothing happens", "Pressure is infinite"], "Pressure or volume would be zero (linear extrapolation)"),
        ("Molar mass M is related by: PV = (m/M)RT, where m is:", ["Mass of gas", "Moles", "Molecules", "Volume"], "Mass of gas"),
    ],
    34: [  # KTG — KE & T, DOF, Cp/Cv
        ("Kinetic theory relates pressure to:", ["Mean squared speed", "Temperature directly only", "Density only", "Volume only"], "Mean squared speed"),
        ("P = (1/3)ρ<v²> where <v²> is:", ["Mean squared speed", "Average speed squared", "RMS speed", "Most probable speed"], "Mean squared speed"),
        ("Average translational KE per molecule at T:", ["(3/2)k_B T", "k_B T", "(1/2)k_B T", "(5/2)k_B T"], "(3/2)k_B T"),
        ("RMS speed v_rms = :", ["√(3k_B T/m)", "√(2k_B T/m)", "√(k_B T/m)", "k_B T/m"], "√(3k_B T/m)"),
        ("v_rms also = :", ["√(3RT/M)", "√(RT/M)", "√(2RT/M)", "RT/M"], "√(3RT/M)"),
        ("Most probable speed v_p = :", ["√(2k_B T/m)", "√(3k_B T/m)", "√(k_B T/m)", "√(8k_B T/(πm))"], "√(2k_B T/m)"),
        ("Mean speed v_avg = :", ["√(8k_B T/(πm))", "√(3k_B T/m)", "√(2k_B T/m)", "k_B T/m"], "√(8k_B T/(πm))"),
        ("Order of speeds: v_p, v_avg, v_rms:", ["v_p < v_avg < v_rms", "v_rms < v_avg < v_p", "All equal", "v_avg > v_rms"], "v_p < v_avg < v_rms"),
        ("Degree of freedom for monatomic gas:", ["3", "5", "6", "7"], "3"),
        ("Degree of freedom for diatomic gas at room T:", ["5 (3 trans + 2 rot)", "3", "7", "6"], "5 (3 trans + 2 rot)"),
        ("Degree of freedom for nonlinear polyatomic gas:", ["6 (3+3)", "5", "7", "3"], "6 (3+3)"),
        ("Energy per molecule per degree of freedom:", ["(1/2)k_B T", "k_B T", "(3/2)k_B T", "R·T"], "(1/2)k_B T"),
        ("Internal energy per mole U = :", ["(f/2)RT", "(3/2)RT", "RT", "(5/2)RT"], "(f/2)RT"),
        ("For monatomic gas, C_v = :", ["(3/2)R", "(5/2)R", "(3)R", "(5/2)R+R"], "(3/2)R"),
        ("For monatomic gas, C_p = :", ["(5/2)R", "(3/2)R", "(7/2)R", "R"], "(5/2)R"),
        ("For diatomic gas at room T, C_v = :", ["(5/2)R", "(3/2)R", "(7/2)R", "R"], "(5/2)R"),
        ("For diatomic gas at room T, γ = :", ["7/5 = 1.4", "5/3", "4/3", "2"], "7/5 = 1.4"),
        ("Law of equipartition of energy says each DOF has energy:", ["(1/2)k_B T", "k_B T", "(3/2)k_B T", "R·T"], "(1/2)k_B T"),
        ("For nonlinear polyatomic gas γ ≈ :", ["4/3", "7/5", "5/3", "2"], "4/3"),
        ("Mean free path λ = :", ["1/(√2 π d² n)", "1/(nd²)", "d/n", "π d² n"], "1/(√2 π d² n)"),
        ("As T increases at constant V, mean free path:", ["Unchanged (for ideal gas at fixed n)", "Increases", "Decreases", "Zero"], "Unchanged (for ideal gas at fixed n)"),
        ("As P increases at constant T, mean free path:", ["Decreases", "Increases", "Unchanged", "Infinite"], "Decreases"),
        ("Brownian motion is due to:", ["Random molecular collisions", "Gravity", "Electromagnetic forces", "Nuclear forces"], "Random molecular collisions"),
        ("If RMS speed is v at T, at 4T it is:", ["2v", "4v", "v/2", "16v"], "2v"),
        ("Temperature is a measure of:", ["Average KE of molecules", "Mass", "Volume", "Density"], "Average KE of molecules"),
    ],
}

def main():
    d = json.loads(DATA.read_text())
    total = 0
    for wk, qlist in QS.items():
        assert len(qlist) == 25, f"Week {wk} has {len(qlist)} questions"
        week_entry = next(w for w in d["11"] if w["week"] == wk)
        new_qs = []
        for q, opts, ans in qlist:
            assert ans in opts, f"Week {wk}: answer '{ans}' not in options"
            new_qs.append({"question": q, "options": opts, "answer": ans})
        week_entry["questions"] = new_qs
        total += 25
    DATA.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
    print(f"Replaced {total} physics/11 placeholder questions across {len(QS)} weeks: {sorted(QS.keys())}")

if __name__ == "__main__":
    main()
