#!/usr/bin/env python3
"""Replace placeholder questions in physics/11 weeks 35-41 (Oscillations + Waves).

7 weeks × 25 MCQs = 175 high-quality NCERT-aligned questions.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = ROOT / "src" / "data" / "physics-quizzes.json"

# QS[week_num] = list of (question, [4 options], correct_answer) tuples
QS = {}

# ============ Week 35: Oscillations - SHM, Displacement, Velocity, Acceleration ============
QS[35] = [
    ("A motion that repeats itself at regular intervals of time is called:",
     ["Periodic motion", "Rotational motion", "Translational motion", "Random motion"],
     "Periodic motion"),
    ("The motion of a particle in SHM is characterized by:",
     ["Constant velocity", "Constant acceleration", "Acceleration ∝ displacement (opposite direction)", "Zero acceleration"],
     "Acceleration ∝ displacement (opposite direction)"),
    ("The general equation of SHM is x(t) = :",
     ["A sin(ωt + φ)", "At + B", "A e^(ωt)", "A/t"],
     "A sin(ωt + φ)"),
    ("In SHM, A denotes:",
     ["Angular frequency", "Amplitude", "Phase", "Period"],
     "Amplitude"),
    ("The angular frequency ω relates to time period T by:",
     ["ω = 2π/T", "ω = T/2π", "ω = πT", "ω = T²"],
     "ω = 2π/T"),
    ("Frequency f and time period T are related by:",
     ["f = 1/T", "f = T", "f = T²", "f = 2T"],
     "f = 1/T"),
    ("The SI unit of angular frequency is:",
     ["rad/s", "Hz", "s", "m/s"],
     "rad/s"),
    ("In SHM, the velocity at displacement x from mean position is v = :",
     ["ω√(A² - x²)", "ωA", "ωx", "ω/A"],
     "ω√(A² - x²)"),
    ("The maximum velocity in SHM occurs at:",
     ["Extreme position", "Mean position", "Quarter amplitude", "Anywhere"],
     "Mean position"),
    ("The maximum velocity v_max in SHM = :",
     ["ωA", "ω²A", "ωA²", "A/ω"],
     "ωA"),
    ("The acceleration in SHM is a = :",
     ["-ω²x", "-ωx", "ω²x", "-x"],
     "-ω²x"),
    ("The maximum acceleration a_max in SHM = :",
     ["ω²A", "ωA", "ω²A²", "A/ω"],
     "ω²A"),
    ("At the mean position in SHM, acceleration is:",
     ["Maximum", "Zero", "Half of maximum", "Infinite"],
     "Zero"),
    ("At extreme positions in SHM, velocity is:",
     ["Maximum", "Zero", "Half of maximum", "Infinite"],
     "Zero"),
    ("The phase (ωt + φ) of SHM determines:",
     ["Amplitude only", "State of the particle at time t", "Time period", "Frequency"],
     "State of the particle at time t"),
    ("In SHM, displacement and acceleration are:",
     ["In same phase", "Out of phase by π", "Out of phase by π/2", "Unrelated"],
     "Out of phase by π"),
    ("In SHM, velocity and displacement differ in phase by:",
     ["0", "π/2", "π", "2π"],
     "π/2"),
    ("SHM is a special case of:",
     ["Uniform circular motion projected on a diameter", "Rotational motion", "Linear motion", "Projectile motion"],
     "Uniform circular motion projected on a diameter"),
    ("If x = A cos(ωt), the particle starts from:",
     ["Mean position", "Extreme position", "Quarter amplitude", "3A/4"],
     "Extreme position"),
    ("If x = A sin(ωt), the particle at t=0 is at:",
     ["Mean position moving towards +A", "Extreme position", "Quarter amplitude", "3A/4"],
     "Mean position moving towards +A"),
    ("The time period T of SHM is independent of:",
     ["Amplitude", "Mass", "Spring constant", "Length"],
     "Amplitude"),
    ("Two SHMs are said to be in phase if their phase difference is:",
     ["0 or 2π", "π", "π/2", "π/4"],
     "0 or 2π"),
    ("The phase constant φ in SHM depends on:",
     ["Initial conditions of motion", "Frequency", "Amplitude", "Mass"],
     "Initial conditions of motion"),
    ("A particle executes SHM with amplitude 5 cm and frequency 2 Hz. Max velocity = :",
     ["20π cm/s", "10 cm/s", "5π cm/s", "2π cm/s"],
     "20π cm/s"),
    ("Dimensions of angular frequency are:",
     ["[T⁻¹]", "[LT⁻¹]", "[T]", "[MLT⁻²]"],
     "[T⁻¹]"),
]

# ============ Week 36: Energy in SHM, Time Period of Spring & Pendulum ============
QS[36] = [
    ("The kinetic energy in SHM at displacement x is:",
     ["½mω²(A² - x²)", "½mω²A²", "½mω²x²", "mω²A²"],
     "½mω²(A² - x²)"),
    ("The potential energy in SHM at displacement x is:",
     ["½mω²x²", "½mω²A²", "½mω²(A² - x²)", "mω²x"],
     "½mω²x²"),
    ("The total mechanical energy in SHM is:",
     ["½mω²A²", "½mω²x²", "mω²A", "zero"],
     "½mω²A²"),
    ("In SHM, total energy is:",
     ["Conserved", "Increasing", "Decreasing", "Zero"],
     "Conserved"),
    ("Maximum KE in SHM occurs at:",
     ["Mean position", "Extreme position", "Quarter amplitude", "Anywhere"],
     "Mean position"),
    ("Maximum PE in SHM occurs at:",
     ["Extreme position", "Mean position", "Quarter amplitude", "Anywhere"],
     "Extreme position"),
    ("At mean position, PE is:",
     ["Zero", "Maximum", "Half of total", "Equal to KE"],
     "Zero"),
    ("At x = A/√2, KE equals:",
     ["PE", "Twice PE", "Half of PE", "Zero"],
     "PE"),
    ("The frequency of KE oscillation in SHM compared to displacement is:",
     ["Double", "Same", "Half", "Quadruple"],
     "Double"),
    ("The time period of a spring-mass system is T = :",
     ["2π√(m/k)", "2π√(k/m)", "π√(m/k)", "√(m/k)"],
     "2π√(m/k)"),
    ("The frequency of a spring-mass system is f = :",
     ["(1/2π)√(k/m)", "2π√(k/m)", "√(k/m)", "(1/2π)√(m/k)"],
     "(1/2π)√(k/m)"),
    ("If mass is doubled in spring-mass system, time period becomes:",
     ["√2 times", "2 times", "½ times", "unchanged"],
     "√2 times"),
    ("If spring constant is quadrupled, time period:",
     ["Halves", "Doubles", "Quadruples", "Unchanged"],
     "Halves"),
    ("Two identical springs in parallel have effective k = :",
     ["2k", "k/2", "k", "4k"],
     "2k"),
    ("Two identical springs in series have effective k = :",
     ["k/2", "2k", "k", "4k"],
     "k/2"),
    ("Time period of simple pendulum T = :",
     ["2π√(L/g)", "2π√(g/L)", "π√(L/g)", "√(L/g)"],
     "2π√(L/g)"),
    ("The period of pendulum is independent of:",
     ["Mass of bob", "Length", "g", "Amplitude for small angles"],
     "Mass of bob"),
    ("If length of pendulum is quadrupled, its time period:",
     ["Doubles", "Halves", "Quadruples", "Unchanged"],
     "Doubles"),
    ("On the Moon (g_moon = g/6), pendulum period compared to Earth:",
     ["√6 times", "6 times", "1/√6 times", "Same"],
     "√6 times"),
    ("A second's pendulum has time period:",
     ["2 s", "1 s", "0.5 s", "4 s"],
     "2 s"),
    ("Length of second's pendulum on Earth ≈ :",
     ["99.4 cm", "100 cm", "50 cm", "25 cm"],
     "99.4 cm"),
    ("A pendulum at equator vs poles:",
     ["Longer period at equator", "Shorter period at equator", "Same period", "Stops"],
     "Longer period at equator"),
    ("The SHM assumption for pendulum requires:",
     ["Small angular displacement", "Large amplitude", "Constant tension", "Frictionless string"],
     "Small angular displacement"),
    ("Spring potential energy at extension x is:",
     ["½kx²", "kx", "kx²", "½k x"],
     "½kx²"),
    ("A 2 kg mass on spring of k = 200 N/m. Frequency ≈ :",
     ["(1/2π) × 10 Hz", "10 Hz", "20 Hz", "2π Hz"],
     "(1/2π) × 10 Hz"),
]

# ============ Week 37: Damped, Forced & Resonance ============
QS[37] = [
    ("Damped oscillations occur when:",
     ["Energy is continuously dissipated", "Energy is conserved", "No friction present", "Amplitude constant"],
     "Energy is continuously dissipated"),
    ("In damped SHM, amplitude decreases with time:",
     ["Exponentially", "Linearly", "Quadratically", "Constantly"],
     "Exponentially"),
    ("The equation of damped SHM is:",
     ["m d²x/dt² + b dx/dt + kx = 0", "m d²x/dt² + kx = 0", "m d²x/dt² = 0", "kx = 0"],
     "m d²x/dt² + b dx/dt + kx = 0"),
    ("The damping constant b has SI units of:",
     ["kg/s", "kg·m/s", "N/m", "m/s"],
     "kg/s"),
    ("In underdamped motion, the system:",
     ["Oscillates with decreasing amplitude", "Returns to equilibrium without oscillating", "Does not move", "Oscillates forever"],
     "Oscillates with decreasing amplitude"),
    ("In critically damped motion:",
     ["System returns to equilibrium in shortest time without oscillation", "Oscillates forever", "Oscillates with increasing amplitude", "Does not move"],
     "System returns to equilibrium in shortest time without oscillation"),
    ("In overdamped motion:",
     ["System returns to equilibrium slowly without oscillation", "Oscillates freely", "Resonates", "Oscillates with decreasing amplitude"],
     "System returns to equilibrium slowly without oscillation"),
    ("A vehicle shock absorber is typically designed to be:",
     ["Critically damped", "Overdamped", "Underdamped", "Undamped"],
     "Critically damped"),
    ("Amplitude of damped oscillator decreases as:",
     ["A₀ e^(-bt/2m)", "A₀/t", "A₀ e^(+bt)", "A₀ t²"],
     "A₀ e^(-bt/2m)"),
    ("Forced oscillations occur when:",
     ["External periodic force is applied", "No external force", "Damping is absent", "System is isolated"],
     "External periodic force is applied"),
    ("In steady-state forced oscillation, frequency = :",
     ["Driving frequency", "Natural frequency", "Sum of both", "Zero"],
     "Driving frequency"),
    ("Resonance occurs when:",
     ["Driving frequency ≈ natural frequency", "Driving frequency = 2× natural", "Driving frequency = 0", "Amplitude = 0"],
     "Driving frequency ≈ natural frequency"),
    ("At resonance, amplitude becomes:",
     ["Maximum", "Minimum", "Zero", "Infinite always"],
     "Maximum"),
    ("Soldiers are asked to break step on bridges to avoid:",
     ["Resonance", "Damping", "Friction", "Weight imbalance"],
     "Resonance"),
    ("The sharpness of resonance depends on:",
     ["Damping", "Amplitude", "Frequency alone", "Phase"],
     "Damping"),
    ("Less damping means:",
     ["Sharper resonance peak", "Flatter peak", "No resonance", "Overdamping"],
     "Sharper resonance peak"),
    ("The quality factor Q of oscillator is:",
     ["ω₀/2γ", "2γ/ω₀", "γ/ω₀", "γω₀"],
     "ω₀/2γ"),
    ("Higher Q means:",
     ["Less damping, longer oscillation", "More damping", "Faster decay", "No oscillation"],
     "Less damping, longer oscillation"),
    ("Pushing a child on swing at the right time illustrates:",
     ["Resonance", "Friction", "Damping", "Gravitation"],
     "Resonance"),
    ("Free oscillations have frequency equal to:",
     ["Natural frequency", "Driving frequency", "Zero", "Infinite"],
     "Natural frequency"),
    ("In a tuning fork held in air, the oscillations are:",
     ["Damped", "Undamped", "Forced resonant", "Simple"],
     "Damped"),
    ("The acoustic resonance of a vibrating string fixed at both ends requires:",
     ["L = nλ/2", "L = nλ", "L = λ/4", "L = 2nλ"],
     "L = nλ/2"),
    ("In resonance tube experiment, air column is adjusted to find:",
     ["Velocity of sound", "Density", "Pressure", "Frequency of tuning fork"],
     "Velocity of sound"),
    ("The Tacoma Narrows bridge collapse is an example of:",
     ["Resonance with wind", "Frictional failure", "Overheating", "Metal fatigue only"],
     "Resonance with wind"),
    ("Musical instruments produce sound by:",
     ["Resonance of vibrating elements", "Random oscillations", "Friction", "Heat emission"],
     "Resonance of vibrating elements"),
]

# ============ Week 38: Waves – Types, Speed of Waves ============
QS[38] = [
    ("A wave is a disturbance that:",
     ["Transfers energy without transferring matter", "Transfers both energy and matter", "Transfers matter only", "Neither"],
     "Transfers energy without transferring matter"),
    ("In a transverse wave, particle motion is:",
     ["Perpendicular to wave propagation", "Parallel to wave propagation", "Circular", "Random"],
     "Perpendicular to wave propagation"),
    ("In a longitudinal wave, particle motion is:",
     ["Parallel to wave propagation", "Perpendicular to propagation", "Circular", "Random"],
     "Parallel to wave propagation"),
    ("Sound waves in air are:",
     ["Longitudinal", "Transverse", "Electromagnetic", "Matter waves"],
     "Longitudinal"),
    ("Light waves are:",
     ["Transverse electromagnetic", "Longitudinal", "Mechanical", "Matter waves"],
     "Transverse electromagnetic"),
    ("Waves on a stretched string are:",
     ["Transverse", "Longitudinal", "Electromagnetic", "None"],
     "Transverse"),
    ("Transverse waves require a medium with:",
     ["Shear elasticity", "Bulk modulus only", "No elasticity", "No mass"],
     "Shear elasticity"),
    ("Transverse waves cannot travel through:",
     ["Liquids/gases (bulk)", "Solids", "Strings", "Membranes"],
     "Liquids/gases (bulk)"),
    ("The SI unit of wavelength is:",
     ["m", "Hz", "m/s", "s"],
     "m"),
    ("The relation between v, f, λ is:",
     ["v = fλ", "v = f/λ", "v = f + λ", "v = f²λ"],
     "v = fλ"),
    ("The speed of transverse wave on a string is v = :",
     ["√(T/μ)", "√(μ/T)", "T × μ", "T + μ"],
     "√(T/μ)"),
    ("μ in the string wave formula is:",
     ["Mass per unit length (linear mass density)", "Tension", "Young's modulus", "Frequency"],
     "Mass per unit length (linear mass density)"),
    ("Speed of sound in air at 0°C is approximately:",
     ["331 m/s", "1500 m/s", "3×10⁸ m/s", "100 m/s"],
     "331 m/s"),
    ("Speed of sound in a solid is generally:",
     ["Highest", "Lowest", "Equal to liquid", "Zero"],
     "Highest"),
    ("Speed of sound v in gas = √(γP/ρ) is:",
     ["Laplace's formula", "Newton's formula", "Doppler's formula", "Bernoulli's"],
     "Laplace's formula"),
    ("Newton's formula for speed of sound is v = :",
     ["√(P/ρ)", "√(γP/ρ)", "√(γρ/P)", "γP/ρ"],
     "√(P/ρ)"),
    ("The ratio γ = Cp/Cv for a diatomic gas is:",
     ["7/5", "5/3", "1", "2"],
     "7/5"),
    ("Speed of sound in air does not depend on:",
     ["Pressure (at constant T)", "Temperature", "Humidity", "Nature of gas"],
     "Pressure (at constant T)"),
    ("Speed of sound in air increases with:",
     ["Increase in temperature", "Decrease in temperature", "Increase in pressure", "Decrease in density"],
     "Increase in temperature"),
    ("At 0°C speed is 331 m/s. At 20°C it is approximately:",
     ["343 m/s", "300 m/s", "400 m/s", "200 m/s"],
     "343 m/s"),
    ("Wave number k is defined as:",
     ["2π/λ", "2πλ", "1/λ", "λ/2π"],
     "2π/λ"),
    ("Equation of a plane progressive wave: y = A sin(kx - ωt). Here ω/k equals:",
     ["Wave speed v", "Amplitude", "Wavelength", "Frequency"],
     "Wave speed v"),
    ("The wave travels in +x direction if the equation is:",
     ["y = A sin(kx - ωt)", "y = A sin(kx + ωt)", "y = A cos(kx)", "y = A"],
     "y = A sin(kx - ωt)"),
    ("The phase velocity of a wave is:",
     ["v = ω/k", "v = k/ω", "v = kω", "v = k + ω"],
     "v = ω/k"),
    ("The intensity of a wave is:",
     ["Energy per unit area per unit time", "Total energy", "Amplitude squared only", "Frequency only"],
     "Energy per unit area per unit time"),
]

# ============ Week 39: Superposition, Standing Waves ============
QS[39] = [
    ("The principle of superposition states that resultant displacement is:",
     ["Sum of individual displacements", "Product of displacements", "Average of displacements", "Maximum of displacements"],
     "Sum of individual displacements"),
    ("Constructive interference occurs when waves are:",
     ["In phase", "Out of phase by π", "Out of phase by π/2", "Unrelated"],
     "In phase"),
    ("Destructive interference occurs when phase difference is:",
     ["π (or odd × π)", "0", "2π", "π/4"],
     "π (or odd × π)"),
    ("In constructive interference, resultant amplitude is:",
     ["A₁ + A₂", "A₁ - A₂", "A₁ × A₂", "Zero"],
     "A₁ + A₂"),
    ("In destructive interference (equal amplitudes), resultant amplitude is:",
     ["Zero", "2A", "A", "A²"],
     "Zero"),
    ("A standing wave is formed by:",
     ["Superposition of two identical waves moving in opposite directions", "One wave only", "Two different-frequency waves", "Wave reflection at infinity"],
     "Superposition of two identical waves moving in opposite directions"),
    ("In a standing wave, a node is:",
     ["Point of zero displacement", "Point of max displacement", "Point of max velocity", "Any point"],
     "Point of zero displacement"),
    ("In a standing wave, an antinode is:",
     ["Point of maximum amplitude", "Point of zero displacement", "Any point", "A moving point"],
     "Point of maximum amplitude"),
    ("Distance between consecutive nodes in a standing wave is:",
     ["λ/2", "λ", "λ/4", "2λ"],
     "λ/2"),
    ("Distance between a node and adjacent antinode is:",
     ["λ/4", "λ/2", "λ", "λ/8"],
     "λ/4"),
    ("Standing waves do NOT transfer:",
     ["Energy", "Amplitude", "Wavelength", "Frequency"],
     "Energy"),
    ("In a string fixed at both ends, ends are:",
     ["Nodes", "Antinodes", "Either", "Neither"],
     "Nodes"),
    ("Fundamental frequency of string fixed at both ends is:",
     ["v/2L", "v/L", "v/4L", "2v/L"],
     "v/2L"),
    ("Harmonics on a string fixed at both ends are:",
     ["All integral multiples of fundamental", "Only odd multiples", "Only even multiples", "None"],
     "All integral multiples of fundamental"),
    ("The nth harmonic frequency is:",
     ["nv/2L", "v/2L", "v/nL", "2nv/L"],
     "nv/2L"),
    ("If tension in string is quadrupled, fundamental frequency:",
     ["Doubles", "Halves", "Quadruples", "Unchanged"],
     "Doubles"),
    ("If linear mass density is quadrupled, frequency:",
     ["Halves", "Doubles", "Quadruples", "Unchanged"],
     "Halves"),
    ("Thicker strings on guitar produce:",
     ["Lower pitch (lower frequency)", "Higher pitch", "Same pitch", "No sound"],
     "Lower pitch (lower frequency)"),
    ("Tightening a string raises its:",
     ["Frequency (pitch)", "Wavelength", "Amplitude", "None"],
     "Frequency (pitch)"),
    ("The equation of a standing wave is y = 2A sin(kx)cos(ωt). Position of nodes satisfies:",
     ["sin(kx) = 0", "cos(ωt) = 0", "sin(kx) = 1", "cos(ωt) = 1"],
     "sin(kx) = 0"),
    ("Energy in standing wave:",
     ["Oscillates between KE and PE, not transmitted", "Travels with wave", "Is zero", "Radiates"],
     "Oscillates between KE and PE, not transmitted"),
    ("Reflection of wave at a fixed end undergoes:",
     ["Phase reversal (π shift)", "No phase change", "Phase change of π/2", "Phase change of 2π"],
     "Phase reversal (π shift)"),
    ("Reflection at a free end undergoes:",
     ["No phase change", "Phase reversal", "Phase change of π/2", "Phase change of 2π"],
     "No phase change"),
    ("Violin, guitar, sitar string vibrations are:",
     ["Standing transverse waves", "Travelling longitudinal", "Damped free", "Electromagnetic"],
     "Standing transverse waves"),
    ("If two waves differ in frequency, their superposition leads to:",
     ["Beats", "Standing waves", "Nothing", "Polarization"],
     "Beats"),
]

# ============ Week 40: Beats, Doppler Effect ============
QS[40] = [
    ("Beats are produced by superposition of two waves of:",
     ["Slightly different frequencies", "Same frequency", "Same amplitude only", "Different directions"],
     "Slightly different frequencies"),
    ("The beat frequency equals:",
     ["|f₁ - f₂|", "f₁ + f₂", "f₁ × f₂", "Average of f₁ and f₂"],
     "|f₁ - f₂|"),
    ("If two tuning forks of 256 Hz and 260 Hz sound together, beats heard = :",
     ["4 per second", "2 per second", "8 per second", "1 per second"],
     "4 per second"),
    ("Beats are audible when beat frequency is:",
     ["Less than about 10 Hz", "Above 20 kHz", "Equal to individual frequencies", "Zero"],
     "Less than about 10 Hz"),
    ("Beats are used to:",
     ["Tune musical instruments", "Measure velocity of light", "Determine density", "None"],
     "Tune musical instruments"),
    ("When beat frequency becomes zero, the two sources are:",
     ["Tuned to same frequency", "Out of tune", "Silent", "Non-interfering"],
     "Tuned to same frequency"),
    ("Doppler effect is the change in:",
     ["Observed frequency due to relative motion", "Amplitude of wave", "Direction of wave", "Speed of light"],
     "Observed frequency due to relative motion"),
    ("Doppler effect occurs with:",
     ["Sound and light waves", "Sound only", "Light only", "Neither"],
     "Sound and light waves"),
    ("When source moves towards stationary observer, observed frequency:",
     ["Increases", "Decreases", "Remains same", "Becomes zero"],
     "Increases"),
    ("When source moves away from stationary observer, observed frequency:",
     ["Decreases", "Increases", "Remains same", "Doubles"],
     "Decreases"),
    ("The Doppler formula for source moving towards stationary observer is:",
     ["f' = f × v/(v - vs)", "f' = f × (v - vs)/v", "f' = f × v/(v + vs)", "f' = f × vs/v"],
     "f' = f × v/(v - vs)"),
    ("The Doppler formula for observer moving towards stationary source is:",
     ["f' = f × (v + vo)/v", "f' = f × v/(v + vo)", "f' = f × (v - vo)/v", "f' = f × vo/v"],
     "f' = f × (v + vo)/v"),
    ("If observer and source both move towards each other:",
     ["f' = f × (v + vo)/(v - vs)", "f' = f × (v - vo)/(v + vs)", "f' = f", "f' = 0"],
     "f' = f × (v + vo)/(v - vs)"),
    ("The Doppler effect is not observed when:",
     ["Motion is perpendicular to line of sight", "Source moves towards observer", "Observer moves towards source", "They move along the same line"],
     "Motion is perpendicular to line of sight"),
    ("Red-shift in astronomy indicates:",
     ["Galaxy is moving away from us", "Galaxy is approaching", "Galaxy is stationary", "Source is heating up"],
     "Galaxy is moving away from us"),
    ("Blue-shift indicates:",
     ["Source approaching observer", "Source receding", "Source stationary", "Absorption"],
     "Source approaching observer"),
    ("SONAR uses Doppler to:",
     ["Measure speed of underwater objects", "Generate sound", "Convert sound to light", "Navigate by GPS"],
     "Measure speed of underwater objects"),
    ("RADAR detecting vehicle speed uses:",
     ["Doppler shift of radio waves", "Reflection only", "Light intensity", "Compass"],
     "Doppler shift of radio waves"),
    ("A source of 500 Hz moves at 34 m/s towards observer (v_sound = 340 m/s). Observed f ≈ :",
     ["555.6 Hz", "500 Hz", "450 Hz", "340 Hz"],
     "555.6 Hz"),
    ("If both source and observer move in same direction with same speed, observed f:",
     ["Equals f", "Greater than f", "Less than f", "Zero"],
     "Equals f"),
    ("Doppler shift is more noticeable when:",
     ["Relative speed is significant fraction of wave speed", "Sources are dim", "Waves are weak", "Distances are large"],
     "Relative speed is significant fraction of wave speed"),
    ("A police siren appears higher pitched when the car:",
     ["Approaches you", "Recedes from you", "Is stationary", "Has siren off"],
     "Approaches you"),
    ("The observed change in frequency in Doppler effect depends on:",
     ["Relative velocity component along line of sight", "Amplitude", "Colour", "Medium density alone"],
     "Relative velocity component along line of sight"),
    ("The expansion of universe is evidenced by Hubble's observation of:",
     ["Cosmological red-shift", "Blue-shift", "Constant frequency", "Absorption lines only"],
     "Cosmological red-shift"),
    ("For Doppler effect in light, the classical formula is modified due to:",
     ["Special relativity", "Gravity", "Thermodynamics", "Quantum effects only"],
     "Special relativity"),
]

# ============ Week 41: Strings & Air Columns ============
QS[41] = [
    ("A closed organ pipe is closed at:",
     ["One end", "Both ends", "Neither end", "Middle"],
     "One end"),
    ("An open organ pipe is open at:",
     ["Both ends", "One end", "Neither end", "Middle"],
     "Both ends"),
    ("Closed end of an organ pipe is a:",
     ["Displacement node / pressure antinode", "Displacement antinode", "Pressure node", "Neither"],
     "Displacement node / pressure antinode"),
    ("Open end of an organ pipe is a:",
     ["Displacement antinode / pressure node", "Displacement node", "Pressure antinode", "Neither"],
     "Displacement antinode / pressure node"),
    ("Fundamental frequency of closed pipe of length L is:",
     ["v/4L", "v/2L", "v/L", "4v/L"],
     "v/4L"),
    ("Fundamental frequency of open pipe of length L is:",
     ["v/2L", "v/4L", "v/L", "2v/L"],
     "v/2L"),
    ("Closed organ pipe supports:",
     ["Only odd harmonics", "Only even harmonics", "All harmonics", "No harmonics"],
     "Only odd harmonics"),
    ("Open organ pipe supports:",
     ["All harmonics", "Only odd", "Only even", "None"],
     "All harmonics"),
    ("The 3rd harmonic of closed pipe has frequency:",
     ["3v/4L", "3v/2L", "v/4L", "v/2L"],
     "3v/4L"),
    ("An open pipe and closed pipe of same length have fundamental ratio:",
     ["2:1 (open:closed)", "1:2", "1:1", "4:1"],
     "2:1 (open:closed)"),
    ("If a closed pipe's length doubles, fundamental frequency:",
     ["Halves", "Doubles", "Quadruples", "Unchanged"],
     "Halves"),
    ("Quality/timbre of sound depends on:",
     ["Presence of harmonics (overtones)", "Loudness only", "Pitch only", "Speed only"],
     "Presence of harmonics (overtones)"),
    ("Loudness of sound depends on:",
     ["Amplitude squared (intensity)", "Frequency only", "Wavelength", "Phase"],
     "Amplitude squared (intensity)"),
    ("Pitch of sound depends on:",
     ["Frequency", "Amplitude", "Phase", "Direction"],
     "Frequency"),
    ("Audible range for humans is approximately:",
     ["20 Hz to 20 kHz", "0 to 100 Hz", "1 kHz to 100 kHz", "100 kHz to 1 MHz"],
     "20 Hz to 20 kHz"),
    ("Ultrasonic waves have frequency:",
     ["Above 20 kHz", "Below 20 Hz", "Between 20 and 20 kHz", "Near zero"],
     "Above 20 kHz"),
    ("Infrasonic waves have frequency:",
     ["Below 20 Hz", "Above 20 kHz", "Between 20 and 20 kHz", "Exactly 10 kHz"],
     "Below 20 Hz"),
    ("End correction in organ pipes arises due to:",
     ["Antinode forming slightly beyond open end", "Temperature effect", "Friction", "Phase lag"],
     "Antinode forming slightly beyond open end"),
    ("For open pipe, effective length = L + 2e where e is:",
     ["End correction per end", "Length of pipe", "Wavelength", "Amplitude"],
     "End correction per end"),
    ("Speed of sound in air at 27°C is approximately:",
     ["348 m/s", "331 m/s", "300 m/s", "400 m/s"],
     "348 m/s"),
    ("A sonometer is used to study:",
     ["Vibrations of stretched strings", "Beats only", "Air columns", "Magnets"],
     "Vibrations of stretched strings"),
    ("The velocity of transverse wave on sonometer wire depends on:",
     ["Tension and linear mass density", "Length only", "Frequency only", "Amplitude"],
     "Tension and linear mass density"),
    ("Resonance tube experiment determines:",
     ["Velocity of sound in air", "Density of water", "Wavelength of light", "Pressure"],
     "Velocity of sound in air"),
    ("In resonance tube, first resonance length L₁ corresponds to:",
     ["λ/4 (approx, with end correction)", "λ/2", "λ", "3λ/4"],
     "λ/4 (approx, with end correction)"),
    ("Second resonance length in resonance tube is approximately:",
     ["3λ/4", "λ/4", "λ/2", "λ"],
     "3λ/4"),
]

# ============ validation ============
for wk, qlist in QS.items():
    assert len(qlist) == 25, f"Week {wk}: expected 25, got {len(qlist)}"
    for (q, opts, ans) in qlist:
        assert len(opts) == 4, f"Week {wk} Q='{q}': needs 4 options"
        assert ans in opts, f"Week {wk} Q='{q}': answer '{ans}' not in options {opts}"

# ============ apply to JSON ============
d = json.loads(JSON_PATH.read_text())
grade_11 = d["11"]

replaced = 0
for wk_entry in grade_11:
    wk_num = wk_entry["week"]
    if wk_num in QS:
        new_qs = []
        for i, (q, opts, ans) in enumerate(QS[wk_num], start=1):
            new_qs.append({
                "id": f"p11-w{wk_num}-q{i}",
                "question": q,
                "options": opts,
                "answer": ans,
            })
        wk_entry["questions"] = new_qs
        replaced += len(new_qs)

JSON_PATH.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
print(f"Replaced {replaced} physics/11 placeholder questions across {len(QS)} weeks: {sorted(QS.keys())}")
