#!/usr/bin/env python3
"""Replace placeholder questions in physics/12 weeks 3-10 (Electrostatics + Current Electricity).

8 weeks × 25 MCQs = 200 NCERT-aligned Class 12 Physics questions.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
JSON_PATH = ROOT / "src" / "data" / "physics-quizzes.json"

QS = {}

# ============ Week 3: Electric Charges and Fields – Gauss's Theorem ============
QS[3] = [
    ("Electric charge is:",
     ["Quantized and conserved", "Only conserved", "Only quantized", "Neither"],
     "Quantized and conserved"),
    ("Elementary charge e ≈ :",
     ["1.6 × 10⁻¹⁹ C", "9.1 × 10⁻³¹ C", "1.67 × 10⁻²⁷ C", "6.62 × 10⁻³⁴ C"],
     "1.6 × 10⁻¹⁹ C"),
    ("Coulomb's law: F = :",
     ["kq₁q₂/r²", "kq₁q₂/r", "q₁q₂/r", "kq₁q₂·r"],
     "kq₁q₂/r²"),
    ("Value of k = 1/(4πε₀) ≈ :",
     ["9 × 10⁹ N·m²/C²", "8.85 × 10⁻¹²", "1.6 × 10⁻¹⁹", "6.67 × 10⁻¹¹"],
     "9 × 10⁹ N·m²/C²"),
    ("Permittivity of free space ε₀ ≈ :",
     ["8.85 × 10⁻¹² C²/(N·m²)", "9 × 10⁹", "1.6 × 10⁻¹⁹", "1"],
     "8.85 × 10⁻¹² C²/(N·m²)"),
    ("Electric field due to point charge: E = :",
     ["kq/r²", "kq/r", "kqr", "q/r²"],
     "kq/r²"),
    ("SI unit of electric field:",
     ["N/C or V/m", "C/N", "Pa", "J"],
     "N/C or V/m"),
    ("Electric field is a:",
     ["Vector", "Scalar", "Tensor", "None"],
     "Vector"),
    ("Electric field lines:",
     ["Begin on +ve charges, end on −ve", "Close on themselves", "Cross each other", "Radiate from electrons"],
     "Begin on +ve charges, end on −ve"),
    ("Electric field lines never:",
     ["Cross each other", "Begin on charge", "Form closed loops", "End on charge"],
     "Cross each other"),
    ("Electric dipole moment: p = :",
     ["q × 2a (for charges ±q separated by 2a)", "q/r", "q + 2a", "kq"],
     "q × 2a (for charges ±q separated by 2a)"),
    ("Field on axis of short dipole at distance r: E = :",
     ["2kp/r³", "kp/r²", "kp/r³", "kp/r"],
     "2kp/r³"),
    ("Field on equator of short dipole: E = :",
     ["kp/r³ (opposite to p)", "2kp/r³", "kp/r²", "kp/r"],
     "kp/r³ (opposite to p)"),
    ("Torque on dipole in field E: τ = :",
     ["p × E", "p + E", "p·E", "pE²"],
     "p × E"),
    ("Dipole in uniform field experiences:",
     ["Torque but zero net force", "Zero torque", "Net force", "Both force and torque"],
     "Torque but zero net force"),
    ("Electric flux Φ = :",
     ["∮E·dA", "∫E", "q/ε₀ always", "E×A"],
     "∮E·dA"),
    ("Gauss's law: ∮E·dA = :",
     ["q_enclosed/ε₀", "q·ε₀", "q/4π", "Zero"],
     "q_enclosed/ε₀"),
    ("Gauss's law holds for:",
     ["Closed surface", "Open surface", "Only spheres", "Only flat surfaces"],
     "Closed surface"),
    ("Field of infinite sheet of charge (surface density σ):",
     ["σ/(2ε₀)", "σ/ε₀", "σ ε₀", "kσ"],
     "σ/(2ε₀)"),
    ("Field of infinite line of charge (linear density λ):",
     ["λ/(2πε₀r)", "λε₀/r", "kλr", "λ/r²"],
     "λ/(2πε₀r)"),
    ("Field inside a conducting sphere (static):",
     ["Zero", "kq/r²", "kq/R²", "Infinite"],
     "Zero"),
    ("Field outside a charged conducting sphere (total charge q):",
     ["kq/r² (as point charge at center)", "Zero", "kq/R²", "kqr"],
     "kq/r² (as point charge at center)"),
    ("Excess charge on a conductor resides:",
     ["On the outer surface", "Uniformly throughout", "At the center", "In layers"],
     "On the outer surface"),
    ("Faraday cage shields interior from external static fields because:",
     ["Induced charges cancel the field inside", "No charges allowed", "Air inside", "Gravity shielding"],
     "Induced charges cancel the field inside"),
    ("The SI unit of charge is the:",
     ["Coulomb", "Ampere", "Volt", "Ohm"],
     "Coulomb"),
]

# ============ Week 4: Electrostatic Potential – Potential & Potential Difference ============
QS[4] = [
    ("Electric potential V at point is:",
     ["Work per unit positive test charge to bring it from ∞", "Force per charge", "Energy×charge", "Field times distance"],
     "Work per unit positive test charge to bring it from ∞"),
    ("SI unit of potential:",
     ["Volt (V)", "N/C", "C", "Pa"],
     "Volt (V)"),
    ("1 V = :",
     ["1 J/C", "1 C/J", "1 N·m", "1 N/C"],
     "1 J/C"),
    ("Potential due to point charge: V = :",
     ["kq/r", "kq/r²", "kqr", "k/qr"],
     "kq/r"),
    ("Potential is a:",
     ["Scalar", "Vector", "Tensor", "Neither"],
     "Scalar"),
    ("Relation between E and V in uniform field:",
     ["E = -dV/dr", "E = V/r always", "V = Er²", "V = E²"],
     "E = -dV/dr"),
    ("In uniform field E over distance d: V = :",
     ["E·d", "E + d", "E/d", "E×d²"],
     "E·d"),
    ("Potential energy of charge q at potential V:",
     ["qV", "qV²", "q/V", "qV/r"],
     "qV"),
    ("PE of two point charges q₁, q₂ at separation r:",
     ["kq₁q₂/r", "kq₁q₂/r²", "kq₁q₂r", "q₁q₂/r²"],
     "kq₁q₂/r"),
    ("Potential at distance r from short dipole (along axis):",
     ["kp/r²", "kp/r³", "kp/r", "kpr"],
     "kp/r²"),
    ("Potential on equatorial plane of dipole:",
     ["Zero", "kp/r²", "kp/r", "kp/r³"],
     "Zero"),
    ("Potential difference between two points: V_B - V_A = :",
     ["-∫E·dr from A to B", "E·r", "∫E·dr", "EA"],
     "-∫E·dr from A to B"),
    ("Work done by electric force on charge q moving from A to B:",
     ["q(V_A - V_B)", "q(V_B - V_A)", "qV_AV_B", "q/V"],
     "q(V_A - V_B)"),
    ("If 1 V potential difference is applied to 1 C charge, work done = :",
     ["1 J", "1 C", "1 V", "1 N"],
     "1 J"),
    ("Electron volt is:",
     ["Energy gained by electron through 1 V = 1.6×10⁻¹⁹ J", "Charge of electron", "1 volt", "1 joule"],
     "Energy gained by electron through 1 V = 1.6×10⁻¹⁹ J"),
    ("1 eV = :",
     ["1.6 × 10⁻¹⁹ J", "1.6 V", "1 J", "9 × 10⁹ J"],
     "1.6 × 10⁻¹⁹ J"),
    ("Potential inside a charged conductor (electrostatic):",
     ["Same as surface (constant)", "Zero", "Varies with r", "Infinite"],
     "Same as surface (constant)"),
    ("Potential due to uniformly charged sphere (total q, radius R) at r > R:",
     ["kq/r", "kq/R", "kqr/R²", "0"],
     "kq/r"),
    ("Potential at surface of charged conducting sphere radius R:",
     ["kq/R", "0", "kq/r", "kq/R²"],
     "kq/R"),
    ("Potential inside uniformly charged sphere (non-conducting) at r < R:",
     ["kq(3R² - r²)/(2R³)", "kq/r", "kq/R", "0"],
     "kq(3R² - r²)/(2R³)"),
    ("Potential gradient has units:",
     ["V/m", "V·m", "N/C (same as E)", "Both V/m and N/C are equivalent"],
     "Both V/m and N/C are equivalent"),
    ("If V is constant in a region, then E is:",
     ["Zero", "Infinite", "Equal to V", "Variable"],
     "Zero"),
    ("Electric potential is positive near:",
     ["Positive charges", "Negative charges", "Neutral charges", "Nothing"],
     "Positive charges"),
    ("If work is done against field, PE of charge:",
     ["Increases", "Decreases", "Unchanged", "Becomes zero"],
     "Increases"),
    ("At infinity, potential is assumed to be:",
     ["Zero", "Infinite", "Negative", "Variable"],
     "Zero"),
]

# ============ Week 5: Electrostatic Potential – Equipotential Surfaces, Capacitors ============
QS[5] = [
    ("An equipotential surface is one on which:",
     ["V is constant", "E is constant", "Both V and E constant", "Neither"],
     "V is constant"),
    ("Electric field is always:",
     ["Perpendicular to equipotential surfaces", "Parallel to them", "Along them", "Random"],
     "Perpendicular to equipotential surfaces"),
    ("Equipotential surfaces for point charge are:",
     ["Concentric spheres", "Parallel planes", "Cylinders", "Random curves"],
     "Concentric spheres"),
    ("Equipotential surfaces for uniform field are:",
     ["Parallel planes", "Spheres", "Cylinders", "Circles"],
     "Parallel planes"),
    ("Work done in moving a charge on equipotential surface:",
     ["Zero", "Positive", "Negative", "Depends on path"],
     "Zero"),
    ("Two equipotential surfaces cannot:",
     ["Intersect each other", "Be parallel", "Close", "Be spherical"],
     "Intersect each other"),
    ("Capacitor stores:",
     ["Charge and electrical energy", "Only current", "Only voltage", "Resistance"],
     "Charge and electrical energy"),
    ("Capacitance C = :",
     ["Q/V", "V/Q", "QV", "Q²V"],
     "Q/V"),
    ("SI unit of capacitance:",
     ["Farad (F)", "Coulomb", "Volt", "Ohm"],
     "Farad (F)"),
    ("1 Farad = :",
     ["1 C/V", "1 V/C", "1 C·V", "1 J/C"],
     "1 C/V"),
    ("Capacitance of parallel-plate capacitor (vacuum): C = :",
     ["ε₀A/d", "A/(ε₀d)", "ε₀·d/A", "4πε₀d"],
     "ε₀A/d"),
    ("If plate area doubles, capacitance:",
     ["Doubles", "Halves", "Unchanged", "Quadruples"],
     "Doubles"),
    ("If plate separation doubles (vacuum), capacitance:",
     ["Halves", "Doubles", "Unchanged", "Quadruples"],
     "Halves"),
    ("Energy stored in capacitor: U = :",
     ["½CV²", "CV", "CV²", "V²/C"],
     "½CV²"),
    ("Also U = :",
     ["Q²/(2C)", "2CV", "CQ²", "C/Q²"],
     "Q²/(2C)"),
    ("For capacitors in series: 1/C = :",
     ["1/C₁ + 1/C₂ + ...", "C₁ + C₂", "C₁C₂", "C₁ - C₂"],
     "1/C₁ + 1/C₂ + ..."),
    ("For capacitors in parallel: C = :",
     ["C₁ + C₂ + ...", "1/C₁ + 1/C₂", "C₁·C₂", "C₁ - C₂"],
     "C₁ + C₂ + ..."),
    ("Series combination of 2 equal capacitors C gives:",
     ["C/2", "2C", "C", "4C"],
     "C/2"),
    ("Parallel combination of 2 equal capacitors C gives:",
     ["2C", "C/2", "C", "4C"],
     "2C"),
    ("Dielectric between plates increases capacitance by factor:",
     ["κ (dielectric constant)", "1/κ", "κ²", "No change"],
     "κ (dielectric constant)"),
    ("With dielectric K, capacitance = :",
     ["κε₀A/d", "ε₀A/d", "Aε₀/κd", "ε₀/Ad"],
     "κε₀A/d"),
    ("Energy density in electric field: u = :",
     ["½ε₀E²", "½E²", "ε₀E", "E²"],
     "½ε₀E²"),
    ("Charge on each capacitor in series is:",
     ["Same", "Different", "Zero", "Sum of all"],
     "Same"),
    ("Voltage across each capacitor in parallel is:",
     ["Same", "Different", "Zero", "Sum of all"],
     "Same"),
    ("In dielectric, E inside material:",
     ["Decreases by factor κ", "Increases", "Unchanged", "Zero"],
     "Decreases by factor κ"),
]

# ============ Week 6: Capacitance – Combinations, Dielectrics, Energy Stored ============
QS[6] = [
    ("A dielectric is inserted to:",
     ["Increase capacitance", "Decrease capacitance", "Remove charge", "Heat the capacitor"],
     "Increase capacitance"),
    ("Dielectric constant of vacuum κ = :",
     ["1", "0", "8.85 × 10⁻¹²", "9 × 10⁹"],
     "1"),
    ("Dielectric constant of water ≈ :",
     ["80", "1", "2", "10"],
     "80"),
    ("Polar dielectrics have:",
     ["Permanent electric dipoles", "No dipoles", "Free electrons", "Free ions"],
     "Permanent electric dipoles"),
    ("Non-polar dielectrics develop:",
     ["Induced dipoles in external field", "Permanent dipoles", "Free charges", "No response"],
     "Induced dipoles in external field"),
    ("Polarization P is:",
     ["Dipole moment per unit volume", "Charge per area", "Force per charge", "Field per charge"],
     "Dipole moment per unit volume"),
    ("Bound charges appear on:",
     ["Dielectric surfaces facing plates", "Conductors only", "Wires", "Air only"],
     "Dielectric surfaces facing plates"),
    ("If charge Q on plates is held constant, inserting dielectric:",
     ["Decreases V and energy", "Increases V", "Unchanged", "Removes charge"],
     "Decreases V and energy"),
    ("If V is held constant, inserting dielectric:",
     ["Increases Q and energy", "Decreases Q", "Unchanged", "Removes voltage"],
     "Increases Q and energy"),
    ("Work done on dielectric when inserted at constant V:",
     ["Negative (it's pulled in)", "Positive (must be pushed)", "Zero", "Infinite"],
     "Negative (it's pulled in)"),
    ("Capacitor of capacitance 2 μF charged to 100 V. Charge = :",
     ["200 μC", "50 μC", "100 μC", "2 μC"],
     "200 μC"),
    ("Same capacitor: Energy stored = :",
     ["0.01 J", "100 J", "200 J", "0.1 J"],
     "0.01 J"),
    ("Two capacitors 2 μF each in series: equivalent capacitance:",
     ["1 μF", "4 μF", "2 μF", "0.5 μF"],
     "1 μF"),
    ("Two capacitors 2 μF each in parallel: equivalent capacitance:",
     ["4 μF", "1 μF", "2 μF", "8 μF"],
     "4 μF"),
    ("Energy conservation on charge sharing between two capacitors:",
     ["Some energy is lost as heat/radiation", "Energy conserved", "Charge not conserved", "Nothing"],
     "Some energy is lost as heat/radiation"),
    ("Van de Graaff generator produces:",
     ["High voltage static electricity", "Current", "Magnetic field", "Heat"],
     "High voltage static electricity"),
    ("Breakdown voltage of air ≈ :",
     ["3 × 10⁶ V/m", "100 V/m", "9 × 10⁹ V/m", "1 V/m"],
     "3 × 10⁶ V/m"),
    ("Applications of capacitors:",
     ["Filter circuits, timing, energy storage", "Resistors replacement", "Magnetic storage", "None"],
     "Filter circuits, timing, energy storage"),
    ("In capacitor circuits, DC cannot pass through a capacitor in:",
     ["Steady state", "Initial state", "Ever", "Always"],
     "Steady state"),
    ("A capacitor acts as:",
     ["Open circuit to DC at steady state", "Short circuit", "Resistor", "Inductor"],
     "Open circuit to DC at steady state"),
    ("Spherical capacitor of inner radius a, outer b: C = :",
     ["4πε₀ ab/(b-a)", "4πε₀(b-a)", "4πε₀/ab", "ε₀/(a+b)"],
     "4πε₀ ab/(b-a)"),
    ("Isolated sphere capacitance: C = :",
     ["4πε₀R", "ε₀/R", "4π R", "R/ε₀"],
     "4πε₀R"),
    ("Cylindrical capacitor (length L, radii a < b): C = :",
     ["2πε₀L / ln(b/a)", "ε₀L ab", "πL/ε₀", "ε₀/ln(b/a)"],
     "2πε₀L / ln(b/a)"),
    ("Increasing dielectric κ by factor 5 (at constant V) increases Q by:",
     ["5", "1/5", "25", "√5"],
     "5"),
    ("A parallel-plate capacitor with area A, separation d, filled with two dielectrics κ₁ and κ₂ in series (each half):",
     ["C = 2ε₀A/(d(1/κ₁ + 1/κ₂))", "C = ε₀A(κ₁+κ₂)/2d", "C = ε₀Aκ₁κ₂/d", "Ambiguous"],
     "C = 2ε₀A/(d(1/κ₁ + 1/κ₂))"),
]

# ============ Week 7: Current Electricity – Ohm's Law, Drift Velocity ============
QS[7] = [
    ("Electric current is defined as:",
     ["Rate of flow of charge", "Charge times time", "Voltage per resistance only", "Charge per volt"],
     "Rate of flow of charge"),
    ("SI unit of current:",
     ["Ampere (A)", "Coulomb", "Volt", "Ohm"],
     "Ampere (A)"),
    ("1 A = :",
     ["1 C/s", "1 s/C", "1 J/C", "1 V/Ω"],
     "1 C/s"),
    ("Ohm's law: V = :",
     ["IR", "I/R", "I²R", "I+R"],
     "IR"),
    ("SI unit of resistance:",
     ["Ohm (Ω)", "Volt", "Ampere", "Farad"],
     "Ohm (Ω)"),
    ("1 Ω = :",
     ["1 V/A", "1 A/V", "1 C/V", "1 V·A"],
     "1 V/A"),
    ("Ohm's law is obeyed by:",
     ["Ohmic conductors (like metals at constant T)", "All materials", "Only semiconductors", "Only insulators"],
     "Ohmic conductors (like metals at constant T)"),
    ("Current direction (conventional) is:",
     ["Opposite to electron flow", "Same as electron flow", "Random", "Perpendicular"],
     "Opposite to electron flow"),
    ("Drift velocity: v_d = :",
     ["I/(nAe)", "IA/n", "nAe·I", "I·e·A"],
     "I/(nAe)"),
    ("n in drift velocity formula is:",
     ["Number of free electrons per unit volume", "Total number", "Charge", "Area"],
     "Number of free electrons per unit volume"),
    ("Drift velocity in typical copper wire is approximately:",
     ["Millimetres per second", "Speed of light", "100 m/s", "Sound speed"],
     "Millimetres per second"),
    ("Mobility μ = :",
     ["v_d/E", "v_d·E", "v_d + E", "E/v_d"],
     "v_d/E"),
    ("SI unit of mobility:",
     ["m²/(V·s)", "m/s", "V/m", "Ω·m"],
     "m²/(V·s)"),
    ("Current density J = :",
     ["I/A", "I·A", "A/I", "I²A"],
     "I/A"),
    ("J vector relates to E: J = :",
     ["σE (where σ is conductivity)", "σ/E", "E·σ²", "σ + E"],
     "σE (where σ is conductivity)"),
    ("SI unit of conductivity:",
     ["S/m (or Ω⁻¹·m⁻¹)", "Ω·m", "V/m", "A/V"],
     "S/m (or Ω⁻¹·m⁻¹)"),
    ("Resistance R of uniform wire = :",
     ["ρL/A", "ρ/(LA)", "ρA/L", "ρL·A"],
     "ρL/A"),
    ("ρ (resistivity) SI unit:",
     ["Ω·m", "Ω/m", "S", "V·A"],
     "Ω·m"),
    ("Conductivity σ = :",
     ["1/ρ", "ρ", "ρ²", "R·A/L"],
     "1/ρ"),
    ("If length of wire doubles (same A), resistance:",
     ["Doubles", "Halves", "Unchanged", "Quadruples"],
     "Doubles"),
    ("If cross-section area doubles (same L), resistance:",
     ["Halves", "Doubles", "Unchanged", "Quadruples"],
     "Halves"),
    ("Temperature coefficient of resistance α is positive for:",
     ["Metals", "Semiconductors", "Insulators", "Superconductors"],
     "Metals"),
    ("For semiconductors, resistance with temperature:",
     ["Decreases", "Increases", "Unchanged", "Becomes negative"],
     "Decreases"),
    ("For superconductors below T_c, resistance is:",
     ["Zero", "Maximum", "Infinite", "Linear in T"],
     "Zero"),
    ("Power dissipated in resistor: P = :",
     ["I²R (also VI, V²/R)", "I/R", "V²R", "V/I"],
     "I²R (also VI, V²/R)"),
]

# ============ Week 8: Current Electricity – Resistivity, Color Code, Combinations ============
QS[8] = [
    ("Resistivity depends on:",
     ["Material and temperature", "Length and area", "Only current", "Voltage only"],
     "Material and temperature"),
    ("Resistivity of pure metals with temperature:",
     ["Increases", "Decreases", "Unchanged", "Oscillates"],
     "Increases"),
    ("Resistivity of alloys like manganin, constantan:",
     ["Very weakly temperature-dependent", "Strongly decreasing", "Zero", "Infinite"],
     "Very weakly temperature-dependent"),
    ("Resistors in series: R = :",
     ["R₁ + R₂ + ...", "1/R₁ + 1/R₂", "R₁·R₂", "R₁ - R₂"],
     "R₁ + R₂ + ..."),
    ("Resistors in parallel: 1/R = :",
     ["1/R₁ + 1/R₂ + ...", "R₁ + R₂", "R₁R₂", "R₁/R₂"],
     "1/R₁ + 1/R₂ + ..."),
    ("Two equal 10 Ω resistors in series:",
     ["20 Ω", "5 Ω", "10 Ω", "100 Ω"],
     "20 Ω"),
    ("Two equal 10 Ω resistors in parallel:",
     ["5 Ω", "20 Ω", "10 Ω", "0.5 Ω"],
     "5 Ω"),
    ("Current through series resistors is:",
     ["Same", "Different", "Zero", "Sum"],
     "Same"),
    ("Voltage across parallel resistors is:",
     ["Same", "Different", "Zero", "Sum"],
     "Same"),
    ("Resistor color code: 1st band yellow, 2nd violet, 3rd red, 4th gold:",
     ["4700 Ω ± 5%", "47 Ω", "470 kΩ", "47 Ω ± 1%"],
     "4700 Ω ± 5%"),
    ("Colors in code: Black = :",
     ["0", "1", "9", "-1"],
     "0"),
    ("Red in color code = :",
     ["2", "3", "4", "1"],
     "2"),
    ("Gold tolerance band = :",
     ["±5%", "±10%", "±1%", "±20%"],
     "±5%"),
    ("Silver tolerance band = :",
     ["±10%", "±5%", "±1%", "±20%"],
     "±10%"),
    ("No color (tolerance) = :",
     ["±20%", "±10%", "±5%", "±1%"],
     "±20%"),
    ("In a household circuit, appliances are typically connected in:",
     ["Parallel", "Series", "Series-parallel", "Star only"],
     "Parallel"),
    ("A 60 W bulb at 220 V has resistance ≈ :",
     ["807 Ω", "60 Ω", "220 Ω", "13,200 Ω"],
     "807 Ω"),
    ("Power rating P = V²/R, so at lower V the bulb:",
     ["Consumes less power", "Consumes same power", "Consumes more power", "No current flows"],
     "Consumes less power"),
    ("Fuse wire is made of:",
     ["Low melting point alloy", "Copper", "Iron", "Gold"],
     "Low melting point alloy"),
    ("A fuse melts when:",
     ["Current exceeds rating", "Voltage is low", "Power is low", "Resistance is low"],
     "Current exceeds rating"),
    ("EMF and potential difference differ because:",
     ["EMF is total energy per charge from source, V is across external", "They are same always", "V > EMF always", "No difference"],
     "EMF is total energy per charge from source, V is across external"),
    ("Terminal voltage V = :",
     ["EMF - Ir", "EMF + Ir", "EMF × I", "EMF/r"],
     "EMF - Ir"),
    ("Internal resistance r is due to:",
     ["Material of electrolyte/battery", "External wire", "Capacitor", "Field only"],
     "Material of electrolyte/battery"),
    ("Two cells of EMF ε₁, ε₂ in series: total EMF = :",
     ["ε₁ + ε₂", "ε₁·ε₂", "ε₁ - ε₂", "(ε₁ + ε₂)/2"],
     "ε₁ + ε₂"),
    ("Two identical cells EMF ε in parallel: total EMF = :",
     ["ε", "2ε", "ε/2", "ε²"],
     "ε"),
]

# ============ Week 9: Current Electricity – Kirchhoff's Laws, Wheatstone Bridge ============
QS[9] = [
    ("Kirchhoff's junction rule (current law) states:",
     ["Sum of currents in = sum of currents out", "Sum of voltages = 0", "Current is zero", "Voltage is zero"],
     "Sum of currents in = sum of currents out"),
    ("Junction rule is based on:",
     ["Conservation of charge", "Conservation of energy", "Ohm's law", "Gauss's law"],
     "Conservation of charge"),
    ("Kirchhoff's loop rule (voltage law):",
     ["Sum of EMFs and potential drops around loop = 0", "Sum of currents = 0", "Nothing", "Power conservation"],
     "Sum of EMFs and potential drops around loop = 0"),
    ("Loop rule is based on:",
     ["Conservation of energy", "Conservation of charge", "Momentum", "Force"],
     "Conservation of energy"),
    ("For Wheatstone bridge balance: P/Q = :",
     ["R/S", "S/R", "P·Q", "R+S"],
     "R/S"),
    ("At bridge balance, galvanometer current = :",
     ["Zero", "Maximum", "I/2", "Infinite"],
     "Zero"),
    ("Wheatstone bridge is used to measure:",
     ["Unknown resistance accurately", "Voltage", "Current", "EMF only"],
     "Unknown resistance accurately"),
    ("Meter bridge is based on:",
     ["Wheatstone bridge principle", "Potentiometer", "Ohm's law only", "Kirchhoff current law"],
     "Wheatstone bridge principle"),
    ("In a meter bridge, balance condition: l₁/l₂ = :",
     ["R/S (known/unknown)", "R·S", "R+S", "R-S"],
     "R/S (known/unknown)"),
    ("Potentiometer is used to measure:",
     ["EMF of a cell accurately (without drawing current)", "Resistance only", "Capacitance", "Frequency"],
     "EMF of a cell accurately (without drawing current)"),
    ("At null point on potentiometer, current from cell is:",
     ["Zero", "Maximum", "Half", "Reversed"],
     "Zero"),
    ("Potential gradient of potentiometer wire:",
     ["Potential difference per unit length", "Voltage only", "Current per length", "Resistance per length"],
     "Potential difference per unit length"),
    ("Potentiometer vs voltmeter:",
     ["Potentiometer is more accurate (no current drawn at balance)", "Voltmeter is more accurate", "Same", "Potentiometer draws more"],
     "Potentiometer is more accurate (no current drawn at balance)"),
    ("In a Wheatstone bridge with P=3, Q=6, R=9, balanced S = :",
     ["18", "4.5", "2", "27"],
     "18"),
    ("Heat generated in resistor (Joule's law): H = :",
     ["I²Rt", "I/R²t", "V/R", "IR"],
     "I²Rt"),
    ("Electric energy (kWh): 1 unit = :",
     ["3.6 × 10⁶ J", "10⁶ J", "1000 J", "36 kJ"],
     "3.6 × 10⁶ J"),
    ("Two resistors 6 Ω and 12 Ω in parallel:",
     ["4 Ω", "18 Ω", "2 Ω", "72 Ω"],
     "4 Ω"),
    ("EMF of cell with terminal V = 1.4 V, current 0.2 A, r = 0.5 Ω: EMF = :",
     ["1.5 V", "1.4 V", "1.3 V", "1.6 V"],
     "1.5 V"),
    ("Galvanometer can be converted to ammeter by:",
     ["Connecting low-resistance shunt in parallel", "High-resistance in series", "Capacitor", "Diode"],
     "Connecting low-resistance shunt in parallel"),
    ("Galvanometer converted to voltmeter by:",
     ["Connecting high resistance in series", "Low resistance in parallel", "Capacitor", "Inductor"],
     "Connecting high resistance in series"),
    ("Ideal ammeter has:",
     ["Zero resistance", "Infinite resistance", "High resistance", "1 Ω"],
     "Zero resistance"),
    ("Ideal voltmeter has:",
     ["Infinite resistance", "Zero resistance", "Low resistance", "1 Ω"],
     "Infinite resistance"),
    ("A 100 W bulb at 220 V running for 5 h uses energy:",
     ["0.5 kWh", "100 J", "1000 J", "5 kWh"],
     "0.5 kWh"),
    ("Internal resistance of typical AA battery ≈ :",
     ["Less than 1 Ω", "100 Ω", "1000 Ω", "Zero"],
     "Less than 1 Ω"),
    ("Grouping cells of EMF ε and internal r: n cells in series give terminal V (no load):",
     ["nε", "ε/n", "ε", "ε²"],
     "nε"),
]

# ============ Week 10: Current Electricity – Meter Bridge, Potentiometer ============
QS[10] = [
    ("Meter bridge is used to find:",
     ["Unknown resistance", "Current", "Voltage", "EMF"],
     "Unknown resistance"),
    ("The balancing length in meter bridge is determined by:",
     ["Galvanometer showing null deflection", "Max deflection", "Half deflection", "Any deflection"],
     "Galvanometer showing null deflection"),
    ("Meter bridge wire is typically made of:",
     ["Manganin or constantan (uniform resistivity)", "Silver", "Iron", "Gold"],
     "Manganin or constantan (uniform resistivity)"),
    ("If balancing length is 60 cm with known R=20 Ω in left, unknown S = :",
     ["30 Ω (using R/S = l₁/(100-l₁))", "60 Ω", "120 Ω", "100 Ω"],
     "30 Ω (using R/S = l₁/(100-l₁))"),
    ("In meter bridge, why is galvanometer placed between C and D (jockey):",
     ["To detect null deflection across the bridge", "To measure current", "To measure voltage", "To cancel EMF"],
     "To detect null deflection across the bridge"),
    ("Potentiometer wire is selected to have:",
     ["Uniform cross-section and constant resistance per unit length", "Varying thickness", "High resistance spots", "No resistance"],
     "Uniform cross-section and constant resistance per unit length"),
    ("Potentiometer can compare:",
     ["EMFs of two cells", "Only one EMF", "Currents only", "Resistances only"],
     "EMFs of two cells"),
    ("Sensitivity of potentiometer increases with:",
     ["Longer wire (smaller gradient)", "Shorter wire", "High gradient", "High current"],
     "Longer wire (smaller gradient)"),
    ("If potentiometer wire resistance is made smaller, gradient:",
     ["Decreases", "Increases", "Unchanged", "Zero"],
     "Decreases"),
    ("Internal resistance of cell found by potentiometer using:",
     ["Comparison with and without external load", "Direct measurement", "Only one reading", "Ohm's law on load"],
     "Comparison with and without external load"),
    ("In potentiometer, driver cell must have:",
     ["EMF greater than cell being measured", "EMF smaller", "EMF equal", "No EMF"],
     "EMF greater than cell being measured"),
    ("Length l₁ balances EMF ε₁, l₂ balances ε₂. Ratio ε₁/ε₂ = :",
     ["l₁/l₂", "l₂/l₁", "l₁·l₂", "l₁ - l₂"],
     "l₁/l₂"),
    ("For internal resistance, balance length with open circuit l₁ and with resistance R l₂:",
     ["r = R(l₁ - l₂)/l₂", "r = R·l₂", "r = l₁ - R", "r = R/l₁"],
     "r = R(l₁ - l₂)/l₂"),
    ("Precautions in potentiometer experiment include:",
     ["Clean connections, avoid parallax, same polarity", "Loose connections", "Random polarity", "Variable length"],
     "Clean connections, avoid parallax, same polarity"),
    ("Why is potentiometer called an ideal voltmeter?",
     ["It draws no current at balance", "It has low resistance", "It measures only current", "It uses battery"],
     "It draws no current at balance"),
    ("In meter bridge, end corrections are needed because:",
     ["Small extra resistances at ends affect accuracy", "Wire is not uniform", "Galvanometer drift", "Battery variation"],
     "Small extra resistances at ends affect accuracy"),
    ("Slide wire resistance per unit length is called:",
     ["Resistance per cm / potential gradient", "Resistivity", "Current density", "Magnetic field"],
     "Resistance per cm / potential gradient"),
    ("In meter bridge with wire of 100 cm and balance at 40 cm, R=4 Ω, S = :",
     ["6 Ω", "10 Ω", "2 Ω", "40 Ω"],
     "6 Ω"),
    ("If jockey presses the wire firmly:",
     ["Damage and uneven resistance", "Better reading", "No effect", "Shorter wire"],
     "Damage and uneven resistance"),
    ("Meter bridge is less accurate when unknown resistance is:",
     ["Very small or very large (balance near ends)", "Moderate", "Equal to known", "Negative"],
     "Very small or very large (balance near ends)"),
    ("A galvanometer can be used as a null detector in:",
     ["Both potentiometer and Wheatstone bridge", "Only ammeter", "Only voltmeter", "Rheostat"],
     "Both potentiometer and Wheatstone bridge"),
    ("The standard cell used in potentiometer is:",
     ["Weston cadmium cell (constant EMF)", "Leclanche cell", "Daniell cell", "Lithium ion"],
     "Weston cadmium cell (constant EMF)"),
    ("EMF of Weston cadmium cell ≈ :",
     ["1.0186 V", "1.5 V", "2 V", "9 V"],
     "1.0186 V"),
    ("Specific resistance (resistivity) of meter bridge wire is best:",
     ["High and constant with T", "Low and variable", "Zero", "Infinite"],
     "High and constant with T"),
    ("The meter bridge uses which resistance combination principle?",
     ["Wheatstone balance with two ratios of lengths", "Series only", "Parallel only", "Kirchhoff junction"],
     "Wheatstone balance with two ratios of lengths"),
]

# ============ validation ============
for wk, qlist in QS.items():
    assert len(qlist) == 25, f"Week {wk}: expected 25, got {len(qlist)}"
    for (q, opts, ans) in qlist:
        assert len(opts) == 4, f"Week {wk} Q='{q}': needs 4 options"
        assert ans in opts, f"Week {wk} Q='{q}': answer '{ans}' not in options {opts}"

# ============ apply to JSON ============
d = json.loads(JSON_PATH.read_text())
grade_12 = d["12"]

replaced = 0
for wk_entry in grade_12:
    wk_num = wk_entry["week"]
    if wk_num in QS:
        new_qs = []
        for i, (q, opts, ans) in enumerate(QS[wk_num], start=1):
            new_qs.append({
                "id": f"p12-w{wk_num}-q{i}",
                "question": q,
                "options": opts,
                "answer": ans,
            })
        wk_entry["questions"] = new_qs
        replaced += len(new_qs)

JSON_PATH.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
print(f"Replaced {replaced} physics/12 placeholder questions across {len(QS)} weeks: {sorted(QS.keys())}")
