#!/usr/bin/env python3
"""
QA Fix Part 2: Replace 150 fake questions on maths-higher/12 wk47-52 with
real NCERT Class 12 revision content.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DATA = ROOT / 'src' / 'data'

maths_h = json.loads((DATA / 'maths-higher-quizzes.json').read_text())

# ─── Week 47: Revision — Applications of Integrals & Differential Equations ───
WEEK_47 = {
    "week": 47,
    "topic": "Revision - Applications of Integrals & Differential Equations",
    "questions": [
        {"question": "The area bounded by y = x², the x-axis, and x = 0 to x = 3 is:",
         "options": ["3 sq units", "6 sq units", "9 sq units", "27 sq units"], "answer": "9 sq units"},
        {"question": "The area between y = sin x and the x-axis from x = 0 to x = π is:",
         "options": ["0", "1", "2", "π"], "answer": "2"},
        {"question": "The area enclosed between the curves y = x² and y = x is:",
         "options": ["1/2", "1/3", "1/6", "1/4"], "answer": "1/6"},
        {"question": "The area of the region bounded by y² = 4x and x = 1 is:",
         "options": ["4/3", "8/3", "4", "16/3"], "answer": "8/3"},
        {"question": "The area enclosed by the circle x² + y² = a² is:",
         "options": ["πa", "πa²", "2πa", "2πa²"], "answer": "πa²"},
        {"question": "The area of the region bounded by y = |x|, x = -1, x = 1 and the x-axis is:",
         "options": ["1/2", "1", "2", "3/2"], "answer": "1"},
        {"question": "The order of the differential equation (d²y/dx²)³ + (dy/dx)⁴ + y = 0 is:",
         "options": ["1", "2", "3", "4"], "answer": "2"},
        {"question": "The degree of the differential equation (d²y/dx²)² + cos(dy/dx) = 0 is:",
         "options": ["1", "2", "Not defined", "3"], "answer": "Not defined"},
        {"question": "The general solution of dy/dx = e^(x+y) is:",
         "options": ["e^x + e^(-y) = C", "e^(-x) + e^(-y) = C", "e^x - e^(-y) = C", "e^x + e^y = C"],
         "answer": "e^x + e^(-y) = C"},
        {"question": "The solution of dy/dx = (1 + y²)/(1 + x²) is:",
         "options": ["tan⁻¹y = tan⁻¹x + C", "tan⁻¹y - tan⁻¹x = C", "y = x + C", "y² = x² + C"],
         "answer": "tan⁻¹y - tan⁻¹x = C"},
        {"question": "The integrating factor of dy/dx + y = e^x is:",
         "options": ["e^x", "e^(-x)", "x", "log x"], "answer": "e^x"},
        {"question": "The integrating factor of x dy/dx + y = x² is:",
         "options": ["x", "1/x", "x²", "log x"], "answer": "x"},
        {"question": "The solution of dy/dx = y/x passing through (1, 1) is:",
         "options": ["y = x", "y = x²", "xy = 1", "y = log x"], "answer": "y = x"},
        {"question": "A homogeneous differential equation of the form dy/dx = f(y/x) is solved by substituting:",
         "options": ["y = vx", "x = vy", "y = v/x", "x = v + y"], "answer": "y = vx"},
        {"question": "The general solution of the linear DE dy/dx + Py = Q (P, Q functions of x) is:",
         "options": ["y·e^∫P dx = ∫Q·e^∫P dx dx + C", "y = e^(-∫P dx) + C", "y = Q/P + C", "y·P = Q + C"],
         "answer": "y·e^∫P dx = ∫Q·e^∫P dx dx + C"},
        {"question": "The area enclosed between y = x³, x-axis, x = -1 and x = 1 is:",
         "options": ["0", "1/2", "1/4", "1"], "answer": "1/2"},
        {"question": "The area bounded by y = cos x, x = 0, x = π/2 and the x-axis is:",
         "options": ["0", "1/2", "1", "π/2"], "answer": "1"},
        {"question": "The differential equation representing the family y = A·cos x + B·sin x is:",
         "options": ["d²y/dx² + y = 0", "d²y/dx² - y = 0", "dy/dx + y = 0", "dy/dx = y"],
         "answer": "d²y/dx² + y = 0"},
        {"question": "The solution of dy/dx = -y (with y(0) = 1) is:",
         "options": ["y = e^x", "y = e^(-x)", "y = -x + 1", "y = 1 - x²"], "answer": "y = e^(-x)"},
        {"question": "The area enclosed by the ellipse x²/a² + y²/b² = 1 is:",
         "options": ["πab", "π(a + b)", "2πab", "πa²b"], "answer": "πab"},
        {"question": "The particular solution of dy/dx = 2xy with y(0) = 1 is:",
         "options": ["y = e^(x²)", "y = e^(2x)", "y = 1 + x²", "y = 2x + 1"], "answer": "y = e^(x²)"},
        {"question": "The area of the region {(x, y) : y² ≤ 4x, 4x² + 4y² ≤ 9} is (approx., standard NCERT):",
         "options": ["π/4 + 2√2/3", "(2π - √3)/3", "9π/8 - √2", "π/2 + √3"],
         "answer": "π/4 + 2√2/3"},
        {"question": "Which of these is a separable differential equation?",
         "options": ["dy/dx = x + y", "dy/dx = xy", "dy/dx = sin(x + y)", "dy/dx = (x + y)²"],
         "answer": "dy/dx = xy"},
        {"question": "The solution of dy/dx + y·tan x = sec x is:",
         "options": ["y = sin x + C cos x", "y = cos x + C sin x", "y·sec x = tan x + C", "y·cos x = sin x + C"],
         "answer": "y·cos x = sin x + C"},
        {"question": "The area bounded by the parabola y² = 4ax and its latus rectum is:",
         "options": ["8a²/3", "4a²/3", "2a²", "16a²/3"], "answer": "8a²/3"},
    ]
}

# ─── Week 48: Revision — Vectors & 3D Geometry ───
WEEK_48 = {
    "week": 48,
    "topic": "Revision - Vectors & 3D Geometry",
    "questions": [
        {"question": "If a⃗ = î + 2ĵ + 3k̂, then |a⃗| equals:",
         "options": ["√6", "√14", "6", "14"], "answer": "√14"},
        {"question": "The unit vector in the direction of 3î + 4ĵ is:",
         "options": ["(3î + 4ĵ)/5", "(3î + 4ĵ)/7", "(3î + 4ĵ)/25", "3î + 4ĵ"], "answer": "(3î + 4ĵ)/5"},
        {"question": "If a⃗·b⃗ = 0 and a⃗, b⃗ are non-zero, then a⃗ and b⃗ are:",
         "options": ["Parallel", "Anti-parallel", "Perpendicular", "Equal"], "answer": "Perpendicular"},
        {"question": "The value of î·(ĵ × k̂) is:",
         "options": ["0", "1", "-1", "î"], "answer": "1"},
        {"question": "If a⃗ × b⃗ = 0 and a⃗, b⃗ are non-zero, then a⃗ and b⃗ are:",
         "options": ["Perpendicular", "Parallel", "Equal", "Of equal magnitude"], "answer": "Parallel"},
        {"question": "The projection of a⃗ = 2î + 3ĵ + 2k̂ on b⃗ = î + 2ĵ + k̂ is:",
         "options": ["10/√6", "10/√5", "√6", "5/√6"], "answer": "10/√6"},
        {"question": "The angle between vectors a⃗ = î + ĵ and b⃗ = ĵ + k̂ is:",
         "options": ["30°", "45°", "60°", "90°"], "answer": "60°"},
        {"question": "The area of the parallelogram with adjacent sides a⃗ = î + ĵ + k̂ and b⃗ = î - ĵ + k̂ is:",
         "options": ["√5", "2√2", "2√3", "√6"], "answer": "2√2"},
        {"question": "The volume of the parallelepiped with edges a⃗ = î + ĵ, b⃗ = ĵ + k̂, c⃗ = k̂ + î is:",
         "options": ["0", "1", "2", "3"], "answer": "2"},
        {"question": "The direction cosines of the vector 2î - 3ĵ + 6k̂ are:",
         "options": ["(2/7, -3/7, 6/7)", "(1/√14, -3/√14, 6/√14)", "(2, -3, 6)", "(2/√49, -3/√49, 6/√49)"],
         "answer": "(2/7, -3/7, 6/7)"},
        {"question": "The distance between the parallel planes 2x - 2y + z = 1 and 2x - 2y + z = 5 is:",
         "options": ["4/3", "4", "2/3", "1"], "answer": "4/3"},
        {"question": "The equation of the line through (1, 2, 3) parallel to b⃗ = î + 2ĵ - k̂ is:",
         "options": ["(x-1)/1 = (y-2)/2 = (z-3)/(-1)", "(x+1)/1 = (y+2)/2 = (z+3)/(-1)",
                     "x/1 = y/2 = z/(-1)", "(x-1)/2 = (y-2)/1 = (z-3)/(-1)"],
         "answer": "(x-1)/1 = (y-2)/2 = (z-3)/(-1)"},
        {"question": "The Cartesian equation of the plane passing through (1, 0, 0) with normal î + ĵ + k̂ is:",
         "options": ["x + y + z = 1", "x + y + z = 0", "x - y - z = 1", "x + y + z = 3"],
         "answer": "x + y + z = 1"},
        {"question": "The angle between the planes 2x + y - z = 3 and x - y + 2z = 1 is:",
         "options": ["cos⁻¹(1/6)", "cos⁻¹(-1/6)", "cos⁻¹(1/3)", "π/3"], "answer": "cos⁻¹(-1/6)"},
        {"question": "The shortest distance between skew lines with direction vectors b⃗₁, b⃗₂ and position vectors a⃗₁, a⃗₂ is:",
         "options": ["|(a⃗₂ - a⃗₁)·(b⃗₁ × b⃗₂)|/|b⃗₁ × b⃗₂|", "|a⃗₂ - a⃗₁|",
                     "|b⃗₁ × b⃗₂|", "|(a⃗₂ - a⃗₁)×(b⃗₁ - b⃗₂)|"],
         "answer": "|(a⃗₂ - a⃗₁)·(b⃗₁ × b⃗₂)|/|b⃗₁ × b⃗₂|"},
        {"question": "If a⃗, b⃗, c⃗ are mutually perpendicular unit vectors, then |a⃗ + b⃗ + c⃗| equals:",
         "options": ["1", "√2", "√3", "3"], "answer": "√3"},
        {"question": "The position vector of the midpoint of the segment joining A(2, 3, -1) and B(-2, 1, 3) is:",
         "options": ["î + 2ĵ + k̂", "2ĵ + k̂", "4ĵ + 2k̂", "0î + 2ĵ + k̂"], "answer": "0î + 2ĵ + k̂"},
        {"question": "The scalar triple product [a⃗ b⃗ c⃗] is zero when:",
         "options": ["a⃗, b⃗, c⃗ are mutually perpendicular", "a⃗, b⃗, c⃗ are coplanar",
                     "|a⃗| = |b⃗| = |c⃗|", "a⃗ = b⃗"], "answer": "a⃗, b⃗, c⃗ are coplanar"},
        {"question": "If a⃗ = 2î + 3ĵ, b⃗ = -î + 2ĵ, then a⃗ · b⃗ equals:",
         "options": ["4", "-2", "2", "-4"], "answer": "4"},
        {"question": "The equation of the plane containing the z-axis and making angle 60° with the plane x + y = 3 is:",
         "options": ["x - y = 0", "y = x·tan 15°", "x + y·tan 15° = 0", "y = √3·x"],
         "answer": "y = √3·x"},
        {"question": "The foot of perpendicular from (1, 2, 3) to the line x = y = z is:",
         "options": ["(2, 2, 2)", "(1, 1, 1)", "(3, 3, 3)", "(0, 0, 0)"], "answer": "(2, 2, 2)"},
        {"question": "The direction ratios of the line of intersection of planes x + y + z = 1 and x - y + z = 2 are:",
         "options": ["(1, 0, -1)", "(1, 1, 1)", "(1, -1, 1)", "(0, 1, 0)"], "answer": "(1, 0, -1)"},
        {"question": "The vector equation of the plane passing through the origin with normal 2î - 3ĵ + k̂ is:",
         "options": ["r⃗ · (2î - 3ĵ + k̂) = 0", "r⃗ · (2î - 3ĵ + k̂) = 1",
                     "r⃗ × (2î - 3ĵ + k̂) = 0", "|r⃗| = 2"], "answer": "r⃗ · (2î - 3ĵ + k̂) = 0"},
        {"question": "If |a⃗| = 3, |b⃗| = 4 and |a⃗ × b⃗| = 6, then the angle between a⃗ and b⃗ is:",
         "options": ["30°", "45°", "60°", "90°"], "answer": "30°"},
        {"question": "The line through (1, -1, 2) perpendicular to the plane 2x - 3y + 4z = 10 has direction ratios:",
         "options": ["(1, -1, 2)", "(2, -3, 4)", "(-2, 3, -4)", "(1, 0, 0)"], "answer": "(2, -3, 4)"},
    ]
}

# ─── Week 49: Revision — Linear Programming & Probability ───
WEEK_49 = {
    "week": 49,
    "topic": "Revision - Linear Programming & Probability",
    "questions": [
        {"question": "In a linear programming problem, the objective function is always:",
         "options": ["Quadratic", "Linear", "Exponential", "Logarithmic"], "answer": "Linear"},
        {"question": "The feasible region of a linear programming problem is:",
         "options": ["Always unbounded", "Always bounded", "A convex region", "A non-convex region"],
         "answer": "A convex region"},
        {"question": "If the feasible region is bounded, the objective function attains its optimum at:",
         "options": ["The centroid", "The origin", "A corner (vertex) point", "The midpoint of the longest side"],
         "answer": "A corner (vertex) point"},
        {"question": "Maximum of Z = 3x + 4y subject to x + y ≤ 4, x ≥ 0, y ≥ 0 is:",
         "options": ["12", "16", "17", "18"], "answer": "16"},
        {"question": "The corner points of a feasible region are (0, 0), (5, 0), (3, 4), (0, 5). The maximum of Z = 2x + 5y is:",
         "options": ["10", "25", "26", "15"], "answer": "26"},
        {"question": "Minimum of Z = 3x + 5y subject to x + 3y ≥ 3, x + y ≥ 2, x, y ≥ 0 is:",
         "options": ["7", "8", "6", "9"], "answer": "7"},
        {"question": "If A and B are independent events with P(A) = 0.3 and P(B) = 0.4, then P(A ∩ B) is:",
         "options": ["0.7", "0.12", "0.1", "0.25"], "answer": "0.12"},
        {"question": "If P(A) = 1/2 and P(B) = 1/3 and A, B are mutually exclusive, then P(A ∪ B) is:",
         "options": ["1/6", "1/2", "1/3", "5/6"], "answer": "5/6"},
        {"question": "If P(A|B) = 0.6 and P(B) = 0.5, then P(A ∩ B) is:",
         "options": ["0.1", "0.3", "0.5", "1.1"], "answer": "0.3"},
        {"question": "Two dice are rolled. The probability that the sum is 7 is:",
         "options": ["1/6", "1/12", "1/36", "7/36"], "answer": "1/6"},
        {"question": "A bag has 5 red and 3 blue balls. Two are drawn without replacement. P(both red) is:",
         "options": ["5/14", "3/14", "25/64", "15/56"], "answer": "5/14"},
        {"question": "A die is rolled. Given that the outcome is odd, the probability it is 3 is:",
         "options": ["1/3", "1/6", "1/2", "2/3"], "answer": "1/3"},
        {"question": "If X is a random variable with E(X) = 5 and Var(X) = 4, then E(X²) is:",
         "options": ["9", "21", "25", "29"], "answer": "29"},
        {"question": "For a binomial distribution B(n, p), the mean is:",
         "options": ["np", "npq", "√(npq)", "p"], "answer": "np"},
        {"question": "For B(10, 0.4), the variance is:",
         "options": ["4", "2.4", "6", "10"], "answer": "2.4"},
        {"question": "If P(A) = 0.4, P(B) = 0.5 and P(A ∩ B) = 0.2, then A and B are:",
         "options": ["Mutually exclusive", "Independent", "Complementary", "Same event"],
         "answer": "Independent"},
        {"question": "Bayes' theorem gives:",
         "options": ["P(A ∩ B)", "P(A|B) in terms of P(B|A), P(A), P(B)",
                     "P(A ∪ B)", "P(A) + P(B)"],
         "answer": "P(A|B) in terms of P(B|A), P(A), P(B)"},
        {"question": "A coin is tossed 3 times. P(exactly 2 heads) is:",
         "options": ["1/8", "3/8", "1/2", "5/8"], "answer": "3/8"},
        {"question": "The probability distribution of a binomial variable has Σp(x) equal to:",
         "options": ["0", "1", "n", "np"], "answer": "1"},
        {"question": "If the feasible region of an LPP is unbounded and Z has a maximum, then maximum must occur at:",
         "options": ["The origin", "Any corner point where Z is largest and the open half-plane does not contain greater values",
                     "Infinity", "The centroid"],
         "answer": "Any corner point where Z is largest and the open half-plane does not contain greater values"},
        {"question": "Maximum of Z = x + 2y subject to 2x + y ≤ 6, x + 2y ≤ 6, x, y ≥ 0 is:",
         "options": ["6", "9", "5", "4"], "answer": "6"},
        {"question": "A family has 2 children. The probability that both are girls given at least one is a girl is:",
         "options": ["1/2", "1/3", "1/4", "2/3"], "answer": "1/3"},
        {"question": "For B(n, p), if n = 5 and p = 1/2, then P(X = 3) is:",
         "options": ["5/16", "5/32", "10/32", "1/32"], "answer": "5/16"},
        {"question": "If P(E) = 0.05, the odds against E are:",
         "options": ["1:19", "19:1", "1:20", "5:95"], "answer": "19:1"},
        {"question": "The minimum of Z = 4x + 3y subject to 3x + 2y ≥ 160, 5x + 2y ≥ 200, x, y ≥ 0 is:",
         "options": ["200", "220", "240", "300"], "answer": "240"},
    ]
}

# ─── Week 50: Full Syllabus Mixed Practice 1 ───
WEEK_50 = {
    "week": 50,
    "topic": "Full Syllabus Mixed Practice - Set 1",
    "questions": [
        {"question": "If A = {1, 2, 3}, the number of equivalence relations containing (1, 2) is:",
         "options": ["1", "2", "3", "4"], "answer": "2"},
        {"question": "The principal value of sin⁻¹(sin(5π/6)) is:",
         "options": ["5π/6", "π/6", "-π/6", "-5π/6"], "answer": "π/6"},
        {"question": "If A is a 3×3 matrix with |A| = 5, then |2A| is:",
         "options": ["10", "20", "40", "80"], "answer": "40"},
        {"question": "The function f(x) = |x| is not differentiable at:",
         "options": ["x = 1", "x = 0", "x = -1", "Everywhere"], "answer": "x = 0"},
        {"question": "The derivative of sin⁻¹(x) with respect to x is:",
         "options": ["1/√(1-x²)", "-1/√(1-x²)", "1/(1+x²)", "-1/(1+x²)"], "answer": "1/√(1-x²)"},
        {"question": "∫(2x)/(1 + x²) dx =",
         "options": ["log|1 + x²| + C", "tan⁻¹x + C", "2 log|x| + C", "x² + C"], "answer": "log|1 + x²| + C"},
        {"question": "∫₀^(π/2) sin²x dx =",
         "options": ["π/4", "π/2", "1/2", "π"], "answer": "π/4"},
        {"question": "If a⃗ = 2î + ĵ and b⃗ = î - ĵ, then a⃗ + b⃗ is:",
         "options": ["3î", "î + 2ĵ", "3î + 0ĵ", "î"], "answer": "3î + 0ĵ"},
        {"question": "The direction ratios of the line joining (1, 2, 3) and (4, 5, 6) are:",
         "options": ["(3, 3, 3)", "(1, 1, 1)", "(5, 7, 9)", "(-3, -3, -3)"], "answer": "(3, 3, 3)"},
        {"question": "The maximum of Z = 3x + 2y over feasible region bounded by x + y ≤ 4, x, y ≥ 0 is:",
         "options": ["8", "12", "10", "6"], "answer": "12"},
        {"question": "If P(A) = 0.6, P(B) = 0.4 and P(A ∩ B) = 0.24, then A and B are:",
         "options": ["Mutually exclusive", "Independent", "Dependent", "Complementary"],
         "answer": "Independent"},
        {"question": "The continuity of f(x) = x²·sin(1/x) at x = 0 (defining f(0) = 0) is:",
         "options": ["Continuous", "Discontinuous", "Undefined", "Infinite"],
         "answer": "Continuous"},
        {"question": "The tangent to y = x² at x = 1 has slope:",
         "options": ["1", "2", "0", "1/2"], "answer": "2"},
        {"question": "The critical points of f(x) = x³ - 3x are:",
         "options": ["0, 1", "1, -1", "-1, 0, 1", "0"], "answer": "1, -1"},
        {"question": "Evaluate the integral ∫ sec²x dx:",
         "options": ["tan x + C", "sin x + C", "cos x + C", "log|sec x| + C"], "answer": "tan x + C"},
        {"question": "The area bounded by y = x, x = 0, x = 2, and x-axis is:",
         "options": ["1", "2", "4", "2√2"], "answer": "2"},
        {"question": "If f(x) = e^(x²), then f'(x) is:",
         "options": ["2x·e^(x²)", "e^(x²)", "x·e^(x²)", "2e^(x²)"], "answer": "2x·e^(x²)"},
        {"question": "The value of ∫₀¹ x² dx is:",
         "options": ["1/2", "1/3", "1/4", "1"], "answer": "1/3"},
        {"question": "If [A B] = [[1, 2]] + [[3, 4]], then [A B] is:",
         "options": ["[1, 6]", "[4, 6]", "[3, 2]", "[1, 2]"], "answer": "[4, 6]"},
        {"question": "The general solution of dy/dx = sec²x is:",
         "options": ["y = tan x + C", "y = sec x + C", "y = log|sec x| + C", "y = cot x + C"],
         "answer": "y = tan x + C"},
        {"question": "The value of cos⁻¹(-1/2) is:",
         "options": ["π/3", "2π/3", "-π/3", "π/6"], "answer": "2π/3"},
        {"question": "If A² = A, then A is called:",
         "options": ["Symmetric", "Skew-symmetric", "Idempotent", "Involutory"], "answer": "Idempotent"},
        {"question": "The direction cosines of a line making equal angles with the coordinate axes are:",
         "options": ["(1, 1, 1)", "(1/√3, 1/√3, 1/√3)", "(1/3, 1/3, 1/3)", "(0, 0, 0)"],
         "answer": "(1/√3, 1/√3, 1/√3)"},
        {"question": "If P(A) = 1/4, P(B|A) = 1/3, then P(A ∩ B) is:",
         "options": ["1/12", "1/7", "1/3", "3/4"], "answer": "1/12"},
        {"question": "∫(dx/(1 + x²)) from 0 to 1 equals:",
         "options": ["π/2", "π/4", "π", "0"], "answer": "π/4"},
    ]
}

# ─── Week 51: Full Syllabus Mixed Practice 2 ───
WEEK_51 = {
    "week": 51,
    "topic": "Full Syllabus Mixed Practice - Set 2",
    "questions": [
        {"question": "If R is defined on ℕ by aRb iff a + b is even, then R is:",
         "options": ["Reflexive only", "Symmetric only", "Equivalence relation", "None"],
         "answer": "Equivalence relation"},
        {"question": "The principal value of tan⁻¹(-1) is:",
         "options": ["π/4", "-π/4", "3π/4", "-3π/4"], "answer": "-π/4"},
        {"question": "If A is skew-symmetric and n odd, then det(A) is:",
         "options": ["Positive", "Negative", "Zero", "Depends on n"], "answer": "Zero"},
        {"question": "The derivative of log(sin x) is:",
         "options": ["cot x", "tan x", "1/sin x", "sec x"], "answer": "cot x"},
        {"question": "The maximum value of f(x) = sin x + cos x is:",
         "options": ["1", "√2", "2", "√3"], "answer": "√2"},
        {"question": "Evaluate ∫ x·e^x dx using integration by parts:",
         "options": ["x·e^x + C", "(x - 1)·e^x + C", "(x + 1)·e^x + C", "x²·e^x + C"],
         "answer": "(x - 1)·e^x + C"},
        {"question": "Evaluate the definite integral ∫₋₁¹ x³ dx:",
         "options": ["0", "2/3", "1", "2"], "answer": "0"},
        {"question": "If a⃗·b⃗ = |a⃗||b⃗|, the angle between them is:",
         "options": ["0", "π/2", "π", "π/4"], "answer": "0"},
        {"question": "The distance between the parallel lines r⃗ = î + t(ĵ + k̂) and r⃗ = 2î + s(ĵ + k̂) is:",
         "options": ["1", "√2", "√3", "2"], "answer": "1"},
        {"question": "The minimum of Z = 2x + 3y subject to x + y ≥ 8, 3x + 5y ≤ 15, x, y ≥ 0 is:",
         "options": ["No feasible solution", "16", "24", "7.5"], "answer": "No feasible solution"},
        {"question": "If P(A) = 0.3, P(B) = 0.5, P(A ∪ B) = 0.7, then P(A ∩ B) is:",
         "options": ["0.1", "0.15", "0.2", "0.3"], "answer": "0.1"},
        {"question": "If f(x) = (x² - 4)/(x - 2), then limₓ→₂ f(x) equals:",
         "options": ["0", "2", "4", "Does not exist"], "answer": "4"},
        {"question": "The point of local maximum of f(x) = -x² + 4x is at x =",
         "options": ["0", "2", "4", "-2"], "answer": "2"},
        {"question": "The absolute maximum of f(x) = x²(1-x) on [0, 1] is at x =",
         "options": ["0", "1/2", "2/3", "1"], "answer": "2/3"},
        {"question": "∫ 1/(x·log x) dx =",
         "options": ["log x + C", "log|log x| + C", "(log x)² + C", "x·log x + C"],
         "answer": "log|log x| + C"},
        {"question": "The area under y = e^x from x = 0 to x = 1 is:",
         "options": ["e", "e - 1", "1", "1/e"], "answer": "e - 1"},
        {"question": "If y = x^x, then dy/dx is:",
         "options": ["x·x^(x-1)", "x^x·(1 + log x)", "x^x·log x", "x^x"],
         "answer": "x^x·(1 + log x)"},
        {"question": "The solution of dy/dx = x + y is (linear DE, μ = e^(-x)):",
         "options": ["y = -x - 1 + C·e^x", "y = x + 1 + C·e^x", "y = e^x + C", "y = x² + C"],
         "answer": "y = -x - 1 + C·e^x"},
        {"question": "The inverse of a 2×2 matrix [[1, 2], [3, 4]] is:",
         "options": ["(-1/2)·[[4, -2], [-3, 1]]", "(1/2)·[[4, -2], [-3, 1]]", "[[4, -2], [-3, 1]]", "Does not exist"],
         "answer": "(-1/2)·[[4, -2], [-3, 1]]"},
        {"question": "For a continuous RV X on [0, 2] with pdf f(x) = x/2, E(X) equals:",
         "options": ["1", "4/3", "2", "1/2"], "answer": "4/3"},
        {"question": "The equation of the plane passing through (1, 0, 0), (0, 1, 0), (0, 0, 1) is:",
         "options": ["x + y + z = 1", "x + y + z = 0", "x·y·z = 1", "x - y + z = 1"],
         "answer": "x + y + z = 1"},
        {"question": "If A and B are independent, P(A) = 0.5, P(B) = 0.6, then P(A ∪ B) is:",
         "options": ["0.8", "0.7", "0.3", "1.1"], "answer": "0.8"},
        {"question": "Evaluate the integral ∫ cos²x dx:",
         "options": ["x/2 + sin(2x)/4 + C", "sin(2x)/2 + C", "cos(2x)/2 + C", "x - sin(2x)/4 + C"],
         "answer": "x/2 + sin(2x)/4 + C"},
        {"question": "The order and degree of (dy/dx)² + y = sin x are respectively:",
         "options": ["1 and 2", "2 and 1", "2 and 2", "1 and 1"], "answer": "1 and 2"},
        {"question": "The principal value of sec⁻¹(-2) is:",
         "options": ["π/3", "2π/3", "-π/3", "-2π/3"], "answer": "2π/3"},
    ]
}

# ─── Week 52: Grand Revision — Full Syllabus ───
WEEK_52 = {
    "week": 52,
    "topic": "Grand Revision - Full Syllabus",
    "questions": [
        {"question": "A relation R is an equivalence relation if it is:",
         "options": ["Reflexive only", "Symmetric and transitive", "Reflexive, symmetric and transitive",
                     "Reflexive and transitive"],
         "answer": "Reflexive, symmetric and transitive"},
        {"question": "Range of y = sin⁻¹(x) is:",
         "options": ["[0, π]", "[-π/2, π/2]", "(-π/2, π/2)", "[-π, π]"], "answer": "[-π/2, π/2]"},
        {"question": "For A of order 3 with det(A) = 4, det(adj A) equals:",
         "options": ["4", "12", "16", "64"], "answer": "16"},
        {"question": "For A of order 3 with det(A) = 5, det(A⁻¹) equals:",
         "options": ["5", "1/5", "1/25", "1/125"], "answer": "1/5"},
        {"question": "If y = tan⁻¹(x), then d²y/dx² at x = 0 is:",
         "options": ["0", "1", "-1", "2"], "answer": "0"},
        {"question": "Evaluate ∫ x·cos x dx using integration by parts:",
         "options": ["x·sin x + cos x + C", "x·sin x - cos x + C",
                     "sin x - x·cos x + C", "x·sin x + C"],
         "answer": "x·sin x + cos x + C"},
        {"question": "If f is continuous on [a, b] and F'(x) = f(x), then ∫ₐᵇ f(x) dx equals:",
         "options": ["F(a) - F(b)", "F(b) - F(a)", "F(b) + F(a)", "(F(a) + F(b))/2"],
         "answer": "F(b) - F(a)"},
        {"question": "The direction of a⃗ × b⃗ is:",
         "options": ["Parallel to a⃗", "Parallel to b⃗",
                     "Perpendicular to both a⃗ and b⃗", "Along bisector of a⃗ and b⃗"],
         "answer": "Perpendicular to both a⃗ and b⃗"},
        {"question": "The equation of a line through (x₁, y₁, z₁) with direction ratios (a, b, c) is:",
         "options": ["(x - x₁)/a = (y - y₁)/b = (z - z₁)/c", "x + y + z = a + b + c",
                     "ax + by + cz = 0", "(x - a)/x₁ = (y - b)/y₁ = (z - c)/z₁"],
         "answer": "(x - x₁)/a = (y - y₁)/b = (z - z₁)/c"},
        {"question": "The feasible region of an LPP is always a:",
         "options": ["Triangle", "Convex polygon or unbounded convex region",
                     "Circle", "Any shape"],
         "answer": "Convex polygon or unbounded convex region"},
        {"question": "If E and F are independent, P(E|F) equals:",
         "options": ["P(E)", "P(F)", "P(E ∩ F)", "P(E ∪ F)"], "answer": "P(E)"},
        {"question": "For B(n, p), mean μ = np and variance σ² = npq, so σ² < μ when:",
         "options": ["p < 1", "p > 1/2", "p = 1", "q = 1"], "answer": "p < 1"},
        {"question": "∫₀^(π/4) tan²x dx equals:",
         "options": ["1 - π/4", "π/4", "1 + π/4", "π/4 - 1"], "answer": "1 - π/4"},
        {"question": "The rate of change of area of a circle of radius r with respect to r is:",
         "options": ["πr", "2πr", "πr²", "π"], "answer": "2πr"},
        {"question": "If f(x) = x³ - 6x² + 9x + 1, the point of inflection is at x =",
         "options": ["0", "1", "2", "3"], "answer": "2"},
        {"question": "The general solution of x·dy/dx + y = log x is:",
         "options": ["y = log x + C/x", "x·y = x·log x - x + C", "y = x·log x + C", "y = C - log x"],
         "answer": "x·y = x·log x - x + C"},
        {"question": "The probability of drawing an ace from a pack of 52 cards is:",
         "options": ["1/52", "1/13", "1/4", "4/13"], "answer": "1/13"},
        {"question": "If a⃗ and b⃗ are unit vectors with angle π/3 between them, |a⃗ - b⃗| equals:",
         "options": ["1", "√2", "1/2", "√3"], "answer": "1"},
        {"question": "The length of the projection of vector 2î + ĵ + 2k̂ on î + ĵ is:",
         "options": ["√2", "3/√2", "3", "1"], "answer": "3/√2"},
        {"question": "The equation of the line through (1, 0, -2) perpendicular to both x-axis and y-axis is:",
         "options": ["x = 1, y = 0 (z varies)", "y = 0, z = -2", "x = 1, z = -2", "x + y + z = -1"],
         "answer": "x = 1, y = 0 (z varies)"},
        {"question": "The maximum of Z = 5x + 3y at (4, 0), (2, 3), (0, 3), (0, 0), (4, 0) corners is:",
         "options": ["12", "19", "20", "24"], "answer": "20"},
        {"question": "The number of all possible one-one functions from {1,2,3} to {a,b,c,d} is:",
         "options": ["12", "24", "64", "81"], "answer": "24"},
        {"question": "If y = sin⁻¹(2x/(1 + x²)) for |x| < 1, then dy/dx is:",
         "options": ["2/(1 + x²)", "1/(1 + x²)", "2/(1 - x²)", "-2/(1 + x²)"],
         "answer": "2/(1 + x²)"},
        {"question": "The value of ∫₀¹ (1 - x)ⁿ dx is:",
         "options": ["1/n", "1/(n + 1)", "n/(n + 1)", "1/n²"], "answer": "1/(n + 1)"},
        {"question": "If A(2, 3, 5), B(-1, 3, 2) are two points, the direction cosines of AB are:",
         "options": ["(-3, 0, -3)/√18", "(3, 0, 3)/√18", "(-1, 1, -1)", "(1, 0, 1)"],
         "answer": "(-3, 0, -3)/√18"},
    ]
}

replacements = {47: WEEK_47, 48: WEEK_48, 49: WEEK_49, 50: WEEK_50, 51: WEEK_51, 52: WEEK_52}

# Splice new weeks into maths-higher/12
g12 = maths_h['12']
new_g12 = []
for w in g12:
    wk = w.get('week')
    if wk in replacements:
        new_g12.append(replacements[wk])
    else:
        new_g12.append(w)
maths_h['12'] = new_g12

# Verify: each replaced week has 25 Qs, 4 options each, answer in options, no dup options, no short Qs
for wk_num, wk_data in replacements.items():
    qs = wk_data['questions']
    assert len(qs) == 25, f"Week {wk_num}: {len(qs)} questions (expected 25)"
    for i, q in enumerate(qs):
        assert len(q['options']) == 4, f"wk{wk_num}/Q{i+1}: {len(q['options'])} options"
        assert q['answer'] in q['options'], f"wk{wk_num}/Q{i+1}: answer not in options"
        assert len(set(q['options'])) == 4, f"wk{wk_num}/Q{i+1}: duplicate options"
        assert len(q['question']) >= 15, f"wk{wk_num}/Q{i+1}: question too short: {q['question']!r}"

(DATA / 'maths-higher-quizzes.json').write_text(json.dumps(maths_h, ensure_ascii=False, indent=2))
print(f"✓ Replaced {len(replacements) * 25} questions across maths-higher/12 wk47-52 with NCERT revision content")
print(f"✓ wrote src/data/maths-higher-quizzes.json")
