#!/usr/bin/env python3
"""Replace placeholder questions in physics/11 weeks 7-14 with real NCERT MCQs.
Topics: Motion in a Plane (Vectors, Projectile, Circular) + Laws of Motion."""
import json
from pathlib import Path

DATA = Path("src/data/physics-quizzes.json")

# Compact MCQ format: (question, [A, B, C, D], correct_answer_string)
QS = {
    # ===== Week 7: Motion in a Plane – Scalars & Vectors, Vector Addition =====
    7: [
        ("Which of the following is a scalar quantity?", ["Velocity", "Displacement", "Speed", "Acceleration"], "Speed"),
        ("Which of the following is a vector quantity?", ["Mass", "Temperature", "Work", "Force"], "Force"),
        ("The magnitude of the resultant of two vectors of magnitudes 3 and 4 acting at right angles is:", ["1", "5", "7", "12"], "5"),
        ("If two vectors of equal magnitude P make an angle of 60° with each other, the magnitude of their resultant is:", ["P", "√2 P", "√3 P", "2P"], "√3 P"),
        ("The resultant of two vectors is maximum when the angle between them is:", ["0°", "45°", "90°", "180°"], "0°"),
        ("The resultant of two vectors is minimum when the angle between them is:", ["0°", "90°", "180°", "270°"], "180°"),
        ("Two equal vectors have a resultant equal in magnitude to either. The angle between them is:", ["60°", "90°", "120°", "180°"], "120°"),
        ("Vector addition obeys which of the following laws?", ["Commutative only", "Associative only", "Both commutative and associative", "Neither"], "Both commutative and associative"),
        ("A unit vector is a vector whose magnitude is:", ["0", "1", "Variable", "Depends on direction"], "1"),
        ("The unit vector along the x-axis is denoted by:", ["ĵ", "k̂", "î", "r̂"], "î"),
        ("If A⃗ = 3î + 4ĵ, the magnitude of A⃗ is:", ["3", "4", "5", "7"], "5"),
        ("The angle θ that A⃗ = î + ĵ makes with the x-axis is:", ["0°", "30°", "45°", "90°"], "45°"),
        ("Null vector has magnitude:", ["1", "0", "Undefined", "∞"], "0"),
        ("Two vectors are said to be equal if they have:", ["Same magnitude only", "Same direction only", "Same magnitude and same direction", "Same initial point"], "Same magnitude and same direction"),
        ("The parallelogram law of vector addition gives the resultant R of vectors P and Q inclined at angle θ as:", ["P + Q", "√(P² + Q² + 2PQcosθ)", "√(P² + Q² − 2PQcosθ)", "P² + Q²"], "√(P² + Q² + 2PQcosθ)"),
        ("Three vectors each of magnitude A are in equilibrium. The angle between any two is:", ["60°", "90°", "120°", "180°"], "120°"),
        ("If |A⃗ + B⃗| = |A⃗ − B⃗|, then the angle between A⃗ and B⃗ is:", ["0°", "45°", "90°", "180°"], "90°"),
        ("Which of the following cannot be the resultant of two vectors of magnitudes 3 N and 5 N?", ["2 N", "5 N", "8 N", "9 N"], "9 N"),
        ("A vector whose magnitude is same but direction is opposite is called:", ["Unit vector", "Null vector", "Negative vector", "Position vector"], "Negative vector"),
        ("Position vector gives:", ["Speed of the particle", "Displacement from a reference point", "Acceleration", "Force"], "Displacement from a reference point"),
        ("Two forces of 5 N each act on a body at 90°. The resultant force is:", ["5 N", "5√2 N", "10 N", "7.5 N"], "5√2 N"),
        ("The triangle law of vector addition applies to:", ["Scalars", "Vectors regardless of type", "Only parallel vectors", "Only equal vectors"], "Vectors regardless of type"),
        ("If the resultant of two equal forces is equal to either one, the angle between them is:", ["90°", "120°", "60°", "180°"], "120°"),
        ("Displacement is:", ["A scalar", "A vector", "Always positive", "Path length"], "A vector"),
        ("Electric current has magnitude and direction but is called a scalar because:", ["It is very small", "It does not obey vector addition rules", "It always acts along the wire", "It is negative"], "It does not obey vector addition rules"),
    ],
    # ===== Week 8: Motion in a Plane – Resolution of Vectors, Dot & Cross Product =====
    8: [
        ("The component of a vector A along a direction making angle θ with it is:", ["A sinθ", "A cosθ", "A tanθ", "A/cosθ"], "A cosθ"),
        ("If A⃗ = 3î + 4ĵ, its x-component is:", ["3", "4", "5", "7"], "3"),
        ("The dot product A⃗·B⃗ of two vectors is:", ["AB sinθ", "AB cosθ", "ABtanθ", "A + B"], "AB cosθ"),
        ("The cross product A⃗×B⃗ has magnitude:", ["AB cosθ", "AB sinθ", "AB tanθ", "A + B"], "AB sinθ"),
        ("For perpendicular vectors A⃗ and B⃗:", ["A⃗·B⃗ = 0", "A⃗×B⃗ = 0", "A⃗·B⃗ = AB", "|A⃗×B⃗|=0"], "A⃗·B⃗ = 0"),
        ("For parallel vectors A⃗ and B⃗:", ["A⃗·B⃗ = 0", "A⃗×B⃗ = 0", "A⃗·B⃗ = −AB", "A⃗·B⃗ = ∞"], "A⃗×B⃗ = 0"),
        ("The dot product is:", ["A vector", "A scalar", "Zero always", "Imaginary"], "A scalar"),
        ("The cross product is:", ["A scalar", "A vector", "Always zero", "Negative"], "A vector"),
        ("î·î equals:", ["0", "1", "î", "ĵ"], "1"),
        ("î×ĵ equals:", ["0", "1", "î", "k̂"], "k̂"),
        ("The angle between A⃗ = î + ĵ and B⃗ = î − ĵ is:", ["0°", "45°", "90°", "180°"], "90°"),
        ("If A⃗·B⃗ = AB, the angle between them is:", ["0°", "90°", "180°", "45°"], "0°"),
        ("The work done by a force F⃗ in displacement s⃗ is:", ["F⃗×s⃗", "F⃗·s⃗", "F·s·tanθ", "F/s"], "F⃗·s⃗"),
        ("Torque is defined as:", ["F⃗·r⃗", "r⃗×F⃗", "r⃗+F⃗", "r⃗−F⃗"], "r⃗×F⃗"),
        ("For A⃗ = 2î + 3ĵ and B⃗ = î + ĵ, A⃗·B⃗ equals:", ["5", "6", "3", "1"], "5"),
        ("Vectors are resolved into components because:", ["They look nicer", "Independent analysis along axes simplifies problems", "It avoids vector notation", "Components are scalars"], "Independent analysis along axes simplifies problems"),
        ("The magnitude of a vector in 3D with components (a, b, c) is:", ["a + b + c", "√(a² + b² + c²)", "abc", "a² + b² + c²"], "√(a² + b² + c²)"),
        ("If A⃗×B⃗ = 0 (both non-zero), then A⃗ and B⃗ are:", ["Perpendicular", "Anti-parallel", "Parallel or anti-parallel", "Random"], "Parallel or anti-parallel"),
        ("The angle between A⃗ and B⃗ when A⃗·B⃗ = −|A⃗||B⃗|:", ["0°", "90°", "180°", "45°"], "180°"),
        ("A·B = B·A because the dot product is:", ["Anti-commutative", "Commutative", "Non-associative", "Undefined"], "Commutative"),
        ("A×B = −B×A because the cross product is:", ["Commutative", "Anti-commutative", "Zero", "Associative only"], "Anti-commutative"),
        ("If a force 10 N makes 60° with the x-axis, its x-component is:", ["5 N", "10 N", "8.66 N", "0"], "5 N"),
        ("If a force 10 N makes 60° with the x-axis, its y-component is:", ["5 N", "10 N", "8.66 N", "0"], "8.66 N"),
        ("Area of parallelogram with sides A⃗ and B⃗ equals:", ["A⃗·B⃗", "|A⃗×B⃗|", "|A⃗||B⃗|cosθ", "A+B"], "|A⃗×B⃗|"),
        ("Volume of parallelepiped formed by A⃗, B⃗, C⃗ equals:", ["A⃗·(B⃗×C⃗)", "A⃗×B⃗×C⃗", "A⃗+B⃗+C⃗", "A⃗·B⃗·C⃗"], "A⃗·(B⃗×C⃗)"),
    ],
    # ===== Week 9: Motion in a Plane – Projectile Motion =====
    9: [
        ("Path of a projectile (ignoring air resistance) is:", ["Straight line", "Circle", "Parabola", "Ellipse"], "Parabola"),
        ("Maximum range of a projectile is achieved at angle of projection:", ["30°", "45°", "60°", "90°"], "45°"),
        ("At the highest point of a projectile motion, the velocity is:", ["Zero", "Horizontal component only", "Vertical component only", "Maximum"], "Horizontal component only"),
        ("At the highest point of a projectile, acceleration is:", ["Zero", "g downward", "g upward", "Horizontal"], "g downward"),
        ("Time of flight for a projectile with initial velocity u at angle θ is:", ["u sinθ/g", "2u sinθ/g", "u²sin2θ/g", "u²/g"], "2u sinθ/g"),
        ("Maximum height of a projectile is:", ["u sinθ/g", "u²sin²θ/(2g)", "u²sin2θ/g", "2u sinθ/g"], "u²sin²θ/(2g)"),
        ("Range of a projectile is:", ["u sinθ/g", "u²sin²θ/(2g)", "u²sin2θ/g", "u sin2θ/g"], "u²sin2θ/g"),
        ("A projectile fired at 30° and 60° with same u have:", ["Same range", "Same height", "Same time of flight", "Same velocity at peak"], "Same range"),
        ("For maximum range on level ground, the ratio of max height to range is:", ["1/2", "1/4", "1", "2"], "1/4"),
        ("A stone is thrown horizontally with velocity 10 m/s from a cliff of height 80 m. Time to reach ground (g=10):", ["2 s", "4 s", "8 s", "16 s"], "4 s"),
        ("In the above case the horizontal range is:", ["20 m", "40 m", "80 m", "160 m"], "40 m"),
        ("A projectile has range R and max height H. Angle of projection satisfies:", ["tanθ = 2H/R", "tanθ = 4H/R", "tanθ = R/H", "tanθ = H/R"], "tanθ = 4H/R"),
        ("A body projected at 45° with u = 20 m/s; max height is (g=10):", ["5 m", "10 m", "20 m", "40 m"], "10 m"),
        ("A body projected at 45° with u = 20 m/s has range:", ["20 m", "40 m", "10 m", "80 m"], "40 m"),
        ("A projectile is thrown vertically upward with 20 m/s. Time of flight (g=10):", ["1 s", "2 s", "4 s", "8 s"], "4 s"),
        ("Horizontal component of velocity of a projectile:", ["Increases", "Decreases", "Remains constant", "Becomes zero at top"], "Remains constant"),
        ("Vertical component of velocity at highest point is:", ["u", "u sinθ", "0", "u cosθ"], "0"),
        ("If air resistance is considered, the range of a projectile:", ["Increases", "Decreases", "Stays same", "Becomes zero"], "Decreases"),
        ("A ball is projected with velocity 10 m/s at 60°. Time to reach max height (g=10):", ["0.5 s", "√3/2 s", "√3 s", "1 s"], "√3/2 s"),
        ("The trajectory y = ax − bx² represents:", ["Circle", "Parabolic motion of a projectile", "SHM", "Straight line"], "Parabolic motion of a projectile"),
        ("Two projectiles with angles θ and (90°−θ) have:", ["Equal heights", "Equal ranges", "Equal times of flight", "Equal speeds at peak"], "Equal ranges"),
        ("At maximum height, kinetic energy of the projectile is:", ["Zero", "Maximum", "½mu²cos²θ", "½mu²"], "½mu²cos²θ"),
        ("Total energy of a projectile at any point (no air resistance) is:", ["Variable", "Constant", "Zero at top", "Maximum at top"], "Constant"),
        ("A stone is dropped from a moving plane (horizontal). To an observer on the plane the stone moves:", ["In a parabola", "Vertically downward", "Horizontally", "In a circle"], "Vertically downward"),
        ("If a projectile is fired at 45° with u=40 m/s, max range (g=10) is:", ["80 m", "160 m", "200 m", "320 m"], "160 m"),
    ],
    # ===== Week 10: Motion in a Plane – Uniform Circular Motion =====
    10: [
        ("In uniform circular motion, which is constant?", ["Velocity", "Acceleration", "Speed", "Displacement"], "Speed"),
        ("Centripetal acceleration is directed:", ["Tangentially", "Away from centre", "Toward the centre", "Along velocity"], "Toward the centre"),
        ("Centripetal acceleration = ", ["v/r", "v²/r", "vr", "r/v²"], "v²/r"),
        ("Angular velocity ω relates to linear velocity v by:", ["v = ω/r", "v = ωr", "v = ω²r", "v = r/ω"], "v = ωr"),
        ("Period T of uniform circular motion is:", ["2π/ω", "ω/2π", "2πr", "ω·r"], "2π/ω"),
        ("Frequency f equals:", ["2π/T", "1/T", "T", "ωT"], "1/T"),
        ("Centripetal force on a body moving in a circle of radius r with speed v is:", ["mv²/r", "mvr", "m/v²r", "mv/r²"], "mv²/r"),
        ("A car of mass 1000 kg moves in a circle of radius 50 m at 10 m/s. The centripetal force is:", ["100 N", "1000 N", "2000 N", "5000 N"], "2000 N"),
        ("A satellite moving in a circular orbit experiences which net force?", ["Zero", "Gravitational pull of Earth", "Air drag", "Magnetic force"], "Gravitational pull of Earth"),
        ("In uniform circular motion, the work done by the centripetal force in one revolution is:", ["Maximum", "Minimum", "Zero", "½mv²"], "Zero"),
        ("Tangential acceleration in uniform circular motion is:", ["v²/r", "zero", "g", "ωr"], "zero"),
        ("If ω is constant, the direction of velocity:", ["Is constant", "Changes continuously", "Reverses every cycle", "Is zero"], "Changes continuously"),
        ("For a particle moving with ω = 2 rad/s in a circle of radius 0.5 m, speed is:", ["0.25 m/s", "0.5 m/s", "1 m/s", "4 m/s"], "1 m/s"),
        ("Centripetal force is:", ["A real new type of force", "A component of net force directed to centre", "Always friction", "Always gravity"], "A component of net force directed to centre"),
        ("A stone tied to a string whirled in a horizontal circle; the string tension provides:", ["Tangential force", "Centripetal force", "Zero", "Gravity"], "Centripetal force"),
        ("If the speed of circular motion doubles, centripetal acceleration becomes:", ["Half", "Same", "Double", "Four times"], "Four times"),
        ("Relation between angular and linear acceleration in circular motion:", ["a = α/r", "a = αr", "a = α+r", "a = α²r"], "a = αr"),
        ("A conical pendulum moves in a horizontal circle. The component providing centripetal force is:", ["Tension cosθ", "Tension sinθ", "mg", "mg sinθ"], "Tension sinθ"),
        ("If radius is doubled and speed kept constant, centripetal force becomes:", ["Half", "Double", "Same", "Four times"], "Half"),
        ("Angular velocity of Earth about its own axis (in rad/s) is approximately:", ["7.27×10⁻⁵", "1.16×10⁻⁵", "2π", "π/12"], "7.27×10⁻⁵"),
        ("For uniform circular motion, velocity and acceleration are:", ["Parallel", "Anti-parallel", "Perpendicular", "Same vectors"], "Perpendicular"),
        ("An object moves in a circle with changing speed. It has:", ["Only centripetal acceleration", "Only tangential acceleration", "Both centripetal and tangential", "No acceleration"], "Both centripetal and tangential"),
        ("A car moving at 20 m/s on a curve of radius 50 m experiences centripetal acceleration:", ["4 m/s²", "8 m/s²", "10 m/s²", "20 m/s²"], "8 m/s²"),
        ("Unit of angular velocity is:", ["m/s", "m/s²", "rad/s", "rad"], "rad/s"),
        ("The minimum speed at the top of a vertical circle (radius r) for string taut (g=10 m/s², r=0.4 m):", ["1 m/s", "2 m/s", "4 m/s", "20 m/s"], "2 m/s"),
    ],
    # ===== Week 11: Laws of Motion – Newton's First & Second Laws, Inertia =====
    11: [
        ("Newton's first law is also called the law of:", ["Action-reaction", "Inertia", "Conservation of energy", "Gravity"], "Inertia"),
        ("Inertia of a body depends on its:", ["Velocity", "Acceleration", "Mass", "Shape"], "Mass"),
        ("Newton's second law states F =", ["ma", "m/a", "m·v", "m·s"], "ma"),
        ("The SI unit of force is:", ["Newton", "Dyne", "kg", "joule"], "Newton"),
        ("1 Newton equals:", ["1 kg·m/s", "1 kg·m/s²", "1 kg/m²", "1 kg·m²/s²"], "1 kg·m/s²"),
        ("If a force of 10 N acts on a 2 kg object, the acceleration is:", ["2 m/s²", "5 m/s²", "10 m/s²", "20 m/s²"], "5 m/s²"),
        ("Momentum of a body is:", ["m/v", "mv", "m+v", "½mv²"], "mv"),
        ("Force is the rate of change of:", ["Mass", "Velocity", "Momentum", "Energy"], "Momentum"),
        ("Impulse equals:", ["Force × displacement", "Force × time", "Force / time", "Work / time"], "Force × time"),
        ("Impulse has the same units as:", ["Force", "Energy", "Momentum", "Power"], "Momentum"),
        ("A body of mass 5 kg initially at rest is acted on by force 20 N for 3 s. Final velocity:", ["4 m/s", "8 m/s", "12 m/s", "15 m/s"], "12 m/s"),
        ("The law of inertia is stated correctly by which of the following?", ["Every body continues in its state of rest or uniform motion in a straight line unless compelled by an external force to change that state", "Every action has an equal reaction", "Force equals mass times acceleration", "Momentum is conserved"], "Every body continues in its state of rest or uniform motion in a straight line unless compelled by an external force to change that state"),
        ("If the net external force on a body is zero, the body is:", ["At rest only", "Moving uniformly only", "Either at rest or moving uniformly", "Accelerating"], "Either at rest or moving uniformly"),
        ("A cricket player lowers his hands while catching a ball to:", ["Increase force", "Reduce time and increase force", "Increase time and reduce force", "Keep force constant"], "Increase time and reduce force"),
        ("An object of 2 kg moves with velocity 3 m/s. Its momentum is:", ["1.5 kg·m/s", "5 kg·m/s", "6 kg·m/s", "9 kg·m/s"], "6 kg·m/s"),
        ("When a bus starts suddenly, passengers tend to fall backward. This is due to:", ["Inertia of motion", "Inertia of rest", "Action-reaction", "Friction"], "Inertia of rest"),
        ("When a bus stops suddenly, passengers tend to fall forward because of:", ["Inertia of rest", "Inertia of motion", "Gravity", "Friction"], "Inertia of motion"),
        ("Newton's second law in vector form is:", ["F⃗ = m a⃗", "F⃗ = m/a⃗", "F⃗ = m·v⃗", "F⃗ = m·g"], "F⃗ = m a⃗"),
        ("Force applied on a 10 kg object accelerating at 2 m/s²:", ["5 N", "10 N", "20 N", "50 N"], "20 N"),
        ("If the same force acts on two bodies of different masses, the one with greater mass has:", ["Greater acceleration", "Smaller acceleration", "Same acceleration", "Zero acceleration"], "Smaller acceleration"),
        ("A body weighs 20 N on Earth. Its mass is (g=10 m/s²):", ["1 kg", "2 kg", "10 kg", "20 kg"], "2 kg"),
        ("Dimensional formula of force is:", ["MLT⁻¹", "MLT⁻²", "ML²T⁻²", "ML²T⁻¹"], "MLT⁻²"),
        ("Newton's first law defines:", ["Force and inertia", "Energy", "Momentum", "Work"], "Force and inertia"),
        ("If the impulse delivered to an object is 10 N·s, its change in momentum is:", ["1 kg·m/s", "5 kg·m/s", "10 kg·m/s", "100 kg·m/s"], "10 kg·m/s"),
        ("A rocket ejects gas to propel itself. This demonstrates:", ["First law", "Inertia", "Conservation of momentum and Newton's laws", "Gravity"], "Conservation of momentum and Newton's laws"),
    ],
    # ===== Week 12: Laws of Motion – Newton's Third Law, Free Body Diagrams =====
    12: [
        ("Newton's third law states that:", ["Every action has an equal and opposite reaction", "Every force causes acceleration", "Every body has mass", "Force = rate of change of momentum"], "Every action has an equal and opposite reaction"),
        ("Action and reaction forces act on:", ["Same body", "Different bodies", "Same direction", "Air"], "Different bodies"),
        ("A book resting on a table: reaction to book's weight (gravity) is:", ["Normal force from table", "The pull book exerts on Earth", "Friction", "None"], "The pull book exerts on Earth"),
        ("When a rocket moves up, the gas is expelled:", ["Upward", "Sideways", "Downward", "Nowhere"], "Downward"),
        ("A free body diagram shows:", ["All forces on one body", "All bodies in the system", "Only gravity", "Only friction"], "All forces on one body"),
        ("The normal reaction on a body on a horizontal surface equals its weight when:", ["Body is accelerating", "Surface is smooth only", "No other vertical force is present", "There is friction"], "No other vertical force is present"),
        ("A person pushes a wall with 50 N. Force on person is:", ["25 N", "50 N", "100 N", "0"], "50 N"),
        ("Two blocks A (2 kg) and B (3 kg) on smooth surface with F=10 N on A pushing B. Acceleration:", ["1 m/s²", "2 m/s²", "3 m/s²", "5 m/s²"], "2 m/s²"),
        ("In the above, force A exerts on B:", ["4 N", "6 N", "10 N", "12 N"], "6 N"),
        ("Tension in a light string attached to a 5 kg mass hanging in equilibrium (g=10 m/s²):", ["25 N", "50 N", "100 N", "500 N"], "50 N"),
        ("When a horse pulls a cart, the cart moves forward because:", ["Action = reaction on different bodies", "Horse exceeds the pull of cart", "The ground pushes back on horse enabling net forward force", "Gravity"], "The ground pushes back on horse enabling net forward force"),
        ("A 2 kg block placed in a lift accelerating up at 2 m/s²; normal reaction is (g=10):", ["16 N", "20 N", "24 N", "40 N"], "24 N"),
        ("A 2 kg block in a lift accelerating down at 2 m/s²; normal reaction:", ["16 N", "20 N", "24 N", "40 N"], "16 N"),
        ("In a free fall, apparent weight is:", ["mg", "0", "2mg", "½mg"], "0"),
        ("A stone thrown horizontally hits a wall. The wall exerts force due to:", ["Only gravity", "Only air", "Newton's third law reaction", "Inertia"], "Newton's third law reaction"),
        ("If action force is 20 N, reaction force is:", ["10 N", "20 N", "40 N", "0"], "20 N"),
        ("In static equilibrium, net force equals:", ["mg", "Weight", "Zero", "Tension"], "Zero"),
        ("Two masses 3 kg and 5 kg connected by a string over a frictionless pulley (Atwood). Acceleration (g=10):", ["0", "2.5 m/s²", "5 m/s²", "7.5 m/s²"], "2.5 m/s²"),
        ("In above Atwood, tension in string:", ["25 N", "30 N", "37.5 N", "50 N"], "37.5 N"),
        ("A man jumps from a boat to the shore. The boat moves backward because of:", ["Gravity", "Friction", "Conservation of momentum (Newton's 3rd law)", "Energy conservation"], "Conservation of momentum (Newton's 3rd law)"),
        ("On a smooth inclined plane of angle θ, acceleration of a block sliding down:", ["g", "g sinθ", "g cosθ", "g tanθ"], "g sinθ"),
        ("On a smooth inclined plane of angle θ, normal reaction on block of mass m:", ["mg", "mg sinθ", "mg cosθ", "mg tanθ"], "mg cosθ"),
        ("A 2 kg block on a smooth incline of 30° accelerates at (g=10):", ["2.5 m/s²", "5 m/s²", "7.5 m/s²", "10 m/s²"], "5 m/s²"),
        ("A 3 kg mass on a rope pulled up with 45 N; acceleration is (g=10):", ["5 m/s²", "10 m/s²", "15 m/s²", "0"], "5 m/s²"),
        ("In equilibrium, sum of forces on a body equals:", ["mg", "0", "Maximum force", "Any value"], "0"),
    ],
    # ===== Week 13: Laws of Motion – Friction (Static, Kinetic, Rolling) =====
    13: [
        ("Friction opposes:", ["Gravity", "Relative motion or tendency of motion", "Normal force", "Inertia"], "Relative motion or tendency of motion"),
        ("Coefficient of static friction μ_s compared to kinetic μ_k is generally:", ["μ_s < μ_k", "μ_s = μ_k", "μ_s > μ_k", "Depends only on surfaces"], "μ_s > μ_k"),
        ("Maximum static friction equals:", ["μ_s·mg", "μ_s·N", "μ_k·N", "N"], "μ_s·N"),
        ("Kinetic friction equals:", ["μ_s·N", "μ_k·N", "μ_k·mg", "μ_r·N"], "μ_k·N"),
        ("A block of mass 5 kg rests on a surface with μ_s=0.4. Minimum force to just move it (g=10):", ["10 N", "15 N", "20 N", "25 N"], "20 N"),
        ("Rolling friction is generally:", ["Largest", "Between static and kinetic", "Smallest", "Same as kinetic"], "Smallest"),
        ("Angle of friction θ and coefficient of friction μ satisfy:", ["μ = sinθ", "μ = cosθ", "μ = tanθ", "μ = secθ"], "μ = tanθ"),
        ("Angle of repose α of a rough incline where μ is the coefficient of friction satisfies:", ["μ = tanα", "μ = sinα", "μ = cosα", "μ = cotα"], "μ = tanα"),
        ("On a rough incline with angle θ greater than angle of repose, the block:", ["Stays at rest", "Slides down", "Moves up", "Hovers"], "Slides down"),
        ("A 2 kg block on a horizontal surface with μ_k=0.2 is given push with 6 N (g=10). Acceleration:", ["0.5 m/s²", "1 m/s²", "2 m/s²", "3 m/s²"], "1 m/s²"),
        ("Friction force when a 2 kg block is pushed with 3 N on a surface with μ_s=0.5 (g=10):", ["3 N", "5 N", "10 N", "Zero"], "3 N"),
        ("If applied force on a stationary block is less than μ_s·N, friction is:", ["Maximum static", "Kinetic", "Equal to applied force", "Zero"], "Equal to applied force"),
        ("Friction depends on:", ["Area of contact only", "Nature of surfaces and normal force", "Mass only", "Gravity only"], "Nature of surfaces and normal force"),
        ("When skidding brakes are used, friction is primarily:", ["Static", "Kinetic", "Rolling", "Fluid"], "Kinetic"),
        ("Advantages of friction include:", ["Walking, writing, braking", "Wear and tear only", "Heat generation only", "Energy loss only"], "Walking, writing, braking"),
        ("To reduce friction, we can use:", ["Lubricants and ball bearings", "Rough surfaces", "Higher normal force", "Adhesives"], "Lubricants and ball bearings"),
        ("A body of mass 10 kg is pulled on a rough horizontal surface (μ=0.1) with force 30 N (g=10). Acceleration:", ["0.5 m/s²", "1 m/s²", "2 m/s²", "3 m/s²"], "2 m/s²"),
        ("Coefficient of rolling friction is typically:", ["0.5", "Larger than 0.5", "0.1 to 0.01", "1"], "0.1 to 0.01"),
        ("A block just slides on incline when tanθ equals:", ["μ_s", "μ_k", "sinθ", "cosθ"], "μ_s"),
        ("A box slides down a 37° incline with μ_k=0.5 (g=10). Acceleration (sin37=0.6, cos37=0.8):", ["1 m/s²", "2 m/s²", "4 m/s²", "6 m/s²"], "2 m/s²"),
        ("A car of mass 1000 kg moving at 10 m/s stops in 5 s on friction alone. Friction force:", ["500 N", "1000 N", "2000 N", "5000 N"], "2000 N"),
        ("In the above, μ_k is (g=10):", ["0.1", "0.2", "0.5", "1"], "0.2"),
        ("Limiting friction is:", ["Kinetic friction", "Max static friction", "Rolling friction", "Always zero"], "Max static friction"),
        ("The friction on a freely rolling wheel is:", ["Static friction at point of contact", "Kinetic friction always", "Rolling friction equal to static max", "Zero always"], "Static friction at point of contact"),
        ("A 5 kg block is pushed horizontally on a rough surface with μ_s=0.3, μ_k=0.2 (g=10). A force of 12 N:", ["Moves the block with 0.4 m/s² acceleration", "Does not move the block", "Moves with 1 m/s²", "Moves with 2 m/s²"], "Moves the block with 0.4 m/s² acceleration"),
    ],
    # ===== Week 14: Laws of Motion – Circular Motion Dynamics, Banking of Roads =====
    14: [
        ("Centripetal force needed for circular motion is provided on a level road by:", ["Tension", "Friction", "Normal reaction", "Gravity"], "Friction"),
        ("Maximum speed on a level circular road with friction coefficient μ and radius r (g=10):", ["√(μrg)", "μrg", "μ/rg", "√(rg/μ)"], "√(μrg)"),
        ("Banking of road helps by:", ["Increasing friction", "Providing component of normal to act as centripetal force", "Reducing weight", "Changing mass"], "Providing component of normal to act as centripetal force"),
        ("Angle of banking θ for speed v and radius r (no friction) satisfies:", ["tanθ = v/rg", "tanθ = v²/rg", "tanθ = rg/v²", "tanθ = v²r/g"], "tanθ = v²/rg"),
        ("For maximum safe speed on a banked road (no friction) with radius 50 m and banking angle 30° (g=10):", ["√(50·10·tan30°)", "√(50·10)", "Same as level road", "50·tan30°"], "√(50·10·tan30°)"),
        ("On a rough banked road, maximum safe speed is:", ["Same as no friction", "Smaller than no friction case", "Larger than no friction case", "Independent of θ"], "Larger than no friction case"),
        ("Conical pendulum: tension T provides:", ["Only weight", "Horizontal centripetal and vertical weight components", "Only centripetal", "Zero"], "Horizontal centripetal and vertical weight components"),
        ("In vertical circle, minimum speed at top of loop (radius r, g=10) for string taut:", ["√(rg)", "√(2rg)", "√(3rg)", "√(5rg)"], "√(rg)"),
        ("Minimum speed at bottom of loop for completing full vertical circle:", ["√(2rg)", "√(3rg)", "√(5rg)", "√(rg)"], "√(5rg)"),
        ("Difference in tension at top and bottom of a vertical loop equals:", ["2mg", "4mg", "6mg", "8mg"], "6mg"),
        ("A car rounding a curve on a banked road needs:", ["Larger μ if banking is sufficient", "No friction if banked for design speed", "More fuel", "Nothing"], "No friction if banked for design speed"),
        ("For a motorcyclist on a circular track, lean angle θ for speed v and radius r:", ["tanθ = v/rg", "tanθ = v²/rg", "tanθ = rg/v²", "tanθ = v·r·g"], "tanθ = v²/rg"),
        ("A 1000 kg car moves at 20 m/s round a curve of radius 100 m. Centripetal force:", ["1000 N", "2000 N", "4000 N", "8000 N"], "4000 N"),
        ("In above case, coefficient of friction required (g=10):", ["0.1", "0.2", "0.4", "0.8"], "0.4"),
        ("The outer rail of a curved railway track is:", ["Lower", "Higher", "Same level", "Removed"], "Higher"),
        ("A stone tied to a string of length 1 m is whirled in a vertical circle. Minimum speed at top (g=10):", ["2 m/s", "√10 m/s", "5 m/s", "10 m/s"], "√10 m/s"),
        ("Minimum speed at bottom in above case:", ["√10 m/s", "√30 m/s", "√50 m/s", "10 m/s"], "√50 m/s"),
        ("Maximum speed on a level road of μ=0.5, r=20 m (g=10):", ["10 m/s", "√100 m/s", "20 m/s", "5 m/s"], "10 m/s"),
        ("A car moves on a banked track at design speed. Friction required is:", ["Maximum", "Equal to weight", "Zero", "μ·N"], "Zero"),
        ("Period of a conical pendulum of length L and half-angle θ:", ["2π√(L/g)", "2π√(L cosθ/g)", "2π√(L sinθ/g)", "2π√(g/L)"], "2π√(L cosθ/g)"),
        ("In uniform circular motion on a rough banked curve with angle θ and coefficient μ, max speed is:", ["√[rg(tanθ+μ)/(1−μ tanθ)]", "√(rg tanθ)", "√(rg μ)", "√(rg)"], "√[rg(tanθ+μ)/(1−μ tanθ)]"),
        ("A cyclist goes round a curve of radius 10 m at 5 m/s. Lean angle (g=10):", ["tan⁻¹(1/4)", "tan⁻¹(1/2)", "tan⁻¹(1)", "45°"], "tan⁻¹(1/4)"),
        ("For circular motion, external centripetal force must be provided by:", ["Normal force alone", "Component of some real force toward centre", "Friction only", "Gravity only"], "Component of some real force toward centre"),
        ("A car moving at 15 m/s on a flat curve of radius 45 m needs a minimum μ of (g=10):", ["0.25", "0.5", "0.75", "1"], "0.5"),
        ("If a car enters a curve too fast on a banked road (v > v_design) without friction, it will tend to:", ["Slide inward", "Slide outward", "Stop", "Stay fine"], "Slide outward"),
    ],
}


def main():
    d = json.loads(DATA.read_text())
    total = 0
    for wk, qlist in QS.items():
        assert len(qlist) == 25, f"Week {wk} has {len(qlist)} questions"
        week_entry = next(w for w in d["11"] if w["week"] == wk)
        new_qs = []
        for q, opts, ans in qlist:
            assert ans in opts, f"Week {wk}: answer '{ans}' not in options"
            new_qs.append({"question": q, "options": opts, "answer": ans})
        week_entry["questions"] = new_qs
        total += 25
    DATA.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
    print(f"Replaced {total} physics/11 placeholder questions across {len(QS)} weeks: {sorted(QS.keys())}")


if __name__ == "__main__":
    main()
