#!/usr/bin/env python3
"""Replace placeholders in chemistry/11 weeks 27-39 (325 MCQs).

Coverage:
- wk27: Electronic effects (I, R, H, E)
- wk28: Types of reactions (substitution, addition, elimination)
- wk29: Alkanes (prep, properties, reactions)
- wk30: Alkenes (prep, Markovnikov, peroxide effect)
- wk31: Alkynes (prep, acidity, addition)
- wk32: Aromatic (benzene, EAS, directive effects)
- wk33: Gas laws (Boyle, Charles, Avogadro, Gay-Lussac, Dalton)
- wk34: Ideal gas, KMT, real gases (van der Waals)
- wk35: Liquids (vapour pressure, surface tension, viscosity)
- wk36: Hydrogen, isotopes, water, H2O2
- wk37: Group 1 alkali metals
- wk38: Group 2 alkaline earth metals
- wk39: Group 13 boron family
"""
import json, pathlib, sys

PATH = pathlib.Path("src/data/chemistry-quizzes.json")

QS = {
27: [
 ("What is the inductive effect?",
  ["Permanent polarisation of σ-bond due to EN difference","Delocalisation of π-electrons","Overlap of σ-bond with π-bond","Resonance effect"],
  "Permanent polarisation of σ-bond due to EN difference"),
 ("Which group shows +I effect (electron donating)?",
  ["−CH₃","−NO₂","−COOH","−Cl"],"−CH₃"),
 ("Which group shows −I effect (electron withdrawing)?",
  ["−NO₂","−CH₃","−C₂H₅","−C(CH₃)₃"],"−NO₂"),
 ("Order of +I effect:",
  ["−C(CH₃)₃ > −CH(CH₃)₂ > −C₂H₅ > −CH₃","−CH₃ > −C₂H₅ > −C(CH₃)₃","−NO₂ > −CN > −COOH","−Cl > −Br > −I"],
  "−C(CH₃)₃ > −CH(CH₃)₂ > −C₂H₅ > −CH₃"),
 ("Order of −I effect (strongest first):",
  ["−NO₂ > −CN > −SO₃H > −COOH > −F","−CH₃ > −NH₂ > −OH","−F > −CH₃ > −H","−I > −Br > −Cl > −F"],
  "−NO₂ > −CN > −SO₃H > −COOH > −F"),
 ("Inductive effect decreases with:",
  ["Distance (becomes negligible after 3rd C)","Increasing temperature","Increasing pressure","Molecular weight"],"Distance (becomes negligible after 3rd C)"),
 ("Resonance effect involves delocalisation of:",
  ["π-electrons or lone pairs","σ-electrons only","Nuclei","Inner shell electrons"],"π-electrons or lone pairs"),
 ("+R (+M) groups are:",
  ["Electron donating via resonance (−OH, −NH₂, −OR, −X)","Electron withdrawing","Non-polar","Acidic"],"Electron donating via resonance (−OH, −NH₂, −OR, −X)"),
 ("−R (−M) groups are:",
  ["Electron withdrawing via resonance (−NO₂, −CN, −COOH, −CHO)","Electron donating","Alkyl groups","Halogens"],"Electron withdrawing via resonance (−NO₂, −CN, −COOH, −CHO)"),
 ("Which shows both +I and +M effect?",
  ["−OR","−NO₂","−CN","−COOH"],"−OR"),
 ("Hyperconjugation is also called:",
  ["Baker-Nathan effect / no-bond resonance","Resonance effect","Inductive effect","Electromeric effect"],"Baker-Nathan effect / no-bond resonance"),
 ("Hyperconjugation involves:",
  ["σ-C-H bond overlap with adjacent π-bond or p-orbital","Only π-bonds","Only σ-bonds","Lone pairs"],"σ-C-H bond overlap with adjacent π-bond or p-orbital"),
 ("Stability of alkenes by hyperconjugation (α-H):",
  ["More α-H → more stable","Less α-H → more stable","Not related","Depends on chain length"],"More α-H → more stable"),
 ("Number of α-H in 2-methylbut-2-ene ((CH₃)₂C=CHCH₃):",
  ["9","6","3","12"],"9"),
 ("Stability order of carbocations:",
  ["3° > 2° > 1° > CH₃⁺","CH₃⁺ > 1° > 2° > 3°","1° > 2° > 3°","All equal"],"3° > 2° > 1° > CH₃⁺"),
 ("Tertiary carbocation is most stable due to:",
  ["Hyperconjugation and +I of alkyl groups","Resonance only","Low mass","High EN"],"Hyperconjugation and +I of alkyl groups"),
 ("Stability order of free radicals:",
  ["3° > 2° > 1° > CH₃·","CH₃· > 1° > 2° > 3°","All equal","1° > 2° > 3°"],"3° > 2° > 1° > CH₃·"),
 ("Stability order of carbanions:",
  ["CH₃⁻ > 1° > 2° > 3° (opposite of carbocation)","3° > 2° > 1° > CH₃⁻","All equal","1° > 2° > 3°"],"CH₃⁻ > 1° > 2° > 3° (opposite of carbocation)"),
 ("Electromeric effect (E effect) is:",
  ["Temporary shift of π-e⁻ in presence of attacking reagent","Permanent polarisation","Resonance","Hyperconjugation"],"Temporary shift of π-e⁻ in presence of attacking reagent"),
 ("+E effect is observed when attacking reagent is:",
  ["Electrophile","Nucleophile","Radical","Base"],"Electrophile"),
 ("Benzyl cation stability is due to:",
  ["Resonance with benzene ring","Inductive effect only","Hyperconjugation","H-bonding"],"Resonance with benzene ring"),
 ("Allyl cation stabilised by:",
  ["Resonance with adjacent C=C","Inductive effect","H-bonding","Lone pair"],"Resonance with adjacent C=C"),
 ("Acidity of carboxylic acids increases with:",
  ["−I groups (Cl, NO₂) near COOH","+I groups (alkyl)","Increasing chain length","Presence of −NH₂"],"−I groups (Cl, NO₂) near COOH"),
 ("Order of acidity: HCOOH, CH₃COOH, ClCH₂COOH, CCl₃COOH:",
  ["CCl₃COOH > ClCH₂COOH > HCOOH > CH₃COOH","CH₃COOH > HCOOH > ClCH₂COOH > CCl₃COOH","All equal","HCOOH > CCl₃COOH"],"CCl₃COOH > ClCH₂COOH > HCOOH > CH₃COOH"),
 ("Basicity order of amines in gas phase:",
  ["3° > 2° > 1° > NH₃ (follows +I)","NH₃ > 1° > 2° > 3°","All equal","2° > 3° > 1°"],"3° > 2° > 1° > NH₃ (follows +I)"),
],
28: [
 ("Substitution reaction involves:",
  ["Replacement of an atom/group by another","Addition of atoms","Removal to form π-bond","Rearrangement only"],"Replacement of an atom/group by another"),
 ("SN1 reaction proceeds via:",
  ["Carbocation intermediate, two steps","Single step","Carbanion","Free radical"],"Carbocation intermediate, two steps"),
 ("SN2 reaction is:",
  ["One-step, bimolecular, backside attack with inversion","Two-step","Unimolecular","Free-radical"],"One-step, bimolecular, backside attack with inversion"),
 ("SN1 is favoured by:",
  ["3° substrates, polar protic solvents","1° substrates","Non-polar solvents","Low T"],"3° substrates, polar protic solvents"),
 ("SN2 is favoured by:",
  ["1° substrates, polar aprotic solvents, strong nucleophile","3° substrates","Carbocation stability","Heat alone"],"1° substrates, polar aprotic solvents, strong nucleophile"),
 ("Walden inversion is observed in:",
  ["SN2 reactions","SN1","E1","E2"],"SN2 reactions"),
 ("Racemisation occurs in:",
  ["SN1 reactions (planar carbocation attacked from both sides)","SN2","E1","E2"],"SN1 reactions (planar carbocation attacked from both sides)"),
 ("Addition reaction is characteristic of:",
  ["Unsaturated compounds (alkenes, alkynes, carbonyls)","Alkanes","Aromatics","Alcohols"],"Unsaturated compounds (alkenes, alkynes, carbonyls)"),
 ("Electrophilic addition to alkene (HBr) gives:",
  ["Markovnikov product (H to less-sub C, Br to more-sub C)","Anti-Markovnikov","Radical addition","No reaction"],"Markovnikov product (H to less-sub C, Br to more-sub C)"),
 ("Nucleophilic addition occurs in:",
  ["Carbonyl compounds (aldehydes/ketones)","Alkenes","Alkanes","Aromatics"],"Carbonyl compounds (aldehydes/ketones)"),
 ("Free radical addition occurs with:",
  ["HBr + peroxide (anti-Markovnikov, Kharasch effect)","HCl + peroxide","HI + peroxide","All acids"],"HBr + peroxide (anti-Markovnikov, Kharasch effect)"),
 ("Elimination E1 involves:",
  ["Carbocation, two steps","Single step concerted","Carbanion","Radical"],"Carbocation, two steps"),
 ("Elimination E2 is:",
  ["One-step, bimolecular, anti-periplanar","Two-step","Carbanion mechanism","Radical mechanism"],"One-step, bimolecular, anti-periplanar"),
 ("Saytzeff rule states:",
  ["More substituted alkene is major product","Less substituted alkene is major","Equal amounts","Only cis"],"More substituted alkene is major product"),
 ("Hofmann rule gives:",
  ["Less substituted alkene (with bulky base)","More substituted","Equal amounts","Only trans"],"Less substituted alkene (with bulky base)"),
 ("Electrophiles are:",
  ["Electron-deficient species (Lewis acids)","Electron-rich","Neutral","Radicals"],"Electron-deficient species (Lewis acids)"),
 ("Nucleophiles are:",
  ["Electron-rich species (Lewis bases)","Electron-deficient","Neutral","Radicals"],"Electron-rich species (Lewis bases)"),
 ("Example of electrophile:",
  ["NO₂⁺, H⁺, Cl⁺","OH⁻, NH₃","H₂O","RO⁻"],"NO₂⁺, H⁺, Cl⁺"),
 ("Example of nucleophile:",
  ["OH⁻, CN⁻, NH₃, H₂O","H⁺, NO₂⁺","AlCl₃","Br⁺"],"OH⁻, CN⁻, NH₃, H₂O"),
 ("Rearrangement reactions typically form:",
  ["More stable carbocation","Less stable carbocation","Same","No effect"],"More stable carbocation"),
 ("1,2-hydride shift occurs in:",
  ["SN1/E1 reactions to give more stable carbocation","SN2","E2","Radical"],"SN1/E1 reactions to give more stable carbocation"),
 ("Homolytic bond cleavage gives:",
  ["Two free radicals","Two ions","One radical and one ion","Nothing"],"Two free radicals"),
 ("Heterolytic bond cleavage gives:",
  ["Cation and anion","Two radicals","Two cations","Two anions"],"Cation and anion"),
 ("Condensation reaction releases:",
  ["Small molecule (H₂O, HCl, NH₃)","Hydrogen gas only","CO₂ only","Nothing"],"Small molecule (H₂O, HCl, NH₃)"),
 ("Aldol condensation forms:",
  ["β-hydroxy aldehyde/ketone (later α,β-unsaturated)","Ester","Ether","Alcohol only"],"β-hydroxy aldehyde/ketone (later α,β-unsaturated)"),
],
29: [
 ("General formula for alkanes:",
  ["CₙH₂ₙ₊₂","CₙH₂ₙ","CₙH₂ₙ₋₂","CₙH₂ₙ₊₁"],"CₙH₂ₙ₊₂"),
 ("Alkanes are also called:",
  ["Paraffins (little affinity)","Olefins","Acetylenes","Aromatics"],"Paraffins (little affinity)"),
 ("Hybridisation of C in alkanes:",
  ["sp³","sp²","sp","sp³d"],"sp³"),
 ("C-C bond length in ethane:",
  ["154 pm","134 pm","120 pm","110 pm"],"154 pm"),
 ("Wurtz reaction: 2R-X + 2Na →",
  ["R-R + 2NaX","R-H + NaX","R-OH + NaX","R-ONa + HX"],"R-R + 2NaX"),
 ("Wurtz reaction used to prepare:",
  ["Symmetrical alkanes with even number of C","Alkenes","Alkynes","Alcohols"],"Symmetrical alkanes with even number of C"),
 ("Kolbe's electrolysis of RCOONa gives:",
  ["R-R + 2CO₂ + H₂","Alcohol","Ketone","Ester"],"R-R + 2CO₂ + H₂"),
 ("Hydrogenation of alkenes gives alkanes using:",
  ["H₂ / Ni (or Pt, Pd)","HCl","H₂O / H⁺","Br₂"],"H₂ / Ni (or Pt, Pd)"),
 ("Reduction of R-X with Zn/HCl gives:",
  ["R-H (alkane)","R-OH","R-R","Alkene"],"R-H (alkane)"),
 ("Alkanes mainly undergo:",
  ["Free-radical substitution","Electrophilic addition","Nucleophilic addition","Ionic substitution"],"Free-radical substitution"),
 ("Halogenation of methane with Cl₂ requires:",
  ["UV light or heat","Dark","Low T","Catalyst only"],"UV light or heat"),
 ("Mechanism of halogenation:",
  ["Free-radical chain (initiation, propagation, termination)","SN2","SN1","EAS"],"Free-radical chain (initiation, propagation, termination)"),
 ("Reactivity of halogens in halogenation:",
  ["F₂ > Cl₂ > Br₂ > I₂","I₂ > Br₂ > Cl₂ > F₂","Cl₂ > F₂","All equal"],"F₂ > Cl₂ > Br₂ > I₂"),
 ("Selectivity of halogenation:",
  ["I₂ most selective (3° > 2° > 1°), F₂ least","F₂ most selective","All equal","Cl₂ > Br₂ > I₂ selectivity"],"I₂ most selective (3° > 2° > 1°), F₂ least"),
 ("Isomerisation of n-alkane to branched alkane requires:",
  ["AlCl₃ / HCl catalyst","Na","NaOH","Water"],"AlCl₃ / HCl catalyst"),
 ("Aromatization of n-hexane:",
  ["Gives benzene (Cr₂O₃/Al₂O₃, 500°C)","Gives cyclohexene","Gives ethene","No reaction"],"Gives benzene (Cr₂O₃/Al₂O₃, 500°C)"),
 ("Pyrolysis (cracking) of alkanes gives:",
  ["Smaller alkanes + alkenes","Only alkanes","Only H₂","Ethers"],"Smaller alkanes + alkenes"),
 ("Combustion of alkanes produces:",
  ["CO₂ + H₂O + heat","CO + H₂","CO₂ only","CH₃OH"],"CO₂ + H₂O + heat"),
 ("Octane number indicates:",
  ["Antiknock quality of petrol","Viscosity","Density","Boiling point"],"Antiknock quality of petrol"),
 ("Iso-octane (2,2,4-trimethylpentane) has octane number:",
  ["100","0","50","200"],"100"),
 ("n-heptane has octane number:",
  ["0","100","50","200"],"0"),
 ("Conformations of ethane:",
  ["Eclipsed and staggered","Only cis-trans","Only optical","None"],"Eclipsed and staggered"),
 ("Most stable conformation of ethane:",
  ["Staggered (60° apart)","Eclipsed","Gauche","Half-chair"],"Staggered (60° apart)"),
 ("Energy difference between eclipsed and staggered ethane:",
  ["≈12.5 kJ/mol","100 kJ/mol","0","1000 kJ/mol"],"≈12.5 kJ/mol"),
 ("Most stable conformation of n-butane:",
  ["Anti (180°)","Gauche","Eclipsed","Skew"],"Anti (180°)"),
],
30: [
 ("General formula for alkenes:",
  ["CₙH₂ₙ","CₙH₂ₙ₊₂","CₙH₂ₙ₋₂","CₙH₂ₙ₊₁"],"CₙH₂ₙ"),
 ("Alkenes are also called:",
  ["Olefins","Paraffins","Acetylenes","Aromatics"],"Olefins"),
 ("Hybridisation of C in alkene:",
  ["sp²","sp³","sp","sp³d"],"sp²"),
 ("C=C bond length in ethene:",
  ["134 pm","154 pm","120 pm","110 pm"],"134 pm"),
 ("Bond angle in ethene:",
  ["120°","109.5°","180°","90°"],"120°"),
 ("Dehydration of alcohol to alkene uses:",
  ["Conc. H₂SO₄ at 170°C","Dilute HCl","NaOH","Water"],"Conc. H₂SO₄ at 170°C"),
 ("Dehydrohalogenation of alkyl halide with alc. KOH gives:",
  ["Alkene (E2)","Alkane","Alcohol","Ether"],"Alkene (E2)"),
 ("Dehalogenation of vicinal dihalide with Zn dust gives:",
  ["Alkene","Alkane","Alkyne","Alcohol"],"Alkene"),
 ("Markovnikov's rule for HX addition:",
  ["H goes to C with more H, X to C with fewer H","X to C with more H","Random","Based on mass"],"H goes to C with more H, X to C with fewer H"),
 ("Addition of HBr to propene gives (Markovnikov):",
  ["2-bromopropane","1-bromopropane","1,2-dibromopropane","Propanol"],"2-bromopropane"),
 ("Addition of HBr to propene in presence of peroxide (anti-Markovnikov) gives:",
  ["1-bromopropane (Kharasch)","2-bromopropane","1,2-dibromopropane","Propanol"],"1-bromopropane (Kharasch)"),
 ("Peroxide effect works only for:",
  ["HBr, not HCl or HI","HCl","HI","All HX"],"HBr, not HCl or HI"),
 ("Addition of H₂O/H₂SO₄ to propene gives:",
  ["Propan-2-ol (Markovnikov)","Propan-1-ol","Propanal","Propanoic acid"],"Propan-2-ol (Markovnikov)"),
 ("Hydroboration-oxidation gives:",
  ["Anti-Markovnikov alcohol (B₂H₆ then H₂O₂/OH⁻)","Markovnikov alcohol","Ketone","Alkyne"],"Anti-Markovnikov alcohol (B₂H₆ then H₂O₂/OH⁻)"),
 ("Oxymercuration-demercuration gives:",
  ["Markovnikov alcohol without rearrangement","Anti-Markovnikov","Ether","Ester"],"Markovnikov alcohol without rearrangement"),
 ("Addition of Br₂ to alkene gives:",
  ["Vicinal dibromide (trans-addition via bromonium ion)","Geminal dibromide","Bromoalcohol","No reaction"],"Vicinal dibromide (trans-addition via bromonium ion)"),
 ("Addition of cold dilute KMnO₄ (Baeyer's) gives:",
  ["cis-diol","trans-diol","Aldehyde","Ketone"],"cis-diol"),
 ("Ozonolysis of CH₃CH=CHCH₃ with Zn/H₂O gives:",
  ["2 CH₃CHO","CH₃COCH₃","CH₃CHO + HCHO","CH₄"],"2 CH₃CHO"),
 ("Catalytic hydrogenation of alkene requires:",
  ["H₂, Ni/Pt/Pd","Na","HCl","H₂O"],"H₂, Ni/Pt/Pd"),
 ("Polymerisation of ethene gives:",
  ["Polyethene","Polypropene","PVC","Teflon"],"Polyethene"),
 ("Wacker process converts ethene to:",
  ["Acetaldehyde (PdCl₂/CuCl₂/O₂)","Ethanol","Ethene oxide","Vinyl chloride"],"Acetaldehyde (PdCl₂/CuCl₂/O₂)"),
 ("Geometrical isomers (cis-trans) in alkenes require:",
  ["Different groups on each C of C=C","Same groups","3° carbons","Any carbons"],"Different groups on each C of C=C"),
 ("In E/Z nomenclature Z means:",
  ["Higher priority groups on same side (cis-like)","Opposite","Lower priority same side","Any"],"Higher priority groups on same side (cis-like)"),
 ("Stability of alkenes:",
  ["More substituted > less substituted (hyperconjugation)","Opposite","All equal","Depends only on size"],"More substituted > less substituted (hyperconjugation)"),
 ("Trans-alkene is more stable than cis due to:",
  ["Less steric strain","H-bonding","Resonance","Inductive effect"],"Less steric strain"),
],
31: [
 ("General formula for alkynes:",
  ["CₙH₂ₙ₋₂","CₙH₂ₙ","CₙH₂ₙ₊₂","CₙH₂ₙ₊₁"],"CₙH₂ₙ₋₂"),
 ("Alkynes are also called:",
  ["Acetylenes","Paraffins","Olefins","Aromatics"],"Acetylenes"),
 ("Hybridisation of C in alkyne:",
  ["sp","sp²","sp³","sp³d"],"sp"),
 ("C≡C bond length in ethyne:",
  ["120 pm","134 pm","154 pm","110 pm"],"120 pm"),
 ("Bond angle in ethyne:",
  ["180° (linear)","120°","109.5°","90°"],"180° (linear)"),
 ("Industrial preparation of ethyne from CaC₂:",
  ["CaC₂ + 2H₂O → Ca(OH)₂ + C₂H₂","CaC₂ + H₂ → CaH₂","CaC₂ + CO₂ → ...","No reaction"],"CaC₂ + 2H₂O → Ca(OH)₂ + C₂H₂"),
 ("Electronic arc preparation:",
  ["C + H₂ at very high T","Na + C","CH₄ at low T","CO + H₂"],"C + H₂ at very high T"),
 ("Kolbe's electrolysis of sodium fumarate gives:",
  ["Ethyne","Ethane","Ethene","Methane"],"Ethyne"),
 ("Alkynes with terminal C-H (≡CH) are:",
  ["Acidic (pKa ≈ 25)","Basic","Neutral","Strongly acidic"],"Acidic (pKa ≈ 25)"),
 ("Acidity order: H₂O, NH₃, RC≡CH, RH:",
  ["H₂O > RC≡CH > NH₃ > RH","RH > NH₃ > RC≡CH > H₂O","All equal","NH₃ > H₂O"],"H₂O > RC≡CH > NH₃ > RH"),
 ("Terminal alkyne with Na gives:",
  ["Sodium acetylide + H₂","Alkene","Alkane","No reaction"],"Sodium acetylide + H₂"),
 ("Terminal alkyne with NaNH₂ gives:",
  ["Sodium acetylide + NH₃","No reaction","Alkene","Alkane"],"Sodium acetylide + NH₃"),
 ("Reaction with AgNO₃/NH₄OH gives (test for terminal alkyne):",
  ["White ppt of Ag-acetylide","No ppt","Red ppt","Black ppt"],"White ppt of Ag-acetylide"),
 ("Reaction with Cu₂Cl₂/NH₄OH gives:",
  ["Red ppt of Cu-acetylide","White ppt","Black ppt","No ppt"],"Red ppt of Cu-acetylide"),
 ("Hydrogenation of alkyne with Lindlar's catalyst gives:",
  ["Cis-alkene","Trans-alkene","Alkane","No reaction"],"Cis-alkene"),
 ("Hydrogenation with Na/liq NH₃ gives:",
  ["Trans-alkene","Cis-alkene","Alkane","No reaction"],"Trans-alkene"),
 ("Full hydrogenation (H₂/Ni) of alkyne gives:",
  ["Alkane","Alkene","Another alkyne","Alcohol"],"Alkane"),
 ("Addition of H₂O/Hg²⁺/H₂SO₄ to alkyne gives:",
  ["Ketone (except ethyne → acetaldehyde)","Alcohol","Aldehyde always","Ether"],"Ketone (except ethyne → acetaldehyde)"),
 ("Ethyne + H₂O/Hg²⁺/H₂SO₄ gives:",
  ["Acetaldehyde","Acetone","Acetic acid","Ethanol"],"Acetaldehyde"),
 ("Addition of Br₂ to alkyne gives:",
  ["Tetrabromide","Dibromide only","Monobromide","Tribromide"],"Tetrabromide"),
 ("Polymerisation of ethyne at red hot tube gives:",
  ["Benzene (3 molecules)","Cyclohexane","Ethane","Ethene"],"Benzene (3 molecules)"),
 ("Cup and Cupreous Cu₂Cl₂ polymerises ethyne to:",
  ["Vinyl acetylene","Benzene","Ethene","Ethane"],"Vinyl acetylene"),
 ("Ozonolysis of alkyne gives:",
  ["Carboxylic acids","Aldehydes only","Ketones only","Alcohols"],"Carboxylic acids"),
 ("Oxyacetylene flame temperature:",
  ["≈3000°C (used for welding)","1000°C","500°C","5000°C"],"≈3000°C (used for welding)"),
 ("% s-character of sp carbon:",
  ["50%","33%","25%","75%"],"50%"),
],
32: [
 ("Benzene molecular formula:",
  ["C₆H₆","C₆H₁₂","C₆H₁₀","C₆H₁₄"],"C₆H₆"),
 ("Hybridisation of C in benzene:",
  ["sp²","sp³","sp","sp³d"],"sp²"),
 ("Benzene C-C bond length:",
  ["139 pm (between single 154 and double 134)","154 pm","134 pm","120 pm"],"139 pm (between single 154 and double 134)"),
 ("Benzene stability is due to:",
  ["Aromaticity / resonance","Large size","H-bonding","Polar C-H"],"Aromaticity / resonance"),
 ("Huckel's rule for aromaticity:",
  ["Planar cyclic with (4n+2) π-electrons","(4n) π-e⁻","Must be saturated","Any cyclic"],"Planar cyclic with (4n+2) π-electrons"),
 ("Number of π-electrons in benzene:",
  ["6","4","8","2"],"6"),
 ("Resonance energy of benzene:",
  ["≈150 kJ/mol","50 kJ/mol","500 kJ/mol","0"],"≈150 kJ/mol"),
 ("Benzene undergoes mainly:",
  ["Electrophilic aromatic substitution","Nucleophilic addition","Free radical addition","Oxidation only"],"Electrophilic aromatic substitution"),
 ("Nitration of benzene uses:",
  ["Conc. HNO₃ + conc. H₂SO₄","Dilute HNO₃","NaNO₂","HNO₂"],"Conc. HNO₃ + conc. H₂SO₄"),
 ("Electrophile in nitration:",
  ["NO₂⁺ (nitronium ion)","NO⁻","NO","NO₃⁻"],"NO₂⁺ (nitronium ion)"),
 ("Sulphonation of benzene uses:",
  ["Fuming H₂SO₄ (oleum)","Dilute H₂SO₄","HCl","NaOH"],"Fuming H₂SO₄ (oleum)"),
 ("Electrophile in sulphonation:",
  ["SO₃ / HSO₃⁺","H⁺","SO₄²⁻","OH⁻"],"SO₃ / HSO₃⁺"),
 ("Halogenation of benzene (Br₂/FeBr₃) gives:",
  ["Bromobenzene + HBr","Hexabromocyclohexane","Phenol","No reaction"],"Bromobenzene + HBr"),
 ("Friedel-Crafts alkylation uses:",
  ["R-X + anhydrous AlCl₃","R-OH only","R-NH₂","Na"],"R-X + anhydrous AlCl₃"),
 ("Friedel-Crafts acylation uses:",
  ["RCOCl + AlCl₃","RCl","RCOOH","Na"],"RCOCl + AlCl₃"),
 ("Friedel-Crafts fails on:",
  ["Strongly deactivated rings (nitrobenzene)","Benzene","Toluene","Aniline (works but messy)"],"Strongly deactivated rings (nitrobenzene)"),
 ("Activating groups (ortho-para directing):",
  ["−NH₂, −OH, −OR, −CH₃, −X (weakly deactivating but o/p directing)","−NO₂, −CN, −COOH","−SO₃H","−CHO"],"−NH₂, −OH, −OR, −CH₃, −X (weakly deactivating but o/p directing)"),
 ("Deactivating groups (meta directing):",
  ["−NO₂, −CN, −COOH, −SO₃H, −CHO","−NH₂, −OH","−CH₃","−OR"],"−NO₂, −CN, −COOH, −SO₃H, −CHO"),
 ("−OH on benzene directs incoming electrophile to:",
  ["Ortho and para","Meta only","Ipso","None"],"Ortho and para"),
 ("−NO₂ on benzene directs electrophile to:",
  ["Meta","Ortho","Para","Both o/p"],"Meta"),
 ("Halogens on benzene are:",
  ["Weakly deactivating but o/p directing","Strongly activating","Meta directing","Ipso directing"],"Weakly deactivating but o/p directing"),
 ("Cyclohexane + Pt/Pd (525°C) gives:",
  ["Benzene (dehydrogenation)","Hexane","Hexene","Toluene"],"Benzene (dehydrogenation)"),
 ("Phenol + Zn dust (distilled) gives:",
  ["Benzene","Cyclohexanol","Toluene","Benzoic acid"],"Benzene"),
 ("Benzene + Cl₂ in sunlight (no catalyst) gives:",
  ["Benzene hexachloride (BHC / C₆H₆Cl₆)","Chlorobenzene","Phenol","Dichlorobenzene"],"Benzene hexachloride (BHC / C₆H₆Cl₆)"),
 ("Toluene oxidation with KMnO₄/H₂SO₄ gives:",
  ["Benzoic acid","Phenol","Benzaldehyde","Benzophenone"],"Benzoic acid"),
],
33: [
 ("Boyle's law:",
  ["P ∝ 1/V at constant T, n","P ∝ V","P ∝ T","V ∝ T"],"P ∝ 1/V at constant T, n"),
 ("Boyle's law equation:",
  ["P₁V₁ = P₂V₂","P₁/T₁ = P₂/T₂","V₁/T₁ = V₂/T₂","PV = nRT"],"P₁V₁ = P₂V₂"),
 ("Charles's law:",
  ["V ∝ T at constant P, n","V ∝ 1/T","P ∝ T","V ∝ P"],"V ∝ T at constant P, n"),
 ("Charles's law equation:",
  ["V₁/T₁ = V₂/T₂","P₁V₁ = P₂V₂","PV = nRT","P₁/T₁ = P₂/T₂"],"V₁/T₁ = V₂/T₂"),
 ("Gay-Lussac's law (pressure-temperature):",
  ["P ∝ T at constant V, n","P ∝ V","P ∝ 1/T","V ∝ T"],"P ∝ T at constant V, n"),
 ("Avogadro's law:",
  ["V ∝ n at constant P, T","V ∝ 1/n","P ∝ n","P ∝ 1/n"],"V ∝ n at constant P, T"),
 ("At STP (0°C, 1 atm), molar volume of gas:",
  ["22.4 L","24 L","10 L","20 L"],"22.4 L"),
 ("At SATP (25°C, 1 bar), molar volume:",
  ["24.79 L","22.4 L","10 L","25 L"],"24.79 L"),
 ("Absolute zero in Kelvin:",
  ["0 K = −273.15°C","0°C","−100 K","100 K"],"0 K = −273.15°C"),
 ("Charles's law cannot be verified at very low T because:",
  ["Gas liquefies","It still holds exactly","Pressure becomes zero","Volume becomes negative"],"Gas liquefies"),
 ("Graham's law of diffusion:",
  ["Rate ∝ 1/√M","Rate ∝ M","Rate ∝ √M","Rate ∝ 1/M"],"Rate ∝ 1/√M"),
 ("Which gas diffuses fastest?",
  ["H₂ (lowest molar mass)","O₂","CO₂","SO₂"],"H₂ (lowest molar mass)"),
 ("Dalton's law of partial pressures:",
  ["P_total = ΣP_i (for non-reacting gases)","P_total = P₁·P₂","P_total = P_avg","P_total independent of composition"],"P_total = ΣP_i (for non-reacting gases)"),
 ("Partial pressure of a gas = (mole fraction) ×",
  ["Total pressure","Temperature","Volume","Mass"],"Total pressure"),
 ("Ideal gas equation:",
  ["PV = nRT","PV = RT","P/V = nRT","PT = nRV"],"PV = nRT"),
 ("Value of R in SI units (J/mol·K):",
  ["8.314","0.0821","1.987","62.36"],"8.314"),
 ("Value of R in L·atm/mol·K:",
  ["0.0821","8.314","1.987","62.36"],"0.0821"),
 ("If pressure is halved at constant T, volume:",
  ["Doubles","Halves","Quadruples","Unchanged"],"Doubles"),
 ("At constant P, if T doubles (in K), V:",
  ["Doubles","Halves","Quadruples","Unchanged"],"Doubles"),
 ("At constant V, if T triples, P:",
  ["Triples","Reduces by 1/3","Doubles","Halves"],"Triples"),
 ("Combined gas law:",
  ["P₁V₁/T₁ = P₂V₂/T₂","P₁V₁ = P₂V₂ only","V₁/T₁ = V₂/T₂ only","PV = nRT only"],"P₁V₁/T₁ = P₂V₂/T₂"),
 ("STP pressure in kPa:",
  ["101.325 kPa","100 kPa","1 kPa","1013 kPa"],"101.325 kPa"),
 ("1 atm equals how many mm Hg?",
  ["760 mm Hg","1000 mm Hg","100 mm Hg","76 mm Hg"],"760 mm Hg"),
 ("1 atm equals how many Pa?",
  ["101325 Pa","1 Pa","1000 Pa","760 Pa"],"101325 Pa"),
 ("1 bar equals:",
  ["10⁵ Pa","1 Pa","101325 Pa","760 Pa"],"10⁵ Pa"),
],
34: [
 ("Ideal gas obeys:",
  ["PV = nRT at all P and T","Only at high P","Only at low T","Never"],"PV = nRT at all P and T"),
 ("Assumptions of kinetic molecular theory:",
  ["Point particles, elastic collisions, negligible IMF, random motion","Strong IMF, inelastic","Large particles only","No motion"],"Point particles, elastic collisions, negligible IMF, random motion"),
 ("Kinetic energy of gas depends on:",
  ["Temperature only (absolute)","Pressure","Volume","Mass"],"Temperature only (absolute)"),
 ("Average KE per mole = ",
  ["(3/2)RT","(3/2)kT","(5/2)RT","RT"],"(3/2)RT"),
 ("Average KE per molecule = ",
  ["(3/2)kT","(3/2)RT","kT","RT"],"(3/2)kT"),
 ("Most probable speed (u_mp):",
  ["√(2RT/M)","√(3RT/M)","√(8RT/πM)","RT/M"],"√(2RT/M)"),
 ("Average speed (u_avg):",
  ["√(8RT/πM)","√(2RT/M)","√(3RT/M)","RT/M"],"√(8RT/πM)"),
 ("Root mean square speed (u_rms):",
  ["√(3RT/M)","√(2RT/M)","√(8RT/πM)","RT/M"],"√(3RT/M)"),
 ("Ratio u_mp : u_avg : u_rms:",
  ["1 : 1.128 : 1.224","1 : 2 : 3","All equal","3 : 2 : 1"],"1 : 1.128 : 1.224"),
 ("At same T, light gas has:",
  ["Higher u_rms","Lower u_rms","Same u_rms","Zero u_rms"],"Higher u_rms"),
 ("Maxwell-Boltzmann distribution shows:",
  ["Distribution of molecular speeds at given T","Only one speed","Pressure vs V","Composition"],"Distribution of molecular speeds at given T"),
 ("As T increases, u_mp:",
  ["Increases","Decreases","Unchanged","Zero"],"Increases"),
 ("Real gas deviates from ideal behaviour because:",
  ["Molecules have finite size and IMF","They are point particles","No collisions","Temperature too high"],"Molecules have finite size and IMF"),
 ("Compressibility factor Z = PV/nRT:",
  ["Z=1 for ideal, ≠1 for real","Z=0 always","Z>10 for ideal","Z infinite"],"Z=1 for ideal, ≠1 for real"),
 ("Z < 1 means gas is:",
  ["More compressible than ideal (attractive forces dominate)","Less compressible","Ideal","Impossible"],"More compressible than ideal (attractive forces dominate)"),
 ("Z > 1 means gas is:",
  ["Less compressible than ideal (repulsion dominates)","More compressible","Ideal","Impossible"],"Less compressible than ideal (repulsion dominates)"),
 ("Van der Waals equation:",
  ["(P + an²/V²)(V − nb) = nRT","PV = nRT","PV = RT","P + V = nRT"],"(P + an²/V²)(V − nb) = nRT"),
 ("Constant 'a' in vdW equation represents:",
  ["Strength of intermolecular attraction","Molecular volume","Pressure","T"],"Strength of intermolecular attraction"),
 ("Constant 'b' in vdW equation represents:",
  ["Excluded volume (4× molecular volume per mole)","Attraction","Temperature","Pressure"],"Excluded volume (4× molecular volume per mole)"),
 ("Gas with highest 'a' (strongest IMF):",
  ["H₂O, NH₃","H₂","He","Ar"],"H₂O, NH₃"),
 ("Boyle temperature (T_B):",
  ["Temperature at which gas behaves ideally over wide P range","Absolute zero","STP temperature","Critical T"],"Temperature at which gas behaves ideally over wide P range"),
 ("Critical temperature (T_c):",
  ["Above which gas cannot be liquefied","Below absolute zero","At STP","Boyle T"],"Above which gas cannot be liquefied"),
 ("Critical T of CO₂:",
  ["31.1°C","100°C","0°C","−273°C"],"31.1°C"),
 ("Liquefaction easier for:",
  ["High T_c, strong IMF","Low T_c, weak IMF","All same","Noble gases"],"High T_c, strong IMF"),
 ("Joule-Thomson expansion cools most gases except:",
  ["H₂, He (above inversion T)","N₂","O₂","CO₂"],"H₂, He (above inversion T)"),
],
35: [
 ("Vapour pressure of a liquid depends on:",
  ["Temperature and nature of liquid","Volume of container","Amount of liquid","Surface area only"],"Temperature and nature of liquid"),
 ("Boiling point is:",
  ["T at which vapour pressure = atmospheric pressure","Melting point","T of maximum density","Freezing point"],"T at which vapour pressure = atmospheric pressure"),
 ("Normal boiling point of water:",
  ["100°C at 1 atm","0°C","25°C","−10°C"],"100°C at 1 atm"),
 ("BP increases with:",
  ["Increasing IMF, increasing molar mass","Decreasing IMF","Volume","Amount"],"Increasing IMF, increasing molar mass"),
 ("Order of BP: H₂O, H₂S, H₂Se, H₂Te:",
  ["H₂O > H₂Te > H₂Se > H₂S (H-bonding in H₂O)","H₂Te > H₂Se > H₂S > H₂O","All equal","H₂S > H₂O"],"H₂O > H₂Te > H₂Se > H₂S (H-bonding in H₂O)"),
 ("Clausius-Clapeyron equation relates:",
  ["ln(P₂/P₁) = −ΔH_vap/R · (1/T₂ − 1/T₁)","PV = nRT","P = ρgh","None"],"ln(P₂/P₁) = −ΔH_vap/R · (1/T₂ − 1/T₁)"),
 ("Surface tension arises from:",
  ["Net inward force on surface molecules","Gravitation","Pressure","Only temperature"],"Net inward force on surface molecules"),
 ("Surface tension of water at 20°C:",
  ["72.8 mN/m","100 mN/m","10 mN/m","1 N/m"],"72.8 mN/m"),
 ("Surface tension decreases with:",
  ["Increasing T","Decreasing T","Increasing area","Pressure"],"Increasing T"),
 ("Adding soap to water:",
  ["Decreases surface tension","Increases","No effect","Increases density"],"Decreases surface tension"),
 ("Capillary action: water rises in glass capillary because:",
  ["Adhesion > cohesion","Cohesion > adhesion","No forces","Gravity only"],"Adhesion > cohesion"),
 ("Mercury in glass capillary:",
  ["Depresses (cohesion > adhesion)","Rises","No change","Boils"],"Depresses (cohesion > adhesion)"),
 ("Droplets are spherical because:",
  ["Sphere has minimum surface area for given V","Maximum area","Random shape","Gravity"],"Sphere has minimum surface area for given V"),
 ("Viscosity is:",
  ["Resistance to flow of liquid","Pressure of gas","Vapour pressure","Density"],"Resistance to flow of liquid"),
 ("Viscosity unit (SI):",
  ["Pa·s (or poiseuille)","atm","mm Hg","J/mol"],"Pa·s (or poiseuille)"),
 ("CGS unit of viscosity:",
  ["Poise (1 P = 0.1 Pa·s)","Pascal","Joule","Newton"],"Poise (1 P = 0.1 Pa·s)"),
 ("Viscosity of liquids as T increases:",
  ["Decreases","Increases","Unchanged","Zero"],"Decreases"),
 ("Glycerol is more viscous than water due to:",
  ["Extensive H-bonding and larger size","Lower mass","Smaller molecules","Lower IMF"],"Extensive H-bonding and larger size"),
 ("Honey pours slowly because of:",
  ["High viscosity","Low viscosity","High vapour pressure","High surface tension"],"High viscosity"),
 ("Poiseuille's equation: rate of flow ∝",
  ["r⁴ (for laminar flow in tube)","r","r²","r³"],"r⁴ (for laminar flow in tube)"),
 ("Liquids are condensed states where:",
  ["IMF comparable to thermal energy","No IMF","Thermal energy >> IMF","No motion"],"IMF comparable to thermal energy"),
 ("Ratio of vapour pressure of solution / pure solvent = X_solvent (Raoult's law):",
  ["P_solution = X_solvent × P°_solvent","P_solution = P°_solvent","P_solution = X_solute · P°","P_solution = 0"],"P_solution = X_solvent × P°_solvent"),
 ("Evaporation is faster with:",
  ["Higher T, lower humidity, more surface area","Higher humidity","Lower T","Enclosed container"],"Higher T, lower humidity, more surface area"),
 ("Latent heat of vaporisation of water:",
  ["40.7 kJ/mol (at 100°C)","5 kJ/mol","0","500 kJ/mol"],"40.7 kJ/mol (at 100°C)"),
 ("Density of water is maximum at:",
  ["4°C","0°C","100°C","25°C"],"4°C"),
],
36: [
 ("Hydrogen's position in periodic table is unique because:",
  ["Resembles alkali metals, halogens, and carbon group","Only alkali","Only halogen","Only noble gas"],"Resembles alkali metals, halogens, and carbon group"),
 ("Isotopes of hydrogen:",
  ["Protium (¹H), Deuterium (²H), Tritium (³H)","Only ¹H","Only ²H","H₂O isotopes"],"Protium (¹H), Deuterium (²H), Tritium (³H)"),
 ("Tritium is:",
  ["Radioactive, β emitter, half-life 12.33 y","Stable","α emitter","γ emitter only"],"Radioactive, β emitter, half-life 12.33 y"),
 ("H₂ preparation by lab (Zn + HCl):",
  ["Zn + 2HCl → ZnCl₂ + H₂","Zn + NaOH","Zn + H₂O only","Zn + O₂"],"Zn + 2HCl → ZnCl₂ + H₂"),
 ("Industrial H₂ from steam-methane reforming:",
  ["CH₄ + H₂O → CO + 3H₂ (Ni catalyst)","CH₄ + O₂ → CO₂ + H₂O","CH₄ + HCl","CO₂ + H₂O"],"CH₄ + H₂O → CO + 3H₂ (Ni catalyst)"),
 ("Water gas is:",
  ["CO + H₂","CO₂ + H₂","CO₂ + H₂O","H₂ only"],"CO + H₂"),
 ("Producer gas is:",
  ["CO + N₂ (from C + air)","CO + H₂","CH₄ + H₂","H₂ + N₂"],"CO + N₂ (from C + air)"),
 ("H₂ is obtained electrolytically at:",
  ["Cathode","Anode","Both","Neither"],"Cathode"),
 ("Para-hydrogen and ortho-hydrogen differ in:",
  ["Spin of two H nuclei (antiparallel vs parallel)","Charges","Masses","Electrons"],"Spin of two H nuclei (antiparallel vs parallel)"),
 ("Ordinary H₂ at 25°C has:",
  ["75% ortho, 25% para","100% ortho","100% para","50-50"],"75% ortho, 25% para"),
 ("Ionic hydrides are formed by:",
  ["Group 1 (except Be), Group 2 (except Be, Mg)","Non-metals","Transition metals","Noble gases"],"Group 1 (except Be), Group 2 (except Be, Mg)"),
 ("Ionic hydrides contain:",
  ["H⁻ (hydride) ion","H⁺","H₂","H₃O⁺"],"H⁻ (hydride) ion"),
 ("Covalent hydrides are:",
  ["Non-metal hydrides (CH₄, NH₃, H₂O)","NaH","CaH₂","KH"],"Non-metal hydrides (CH₄, NH₃, H₂O)"),
 ("Metallic (interstitial) hydrides are:",
  ["Formed by transition metals, non-stoichiometric","Ionic","Polar covalent","Noble"],"Formed by transition metals, non-stoichiometric"),
 ("Hardness of water is due to:",
  ["Ca²⁺, Mg²⁺ ions","Na⁺, K⁺","Cl⁻","OH⁻"],"Ca²⁺, Mg²⁺ ions"),
 ("Temporary hardness is due to:",
  ["Bicarbonates of Ca/Mg (removed by boiling)","Chlorides/sulphates","NaCl","HCl"],"Bicarbonates of Ca/Mg (removed by boiling)"),
 ("Permanent hardness is due to:",
  ["Chlorides and sulphates of Ca/Mg","Bicarbonates","NaCl","HCl"],"Chlorides and sulphates of Ca/Mg"),
 ("Permanent hardness removed by:",
  ["Washing soda / ion-exchange / Calgon method","Boiling","Filtering","Adding CaCl₂"],"Washing soda / ion-exchange / Calgon method"),
 ("H₂O₂ preparation by industrial (anthraquinone):",
  ["Autoxidation of 2-alkylanthraquinol","H₂ + O₂","NaOH + Cl₂","H₂O + HCl"],"Autoxidation of 2-alkylanthraquinol"),
 ("Structure of H₂O₂:",
  ["Open-book (non-planar, 2 OH groups)","Planar","Linear","Tetrahedral"],"Open-book (non-planar, 2 OH groups)"),
 ("H₂O₂ is:",
  ["Both oxidising and reducing agent","Only oxidising","Only reducing","Inert"],"Both oxidising and reducing agent"),
 ("Strength of H₂O₂: '10 V' means:",
  ["1 volume gives 10 volumes of O₂ at STP","10 g H₂O₂ per L","10 M","10%"],"1 volume gives 10 volumes of O₂ at STP"),
 ("Decomposition of H₂O₂ (catalysed by MnO₂):",
  ["2H₂O₂ → 2H₂O + O₂","H₂O₂ → H₂ + O₂","Stable, no decomposition","H₂O₂ → H₂O only"],"2H₂O₂ → 2H₂O + O₂"),
 ("H₂O₂ is stored in:",
  ["Wax-lined dark bottles (away from light/dust)","Clear bottles in sun","Metal cans","Open containers"],"Wax-lined dark bottles (away from light/dust)"),
 ("Heavy water (D₂O) is used as:",
  ["Moderator in nuclear reactors","Fuel","Coolant only","Electrolyte"],"Moderator in nuclear reactors"),
],
37: [
 ("Group 1 elements are called:",
  ["Alkali metals","Alkaline earth","Halogens","Noble gases"],"Alkali metals"),
 ("Group 1 electronic configuration:",
  ["ns¹","ns²","ns²np¹","ns²np⁵"],"ns¹"),
 ("Most abundant alkali metal in earth's crust:",
  ["Na","Li","K","Cs"],"Na"),
 ("Least abundant (stable) alkali metal:",
  ["Cs","Li","Na","K"],"Cs"),
 ("Alkali metals are stored in:",
  ["Kerosene","Water","Air","Alcohol"],"Kerosene"),
 ("Down the group, atomic radius of alkali metals:",
  ["Increases","Decreases","Unchanged","Zero"],"Increases"),
 ("Ionisation energy down the group:",
  ["Decreases","Increases","Unchanged","Zero"],"Decreases"),
 ("Reactivity of alkali metals down the group:",
  ["Increases","Decreases","Unchanged","None"],"Increases"),
 ("Melting point of alkali metals down the group:",
  ["Decreases (metallic bond weakens)","Increases","Unchanged","Zero"],"Decreases (metallic bond weakens)"),
 ("Oxidation state of alkali metals:",
  ["+1","+2","−1","+3"],"+1"),
 ("Alkali metal + O₂ (limited) gives:",
  ["M₂O (oxide, mainly Li)","MO","MO₂","M₂O₂"],"M₂O (oxide, mainly Li)"),
 ("Na + O₂ gives mainly:",
  ["Na₂O₂ (peroxide)","Na₂O","NaO₂","NaO"],"Na₂O₂ (peroxide)"),
 ("K, Rb, Cs + O₂ give mainly:",
  ["MO₂ (superoxide)","M₂O","M₂O₂","M₂O₃"],"MO₂ (superoxide)"),
 ("Alkali metal + H₂O gives:",
  ["MOH + H₂","MO + H₂","M₂O + H₂","No reaction"],"MOH + H₂"),
 ("Most vigorous reaction with water:",
  ["Cs > Rb > K > Na > Li","Li > Na > K > Rb","Na most","Li most"],"Cs > Rb > K > Na > Li"),
 ("Flame colour of Na:",
  ["Golden yellow","Red","Violet","Blue"],"Golden yellow"),
 ("Flame colour of K:",
  ["Violet/lilac","Yellow","Green","Blue"],"Violet/lilac"),
 ("Flame colour of Li:",
  ["Crimson red","Yellow","Violet","Green"],"Crimson red"),
 ("Alkali metals in liquid NH₃ give:",
  ["Blue solution (solvated electrons)","Yellow","Red","Colourless"],"Blue solution (solvated electrons)"),
 ("Blue colour is due to:",
  ["Ammoniated (solvated) electrons","Na⁺ ions","NH₂⁻","H₂"],"Ammoniated (solvated) electrons"),
 ("Diagonal relationship:",
  ["Li with Mg, Be with Al","Na with Mg","K with Ca","Cs with Ba"],"Li with Mg, Be with Al"),
 ("NaOH preparation by electrolysis (Castner-Kellner):",
  ["Electrolysis of brine with Hg cathode","NaCl + H₂O (thermal)","Na + H₂O","Na₂CO₃ + Ca(OH)₂"],"Electrolysis of brine with Hg cathode"),
 ("Na₂CO₃ (washing soda) by Solvay process:",
  ["Uses NH₃, CO₂, NaCl, H₂O","Na + HCl","NaCl + HCl","Na + CO₂"],"Uses NH₃, CO₂, NaCl, H₂O"),
 ("NaHCO₃ (baking soda) is:",
  ["Mild alkali, used in baking and antacid","Strong base","Strong acid","Salt only"],"Mild alkali, used in baking and antacid"),
 ("Soda ash is:",
  ["Anhydrous Na₂CO₃","NaHCO₃","NaOH","Na₂O₂"],"Anhydrous Na₂CO₃"),
],
38: [
 ("Group 2 elements are called:",
  ["Alkaline earth metals","Alkali metals","Halogens","Chalcogens"],"Alkaline earth metals"),
 ("Group 2 electronic configuration:",
  ["ns²","ns¹","ns²np¹","ns²np²"],"ns²"),
 ("Group 2 elements:",
  ["Be, Mg, Ca, Sr, Ba, Ra","Li, Na, K, Rb, Cs","B, Al, Ga, In","N, P, As"],"Be, Mg, Ca, Sr, Ba, Ra"),
 ("Oxidation state of alkaline earth metals:",
  ["+2","+1","−2","+3"],"+2"),
 ("Which is radioactive?",
  ["Ra","Ba","Ca","Mg"],"Ra"),
 ("Down the group, reactivity of Group 2 metals:",
  ["Increases","Decreases","Unchanged","Zero"],"Increases"),
 ("Atomic/ionic radius of Group 2 vs Group 1 (same period):",
  ["Smaller (higher Z_eff)","Larger","Equal","Zero"],"Smaller (higher Z_eff)"),
 ("IE of Group 2 vs Group 1 (same period):",
  ["Higher","Lower","Equal","Zero"],"Higher"),
 ("Density trend in Group 2:",
  ["Decreases then increases (Ca lowest)","Always increases","Always decreases","Random"],"Decreases then increases (Ca lowest)"),
 ("Be is different from other Group 2 because:",
  ["Small size, high polarising power, covalent compounds","Lowest EN","Radioactive","Gas at RT"],"Small size, high polarising power, covalent compounds"),
 ("Mg burns in air with:",
  ["Dazzling white flame","Yellow flame","Red flame","No flame"],"Dazzling white flame"),
 ("Mg + N₂ gives:",
  ["Mg₃N₂","MgN","Mg₂N","Mg(NO₃)₂"],"Mg₃N₂"),
 ("Ca(OH)₂ is called:",
  ["Slaked lime","Quicklime","Lime water (solution)","Plaster of Paris"],"Slaked lime"),
 ("CaO is called:",
  ["Quicklime","Slaked lime","Lime water","Limestone"],"Quicklime"),
 ("CaCO₃ is called:",
  ["Limestone (common form)","Quicklime","Slaked lime","Dolomite"],"Limestone (common form)"),
 ("Dolomite is:",
  ["CaCO₃·MgCO₃","CaSO₄","CaCl₂","MgCl₂"],"CaCO₃·MgCO₃"),
 ("Plaster of Paris formula:",
  ["CaSO₄·½H₂O","CaSO₄·2H₂O","CaSO₄","CaCO₃"],"CaSO₄·½H₂O"),
 ("Gypsum formula:",
  ["CaSO₄·2H₂O","CaSO₄·½H₂O","CaSO₄","CaO"],"CaSO₄·2H₂O"),
 ("PoP when mixed with water:",
  ["Sets into hard mass, expands slightly","Dissolves","No reaction","Liquefies permanently"],"Sets into hard mass, expands slightly"),
 ("Calcium flame colour:",
  ["Brick red","Green","Yellow","Violet"],"Brick red"),
 ("Barium flame colour:",
  ["Apple green","Red","Violet","Yellow"],"Apple green"),
 ("Strontium flame colour:",
  ["Crimson red","Yellow","Green","Blue"],"Crimson red"),
 ("Milk of magnesia is:",
  ["Mg(OH)₂ suspension","Ca(OH)₂","MgCl₂","MgSO₄"],"Mg(OH)₂ suspension"),
 ("Epsom salt is:",
  ["MgSO₄·7H₂O","CaSO₄","MgCl₂","Na₂SO₄"],"MgSO₄·7H₂O"),
 ("Diagonal relationship in Group 2:",
  ["Be with Al","Mg with Na","Ca with K","Ba with Cs"],"Be with Al"),
],
39: [
 ("Group 13 elements are called:",
  ["Boron family","Carbon family","Nitrogen family","Oxygen family"],"Boron family"),
 ("Group 13 elements:",
  ["B, Al, Ga, In, Tl","C, Si, Ge, Sn, Pb","N, P, As, Sb, Bi","O, S, Se, Te, Po"],"B, Al, Ga, In, Tl"),
 ("Group 13 electronic configuration:",
  ["ns²np¹","ns²","ns²np²","ns²np⁵"],"ns²np¹"),
 ("Common oxidation state:",
  ["+3 (also +1 for heavier elements)","+2 only","+1 only","+5"],"+3 (also +1 for heavier elements)"),
 ("Inert pair effect is most prominent in:",
  ["Tl (+1 more stable than +3)","B","Al","Ga"],"Tl (+1 more stable than +3)"),
 ("B is:",
  ["Non-metal (metalloid)","Metal","Noble gas","Halogen"],"Non-metal (metalloid)"),
 ("Al and below are:",
  ["Metals","Non-metals","Metalloids","Gases"],"Metals"),
 ("Most abundant metal in earth's crust:",
  ["Al","Fe","Cu","Zn"],"Al"),
 ("Bauxite is:",
  ["Al₂O₃·2H₂O (Al ore)","FeO","CaCO₃","NaCl"],"Al₂O₃·2H₂O (Al ore)"),
 ("Al extracted by:",
  ["Hall-Héroult (electrolysis of Al₂O₃ in molten cryolite)","Smelting","Bessemer","Froth flotation only"],"Hall-Héroult (electrolysis of Al₂O₃ in molten cryolite)"),
 ("Cryolite is:",
  ["Na₃AlF₆","Al₂O₃","AlCl₃","AlF₃"],"Na₃AlF₆"),
 ("B exists as:",
  ["Icosahedral B₁₂ units (amorphous or crystalline)","Diatomic","Monatomic gas","Rings"],"Icosahedral B₁₂ units (amorphous or crystalline)"),
 ("B is obtained by:",
  ["Reduction of B₂O₃ with Mg","Electrolysis","Reduction with C","Decomposition only"],"Reduction of B₂O₃ with Mg"),
 ("Diborane (B₂H₆) has:",
  ["3c-2e banana bonds (bridging H)","Normal covalent bonds","Ionic bonds","Metallic bonds"],"3c-2e banana bonds (bridging H)"),
 ("Number of terminal vs bridging H in B₂H₆:",
  ["4 terminal + 2 bridging","6 terminal","0 bridging","4 bridging"],"4 terminal + 2 bridging"),
 ("Boric acid (H₃BO₃) structure:",
  ["Layered (2D) with H-bonding","Tetrahedral","Diatomic","Chain"],"Layered (2D) with H-bonding"),
 ("H₃BO₃ is:",
  ["Weak monobasic acid (Lewis acid, accepts OH⁻ from water)","Strong triprotic","Base","Amphoteric"],"Weak monobasic acid (Lewis acid, accepts OH⁻ from water)"),
 ("Borax formula:",
  ["Na₂B₄O₇·10H₂O","NaBO₂","NaBH₄","B(OH)₃"],"Na₂B₄O₇·10H₂O"),
 ("Borax bead test identifies:",
  ["Transition metal ions (distinctive colours)","Alkali metals","Non-metals","Halides"],"Transition metal ions (distinctive colours)"),
 ("Al₂O₃ is:",
  ["Amphoteric","Only acidic","Only basic","Neutral"],"Amphoteric"),
 ("Al + NaOH gives:",
  ["Sodium aluminate + H₂","Al(OH)₃","Al₂O₃","No reaction"],"Sodium aluminate + H₂"),
 ("Al + HCl gives:",
  ["AlCl₃ + H₂","Al₂O₃","Al(OH)₃","No reaction"],"AlCl₃ + H₂"),
 ("Al is passivated by:",
  ["Conc. HNO₃ (forms oxide layer)","Dilute HCl","NaOH","Water"],"Conc. HNO₃ (forms oxide layer)"),
 ("AlCl₃ exists as:",
  ["Dimer Al₂Cl₆ in vapour","Monomer always","Ionic always","Atomic"],"Dimer Al₂Cl₆ in vapour"),
 ("Alums general formula:",
  ["M₂SO₄·M′₂(SO₄)₃·24H₂O","NaCl","KMnO₄","Al(OH)₃"],"M₂SO₄·M′₂(SO₄)₃·24H₂O"),
],
}

def main():
    d=json.loads(PATH.read_text())
    total=0
    for wk,qs in QS.items():
        assert len(qs)==25, f"wk{wk}: {len(qs)}"
        week=next(w for w in d["11"] if w["week"]==wk)
        new=[]
        for i,(q,opts,ans) in enumerate(qs,1):
            assert len(opts)==4
            assert ans in opts, f"wk{wk} Q{i}"
            new.append({"id":i,"question":q,"options":opts,"answer":ans})
        week["questions"]=new
        total+=len(qs)
    PATH.write_text(json.dumps(d,indent=2,ensure_ascii=False)+"\n")
    print(f"Replaced {total} chemistry/11 placeholder questions across {len(QS)} weeks: {sorted(QS.keys())}")

if __name__=="__main__":
    main()
