#!/usr/bin/env python3
"""Replace placeholder MCQs in chemistry-quizzes.json for class 11, weeks 4-14.

Coverage: Structure of Atom (wk4-6), Classification of Elements (wk7-8),
Chemical Bonding (wk9-14). 11 weeks × 25 = 275 real NCERT-aligned MCQs.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "src" / "data" / "chemistry-quizzes.json"

QS = {
    # ============ wk4: Structure of Atom – Discovery of Subatomic Particles ============
    4: [
        ("Cathode rays were discovered by:", ["J.J. Thomson", "Rutherford", "Goldstein", "Chadwick"], "J.J. Thomson"),
        ("The charge on an electron is:", ["−1.6 × 10⁻¹⁹ C", "+1.6 × 10⁻¹⁹ C", "−1.6 × 10⁻¹⁸ C", "zero"], "−1.6 × 10⁻¹⁹ C"),
        ("The charge-to-mass ratio (e/m) of electron is:", ["1.758 × 10¹¹ C/kg", "9.11 × 10⁻³¹ C/kg", "1.6 × 10⁻¹⁹ C/kg", "6.022 × 10²³ C/kg"], "1.758 × 10¹¹ C/kg"),
        ("Mass of one electron is approximately:", ["9.11 × 10⁻³¹ kg", "1.67 × 10⁻²⁷ kg", "1.6 × 10⁻¹⁹ kg", "9.11 × 10⁻²⁷ kg"], "9.11 × 10⁻³¹ kg"),
        ("Anode rays (canal rays) were discovered by:", ["Goldstein", "Thomson", "Rutherford", "Bohr"], "Goldstein"),
        ("The proton was discovered by:", ["Rutherford", "Thomson", "Chadwick", "Goldstein"], "Rutherford"),
        ("The neutron was discovered by:", ["Chadwick", "Rutherford", "Thomson", "Bohr"], "Chadwick"),
        ("Mass of a proton is approximately:", ["1.672 × 10⁻²⁷ kg", "9.11 × 10⁻³¹ kg", "1.6 × 10⁻¹⁹ kg", "6.022 × 10²³ kg"], "1.672 × 10⁻²⁷ kg"),
        ("Thomson's model of atom is often called:", ["Plum pudding model", "Nuclear model", "Planetary model", "Quantum model"], "Plum pudding model"),
        ("In Rutherford's α-particle scattering experiment, most α-particles:", ["Passed through undeflected", "Bounced back", "Were absorbed", "Were deflected 90°"], "Passed through undeflected"),
        ("Rutherford concluded that the atom has a:", ["Small dense positive nucleus", "Uniform positive charge", "Negative nucleus", "Hollow structure"], "Small dense positive nucleus"),
        ("The size of the nucleus compared to atom is about:", ["10⁻⁵ times", "10⁻² times", "1/2 times", "Same"], "10⁻⁵ times"),
        ("An atom of ³⁵Cl has:", ["17 protons, 18 neutrons", "18 protons, 17 neutrons", "17 protons, 17 neutrons", "18 protons, 18 neutrons"], "17 protons, 18 neutrons"),
        ("Isotopes have the same:", ["Atomic number", "Mass number", "Number of neutrons", "Density"], "Atomic number"),
        ("Isobars have the same:", ["Mass number", "Atomic number", "Number of neutrons", "Electrons"], "Mass number"),
        ("₁H¹, ₁H², ₁H³ are:", ["Isotopes", "Isobars", "Isotones", "Isoelectronic"], "Isotopes"),
        ("¹⁴₆C and ¹⁴₇N are:", ["Isobars", "Isotopes", "Isotones", "Same element"], "Isobars"),
        ("A species having same number of neutrons is called:", ["Isotones", "Isotopes", "Isobars", "Isomers"], "Isotones"),
        ("Frequency and wavelength are related by:", ["c = νλ", "c = ν/λ", "λ = cν", "ν = c × λ"], "c = νλ"),
        ("The energy of a photon is given by:", ["E = hν", "E = mc²", "E = ½mv²", "E = hc"], "E = hν"),
        ("Planck's constant h has value:", ["6.626 × 10⁻³⁴ J·s", "9.11 × 10⁻³¹ J·s", "1.6 × 10⁻¹⁹ J·s", "3 × 10⁸ J·s"], "6.626 × 10⁻³⁴ J·s"),
        ("The threshold frequency in photoelectric effect is:", ["Minimum ν to eject electron", "Maximum ν possible", "Frequency of light", "Half of work function"], "Minimum ν to eject electron"),
        ("Work function W and threshold frequency ν₀ are related by:", ["W = hν₀", "W = ν₀/h", "W = hc/ν₀", "W = h²ν₀"], "W = hν₀"),
        ("Einstein's photoelectric equation: KE_max =", ["hν − hν₀", "hν + hν₀", "hν × hν₀", "ν/ν₀"], "hν − hν₀"),
        ("Electromagnetic spectrum in order of increasing wavelength:", ["γ < X < UV < visible < IR < radio", "Radio < IR < visible < UV < X < γ", "Visible < UV < IR", "Random order"], "γ < X < UV < visible < IR < radio"),
    ],
    # ============ wk5: Bohr's Model, Quantum Numbers, Orbitals ============
    5: [
        ("Bohr's first postulate: electron revolves in:", ["Stationary orbits", "Random paths", "Elliptical paths", "Straight lines"], "Stationary orbits"),
        ("Angular momentum of electron in Bohr orbit is:", ["nh/2π", "h/2π", "nh", "n²h"], "nh/2π"),
        ("Energy of electron in nth Bohr orbit of H-atom:", ["−13.6/n² eV", "−13.6 × n² eV", "−13.6 eV", "−13.6/n eV"], "−13.6/n² eV"),
        ("Radius of first Bohr orbit of H-atom is:", ["0.529 Å", "5.29 Å", "0.0529 Å", "1 Å"], "0.529 Å"),
        ("Radius of nth Bohr orbit: rₙ =", ["0.529 × n² Å", "0.529 × n Å", "0.529/n² Å", "0.529/n Å"], "0.529 × n² Å"),
        ("Lyman series of H-spectrum lies in:", ["UV region", "Visible", "IR", "Microwave"], "UV region"),
        ("Balmer series lies in:", ["Visible region", "UV", "IR", "Radio"], "Visible region"),
        ("Rydberg formula for H-atom: 1/λ =", ["R(1/n₁² − 1/n₂²)", "R(n₁² − n₂²)", "Rn₁n₂", "R/(n₁ + n₂)"], "R(1/n₁² − 1/n₂²)"),
        ("Value of Rydberg constant R_H:", ["1.097 × 10⁷ m⁻¹", "6.626 × 10⁻³⁴ m⁻¹", "3 × 10⁸ m⁻¹", "9.11 × 10⁻³¹ m⁻¹"], "1.097 × 10⁷ m⁻¹"),
        ("de Broglie wavelength: λ =", ["h/mv", "mv/h", "hv/m", "h/v"], "h/mv"),
        ("Heisenberg's uncertainty principle: Δx·Δp ≥", ["h/4π", "h/2π", "h", "2πh"], "h/4π"),
        ("Principal quantum number n determines:", ["Size and energy of orbital", "Shape", "Orientation", "Spin"], "Size and energy of orbital"),
        ("Azimuthal quantum number l determines:", ["Shape of orbital", "Size", "Orientation", "Spin"], "Shape of orbital"),
        ("For n = 3, allowed values of l are:", ["0, 1, 2", "0, 1, 2, 3", "1, 2, 3", "0, 1"], "0, 1, 2"),
        ("Magnetic quantum number m_l determines:", ["Orientation of orbital", "Shape", "Size", "Spin"], "Orientation of orbital"),
        ("For l = 2 (d-orbital), number of m_l values:", ["5", "3", "7", "2"], "5"),
        ("Spin quantum number m_s values:", ["+½ and −½", "0 and 1", "+1 and −1", "±2"], "+½ and −½"),
        ("Shape of s-orbital is:", ["Spherical", "Dumbbell", "Double dumbbell", "Tetrahedral"], "Spherical"),
        ("Shape of p-orbital is:", ["Dumbbell", "Spherical", "Clover leaf", "Cubic"], "Dumbbell"),
        ("Number of orbitals in d-subshell:", ["5", "3", "7", "1"], "5"),
        ("Maximum electrons in n=3 shell:", ["18", "8", "10", "32"], "18"),
        ("Maximum electrons in 4f subshell:", ["14", "10", "6", "2"], "14"),
        ("Nodal surface where ψ = 0 is called:", ["Node", "Orbital", "Shell", "Orbit"], "Node"),
        ("Number of radial nodes = ", ["n − l − 1", "n − l", "l", "n"], "n − l − 1"),
        ("Number of angular nodes = ", ["l", "n", "n − l", "m"], "l"),
    ],
    # ============ wk6: Aufbau, Pauli, Hund's Rules, Electronic Configuration ============
    6: [
        ("Aufbau principle states electrons fill:", ["Lower energy orbitals first", "Higher first", "s orbitals only", "Randomly"], "Lower energy orbitals first"),
        ("Order of filling: 4s vs 3d:", ["4s fills before 3d", "3d before 4s", "Same energy", "Never fills"], "4s fills before 3d"),
        ("Pauli's exclusion principle states:", ["No two electrons have same 4 quantum numbers", "Electrons fill singly", "Two electrons per orbital", "Same spin only"], "No two electrons have same 4 quantum numbers"),
        ("Maximum electrons per orbital:", ["2", "1", "3", "4"], "2"),
        ("Hund's rule of maximum multiplicity:", ["Orbitals of same subshell filled singly first", "Paired first", "Random", "Lowest energy only"], "Orbitals of same subshell filled singly first"),
        ("Electronic configuration of N (Z=7):", ["1s² 2s² 2p³", "1s² 2s² 2p⁴", "1s² 2s² 2p²", "1s² 2p⁵"], "1s² 2s² 2p³"),
        ("Electronic configuration of O (Z=8):", ["1s² 2s² 2p⁴", "1s² 2s² 2p⁵", "1s² 2s² 2p³", "1s² 2s² 2p⁶"], "1s² 2s² 2p⁴"),
        ("Electronic configuration of Na (Z=11):", ["1s² 2s² 2p⁶ 3s¹", "1s² 2s² 2p⁵ 3s²", "[Ne] 3s²", "[Ar] 3s¹"], "1s² 2s² 2p⁶ 3s¹"),
        ("Electronic configuration of Cr (Z=24) (actual):", ["[Ar] 3d⁵ 4s¹", "[Ar] 3d⁴ 4s²", "[Ar] 3d⁶ 4s⁰", "[Ne] 3d⁵"], "[Ar] 3d⁵ 4s¹"),
        ("Electronic configuration of Cu (Z=29) (actual):", ["[Ar] 3d¹⁰ 4s¹", "[Ar] 3d⁹ 4s²", "[Ar] 3d⁸ 4s³", "[Ar] 3d¹⁰ 4s²"], "[Ar] 3d¹⁰ 4s¹"),
        ("Why is [Ar] 3d⁵ 4s¹ more stable than [Ar] 3d⁴ 4s²:", ["Half-filled stability", "Fully filled", "Higher energy", "Aufbau"], "Half-filled stability"),
        ("Cu: 3d¹⁰4s¹ is more stable due to:", ["Fully-filled d subshell", "Half-filled", "Paired s", "Random"], "Fully-filled d subshell"),
        ("Fe (Z=26) configuration:", ["[Ar] 3d⁶ 4s²", "[Ar] 3d⁸ 4s⁰", "[Ar] 3d⁷ 4s¹", "[Ar] 3d⁵ 4s³"], "[Ar] 3d⁶ 4s²"),
        ("Zn (Z=30) configuration:", ["[Ar] 3d¹⁰ 4s²", "[Ar] 3d⁹ 4s¹", "[Kr] 3d¹⁰", "[Ar] 4s² 3d⁸"], "[Ar] 3d¹⁰ 4s²"),
        ("Number of unpaired electrons in Fe²⁺ ([Ar] 3d⁶):", ["4", "6", "2", "0"], "4"),
        ("Number of unpaired electrons in Mn²⁺ ([Ar] 3d⁵):", ["5", "3", "1", "2"], "5"),
        ("Ground state configuration of carbon (Z=6):", ["1s² 2s² 2p²", "1s² 2p⁴", "1s² 2s⁴", "1s² 2s² 2p¹ 2p¹"], "1s² 2s² 2p²"),
        ("Stability order: half-filled, fully-filled subshells are:", ["More stable", "Less stable", "Equally stable", "Unstable"], "More stable"),
        ("Electron spin generates:", ["Magnetic moment", "Gravity", "Electric force", "Mass"], "Magnetic moment"),
        ("Magnetic moment μ = √[n(n+2)] BM, where n is:", ["Unpaired electrons", "Total electrons", "Protons", "Neutrons"], "Unpaired electrons"),
        ("(n+l) rule: 4s and 3d — which has lower (n+l)?", ["4s [(4+0)=4] lower than 3d [(3+2)=5]", "3d lower", "Equal", "Neither"], "4s [(4+0)=4] lower than 3d [(3+2)=5]"),
        ("A paramagnetic species has:", ["Unpaired electrons", "All paired", "Zero electrons", "Positive charge"], "Unpaired electrons"),
        ("Diamagnetic species have:", ["All electrons paired", "Unpaired electrons", "Net spin", "Magnetic moment"], "All electrons paired"),
        ("Noble gas configuration of Ar:", ["1s² 2s² 2p⁶ 3s² 3p⁶", "1s² 2s² 2p⁶", "[Ne] 3s² 3p⁴", "[Kr]"], "1s² 2s² 2p⁶ 3s² 3p⁶"),
        ("Shorthand (core) notation uses the:", ["Previous noble gas", "Next noble gas", "Hydrogen", "Carbon"], "Previous noble gas"),
    ],
    # ============ wk7: Periodic Table – Genesis, Mendeleev, Modern ============
    7: [
        ("Dobereiner's triads are based on:", ["Atomic masses (middle = average)", "Atomic numbers", "Density", "Color"], "Atomic masses (middle = average)"),
        ("Newland's law of octaves applied to:", ["Elements arranged by atomic mass", "Atomic number", "Density", "Valency"], "Elements arranged by atomic mass"),
        ("Mendeleev's periodic law states properties are periodic function of:", ["Atomic mass", "Atomic number", "Density", "Valency"], "Atomic mass"),
        ("Modern periodic law states properties are periodic function of:", ["Atomic number", "Atomic mass", "Electrons", "Protons only"], "Atomic number"),
        ("Modern periodic law was given by:", ["Moseley", "Mendeleev", "Newland", "Lothar Meyer"], "Moseley"),
        ("Moseley's work was based on:", ["X-ray spectra", "Density", "Atomic mass", "Melting point"], "X-ray spectra"),
        ("Number of periods in modern periodic table:", ["7", "8", "6", "9"], "7"),
        ("Number of groups in modern periodic table:", ["18", "7", "8", "16"], "18"),
        ("The IUPAC name for element with Z=119 is:", ["Ununennium", "Ununseptium", "Flerovium", "Oganesson"], "Ununennium"),
        ("Group 1 elements are called:", ["Alkali metals", "Alkaline earth", "Halogens", "Noble gases"], "Alkali metals"),
        ("Group 2 elements are called:", ["Alkaline earth metals", "Alkali metals", "Chalcogens", "Pnictogens"], "Alkaline earth metals"),
        ("Group 17 elements are called:", ["Halogens", "Chalcogens", "Noble gases", "Alkali metals"], "Halogens"),
        ("Group 18 elements are called:", ["Noble gases", "Halogens", "Alkaline earth", "Transition"], "Noble gases"),
        ("d-block elements are in groups:", ["3–12", "1–2", "13–18", "1–7"], "3–12"),
        ("f-block elements include:", ["Lanthanides and actinides", "Only lanthanides", "Only actinides", "Noble gases"], "Lanthanides and actinides"),
        ("s-block contains groups:", ["1 and 2", "3–12", "13–17", "18"], "1 and 2"),
        ("p-block contains groups:", ["13–18", "1–2", "3–12", "f-block"], "13–18"),
        ("Element with Z=11 belongs to period/group:", ["Period 3, Group 1", "Period 2, Group 1", "Period 3, Group 11", "Period 4, Group 1"], "Period 3, Group 1"),
        ("Element with configuration [Ar] 3d⁷ 4s² is:", ["Co (Z=27)", "Fe (Z=26)", "Ni (Z=28)", "Mn (Z=25)"], "Co (Z=27)"),
        ("Lanthanide contraction is due to:", ["Poor shielding by 4f electrons", "Fully filled s", "Small nuclei", "Hund's rule"], "Poor shielding by 4f electrons"),
        ("Cause of periodicity in properties:", ["Recurrence of similar configuration", "Same mass", "Same density", "Random"], "Recurrence of similar configuration"),
        ("Eka-aluminium predicted by Mendeleev was later identified as:", ["Gallium", "Germanium", "Scandium", "Technetium"], "Gallium"),
        ("Which pair has same group but different periods:", ["Na, K", "Na, Mg", "Na, Al", "Na, Cl"], "Na, K"),
        ("Element in Period 4, Group 17 is:", ["Br", "Cl", "I", "F"], "Br"),
        ("Transuranic elements have Z:", ["> 92", "< 92", "= 92", "= 118 only"], "> 92"),
    ],
    # ============ wk8: Periodic Trends (Atomic Radius, IE, EA, EN) ============
    8: [
        ("Atomic radius along a period (left to right):", ["Decreases", "Increases", "Constant", "Zigzag"], "Decreases"),
        ("Atomic radius down a group:", ["Increases", "Decreases", "Constant", "Random"], "Increases"),
        ("Reason for decrease in radius along period:", ["Increase in Z_eff", "More shells", "Shielding", "Mass"], "Increase in Z_eff"),
        ("Reason for increase in radius down a group:", ["More shells", "Higher Z_eff", "Fewer electrons", "Less shielding"], "More shells"),
        ("Cation is ___ than parent atom:", ["Smaller", "Larger", "Same", "Double"], "Smaller"),
        ("Anion is ___ than parent atom:", ["Larger", "Smaller", "Same", "Half"], "Larger"),
        ("Order of radii: Na⁺, Mg²⁺, Al³⁺ (isoelectronic):", ["Na⁺ > Mg²⁺ > Al³⁺", "Al³⁺ > Mg²⁺ > Na⁺", "All equal", "Mg²⁺ largest"], "Na⁺ > Mg²⁺ > Al³⁺"),
        ("First ionization enthalpy (IE₁) is:", ["Energy to remove 1 outermost electron", "Energy to add electron", "Energy to form bond", "Heat of formation"], "Energy to remove 1 outermost electron"),
        ("IE along a period:", ["Increases", "Decreases", "Constant", "Alternates"], "Increases"),
        ("IE down a group:", ["Decreases", "Increases", "Constant", "Zigzag"], "Decreases"),
        ("IE order: Li, Be, B, C:", ["Li < B < Be < C", "Li < Be < B < C", "Li > B > Be > C", "Li > Be > B > C"], "Li < B < Be < C"),
        ("IE of Be > B because:", ["2s² is more stable", "B has more electrons", "Be has more protons", "Random"], "2s² is more stable"),
        ("IE of N > O because:", ["Half-filled 2p³ stability of N", "O is larger", "N is heavier", "Random"], "Half-filled 2p³ stability of N"),
        ("Successive ionization energies:", ["IE₁ < IE₂ < IE₃ ...", "IE₁ > IE₂", "All equal", "Random"], "IE₁ < IE₂ < IE₃ ..."),
        ("Element with highest IE₁ in period 2:", ["Ne", "Li", "F", "O"], "Ne"),
        ("Electron gain enthalpy (ΔH_eg) is:", ["Energy change on adding e⁻", "Energy to remove", "Bond energy", "Heat of ionization"], "Energy change on adding e⁻"),
        ("ΔH_eg of halogens is:", ["Most negative", "Most positive", "Zero", "Very small"], "Most negative"),
        ("ΔH_eg of noble gases:", ["Positive (absorbs energy)", "Most negative", "Zero", "Large negative"], "Positive (absorbs energy)"),
        ("Which has more negative ΔH_eg: Cl or F?", ["Cl (more negative)", "F (more negative)", "Equal", "Neither"], "Cl (more negative)"),
        ("Electronegativity (EN) is:", ["Tendency to attract bonded electrons", "To lose electrons", "To form cation", "Mass"], "Tendency to attract bonded electrons"),
        ("Pauling's scale max EN is for:", ["Fluorine (4.0)", "Oxygen", "Chlorine", "Nitrogen"], "Fluorine (4.0)"),
        ("EN order: F, Cl, Br, I:", ["F > Cl > Br > I", "I > Br > Cl > F", "All equal", "Cl > F"], "F > Cl > Br > I"),
        ("Metallic character along a period:", ["Decreases", "Increases", "Constant", "Zigzag"], "Decreases"),
        ("Metallic character down a group:", ["Increases", "Decreases", "Constant", "Random"], "Increases"),
        ("Most metallic element is:", ["Francium (Fr)", "Cesium (Cs)", "Sodium", "Fluorine"], "Cesium (Cs)"),
    ],
    # ============ wk9: Ionic Bond, Lattice Energy, Born-Haber Cycle ============
    9: [
        ("Ionic bond is formed by:", ["Transfer of electrons", "Sharing", "Overlapping", "Resonance"], "Transfer of electrons"),
        ("Ionic compounds are formed between:", ["Metal and non-metal", "Two non-metals", "Two metals", "Noble gases"], "Metal and non-metal"),
        ("Favorable conditions for ionic bond:", ["Low IE of metal, high EA of non-metal", "High IE, low EA", "Both high", "Both low"], "Low IE of metal, high EA of non-metal"),
        ("Lattice energy is defined as energy:", ["Released when 1 mol ionic solid forms from gaseous ions", "Absorbed in melting", "To break covalent bond", "Heat of formation"], "Released when 1 mol ionic solid forms from gaseous ions"),
        ("Lattice energy depends on:", ["Charge and size of ions", "Temperature only", "Color", "Density"], "Charge and size of ions"),
        ("Lattice energy is higher for ions with:", ["Higher charge, smaller size", "Lower charge, larger size", "Same charge", "Equal size"], "Higher charge, smaller size"),
        ("Born-Haber cycle is used to calculate:", ["Lattice energy", "Bond energy", "IE", "EA"], "Lattice energy"),
        ("In Born-Haber cycle for NaCl, sublimation refers to:", ["Na(s) → Na(g)", "Cl₂ → 2Cl", "Na → Na⁺", "NaCl(s) formation"], "Na(s) → Na(g)"),
        ("Ionization energy step in Born-Haber:", ["Na(g) → Na⁺(g) + e⁻", "Na(s) → Na(g)", "Cl → Cl⁻", "Na⁺ + Cl⁻ → NaCl"], "Na(g) → Na⁺(g) + e⁻"),
        ("Bond dissociation step for Cl₂:", ["½Cl₂(g) → Cl(g)", "Cl⁻ → Cl", "Cl₂ → 2Cl⁻", "Cl → Cl⁺"], "½Cl₂(g) → Cl(g)"),
        ("Electron gain step:", ["Cl(g) + e⁻ → Cl⁻(g)", "Na → Na⁺", "Cl → Cl⁺", "Cl⁻ → Cl"], "Cl(g) + e⁻ → Cl⁻(g)"),
        ("Lattice formation enthalpy U of NaCl is:", ["Large negative (−787 kJ/mol)", "Positive", "Zero", "Small positive"], "Large negative (−787 kJ/mol)"),
        ("High melting point of ionic compounds is due to:", ["Strong electrostatic forces", "Weak vdW", "Covalent bonds", "Metallic bond"], "Strong electrostatic forces"),
        ("Ionic compounds are soluble in:", ["Polar solvents (water)", "Non-polar solvents", "Benzene", "CCl₄"], "Polar solvents (water)"),
        ("Ionic compounds conduct electricity when:", ["Molten or dissolved", "Solid", "Never", "As gas"], "Molten or dissolved"),
        ("Fajan's rules predict:", ["Covalent character in ionic bonds", "Bond length", "IE", "EA"], "Covalent character in ionic bonds"),
        ("Covalent character increases with:", ["Small cation, large anion, high charge", "Large cation, small anion", "Same size", "Low charge"], "Small cation, large anion, high charge"),
        ("Which compound is most covalent: NaCl, MgCl₂, AlCl₃:", ["AlCl₃", "NaCl", "MgCl₂", "All same"], "AlCl₃"),
        ("Polarizing power of cation depends on:", ["Charge and size", "Color", "Mass", "Volume only"], "Charge and size"),
        ("Polarizability of anion is higher for:", ["Larger anions", "Smaller anions", "Neutral", "Cations"], "Larger anions"),
        ("Crystal structure of NaCl is:", ["Face-centered cubic", "Body-centered cubic", "Hexagonal", "Triclinic"], "Face-centered cubic"),
        ("Coordination number in NaCl:", ["6:6", "4:4", "8:8", "12:12"], "6:6"),
        ("Coordination number in CsCl:", ["8:8", "6:6", "4:4", "12:12"], "8:8"),
        ("Coordination number in ZnS (zinc blende):", ["4:4", "6:6", "8:8", "3:3"], "4:4"),
        ("Bond energy of ionic bond is typically:", ["400–4000 kJ/mol", "10 kJ/mol", "Negative always", "Less than vdW"], "400–4000 kJ/mol"),
    ],
    # ============ wk10: Covalent Bond, Lewis Structures, Formal Charge ============
    10: [
        ("Covalent bond is formed by:", ["Sharing of electrons", "Transfer", "Electrostatic", "Metallic"], "Sharing of electrons"),
        ("Octet rule states atoms tend to have:", ["8 electrons in valence shell", "2 electrons", "10 electrons", "18 electrons"], "8 electrons in valence shell"),
        ("Lewis symbol shows:", ["Valence electrons as dots", "All electrons", "Protons", "Nucleus"], "Valence electrons as dots"),
        ("Number of valence electrons in N:", ["5", "3", "7", "2"], "5"),
        ("Lewis structure of H₂O has:", ["2 bond pairs, 2 lone pairs on O", "4 bond pairs", "1 lone pair", "3 bond pairs"], "2 bond pairs, 2 lone pairs on O"),
        ("Lewis structure of NH₃ has:", ["3 bond pairs, 1 lone pair on N", "4 bond pairs", "0 lone pairs", "2 lone pairs"], "3 bond pairs, 1 lone pair on N"),
        ("Number of covalent bonds in CO₂:", ["4 (two double bonds)", "2", "6", "3"], "4 (two double bonds)"),
        ("Number of bonds in N₂:", ["3 (triple bond)", "1", "2", "4"], "3 (triple bond)"),
        ("Single bond consists of:", ["One σ bond", "One π bond", "σ + π", "Two σ"], "One σ bond"),
        ("Double bond consists of:", ["1σ + 1π", "2σ", "2π", "1σ + 2π"], "1σ + 1π"),
        ("Triple bond consists of:", ["1σ + 2π", "3σ", "2σ + 1π", "3π"], "1σ + 2π"),
        ("Bond order for N₂:", ["3", "2", "1", "4"], "3"),
        ("Formal charge formula: FC =", ["(Valence e⁻) − (lone pair e⁻) − ½(bond pair e⁻)", "Valence − shared", "Lone − bonded", "Total e⁻"], "(Valence e⁻) − (lone pair e⁻) − ½(bond pair e⁻)"),
        ("Formal charge on C in CO₂ is:", ["0", "+1", "−1", "+2"], "0"),
        ("Formal charge on O in ozone O₃ central atom:", ["+1", "0", "−1", "+2"], "+1"),
        ("Exception to octet rule — incomplete octet:", ["BF₃ (6 e⁻ around B)", "PCl₅", "SF₆", "CO₂"], "BF₃ (6 e⁻ around B)"),
        ("Exception — expanded octet:", ["SF₆ (12 e⁻ around S)", "H₂O", "NH₃", "CH₄"], "SF₆ (12 e⁻ around S)"),
        ("Exception — odd electron species:", ["NO (11 valence e⁻)", "CO₂", "N₂", "CH₄"], "NO (11 valence e⁻)"),
        ("Resonance structures differ only in:", ["Position of electrons", "Position of atoms", "Formula", "Both"], "Position of electrons"),
        ("Resonance hybrid is:", ["More stable than any contributor", "Less stable", "Same as average", "Does not exist"], "More stable than any contributor"),
        ("Resonance in benzene gives it:", ["Delocalized π electrons", "Localized bonds", "Ionic character", "No stability"], "Delocalized π electrons"),
        ("Number of resonance structures of CO₃²⁻:", ["3", "2", "4", "1"], "3"),
        ("Bond length order: C−C, C=C, C≡C:", ["C−C > C=C > C≡C", "C≡C > C=C > C−C", "Equal", "C=C longest"], "C−C > C=C > C≡C"),
        ("Bond energy order: C−C, C=C, C≡C:", ["C≡C > C=C > C−C", "C−C > C=C > C≡C", "Equal", "C=C highest"], "C≡C > C=C > C−C"),
        ("A coordinate (dative) bond is:", ["Both electrons from one atom", "One from each", "Ionic", "Metallic"], "Both electrons from one atom"),
    ],
    # ============ wk11: VSEPR Theory, Molecular Geometry ============
    11: [
        ("VSEPR stands for:", ["Valence Shell Electron Pair Repulsion", "Valence Shell Exchange", "Voltage Electron Pair", "Vibrational Spectrum"], "Valence Shell Electron Pair Repulsion"),
        ("VSEPR theory was given by:", ["Sidgwick & Powell (Gillespie & Nyholm)", "Bohr", "Lewis", "Pauling"], "Sidgwick & Powell (Gillespie & Nyholm)"),
        ("Repulsion order (maximum first):", ["lp-lp > lp-bp > bp-bp", "bp-bp > lp-bp", "All equal", "lp-bp > lp-lp"], "lp-lp > lp-bp > bp-bp"),
        ("Shape of BeCl₂ (AB₂, no lp):", ["Linear", "Bent", "Trigonal", "Tetrahedral"], "Linear"),
        ("Bond angle in BeCl₂:", ["180°", "120°", "109.5°", "90°"], "180°"),
        ("Shape of BF₃ (AB₃):", ["Trigonal planar", "Pyramidal", "Bent", "Tetrahedral"], "Trigonal planar"),
        ("Bond angle in BF₃:", ["120°", "109.5°", "90°", "180°"], "120°"),
        ("Shape of CH₄ (AB₄):", ["Tetrahedral", "Square planar", "Pyramidal", "Linear"], "Tetrahedral"),
        ("Bond angle in CH₄:", ["109.5°", "120°", "90°", "104.5°"], "109.5°"),
        ("Shape of NH₃ (AB₃E, 1 lp):", ["Trigonal pyramidal", "Trigonal planar", "Tetrahedral", "Bent"], "Trigonal pyramidal"),
        ("Bond angle in NH₃:", ["107°", "109.5°", "120°", "104.5°"], "107°"),
        ("Shape of H₂O (AB₂E₂, 2 lp):", ["Bent (angular)", "Linear", "Tetrahedral", "T-shape"], "Bent (angular)"),
        ("Bond angle in H₂O:", ["104.5°", "109.5°", "120°", "180°"], "104.5°"),
        ("Bond angle decreases NH₃ (107°) to H₂O (104.5°) because:", ["More lone pairs", "Less repulsion", "Bigger atom", "Random"], "More lone pairs"),
        ("Shape of PCl₅ (AB₅):", ["Trigonal bipyramidal", "Square pyramidal", "Octahedral", "Tetrahedral"], "Trigonal bipyramidal"),
        ("Axial bond angle in PCl₅:", ["90° (axial-equatorial)", "120°", "109.5°", "180°"], "90° (axial-equatorial)"),
        ("Shape of SF₆ (AB₆):", ["Octahedral", "Trigonal bipyramidal", "Tetrahedral", "Cubic"], "Octahedral"),
        ("Bond angle in SF₆:", ["90° (all)", "109.5°", "120°", "60°"], "90° (all)"),
        ("Shape of SF₄ (AB₄E):", ["See-saw", "Square planar", "Tetrahedral", "Linear"], "See-saw"),
        ("Shape of ClF₃ (AB₃E₂):", ["T-shape", "Trigonal planar", "Linear", "Bent"], "T-shape"),
        ("Shape of XeF₂ (AB₂E₃):", ["Linear", "Bent", "T-shape", "Trigonal"], "Linear"),
        ("Shape of XeF₄ (AB₄E₂):", ["Square planar", "Tetrahedral", "See-saw", "Octahedral"], "Square planar"),
        ("Shape of BrF₅ (AB₅E):", ["Square pyramidal", "Trigonal bipyramidal", "Octahedral", "T-shape"], "Square pyramidal"),
        ("Total electron pairs in SO₄²⁻:", ["4 (tetrahedral)", "3", "5", "6"], "4 (tetrahedral)"),
        ("Polar molecule among CO₂, H₂O, CH₄:", ["H₂O", "CO₂", "CH₄", "None"], "H₂O"),
    ],
    # ============ wk12: Hybridization ============
    12: [
        ("Hybridization is mixing of:", ["Atomic orbitals of similar energy", "Different shells", "Nuclei", "Electrons only"], "Atomic orbitals of similar energy"),
        ("Hybridization in BeCl₂:", ["sp", "sp²", "sp³", "sp³d"], "sp"),
        ("Hybridization in BF₃:", ["sp²", "sp", "sp³", "sp³d²"], "sp²"),
        ("Hybridization in CH₄:", ["sp³", "sp²", "sp", "sp³d"], "sp³"),
        ("Hybridization in NH₃:", ["sp³", "sp²", "sp", "dsp²"], "sp³"),
        ("Hybridization in H₂O:", ["sp³", "sp²", "sp", "d²sp"], "sp³"),
        ("Hybridization in C₂H₄ (each C):", ["sp²", "sp³", "sp", "dsp²"], "sp²"),
        ("Hybridization in C₂H₂ (each C):", ["sp", "sp²", "sp³", "sp³d"], "sp"),
        ("Hybridization in PCl₅:", ["sp³d", "sp³", "sp³d²", "sp²"], "sp³d"),
        ("Hybridization in SF₆:", ["sp³d²", "sp³d", "sp³", "d²sp³"], "sp³d²"),
        ("sp hybrid orbital angle:", ["180°", "120°", "109.5°", "90°"], "180°"),
        ("sp² hybrid orbital angle:", ["120°", "180°", "109.5°", "90°"], "120°"),
        ("sp³ hybrid orbital angle:", ["109.5°", "120°", "90°", "180°"], "109.5°"),
        ("Number of hybrid orbitals formed from sp³:", ["4", "3", "2", "5"], "4"),
        ("% s-character in sp hybrid:", ["50%", "33%", "25%", "100%"], "50%"),
        ("% s-character in sp² hybrid:", ["33.3%", "50%", "25%", "75%"], "33.3%"),
        ("% s-character in sp³ hybrid:", ["25%", "50%", "33%", "75%"], "25%"),
        ("Bond length order: C−C in CH₄, C₂H₄, C₂H₂:", ["CH₄ > C₂H₄ > C₂H₂", "C₂H₂ > C₂H₄ > CH₄", "All equal", "CH₄ < C₂H₂"], "CH₄ > C₂H₄ > C₂H₂"),
        ("Hybridization in NO₃⁻:", ["sp² (trigonal planar)", "sp³", "sp", "sp³d"], "sp² (trigonal planar)"),
        ("Hybridization in SO₃:", ["sp²", "sp³", "sp³d", "sp"], "sp²"),
        ("Hybridization in XeF₂:", ["sp³d", "sp³", "sp³d²", "sp²"], "sp³d"),
        ("Hybridization in XeF₄:", ["sp³d²", "sp³d", "sp³", "dsp²"], "sp³d²"),
        ("Hybridization in XeF₆:", ["sp³d³", "sp³d²", "sp³d", "sp³"], "sp³d³"),
        ("Hybridization in benzene (each C):", ["sp²", "sp³", "sp", "sp³d"], "sp²"),
        ("Hybridization in CO₃²⁻ central C:", ["sp²", "sp³", "sp", "sp³d"], "sp²"),
    ],
    # ============ wk13: Molecular Orbital Theory ============
    13: [
        ("MO theory was proposed by:", ["Mulliken & Hund", "Pauling", "Sidgwick", "Lewis"], "Mulliken & Hund"),
        ("Number of MOs formed from N AOs:", ["N", "2N", "N/2", "1"], "N"),
        ("Bonding MO has energy:", ["Lower than AOs", "Higher than AOs", "Same as AOs", "Zero"], "Lower than AOs"),
        ("Antibonding MO (e.g. σ*) has:", ["Higher energy than AOs", "Lower energy", "Same", "Negative"], "Higher energy than AOs"),
        ("Bond order = ", ["(N_b − N_a)/2", "N_b + N_a", "N_b/N_a", "(N_b − N_a)"], "(N_b − N_a)/2"),
        ("Bond order of H₂:", ["1", "0", "2", "½"], "1"),
        ("Bond order of He₂:", ["0 (unstable)", "1", "2", "½"], "0 (unstable)"),
        ("Bond order of N₂:", ["3", "2", "1", "2.5"], "3"),
        ("Bond order of O₂:", ["2", "3", "1", "1.5"], "2"),
        ("Magnetic nature of O₂:", ["Paramagnetic", "Diamagnetic", "Ferromagnetic", "Antiferromagnetic"], "Paramagnetic"),
        ("O₂ is paramagnetic because:", ["2 unpaired e⁻ in π* orbitals", "All paired", "Ionic", "High energy"], "2 unpaired e⁻ in π* orbitals"),
        ("Bond order of O₂⁻ (superoxide):", ["1.5", "2", "1", "2.5"], "1.5"),
        ("Bond order of O₂²⁻ (peroxide):", ["1", "2", "1.5", "3"], "1"),
        ("Bond order of F₂:", ["1", "0", "2", "3"], "1"),
        ("Which is not stable: He₂ or Be₂:", ["Both (bond order = 0)", "Only He₂", "Only Be₂", "Both stable"], "Both (bond order = 0)"),
        ("MO energy order for O₂, F₂:", ["σ1s < σ*1s < σ2s < σ*2s < σ2p_z < π2p < π*2p < σ*2p_z", "Reverse", "σ < π only", "All equal"], "σ1s < σ*1s < σ2s < σ*2s < σ2p_z < π2p < π*2p < σ*2p_z"),
        ("For B₂, C₂, N₂ the order differs in:", ["π2p < σ2p_z", "σ before π", "Same as O₂", "No change"], "π2p < σ2p_z"),
        ("Bond order and stability:", ["Higher bond order → more stable", "Opposite", "Unrelated", "Random"], "Higher bond order → more stable"),
        ("Bond length and bond order:", ["Higher bond order → shorter", "Longer", "Same", "Zero"], "Higher bond order → shorter"),
        ("N₂⁺ bond order:", ["2.5", "3", "1.5", "2"], "2.5"),
        ("N₂⁻ bond order:", ["2.5", "3", "1.5", "2"], "2.5"),
        ("HOMO stands for:", ["Highest Occupied MO", "Highest Oxidation", "Hybrid", "Helium"], "Highest Occupied MO"),
        ("LUMO stands for:", ["Lowest Unoccupied MO", "Lowest Oxidation", "Lattice", "Linear"], "Lowest Unoccupied MO"),
        ("Constructive overlap gives:", ["Bonding MO", "Antibonding MO", "No MO", "Non-bonding"], "Bonding MO"),
        ("Destructive overlap gives:", ["Antibonding MO (with node)", "Bonding", "No effect", "Hybrid"], "Antibonding MO (with node)"),
    ],
    # ============ wk14: H-bonding, Metallic, van der Waals Forces ============
    14: [
        ("Hydrogen bond is between H bonded to ___ and another ___ atom:", ["F/O/N; F/O/N", "C; C", "H; H", "Metal; metal"], "F/O/N; F/O/N"),
        ("Why does water have high boiling point:", ["Extensive H-bonding", "High mass", "Covalent bonds", "Metallic"], "Extensive H-bonding"),
        ("Intramolecular H-bond is in:", ["o-nitrophenol", "p-nitrophenol", "Water", "HF dimer"], "o-nitrophenol"),
        ("Intermolecular H-bond example:", ["HF chains", "o-nitrophenol", "N₂", "CCl₄"], "HF chains"),
        ("H-bond energy is about:", ["10–40 kJ/mol", "400 kJ/mol", "1000 kJ/mol", "0.1 kJ/mol"], "10–40 kJ/mol"),
        ("Boiling point order: H₂O > H₂S because:", ["H₂O has H-bonding", "H₂S is ionic", "H₂S heavier", "No reason"], "H₂O has H-bonding"),
        ("Ice is less dense than water because:", ["Open cage structure due to H-bonds", "Lower mass", "Fewer molecules", "Higher temperature"], "Open cage structure due to H-bonds"),
        ("H-bonds are present in which biomolecules:", ["DNA, proteins", "Only carbohydrates", "Lipids only", "None"], "DNA, proteins"),
        ("Metallic bond is formed by:", ["Delocalized sea of electrons", "Sharing pairs", "Transfer", "H-bonding"], "Delocalized sea of electrons"),
        ("Metals conduct electricity because:", ["Free-moving electrons", "H-bonds", "Ionic", "Covalent"], "Free-moving electrons"),
        ("Malleability of metals due to:", ["Layers of atoms can slide", "Strong covalent", "Ionic lattice", "H-bonds"], "Layers of atoms can slide"),
        ("Which is strongest: metallic bond of Na or W:", ["W (more valence e⁻, higher charge)", "Na", "Both equal", "Neither"], "W (more valence e⁻, higher charge)"),
        ("van der Waals forces include:", ["Dispersion, dipole-dipole, dipole-induced dipole", "H-bond only", "Ionic", "Covalent"], "Dispersion, dipole-dipole, dipole-induced dipole"),
        ("London dispersion forces are:", ["Instantaneous induced dipole forces", "Permanent dipoles", "H-bonds", "Ionic"], "Instantaneous induced dipole forces"),
        ("Dispersion force is largest for:", ["Large, more polarizable atoms", "Small atoms", "Polar", "Ions"], "Large, more polarizable atoms"),
        ("Dipole-dipole force exists in:", ["HCl", "N₂", "CH₄", "He"], "HCl"),
        ("Dispersion force only in:", ["Noble gases, nonpolar molecules", "H₂O", "HF", "NH₃"], "Noble gases, nonpolar molecules"),
        ("Relative strength order:", ["Ionic > H-bond > dipole-dipole > dispersion", "Reverse", "Random", "Equal"], "Ionic > H-bond > dipole-dipole > dispersion"),
        ("Boiling point of halogens increases F₂ < Cl₂ < Br₂ < I₂ due to:", ["Increasing dispersion force", "H-bond", "Ionic", "Covalent"], "Increasing dispersion force"),
        ("Which has higher bp: o-nitrophenol or p-nitrophenol:", ["p-nitrophenol (intermolecular H-bond)", "o-nitrophenol", "Equal", "Neither"], "p-nitrophenol (intermolecular H-bond)"),
        ("Polarity in HCl is due to:", ["Difference in EN", "Same EN", "Ionic bond", "H-bond"], "Difference in EN"),
        ("Dipole moment of CO₂:", ["Zero (linear, symmetric)", "Non-zero", "Very large", "Infinite"], "Zero (linear, symmetric)"),
        ("Dipole moment of H₂O:", ["1.85 D (bent, net dipole)", "Zero", "10 D", "0.1 D"], "1.85 D (bent, net dipole)"),
        ("Which has no H-bonding: HF, H₂O, NH₃, CH₄:", ["CH₄", "HF", "H₂O", "NH₃"], "CH₄"),
        ("Strongest intermolecular force in liquid NH₃:", ["H-bonding", "Ionic", "Dispersion only", "Metallic"], "H-bonding"),
    ],
}

def main():
    with open(TARGET, "r", encoding="utf-8") as f:
        d = json.load(f)

    total_replaced = 0
    weeks_updated = []
    for week_entry in d["11"]:
        wk = week_entry["week"]
        if wk not in QS:
            continue
        qlist = QS[wk]
        assert len(qlist) == 25, f"wk{wk} has {len(qlist)} questions, expected 25"
        new_questions = []
        for i, (q, opts, ans) in enumerate(qlist, 1):
            assert len(opts) == 4, f"wk{wk} q{i} has {len(opts)} options"
            assert ans in opts, f"wk{wk} q{i} answer {ans!r} not in options"
            new_questions.append({
                "id": f"c11-w{wk}-q{i}",
                "question": q,
                "options": opts,
                "answer": ans,
            })
        week_entry["questions"] = new_questions
        total_replaced += len(new_questions)
        weeks_updated.append(wk)

    with open(TARGET, "w", encoding="utf-8") as f:
        f.write(json.dumps(d, indent=2, ensure_ascii=False) + "\n")

    print(f"Replaced {total_replaced} chemistry/11 placeholder questions across {len(weeks_updated)} weeks: {weeks_updated}")

if __name__ == "__main__":
    main()
