#!/usr/bin/env python3
"""Replace placeholder MCQs in chemistry-quizzes.json for class 11, weeks 15-26.

Coverage: Thermodynamics (wk15-17), Equilibrium (wk18-21), Redox (wk22-23),
Organic chemistry basics (wk24-26). 12 weeks × 25 = 300 real MCQs.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
TARGET = ROOT / "src" / "data" / "chemistry-quizzes.json"

QS = {
    # ============ wk15: System, Surroundings, State Functions, First Law ============
    15: [
        ("In thermodynamics, 'system' means:", ["Part under study", "Rest of universe", "Both", "Only container"], "Part under study"),
        ("Everything outside system is:", ["Surroundings", "Boundary", "Universe", "State"], "Surroundings"),
        ("Universe = ", ["System + surroundings", "System only", "Surroundings only", "Reactants"], "System + surroundings"),
        ("A system that exchanges both matter and energy is:", ["Open", "Closed", "Isolated", "Adiabatic"], "Open"),
        ("A system that exchanges energy but not matter:", ["Closed", "Open", "Isolated", "Rigid"], "Closed"),
        ("A system that exchanges neither is:", ["Isolated", "Open", "Closed", "Adiabatic"], "Isolated"),
        ("Example of isolated system:", ["Thermos flask (ideal)", "Open beaker", "Closed flask", "Reactor"], "Thermos flask (ideal)"),
        ("State function depends on:", ["Initial and final states", "Path", "Both", "Neither"], "Initial and final states"),
        ("Which is a state function:", ["U (internal energy)", "q", "w", "Heat capacity"], "U (internal energy)"),
        ("Which is NOT a state function:", ["Work (w)", "Enthalpy (H)", "Entropy (S)", "Gibbs energy (G)"], "Work (w)"),
        ("First law of thermodynamics:", ["ΔU = q + w", "ΔU = q − w", "ΔH = ΔU", "q = w"], "ΔU = q + w"),
        ("Sign convention: heat absorbed by system:", ["+q", "−q", "Zero", "Undefined"], "+q"),
        ("Sign convention: work done ON system:", ["+w", "−w", "Zero", "Infinity"], "+w"),
        ("Work of expansion at constant P: w =", ["−PΔV", "PΔV", "ΔPV", "PV"], "−PΔV"),
        ("In isothermal process:", ["ΔT = 0", "Δq = 0", "ΔV = 0", "ΔP = 0"], "ΔT = 0"),
        ("In adiabatic process:", ["q = 0", "T = 0", "V = 0", "ΔU = 0"], "q = 0"),
        ("In isochoric process:", ["ΔV = 0", "ΔT = 0", "ΔP = 0", "q = 0"], "ΔV = 0"),
        ("In isobaric process:", ["ΔP = 0", "ΔT = 0", "ΔV = 0", "q = 0"], "ΔP = 0"),
        ("For isothermal reversible expansion of ideal gas: w =", ["−nRT ln(V₂/V₁)", "nRT ln(V₂/V₁)", "−PΔV", "zero"], "−nRT ln(V₂/V₁)"),
        ("For isothermal process of ideal gas, ΔU =", ["0", "−nRT", "nRT", "CvΔT"], "0"),
        ("Enthalpy H is defined as:", ["U + PV", "U − PV", "q + w", "TΔS"], "U + PV"),
        ("At constant P: ΔH =", ["q_p", "q_v", "ΔU", "w"], "q_p"),
        ("At constant V: ΔU =", ["q_v", "q_p", "ΔH", "w"], "q_v"),
        ("ΔH − ΔU = ", ["Δn_g·RT", "nRT", "ΔnRT/V", "−PV"], "Δn_g·RT"),
        ("Heat capacity C = ", ["q/ΔT", "q × ΔT", "ΔT/q", "1/q"], "q/ΔT"),
    ],
    # ============ wk16: Enthalpy, Hess's Law, Bond Enthalpy ============
    16: [
        ("Standard enthalpy of formation ΔH°f of elements in standard state:", ["Zero", "Positive", "Negative", "Equal to one"], "Zero"),
        ("ΔH°f of H₂O(l) at 298 K is:", ["−285.8 kJ/mol", "+285.8 kJ/mol", "Zero", "−44 kJ/mol"], "−285.8 kJ/mol"),
        ("Exothermic reaction has:", ["ΔH negative", "ΔH positive", "ΔH zero", "ΔS negative"], "ΔH negative"),
        ("Endothermic reaction has:", ["ΔH positive", "ΔH negative", "ΔH zero", "ΔS zero"], "ΔH positive"),
        ("Hess's law is a consequence of:", ["First law of thermodynamics", "Second law", "Third law", "Zeroth law"], "First law of thermodynamics"),
        ("Hess's law states ΔH of reaction is:", ["Same regardless of path", "Path dependent", "Zero always", "Positive"], "Same regardless of path"),
        ("Born-Haber cycle uses ___ law:", ["Hess's", "Newton's", "Dalton's", "Boyle's"], "Hess's"),
        ("Enthalpy of combustion is always:", ["Negative", "Positive", "Zero", "Variable"], "Negative"),
        ("Enthalpy of neutralization (strong acid + strong base):", ["−57.1 kJ/mol", "+57.1 kJ/mol", "Zero", "−285.8 kJ/mol"], "−57.1 kJ/mol"),
        ("Enthalpy of atomization is:", ["Energy to break 1 mol substance into atoms", "To form molecule", "Of formation", "Of combustion"], "Energy to break 1 mol substance into atoms"),
        ("Bond enthalpy is energy to break:", ["1 mol gaseous bonds", "Liquid bonds", "Solid bonds", "Half mol"], "1 mol gaseous bonds"),
        ("ΔH of reaction from bond enthalpies = ", ["(Bonds broken) − (bonds formed)", "(Bonds formed) − (broken)", "Sum of all bonds", "Zero"], "(Bonds broken) − (bonds formed)"),
        ("Mean bond enthalpy of C−H in CH₄ is:", ["~416 kJ/mol", "100 kJ/mol", "1000 kJ/mol", "50 kJ/mol"], "~416 kJ/mol"),
        ("Enthalpy of sublimation = ΔH_fusion +", ["ΔH_vaporization", "ΔH_condensation", "−ΔH_fusion", "ΔH_combustion"], "ΔH_vaporization"),
        ("Enthalpy of vaporization of water at 100°C:", ["+40.7 kJ/mol", "−40.7 kJ/mol", "+6 kJ/mol", "+285 kJ/mol"], "+40.7 kJ/mol"),
        ("Enthalpy of fusion of ice at 0°C:", ["+6.0 kJ/mol", "+40.7 kJ/mol", "0", "−6 kJ/mol"], "+6.0 kJ/mol"),
        ("Standard state of carbon is:", ["Graphite", "Diamond", "Fullerene", "C₆₀"], "Graphite"),
        ("ΔH°_reaction from ΔH°f: ΔH° = ", ["Σ ΔH°f (products) − Σ ΔH°f (reactants)", "Reverse", "Sum of all", "Product only"], "Σ ΔH°f (products) − Σ ΔH°f (reactants)"),
        ("Enthalpy of solution is:", ["Heat change when 1 mol dissolves", "Heat of reaction", "Heat of fusion", "Heat of neutralization"], "Heat change when 1 mol dissolves"),
        ("Heat of combustion of 1 mol C:", ["−393.5 kJ/mol", "+393.5", "−1367", "−285"], "−393.5 kJ/mol"),
        ("Calorific value is defined for:", ["Fuel (heat released per g)", "Element", "Compound", "Gas"], "Fuel (heat released per g)"),
        ("Enthalpy of solution of NaOH in water is:", ["Negative (exothermic)", "Positive", "Zero", "Variable"], "Negative (exothermic)"),
        ("ΔH of reversing a reaction:", ["Sign reverses", "Magnitude doubles", "Same value", "Zero"], "Sign reverses"),
        ("For 2H₂(g) + O₂(g) → 2H₂O(l), ΔH = ", ["2 × ΔH°f(H₂O)", "ΔH°f(H₂O)", "Zero", "Sum of bonds"], "2 × ΔH°f(H₂O)"),
        ("Enthalpy depends on:", ["Amount, state, temperature", "Only T", "Only amount", "None"], "Amount, state, temperature"),
    ],
    # ============ wk17: Entropy, Gibbs Free Energy, Spontaneity ============
    17: [
        ("Entropy S is a measure of:", ["Disorder / randomness", "Energy", "Temperature", "Mass"], "Disorder / randomness"),
        ("Units of entropy:", ["J K⁻¹ mol⁻¹", "kJ mol⁻¹", "K", "J/s"], "J K⁻¹ mol⁻¹"),
        ("Second law of thermodynamics:", ["Entropy of universe always increases in spontaneous process", "ΔU = 0", "q = w", "ΔH = TΔS"], "Entropy of universe always increases in spontaneous process"),
        ("For reversible process: ΔS_sys =", ["q_rev/T", "q_irr/T", "w/T", "U/T"], "q_rev/T"),
        ("ΔS for gas → liquid is:", ["Negative", "Positive", "Zero", "Infinity"], "Negative"),
        ("ΔS for solid → gas is:", ["Positive", "Negative", "Zero", "−infinity"], "Positive"),
        ("Entropy increases in which direction:", ["Solid < liquid < gas", "Gas < liquid < solid", "Random", "Equal"], "Solid < liquid < gas"),
        ("Third law of thermodynamics:", ["S = 0 for perfect crystal at 0 K", "ΔS ∞ at 0 K", "S = R at 0 K", "Entropy is zero always"], "S = 0 for perfect crystal at 0 K"),
        ("Gibbs free energy G = ", ["H − TS", "U − TS", "H + TS", "U + TS"], "H − TS"),
        ("For spontaneous process:", ["ΔG < 0", "ΔG > 0", "ΔG = 0", "ΔH < 0"], "ΔG < 0"),
        ("At equilibrium:", ["ΔG = 0", "ΔG < 0", "ΔG > 0", "ΔS = 0"], "ΔG = 0"),
        ("ΔG = ΔH − TΔS. For ΔH < 0, ΔS > 0:", ["Spontaneous at all T", "Non-spontaneous", "Depends on T", "Never spontaneous"], "Spontaneous at all T"),
        ("ΔH > 0, ΔS < 0: Reaction is:", ["Non-spontaneous at all T", "Spontaneous", "Depends on T", "Equilibrium"], "Non-spontaneous at all T"),
        ("ΔH < 0, ΔS < 0: Spontaneous at:", ["Low T", "High T", "All T", "Never"], "Low T"),
        ("ΔH > 0, ΔS > 0: Spontaneous at:", ["High T", "Low T", "All T", "Never"], "High T"),
        ("ΔG° = ", ["−RT ln K", "RT ln K", "−RT K", "RT/K"], "−RT ln K"),
        ("When K > 1, ΔG° is:", ["Negative", "Positive", "Zero", "Infinity"], "Negative"),
        ("When K < 1, ΔG° is:", ["Positive", "Negative", "Zero", "Unknown"], "Positive"),
        ("Enthalpy-driven reactions have:", ["ΔH dominant negative", "ΔS large", "T high", "Small values"], "ΔH dominant negative"),
        ("Entropy-driven reactions have:", ["TΔS dominant", "ΔH dominant", "Both zero", "Neither"], "TΔS dominant"),
        ("ΔS universe = ΔS system + ", ["ΔS surroundings", "ΔH", "ΔG", "ΔU"], "ΔS surroundings"),
        ("ΔS_surr = ", ["−ΔH_sys/T", "ΔH_sys/T", "TΔH_sys", "ΔS_sys"], "−ΔH_sys/T"),
        ("For 2H₂ + O₂ → 2H₂O(g), ΔS_sys is:", ["Negative (moles decrease)", "Positive", "Zero", "Infinity"], "Negative (moles decrease)"),
        ("The entropy of universe is:", ["Always increasing", "Constant", "Decreasing", "Zero"], "Always increasing"),
        ("Standard Gibbs energy of formation of elements:", ["Zero", "Positive", "Negative", "Variable"], "Zero"),
    ],
    # ============ wk18: Physical & Chemical Equilibrium, Law of Mass Action ============
    18: [
        ("Equilibrium is characterized by:", ["Equal rates of forward and backward reactions", "No reaction", "Only forward reaction", "Complete conversion"], "Equal rates of forward and backward reactions"),
        ("Physical equilibrium example:", ["H₂O(l) ⇌ H₂O(g)", "N₂ + 3H₂ ⇌ 2NH₃", "Combustion", "Neutralization"], "H₂O(l) ⇌ H₂O(g)"),
        ("Chemical equilibrium example:", ["N₂ + 3H₂ ⇌ 2NH₃", "Ice melting", "Dissolution", "Boiling"], "N₂ + 3H₂ ⇌ 2NH₃"),
        ("At equilibrium, concentrations of reactants and products are:", ["Constant", "Equal", "Zero", "Increasing"], "Constant"),
        ("Law of mass action states rate ∝ :", ["Product of concentrations of reactants (each ^stoichiometric coef)", "Reactant sum", "Product sum only", "1/[Reactants]"], "Product of concentrations of reactants (each ^stoichiometric coef)"),
        ("For aA + bB ⇌ cC + dD, Kc = ", ["[C]^c[D]^d / [A]^a[B]^b", "[A][B]/[C][D]", "[C]+[D] / [A]+[B]", "Zero"], "[C]^c[D]^d / [A]^a[B]^b"),
        ("Kc depends on:", ["Temperature", "Concentration", "Pressure only", "Volume only"], "Temperature"),
        ("Kp for gaseous reactions uses:", ["Partial pressures", "Concentrations", "Molarities", "Volumes"], "Partial pressures"),
        ("Kp = Kc × (RT)^Δn where Δn is:", ["Moles gas products − reactants", "Total moles", "Zero always", "Stoichiometry"], "Moles gas products − reactants"),
        ("For N₂ + 3H₂ ⇌ 2NH₃, Δn_g =", ["−2", "+2", "0", "1"], "−2"),
        ("Reaction quotient Q uses:", ["Current concentrations", "Equilibrium concentrations only", "Initial only", "Pressure only"], "Current concentrations"),
        ("If Q < K, reaction proceeds:", ["Forward", "Reverse", "At equilibrium", "Does not proceed"], "Forward"),
        ("If Q > K, reaction proceeds:", ["Reverse", "Forward", "Equilibrium", "Complete"], "Reverse"),
        ("If Q = K:", ["At equilibrium", "Forward", "Reverse", "No reaction"], "At equilibrium"),
        ("Kc for reversed reaction is:", ["1/Kc", "Kc", "−Kc", "Kc²"], "1/Kc"),
        ("Kc for doubled reaction:", ["Kc²", "2Kc", "Kc/2", "√Kc"], "Kc²"),
        ("Dissociation constant α for aA ⇌ bB is related to Kc via ICE table at:", ["Initial concentrations", "Equilibrium concentrations", "Both", "Half"], "Equilibrium concentrations"),
        ("At equilibrium, Gibbs energy change ΔG = ", ["0", "Negative", "Positive", "Infinity"], "0"),
        ("Units of Kc for A + B ⇌ C:", ["M⁻¹", "M", "Dimensionless if pure", "M²"], "M⁻¹"),
        ("Units of Kc for A ⇌ B:", ["Dimensionless", "M", "M⁻¹", "M²"], "Dimensionless"),
        ("Homogeneous equilibrium: all species in:", ["Same phase", "Different phases", "Any phase", "Liquid only"], "Same phase"),
        ("Heterogeneous equilibrium example:", ["CaCO₃(s) ⇌ CaO(s) + CO₂(g)", "N₂ + H₂ ⇌ NH₃", "2NO₂ ⇌ N₂O₄", "H₂ + I₂ ⇌ HI"], "CaCO₃(s) ⇌ CaO(s) + CO₂(g)"),
        ("In heterogeneous equilibrium, pure solids and liquids:", ["Excluded from K expression", "Included fully", "Half included", "Inverted"], "Excluded from K expression"),
        ("Relation ΔG° = −RT ln K at equilibrium allows:", ["K determination from ΔG°", "Nothing", "Rate calculation", "Mass measurement"], "K determination from ΔG°"),
        ("Large K means:", ["Products favored", "Reactants favored", "Equal amounts", "No reaction"], "Products favored"),
    ],
    # ============ wk19: K_p, K_c, Le Chatelier's Principle ============
    19: [
        ("Le Chatelier's principle states system responds to disturbance by:", ["Shifting to counteract disturbance", "Breaking", "No change", "Accelerating"], "Shifting to counteract disturbance"),
        ("Adding more reactant shifts equilibrium:", ["Forward", "Reverse", "No change", "Stops"], "Forward"),
        ("Removing product shifts equilibrium:", ["Forward", "Reverse", "No change", "Stops"], "Forward"),
        ("For N₂ + 3H₂ ⇌ 2NH₃, increasing pressure favors:", ["Forward (fewer moles)", "Reverse", "No change", "Decomposition"], "Forward (fewer moles)"),
        ("For N₂O₄ ⇌ 2NO₂, increasing pressure:", ["Favors reverse (fewer moles)", "Favors forward", "No change", "Stops"], "Favors reverse (fewer moles)"),
        ("Adding inert gas at constant V:", ["No shift", "Forward shift", "Reverse shift", "Stops reaction"], "No shift"),
        ("Adding inert gas at constant P:", ["Shifts toward more moles of gas", "No shift", "Stops", "Forward always"], "Shifts toward more moles of gas"),
        ("For exothermic reaction, increasing T:", ["Shifts reverse (decrease K)", "Forward", "No change", "Stops"], "Shifts reverse (decrease K)"),
        ("For endothermic reaction, increasing T:", ["Shifts forward (increase K)", "Reverse", "No change", "Stops"], "Shifts forward (increase K)"),
        ("Catalyst effect on equilibrium:", ["No shift, only faster approach", "Shifts forward", "Shifts reverse", "Changes K"], "No shift, only faster approach"),
        ("Haber process uses catalyst:", ["Fe with promoters (Mo, K₂O)", "Pt", "Ni", "V₂O₅"], "Fe with promoters (Mo, K₂O)"),
        ("Contact process produces H₂SO₄ via:", ["2SO₂ + O₂ ⇌ 2SO₃, V₂O₅", "Haber", "NH₃ oxidation", "Electrolysis"], "2SO₂ + O₂ ⇌ 2SO₃, V₂O₅"),
        ("Optimum T for Haber process:", ["~700 K (450°C)", "1000 K", "300 K", "2000 K"], "~700 K (450°C)"),
        ("Optimum P for Haber process:", ["200 atm", "1 atm", "1000 atm", "10 atm"], "200 atm"),
        ("For A(g) ⇌ B(g), halving V:", ["No shift (Δn = 0)", "Forward", "Reverse", "Stops"], "No shift (Δn = 0)"),
        ("For PCl₅ ⇌ PCl₃ + Cl₂, increasing V:", ["Forward (more moles)", "Reverse", "No change", "Stops"], "Forward (more moles)"),
        ("Vapor pressure of water increases with:", ["Temperature", "Pressure", "Volume", "Adding salt"], "Temperature"),
        ("Henry's law: solubility of gas ∝", ["Partial pressure", "Volume", "Temperature", "Molarity"], "Partial pressure"),
        ("Raoult's law for solvent:", ["P_A = X_A P°_A", "P_A = P°_A/X_A", "P_A = X_A T", "P = RT"], "P_A = X_A P°_A"),
        ("Van't Hoff equation: d(lnK)/dT =", ["ΔH°/RT²", "ΔS/R", "ΔG°/RT", "R/T"], "ΔH°/RT²"),
        ("If ΔH > 0, K increases with:", ["T", "P", "V", "Catalyst"], "T"),
        ("If ΔH < 0, K decreases with:", ["T", "V", "P", "Inert gas"], "T"),
        ("CO(g) + H₂O(g) ⇌ CO₂(g) + H₂(g), ΔH=−ve. Increasing T:", ["Decreases K, favors reverse", "Increases K", "No effect", "Stops"], "Decreases K, favors reverse"),
        ("Equilibrium is dynamic — this means:", ["Both reactions continue at equal rates", "Stops", "Only forward", "Backward"], "Both reactions continue at equal rates"),
        ("Degree of dissociation α for PCl₅ ⇌ PCl₃ + Cl₂ increases with:", ["T and V (lower P)", "Higher P", "Lower T", "Adding PCl₅"], "T and V (lower P)"),
    ],
    # ============ wk20: Ionic Equilibrium, Acids & Bases ============
    20: [
        ("Arrhenius acid:", ["Gives H⁺ in water", "Gives OH⁻", "Accepts H⁺", "Donates lone pair"], "Gives H⁺ in water"),
        ("Arrhenius base:", ["Gives OH⁻", "Gives H⁺", "Accepts OH⁻", "Accepts pair"], "Gives OH⁻"),
        ("Brønsted acid:", ["Proton donor", "Proton acceptor", "Electron donor", "Electron acceptor"], "Proton donor"),
        ("Brønsted base:", ["Proton acceptor", "Proton donor", "Electron donor", "OH⁻ giver"], "Proton acceptor"),
        ("Conjugate base of HCl:", ["Cl⁻", "H⁺", "HCl₂⁻", "H₂O"], "Cl⁻"),
        ("Conjugate acid of NH₃:", ["NH₄⁺", "NH₂⁻", "NH₃⁺", "N₂"], "NH₄⁺"),
        ("Lewis acid:", ["Electron pair acceptor", "Electron pair donor", "Proton donor", "Hydroxide donor"], "Electron pair acceptor"),
        ("Lewis base:", ["Electron pair donor", "Acceptor", "Proton donor", "Hydroxide acceptor"], "Electron pair donor"),
        ("BF₃ is:", ["Lewis acid", "Lewis base", "Brønsted acid", "Arrhenius acid"], "Lewis acid"),
        ("NH₃ acts as:", ["Lewis/Brønsted base", "Lewis acid", "Oxidizer", "Reductant only"], "Lewis/Brønsted base"),
        ("H₂O can act as:", ["Both acid and base (amphoteric)", "Only acid", "Only base", "Neutral"], "Both acid and base (amphoteric)"),
        ("Autoionization: 2H₂O ⇌ H₃O⁺ + OH⁻ with Kw = ", ["10⁻¹⁴ at 25°C", "10⁻⁷", "10⁻²", "10⁻¹⁰"], "10⁻¹⁴ at 25°C"),
        ("In pure water at 25°C, [H⁺] = [OH⁻] =", ["10⁻⁷ M", "10⁻¹⁴ M", "1 M", "10⁻² M"], "10⁻⁷ M"),
        ("Strong acid examples:", ["HCl, HNO₃, H₂SO₄", "CH₃COOH", "H₂CO₃", "HF only"], "HCl, HNO₃, H₂SO₄"),
        ("Strong base examples:", ["NaOH, KOH, Ba(OH)₂", "NH₃", "Al(OH)₃", "Fe(OH)₃"], "NaOH, KOH, Ba(OH)₂"),
        ("Weak acid example:", ["CH₃COOH", "HCl", "HClO₄", "HNO₃"], "CH₃COOH"),
        ("Weak base example:", ["NH₃", "NaOH", "KOH", "Ba(OH)₂"], "NH₃"),
        ("Ka × Kb = ", ["Kw", "1", "0", "2Kw"], "Kw"),
        ("pKa + pKb = ", ["14 (at 25°C)", "7", "0", "10"], "14 (at 25°C)"),
        ("Smaller Ka means:", ["Weaker acid", "Stronger acid", "Neutral", "Base"], "Weaker acid"),
        ("Acid strength order: HF, HCl, HBr, HI:", ["HI > HBr > HCl > HF", "HF > HCl > HBr > HI", "HCl > HBr", "All equal"], "HI > HBr > HCl > HF"),
        ("Oxyacid strength: HOCl, HOBr, HOI:", ["HOCl > HOBr > HOI", "HOI > HOBr > HOCl", "Equal", "HOBr largest"], "HOCl > HOBr > HOI"),
        ("Leveling effect: strongest acid in water:", ["H₃O⁺", "HCl", "HClO₄", "H₂SO₄"], "H₃O⁺"),
        ("Degree of ionization α for weak acid is:", ["Small", "1", "Large", "Zero"], "Small"),
        ("For weak acid HA with conc c, [H⁺] ≈", ["√(Ka·c)", "Ka/c", "Ka·c", "c/Ka"], "√(Ka·c)"),
    ],
    # ============ wk21: pH, Buffer Solutions, Solubility Product, Common Ion Effect ============
    21: [
        ("pH = ", ["−log[H⁺]", "log[H⁺]", "10^[H⁺]", "1/[H⁺]"], "−log[H⁺]"),
        ("pH of pure water at 25°C:", ["7", "0", "14", "1"], "7"),
        ("pH of 0.01 M HCl:", ["2", "12", "7", "4"], "2"),
        ("pH of 0.1 M NaOH:", ["13", "1", "7", "14"], "13"),
        ("pOH = ", ["−log[OH⁻]", "log[OH⁻]", "14 − pH is true", "pH − 14"], "−log[OH⁻]"),
        ("pH + pOH = ", ["14 (at 25°C)", "7", "0", "10"], "14 (at 25°C)"),
        ("pH below 7 is:", ["Acidic", "Basic", "Neutral", "Buffer"], "Acidic"),
        ("pH above 7 is:", ["Basic", "Acidic", "Neutral", "Buffer"], "Basic"),
        ("Buffer solution resists change in:", ["pH on adding small acid/base", "Temperature", "Volume", "Color"], "pH on adding small acid/base"),
        ("Acidic buffer: weak acid + ", ["Its salt with strong base", "Strong acid", "Strong base", "Water"], "Its salt with strong base"),
        ("Basic buffer: weak base + ", ["Its salt with strong acid", "Strong acid", "Water", "Strong base"], "Its salt with strong acid"),
        ("Henderson-Hasselbalch equation:", ["pH = pKa + log([A⁻]/[HA])", "pH = pKa + [A⁻]", "pH = pKa × [A⁻]", "pH = log(Ka)"], "pH = pKa + log([A⁻]/[HA])"),
        ("Buffer works best when:", ["pH = pKa (equal [A⁻] and [HA])", "pH = 0", "pH = 14", "[A⁻] ≫ [HA]"], "pH = pKa (equal [A⁻] and [HA])"),
        ("Solubility product Ksp for AgCl:", ["[Ag⁺][Cl⁻]", "[Ag⁺]+[Cl⁻]", "[Ag⁺]/[Cl⁻]", "[Cl⁻]²"], "[Ag⁺][Cl⁻]"),
        ("Ksp for CaF₂:", ["[Ca²⁺][F⁻]²", "[Ca²⁺][F⁻]", "[Ca²⁺]²[F⁻]", "[F⁻]²"], "[Ca²⁺][F⁻]²"),
        ("Solubility s of AgCl: Ksp =", ["s²", "s", "2s", "s³"], "s²"),
        ("Solubility s of CaF₂: Ksp =", ["4s³", "s³", "s²", "2s³"], "4s³"),
        ("Common ion effect: adding Cl⁻ to AgCl solution:", ["Decreases Ag⁺ solubility", "Increases", "No effect", "Dissolves more"], "Decreases Ag⁺ solubility"),
        ("If ionic product IP > Ksp:", ["Precipitation occurs", "Dissolution", "Equilibrium", "No change"], "Precipitation occurs"),
        ("If IP < Ksp:", ["Unsaturated, more dissolves", "Precipitation", "Equilibrium", "Crystals form"], "Unsaturated, more dissolves"),
        ("If IP = Ksp:", ["Saturated (equilibrium)", "Unsaturated", "Supersaturated", "Precipitation"], "Saturated (equilibrium)"),
        ("Hydrolysis of salt of strong acid + weak base (e.g. NH₄Cl):", ["Solution is acidic", "Basic", "Neutral", "Strongly basic"], "Solution is acidic"),
        ("Hydrolysis of salt of weak acid + strong base (e.g. CH₃COONa):", ["Basic", "Acidic", "Neutral", "Strongly acidic"], "Basic"),
        ("Salt of strong acid + strong base (NaCl):", ["Neutral", "Acidic", "Basic", "Buffer"], "Neutral"),
        ("pH of 10⁻⁸ M HCl is:", ["Slightly less than 7", "1", "8", "0"], "Slightly less than 7"),
    ],
    # ============ wk22: Oxidation Number, Types of Redox Reactions ============
    22: [
        ("Oxidation is:", ["Loss of electrons / increase in O.N.", "Gain of electrons", "No change", "Proton gain"], "Loss of electrons / increase in O.N."),
        ("Reduction is:", ["Gain of electrons / decrease in O.N.", "Loss of electrons", "No change", "Proton loss"], "Gain of electrons / decrease in O.N."),
        ("Redox reaction = ", ["Simultaneous oxidation and reduction", "Only oxidation", "Only reduction", "No electron transfer"], "Simultaneous oxidation and reduction"),
        ("Oxidizing agent:", ["Accepts electrons / is reduced", "Loses electrons", "Unchanged", "No role"], "Accepts electrons / is reduced"),
        ("Reducing agent:", ["Loses electrons / is oxidized", "Accepts electrons", "Unchanged", "Donates H⁺"], "Loses electrons / is oxidized"),
        ("Oxidation number of H in H₂O:", ["+1", "−1", "0", "+2"], "+1"),
        ("Oxidation number of H in NaH:", ["−1", "+1", "0", "+2"], "−1"),
        ("Oxidation number of O in H₂O₂:", ["−1", "−2", "+1", "0"], "−1"),
        ("Oxidation number of O in OF₂:", ["+2", "−2", "0", "−1"], "+2"),
        ("Oxidation number of Mn in KMnO₄:", ["+7", "+4", "+6", "+2"], "+7"),
        ("Oxidation number of Cr in K₂Cr₂O₇:", ["+6", "+3", "+7", "+4"], "+6"),
        ("Oxidation number of N in HNO₃:", ["+5", "+3", "+4", "−3"], "+5"),
        ("Oxidation number of S in H₂SO₄:", ["+6", "+4", "−2", "+2"], "+6"),
        ("Oxidation number of C in CO₂:", ["+4", "−4", "+2", "0"], "+4"),
        ("Oxidation number of C in CH₄:", ["−4", "+4", "0", "+2"], "−4"),
        ("Element in free state has O.N.:", ["0", "+1", "−1", "Variable"], "0"),
        ("Combination reaction e.g. 2H₂ + O₂ → 2H₂O is:", ["Redox", "Non-redox", "Displacement", "Decomposition"], "Redox"),
        ("Decomposition reaction e.g. 2KClO₃ → 2KCl + 3O₂:", ["Redox", "Non-redox", "Combination", "Disproportionation"], "Redox"),
        ("Displacement: Zn + CuSO₄ → ZnSO₄ + Cu is:", ["Redox (Zn is reducing agent)", "Non-redox", "Combustion", "Hydrolysis"], "Redox (Zn is reducing agent)"),
        ("Disproportionation: same element is:", ["Both oxidized and reduced", "Only oxidized", "Only reduced", "Unchanged"], "Both oxidized and reduced"),
        ("Example of disproportionation:", ["2H₂O₂ → 2H₂O + O₂", "H₂ + O₂ → H₂O", "Na + Cl₂ → NaCl", "CaCO₃ → CaO + CO₂"], "2H₂O₂ → 2H₂O + O₂"),
        ("Comproportionation example:", ["Ag + Ag³⁺ → Ag²⁺ (hypothetical), or 5Fe²⁺ + 6H⁺ + MnO₄⁻ → Mn²⁺ + 5Fe³⁺", "Decomposition", "Combustion", "Neutralization"], "Ag + Ag³⁺ → Ag²⁺ (hypothetical), or 5Fe²⁺ + 6H⁺ + MnO₄⁻ → Mn²⁺ + 5Fe³⁺"),
        ("In 2Na + Cl₂ → 2NaCl, Na is:", ["Oxidized (reducing agent)", "Reduced", "Unchanged", "Oxidizing agent"], "Oxidized (reducing agent)"),
        ("In electrolytic cell, oxidation occurs at:", ["Anode", "Cathode", "Both", "Neither"], "Anode"),
        ("Reduction occurs at:", ["Cathode", "Anode", "Both", "Neither"], "Cathode"),
    ],
    # ============ wk23: Balancing Redox, Half-Reactions, Electrochemical Cells ============
    23: [
        ("In oxidation number method, first balance:", ["Atoms other than H and O", "H first", "O first", "Electrons first"], "Atoms other than H and O"),
        ("In half-reaction method for acidic solution, balance O by adding:", ["H₂O", "OH⁻", "O₂", "H₂"], "H₂O"),
        ("In half-reaction method for acidic solution, balance H by adding:", ["H⁺", "H₂O", "OH⁻", "H₂"], "H⁺"),
        ("In basic solution, after balancing as acidic, add OH⁻ to:", ["Both sides to neutralize H⁺", "Only left", "Only right", "Not needed"], "Both sides to neutralize H⁺"),
        ("Balance Fe²⁺ + MnO₄⁻ + H⁺ → Fe³⁺ + Mn²⁺ + H₂O. Fe²⁺ coef =", ["5", "1", "2", "3"], "5"),
        ("Electrons lost by reducing agent =", ["Electrons gained by oxidizing agent", "Half", "Double", "Zero"], "Electrons gained by oxidizing agent"),
        ("Galvanic cell converts:", ["Chemical energy to electrical", "Electrical to chemical", "Heat to work", "Mass to energy"], "Chemical energy to electrical"),
        ("Daniell cell: Zn | Zn²⁺ || Cu²⁺ | Cu. Anode is:", ["Zn electrode", "Cu electrode", "Salt bridge", "Wire"], "Zn electrode"),
        ("Cathode in Daniell cell:", ["Cu", "Zn", "Salt bridge", "Both"], "Cu"),
        ("EMF of Daniell cell ~", ["1.10 V", "0.34 V", "−0.76 V", "0 V"], "1.10 V"),
        ("Salt bridge maintains:", ["Electrical neutrality of solutions", "Current flow in wire", "Heat", "Mass balance"], "Electrical neutrality of solutions"),
        ("Standard hydrogen electrode E° =", ["0.00 V", "+1.00 V", "−1.00 V", "+0.34 V"], "0.00 V"),
        ("Standard electrode potential of Zn²⁺/Zn:", ["−0.76 V", "+0.34 V", "+0.76 V", "0.00 V"], "−0.76 V"),
        ("Standard electrode potential of Cu²⁺/Cu:", ["+0.34 V", "−0.34 V", "+1.10 V", "0"], "+0.34 V"),
        ("E°_cell = ", ["E°_cathode − E°_anode", "E°_anode − E°_cathode", "Sum", "Zero"], "E°_cathode − E°_anode"),
        ("ΔG° = ", ["−nFE°", "nFE°", "−E°/nF", "nF/E°"], "−nFE°"),
        ("F (Faraday constant) = ", ["96500 C/mol", "6.022×10²³", "9.11×10⁻³¹", "8.314 J/mol·K"], "96500 C/mol"),
        ("Nernst equation at 298 K:", ["E = E° − (0.0591/n) log Q", "E = E° − RT ln Q", "E = E° × Q", "E = log Q"], "E = E° − (0.0591/n) log Q"),
        ("At equilibrium, E_cell = ", ["0", "E°", "−E°", "Infinity"], "0"),
        ("Higher E° means:", ["Better oxidizing agent (more tendency to be reduced)", "Stronger reducing agent", "Less reactive", "Inert"], "Better oxidizing agent (more tendency to be reduced)"),
        ("Most powerful oxidizing agent from list:", ["F₂ (E° = +2.87 V)", "Cl₂", "O₂", "H⁺"], "F₂ (E° = +2.87 V)"),
        ("Most powerful reducing agent:", ["Li (E°_Li⁺/Li = −3.04 V)", "Na", "K", "Zn"], "Li (E°_Li⁺/Li = −3.04 V)"),
        ("Electrolysis of molten NaCl produces:", ["Na at cathode, Cl₂ at anode", "Na at anode", "H₂ at cathode", "NaOH"], "Na at cathode, Cl₂ at anode"),
        ("Faraday's first law: mass deposited ∝", ["Charge passed", "Time only", "Voltage only", "1/current"], "Charge passed"),
        ("Equivalent mass in electrolysis = ", ["Molar mass / n (electrons)", "Molar mass × n", "Molar mass", "1/n"], "Molar mass / n (electrons)"),
    ],
    # ============ wk24: Hybridisation, Classification of Organic Compounds ============
    24: [
        ("Carbon's valency is:", ["4", "2", "6", "3"], "4"),
        ("Tetravalency of carbon is due to:", ["sp³ hybridization", "sp² only", "sp only", "d-orbitals"], "sp³ hybridization"),
        ("Catenation is:", ["Self-linking of atoms (C−C chains)", "Oxidation", "Reduction", "Polymerization only"], "Self-linking of atoms (C−C chains)"),
        ("In CH₃−CH₃ (ethane) each C is:", ["sp³", "sp²", "sp", "sp³d"], "sp³"),
        ("In H₂C=CH₂ (ethene) each C is:", ["sp²", "sp³", "sp", "dsp²"], "sp²"),
        ("In HC≡CH (ethyne) each C is:", ["sp", "sp²", "sp³", "sp³d"], "sp"),
        ("σ bond is formed by:", ["Head-on overlap", "Sideways", "No overlap", "Ionic"], "Head-on overlap"),
        ("π bond is formed by:", ["Sideways overlap", "Head-on", "No overlap", "Ionic"], "Sideways overlap"),
        ("Homolytic cleavage produces:", ["Free radicals", "Ions", "Neutral molecules", "Electrons only"], "Free radicals"),
        ("Heterolytic cleavage produces:", ["Ions (carbocation/carbanion)", "Free radicals", "Atoms", "Neutral"], "Ions (carbocation/carbanion)"),
        ("Carbocation: C has ___ electrons:", ["6 (empty p)", "8", "4", "10"], "6 (empty p)"),
        ("Order of carbocation stability:", ["3° > 2° > 1° > methyl", "Methyl > 1° > 2° > 3°", "Equal", "Random"], "3° > 2° > 1° > methyl"),
        ("Carbanion: C has ___ electrons:", ["8 (lone pair)", "6", "4", "10"], "8 (lone pair)"),
        ("Order of carbanion stability:", ["Methyl > 1° > 2° > 3°", "3° > 2°", "Equal", "Random"], "Methyl > 1° > 2° > 3°"),
        ("Functional group of alcohols:", ["−OH", "−CHO", "−COOH", "−NH₂"], "−OH"),
        ("Functional group of aldehyde:", ["−CHO", "−CO−", "−COOH", "−OH"], "−CHO"),
        ("Functional group of ketone:", [">C=O (in chain)", "−CHO", "−COOH", "−OH"], ">C=O (in chain)"),
        ("Functional group of carboxylic acid:", ["−COOH", "−CHO", "−CO−", "−OH"], "−COOH"),
        ("Functional group of amine:", ["−NH₂", "−OH", "−NO₂", "−CN"], "−NH₂"),
        ("Electrophile is:", ["Electron-deficient (+/neutral)", "Electron-rich", "Neutral radical", "None"], "Electron-deficient (+/neutral)"),
        ("Example of electrophile:", ["NO₂⁺, H⁺, BF₃", "NH₃, OH⁻", "Cl⁻", "Na"], "NO₂⁺, H⁺, BF₃"),
        ("Nucleophile is:", ["Electron-rich (pair donor)", "Electron-poor", "Neutral radical", "None"], "Electron-rich (pair donor)"),
        ("Example of nucleophile:", ["OH⁻, CN⁻, NH₃", "NO₂⁺, H⁺", "BF₃", "AlCl₃"], "OH⁻, CN⁻, NH₃"),
        ("Inductive effect is:", ["Transmission of polarity through σ bonds", "Through π", "Through H-bond", "No transmission"], "Transmission of polarity through σ bonds"),
        ("Resonance effect is through:", ["π bonds / lone pairs", "σ bonds", "H-bonds", "Ionic"], "π bonds / lone pairs"),
    ],
    # ============ wk25: IUPAC Nomenclature (Alkanes, Alkenes, Alkynes) ============
    25: [
        ("IUPAC name of CH₄:", ["Methane", "Ethane", "Propane", "Butane"], "Methane"),
        ("IUPAC name of CH₃CH₃:", ["Ethane", "Methane", "Propane", "Ethene"], "Ethane"),
        ("IUPAC name of CH₃CH₂CH₃:", ["Propane", "Butane", "Ethane", "Propene"], "Propane"),
        ("General formula of alkanes:", ["CₙH₂ₙ₊₂", "CₙH₂ₙ", "CₙH₂ₙ₋₂", "CₙHₙ"], "CₙH₂ₙ₊₂"),
        ("General formula of alkenes:", ["CₙH₂ₙ", "CₙH₂ₙ₊₂", "CₙH₂ₙ₋₂", "CₙHₙ"], "CₙH₂ₙ"),
        ("General formula of alkynes:", ["CₙH₂ₙ₋₂", "CₙH₂ₙ", "CₙH₂ₙ₊₂", "CₙHₙ"], "CₙH₂ₙ₋₂"),
        ("IUPAC name of (CH₃)₃CH:", ["2-Methylpropane", "Isobutane", "Butane", "n-Butane"], "2-Methylpropane"),
        ("IUPAC name of CH₃CH₂CH=CH₂:", ["But-1-ene", "But-2-ene", "Butane", "Butyne"], "But-1-ene"),
        ("IUPAC name of CH₃C≡CCH₃:", ["But-2-yne", "But-1-yne", "Butane", "Propyne"], "But-2-yne"),
        ("IUPAC name of CH₃CHO:", ["Ethanal", "Methanal", "Propanal", "Acetone"], "Ethanal"),
        ("IUPAC name of CH₃COCH₃:", ["Propan-2-one", "Propanone", "Acetone (common)", "Both A and C"], "Both A and C"),
        ("IUPAC name of CH₃COOH:", ["Ethanoic acid", "Methanoic acid", "Propanoic acid", "Formic acid"], "Ethanoic acid"),
        ("IUPAC name of CH₃OH:", ["Methanol", "Ethanol", "Propanol", "Methoxide"], "Methanol"),
        ("IUPAC name of CH₃CH₂OH:", ["Ethanol", "Methanol", "Ethanal", "Ethanoic acid"], "Ethanol"),
        ("IUPAC name of CH₃NH₂:", ["Methanamine", "Methylamine (common)", "Both same", "Methanal"], "Both same"),
        ("Longest chain must contain:", ["Functional group and maximum substituents", "Random carbons", "Shortest path", "Only one substituent"], "Functional group and maximum substituents"),
        ("Numbering gives lowest locants to:", ["Principal functional group", "Random", "Highest first", "Substituents only"], "Principal functional group"),
        ("Alphabetical order for substituents ignores:", ["Multiplying prefixes (di, tri)", "All letters", "First letter", "None"], "Multiplying prefixes (di, tri)"),
        ("IUPAC name of CH₃CH(CH₃)CH₂CH₃:", ["2-Methylbutane", "3-Methylbutane", "Pentane", "Isopentane"], "2-Methylbutane"),
        ("IUPAC name of CH₃CH(Cl)CH₃:", ["2-Chloropropane", "1-Chloropropane", "Propylchloride", "Chloropropane"], "2-Chloropropane"),
        ("Name for −CHO group when naming acid/ester:", ["'Oxo' prefix / aldehyde suffix", "Ketone", "Amine", "Nitrile"], "'Oxo' prefix / aldehyde suffix"),
        ("IUPAC name of HCOOH:", ["Methanoic acid (formic)", "Ethanoic acid", "Propanoic acid", "Formal"], "Methanoic acid (formic)"),
        ("CH₂=CHCl is called:", ["Chloroethene (vinyl chloride)", "Ethyl chloride", "Chloromethane", "Vinyl chloride only"], "Chloroethene (vinyl chloride)"),
        ("IUPAC name of benzene derivative C₆H₅CH₃:", ["Methylbenzene (toluene)", "Benzene", "Phenol", "Xylene"], "Methylbenzene (toluene)"),
        ("Priority of functional groups (decreasing):", ["−COOH > −CHO > −CO− > −OH > −NH₂", "Opposite", "Random", "−OH highest"], "−COOH > −CHO > −CO− > −OH > −NH₂"),
    ],
    # ============ wk26: Isomerism (Structural and Stereo) ============
    26: [
        ("Isomers are compounds with:", ["Same molecular formula, different structure", "Different formulas", "Same structure", "Different masses"], "Same molecular formula, different structure"),
        ("Structural isomers differ in:", ["Connectivity of atoms", "Spatial arrangement only", "Molecular formula", "Mass"], "Connectivity of atoms"),
        ("Chain isomers differ in:", ["Chain skeleton", "Position of functional group", "Functional group type", "Geometry"], "Chain skeleton"),
        ("Example of chain isomers:", ["n-butane and iso-butane", "Butan-1-ol and butan-2-ol", "Ethanol and dimethyl ether", "cis/trans but-2-ene"], "n-butane and iso-butane"),
        ("Position isomers differ in:", ["Position of functional group", "Chain", "Functional group", "Geometry"], "Position of functional group"),
        ("Example of position isomers:", ["Butan-1-ol and butan-2-ol", "n-butane, iso-butane", "Ethanol, DME", "cis-2-butene"], "Butan-1-ol and butan-2-ol"),
        ("Functional group isomers differ in:", ["Functional group", "Chain", "Position", "Stereo"], "Functional group"),
        ("Example of functional group isomers:", ["Ethanol and dimethyl ether", "n-butane, iso-butane", "cis-2-butene", "Butan-1-ol, butan-2-ol"], "Ethanol and dimethyl ether"),
        ("Metamers differ in:", ["Alkyl groups on same functional group", "Chain", "Position", "Geometry"], "Alkyl groups on same functional group"),
        ("Example of metamers:", ["Methoxypropane and ethoxyethane", "Ethanol and DME", "n-butane, iso-butane", "Butan-1-ol and 2-ol"], "Methoxypropane and ethoxyethane"),
        ("Tautomers are:", ["Dynamic isomers (keto-enol)", "Chain isomers", "Geometrical isomers", "Optical isomers"], "Dynamic isomers (keto-enol)"),
        ("Keto-enol tautomerism example:", ["CH₃COCH₃ ⇌ CH₂=C(OH)CH₃", "Cis-trans", "Geometrical", "Chain"], "CH₃COCH₃ ⇌ CH₂=C(OH)CH₃"),
        ("Stereoisomers have:", ["Same connectivity, different spatial arrangement", "Different connectivity", "Different formula", "Same everything"], "Same connectivity, different spatial arrangement"),
        ("Geometrical (cis-trans) isomerism arises in:", ["Alkenes with restricted rotation", "All alkanes", "All alcohols", "Noble gases"], "Alkenes with restricted rotation"),
        ("cis-2-butene has CH₃ groups on:", ["Same side of C=C", "Opposite sides", "Triple bond", "Random"], "Same side of C=C"),
        ("trans-2-butene has CH₃ groups on:", ["Opposite sides of C=C", "Same side", "Tetrahedral", "Random"], "Opposite sides of C=C"),
        ("Requirement for geometrical isomerism:", ["Each carbon of C=C must have 2 different groups", "Same groups", "Single bond only", "No requirement"], "Each carbon of C=C must have 2 different groups"),
        ("Which has no geometrical isomers: 2-methylbut-2-ene, but-2-ene:", ["2-methylbut-2-ene (C has 2 CH₃)", "But-2-ene", "Both have", "Neither"], "2-methylbut-2-ene (C has 2 CH₃)"),
        ("Optical isomers rotate:", ["Plane of polarized light", "Unpolarized light", "Frequency", "Wavelength"], "Plane of polarized light"),
        ("Dextrorotatory rotates plane:", ["Clockwise (+)", "Anticlockwise", "No rotation", "Random"], "Clockwise (+)"),
        ("Chiral center is a carbon bonded to:", ["4 different groups", "4 same", "3 different", "2 different"], "4 different groups"),
        ("Enantiomers are:", ["Non-superimposable mirror images", "Identical", "Diastereomers", "Geometric"], "Non-superimposable mirror images"),
        ("Racemic mixture contains:", ["50% (+) and 50% (−) enantiomers", "Only (+)", "Only (−)", "Diastereomers"], "50% (+) and 50% (−) enantiomers"),
        ("Racemic mixture is:", ["Optically inactive", "Optically active (+)", "Optically active (−)", "Both active"], "Optically inactive"),
        ("Meso compound has:", ["Chiral centers but internal plane of symmetry (optically inactive)", "No chiral centers", "Active", "Enantiomer only"], "Chiral centers but internal plane of symmetry (optically inactive)"),
    ],
}

def main():
    with open(TARGET, "r", encoding="utf-8") as f:
        d = json.load(f)

    total_replaced = 0
    weeks_updated = []
    for week_entry in d["11"]:
        wk = week_entry["week"]
        if wk not in QS:
            continue
        qlist = QS[wk]
        assert len(qlist) == 25, f"wk{wk} has {len(qlist)} questions, expected 25"
        new_questions = []
        for i, (q, opts, ans) in enumerate(qlist, 1):
            assert len(opts) == 4, f"wk{wk} q{i} has {len(opts)} options"
            assert ans in opts, f"wk{wk} q{i} answer {ans!r} not in options"
            new_questions.append({
                "id": f"c11-w{wk}-q{i}",
                "question": q,
                "options": opts,
                "answer": ans,
            })
        week_entry["questions"] = new_questions
        total_replaced += len(new_questions)
        weeks_updated.append(wk)

    with open(TARGET, "w", encoding="utf-8") as f:
        f.write(json.dumps(d, indent=2, ensure_ascii=False) + "\n")

    print(f"Replaced {total_replaced} chemistry/11 placeholder questions across {len(weeks_updated)} weeks: {weeks_updated}")

if __name__ == "__main__":
    main()
