"""Batch 2: physics/11 wk15-23 — Work/Energy/Power, Rotation, Gravitation. 225 real NCERT MCQs."""
import json
from pathlib import Path

DATA = Path("src/data/physics-quizzes.json")

QS = {
    15: [  # Work, Energy, Power – Work, KE, Work-Energy Theorem
        ("Work done by a force is defined as:", ["Force × distance", "Force × displacement in direction of force", "Force × time", "Force / displacement"], "Force × displacement in direction of force"),
        ("The SI unit of work is:", ["Newton", "Joule", "Watt", "Pascal"], "Joule"),
        ("1 joule equals:", ["1 N·m", "1 kg·m/s", "1 N/m", "1 kg·m²/s"], "1 N·m"),
        ("Work done by a force of 10 N moving a body through 5 m along the force is:", ["50 J", "25 J", "2 J", "100 J"], "50 J"),
        ("Work done is zero when:", ["Force and displacement are perpendicular", "Force is zero", "Displacement is zero", "All of these"], "All of these"),
        ("The work-energy theorem states:", ["W = ΔKE", "W = ΔPE", "W = KE + PE", "W = F·t"], "W = ΔKE"),
        ("Kinetic energy of a body of mass m moving with velocity v is:", ["mv", "½mv²", "mv²", "2mv²"], "½mv²"),
        ("If momentum is doubled, kinetic energy becomes:", ["Doubled", "Halved", "Four times", "Same"], "Four times"),
        ("Work done by gravity on a body falling freely through height h is:", ["mgh (negative)", "mgh (positive)", "Zero", "½mgh"], "mgh (positive)"),
        ("Work done by friction is always:", ["Positive", "Negative", "Zero", "Depends on direction"], "Negative"),
        ("Dimensions of work are:", ["[ML²T⁻²]", "[MLT⁻²]", "[MLT⁻¹]", "[ML²T⁻¹]"], "[ML²T⁻²]"),
        ("1 erg equals:", ["10⁻⁷ J", "10⁷ J", "10⁻³ J", "10³ J"], "10⁻⁷ J"),
        ("A body of mass 2 kg moves with velocity 4 m/s. Its KE is:", ["16 J", "8 J", "32 J", "4 J"], "16 J"),
        ("If KE of a body is quadrupled, its momentum becomes:", ["Doubled", "Quadrupled", "Halved", "Unchanged"], "Doubled"),
        ("Work done in lifting a 5 kg mass by 2 m (g=10 m/s²) is:", ["100 J", "50 J", "25 J", "10 J"], "100 J"),
        ("Work is a:", ["Scalar quantity", "Vector quantity", "Tensor", "Pseudo-vector"], "Scalar quantity"),
        ("Work done by centripetal force in circular motion is:", ["Positive", "Negative", "Zero", "Maximum"], "Zero"),
        ("W = F·d·cosθ. Work is maximum when θ equals:", ["0°", "90°", "180°", "45°"], "0°"),
        ("If a force of 20 N acts at 60° to displacement of 10 m, work done is:", ["100 J", "200 J", "173 J", "50 J"], "100 J"),
        ("The area under a force-displacement graph represents:", ["Work", "Power", "Energy", "Momentum"], "Work"),
        ("A variable force F = 2x N acts on a body. Work done from x=0 to x=3 m is:", ["9 J", "6 J", "18 J", "3 J"], "9 J"),
        ("Relation between KE and momentum p is:", ["KE = p²/2m", "KE = p/2m", "KE = 2pm", "KE = p²m"], "KE = p²/2m"),
        ("A body at rest has KE:", ["Zero", "Infinite", "Maximum", "mgh"], "Zero"),
        ("If velocity is doubled, KE becomes:", ["Doubled", "Halved", "Four times", "Same"], "Four times"),
        ("Two bodies of equal mass have KE in ratio 1:4. Ratio of velocities is:", ["1:2", "1:4", "2:1", "1:16"], "1:2"),
    ],
    16: [  # Work, Energy, Power – PE, Conservation
        ("Potential energy is energy due to:", ["Motion", "Position or configuration", "Temperature", "Mass"], "Position or configuration"),
        ("Gravitational PE near Earth's surface is:", ["mgh", "½mv²", "mgR", "½kx²"], "mgh"),
        ("Spring PE for extension x is:", ["½kx²", "kx", "½kx", "kx²"], "½kx²"),
        ("Law of conservation of energy states:", ["Energy cannot be created or destroyed", "KE is always conserved", "PE is always conserved", "Mass and energy are interchangeable only"], "Energy cannot be created or destroyed"),
        ("A ball dropped from height h has maximum KE:", ["At top", "At midpoint", "Just before striking ground", "Same everywhere"], "Just before striking ground"),
        ("Work done by a conservative force in a closed path is:", ["Positive", "Negative", "Zero", "Infinite"], "Zero"),
        ("Example of non-conservative force:", ["Gravity", "Spring force", "Friction", "Electrostatic force"], "Friction"),
        ("For a conservative force F, relation with PE U is:", ["F = -dU/dx", "F = dU/dx", "F = U·x", "F = U/x"], "F = -dU/dx"),
        ("A spring of constant 200 N/m is stretched 10 cm. PE stored is:", ["1 J", "2 J", "0.5 J", "10 J"], "1 J"),
        ("Total mechanical energy of a freely falling body is:", ["Increasing", "Decreasing", "Constant", "Zero"], "Constant"),
        ("Escape from a system's conservative force corresponds to energy:", ["Zero total", "Negative total", "Positive total", "Any"], "Zero total"),
        ("The PE at natural length of spring is:", ["Zero", "½kx²", "Maximum", "Negative"], "Zero"),
        ("Einstein's mass-energy equivalence is:", ["E = mc²", "E = mc", "E = mv²", "E = ½mc²"], "E = mc²"),
        ("If 1 kg mass is fully converted to energy, energy released is about:", ["9 × 10¹⁶ J", "3 × 10⁸ J", "9 × 10⁸ J", "3 × 10¹⁶ J"], "9 × 10¹⁶ J"),
        ("A simple pendulum has maximum KE at:", ["Extreme position", "Mean position", "Midway", "Nowhere"], "Mean position"),
        ("A simple pendulum has maximum PE at:", ["Extreme position", "Mean position", "Midway", "Bottom"], "Extreme position"),
        ("Energy stored in a stretched wire is:", ["½ × stress × strain × volume", "stress × strain", "½ × stress × volume", "Young's modulus × volume"], "½ × stress × strain × volume"),
        ("Unit of spring constant k:", ["N/m", "N·m", "N·s", "N/m²"], "N/m"),
        ("Two springs k₁ and k₂ in series have equivalent:", ["k₁+k₂", "k₁k₂/(k₁+k₂)", "k₁-k₂", "(k₁+k₂)/2"], "k₁k₂/(k₁+k₂)"),
        ("Two springs k₁ and k₂ in parallel have equivalent:", ["k₁+k₂", "k₁k₂/(k₁+k₂)", "k₁-k₂", "(k₁+k₂)/2"], "k₁+k₂"),
        ("PE of a body at height h above Earth's surface (h<<R):", ["mgh", "-GMm/R", "mgR", "GMm/(R+h)"], "mgh"),
        ("A body of mass 1 kg is at height 10 m. Its PE (g=10):", ["100 J", "50 J", "10 J", "1000 J"], "100 J"),
        ("Which has more PE: 2 kg at 5 m or 1 kg at 10 m?", ["Equal", "2 kg at 5 m", "1 kg at 10 m", "Cannot say"], "Equal"),
        ("The potential well represents:", ["Region of stable equilibrium", "Unstable equilibrium", "No equilibrium", "Infinite PE"], "Region of stable equilibrium"),
        ("Energy conservation is obeyed in:", ["All physical processes", "Only mechanical", "Only thermal", "Only electrical"], "All physical processes"),
    ],
    17: [  # Power, Collisions
        ("Power is defined as:", ["Rate of doing work", "Force per unit area", "Work per unit volume", "Energy per unit mass"], "Rate of doing work"),
        ("SI unit of power is:", ["Joule", "Watt", "Newton", "Pascal"], "Watt"),
        ("1 horsepower equals approximately:", ["746 W", "1000 W", "500 W", "100 W"], "746 W"),
        ("Average power = :", ["Work done / time", "Force / time", "Force × velocity", "Energy × time"], "Work done / time"),
        ("Instantaneous power P equals:", ["F·v", "F/v", "F+v", "F-v"], "F·v"),
        ("Dimensions of power:", ["[ML²T⁻³]", "[MLT⁻²]", "[ML²T⁻²]", "[MLT⁻¹]"], "[ML²T⁻³]"),
        ("A pump lifts 100 kg of water per second to height 10 m (g=10). Power:", ["10 kW", "1 kW", "100 W", "100 kW"], "10 kW"),
        ("1 kilowatt-hour equals:", ["3.6 × 10⁶ J", "1000 J", "3600 J", "10⁶ J"], "3.6 × 10⁶ J"),
        ("Collision in which KE is conserved is called:", ["Elastic", "Inelastic", "Perfectly inelastic", "Semi-elastic"], "Elastic"),
        ("In inelastic collision:", ["KE is conserved", "Momentum is conserved, KE is not", "Both conserved", "Neither conserved"], "Momentum is conserved, KE is not"),
        ("Perfectly inelastic collision means:", ["Bodies separate with same speed", "Bodies stick together after collision", "No force acts", "Maximum KE loss with bodies sticking"], "Bodies stick together after collision"),
        ("Momentum is conserved in:", ["Elastic collision only", "Inelastic collision only", "All collisions", "No collision"], "All collisions"),
        ("Coefficient of restitution for perfectly elastic collision is:", ["0", "1", "0.5", "∞"], "1"),
        ("Coefficient of restitution for perfectly inelastic collision is:", ["0", "1", "0.5", "∞"], "0"),
        ("Two identical balls, one at rest, undergo head-on elastic collision. After collision:", ["Both move together", "Moving ball stops, other moves with same speed", "Both rebound", "Moving ball continues at same speed"], "Moving ball stops, other moves with same speed"),
        ("In elastic collision between two equal masses where one is at rest, they:", ["Move in opposite directions with same speed", "Exchange velocities", "Stick together", "Both stop"], "Exchange velocities"),
        ("A 2 kg body at 5 m/s collides head-on with 3 kg at rest, sticking together. Final speed:", ["2 m/s", "3 m/s", "1 m/s", "5 m/s"], "2 m/s"),
        ("Coefficient of restitution e is defined as:", ["v_separation / v_approach", "v_approach / v_separation", "KE_final / KE_initial", "p_final / p_initial"], "v_separation / v_approach"),
        ("A ball falls from height h, rebounds to h'. e equals:", ["√(h'/h)", "h'/h", "√(h/h')", "h'/(h+h')"], "√(h'/h)"),
        ("When a bullet embeds in a block, the collision is:", ["Elastic", "Perfectly inelastic", "Semi-elastic", "Super-elastic"], "Perfectly inelastic"),
        ("Loss in KE in perfectly inelastic collision of two equal masses (one at rest) is:", ["25%", "50%", "75%", "100%"], "50%"),
        ("A machine does 600 J of work in 20 s. Power is:", ["30 W", "60 W", "12000 W", "600 W"], "30 W"),
        ("Average power × time equals:", ["Work", "Force", "Momentum", "Energy density"], "Work"),
        ("Which is not a unit of power?", ["Watt", "Horsepower", "Joule/second", "Joule"], "Joule"),
        ("If power = 100 W and velocity = 10 m/s, force is:", ["10 N", "1000 N", "1 N", "100 N"], "10 N"),
    ],
    18: [  # Centre of Mass
        ("Centre of mass of a system of particles is:", ["Point where total mass is assumed concentrated", "Geometrical centre always", "Centre of gravity only", "Point of maximum mass"], "Point where total mass is assumed concentrated"),
        ("Position of COM for two particles m₁ at x₁ and m₂ at x₂:", ["(m₁x₁+m₂x₂)/(m₁+m₂)", "(x₁+x₂)/2", "m₁+m₂ / x₁+x₂", "m₁x₂+m₂x₁"], "(m₁x₁+m₂x₂)/(m₁+m₂)"),
        ("COM of a uniform rod is at:", ["One end", "Midpoint", "Quarter length", "Depends on orientation"], "Midpoint"),
        ("COM of a uniform circular disc is at:", ["Rim", "Centre", "One-fourth radius", "Half radius"], "Centre"),
        ("Velocity of COM of a system is:", ["Σmᵢvᵢ / Σmᵢ", "Σvᵢ / n", "Σmᵢ / Σvᵢ", "mean velocity"], "Σmᵢvᵢ / Σmᵢ"),
        ("If no external force acts, velocity of COM is:", ["Zero", "Constant", "Changing", "Maximum"], "Constant"),
        ("Internal forces affect COM motion:", ["Yes, strongly", "No, only external forces do", "Depends on type", "Only gravitational"], "No, only external forces do"),
        ("A body explodes in mid-air. COM of fragments:", ["Stops", "Moves in original trajectory", "Moves upward", "Moves randomly"], "Moves in original trajectory"),
        ("For a system with constant total mass, F_ext = :", ["m·a_cm", "M·a_cm", "M·v_cm", "ma"], "M·a_cm"),
        ("COM of Earth-Moon system lies:", ["At Earth's centre", "At Moon's centre", "Inside Earth, between them", "Outside Earth"], "Inside Earth, between them"),
        ("If COM is at origin for two particles m₁ and m₂ at x₁ and x₂, then:", ["m₁x₁ + m₂x₂ = 0", "x₁+x₂=0", "m₁=m₂", "x₁=x₂"], "m₁x₁ + m₂x₂ = 0"),
        ("Two masses 3 kg and 5 kg are at positions 2 m and 10 m. COM is at:", ["7 m", "6 m", "5 m", "8 m"], "7 m"),
        ("For a uniform triangular lamina, COM is at:", ["Centroid", "Orthocentre", "Incentre", "Circumcentre"], "Centroid"),
        ("COM of a uniform hemispherical shell is at:", ["Centre", "Radius/2", "3R/8 from flat face", "R/2 from flat face"], "R/2 from flat face"),
        ("COM of uniform solid hemisphere from flat face:", ["3R/8", "R/2", "R/4", "5R/8"], "3R/8"),
        ("Momentum of system equals:", ["M·v_cm", "Σmᵢvᵢ", "Both a and b", "m/v"], "Both a and b"),
        ("If a system has F_ext = 0, total momentum is:", ["Conserved", "Increasing", "Zero", "Variable"], "Conserved"),
        ("Two particles of equal mass move in opposite directions with same speed. COM velocity:", ["Zero", "Same as particles", "Double", "Half"], "Zero"),
        ("A boy walks from one end of a boat to the other. COM of boy+boat:", ["Moves with boy", "Stays fixed (no external force)", "Moves opposite to boy", "Depends on mass"], "Stays fixed (no external force)"),
        ("The acceleration of COM depends on:", ["External forces only", "Internal forces only", "Both", "Neither"], "External forces only"),
        ("COM and centre of gravity coincide when:", ["g is uniform", "Body is symmetric", "Body is rigid", "Always"], "g is uniform"),
        ("For a uniform sphere, COM is at:", ["Geometric centre", "Surface", "At R/2", "At any point"], "Geometric centre"),
        ("If m₁=2, m₂=3 kg at (0,0) and (5,0), COM x-coordinate:", ["3 m", "2.5 m", "2 m", "5 m"], "3 m"),
        ("COM of a system of particles depends on:", ["Masses and positions", "Velocities", "Forces", "Time only"], "Masses and positions"),
        ("Total linear momentum P equals:", ["Mv_cm", "Σpᵢ", "Both", "None"], "Both"),
    ],
    19: [  # Rotational — MOI, Torque, Angular Momentum
        ("Moment of inertia is the rotational analogue of:", ["Mass", "Velocity", "Force", "Energy"], "Mass"),
        ("SI unit of moment of inertia:", ["kg·m²", "kg·m", "kg/m²", "kg·m/s"], "kg·m²"),
        ("MOI of a ring of mass M and radius R about its axis perpendicular to its plane:", ["MR²", "½MR²", "⅔MR²", "⅖MR²"], "MR²"),
        ("MOI of a disc about its axis:", ["½MR²", "MR²", "⅖MR²", "¼MR²"], "½MR²"),
        ("MOI of a solid sphere about its diameter:", ["⅖MR²", "⅔MR²", "MR²", "½MR²"], "⅖MR²"),
        ("MOI of a hollow sphere about diameter:", ["⅔MR²", "⅖MR²", "MR²", "½MR²"], "⅔MR²"),
        ("MOI of a rod of length L about centre perpendicular to length:", ["ML²/12", "ML²/3", "ML²/2", "ML²"], "ML²/12"),
        ("MOI of a rod about one end perpendicular to length:", ["ML²/3", "ML²/12", "ML²/2", "ML²"], "ML²/3"),
        ("Torque equals:", ["r × F", "r·F", "r/F", "F/r"], "r × F"),
        ("Unit of torque is:", ["N·m", "N/m", "N·s", "J/s"], "N·m"),
        ("Rotational analogue of Newton's second law:", ["τ = Iα", "τ = Iω", "τ = I/α", "τ = F/a"], "τ = Iα"),
        ("Angular momentum L equals:", ["Iω", "mv", "mω", "rω"], "Iω"),
        ("SI unit of angular momentum:", ["kg·m²/s", "kg·m/s", "J·s", "Both a and c"], "Both a and c"),
        ("Law of conservation of angular momentum states:", ["If τ_ext=0, L is constant", "L always increases", "Iω always constant", "None"], "If τ_ext=0, L is constant"),
        ("An ice skater pulls arms in; her angular velocity:", ["Decreases", "Increases", "Unchanged", "Becomes zero"], "Increases"),
        ("Relation between τ and L:", ["τ = dL/dt", "τ = L·t", "τ = L/t", "τ = Lω"], "τ = dL/dt"),
        ("Parallel axis theorem: I = I_cm + Md². Here d is:", ["Distance between the axes", "Radius of gyration", "Side of object", "Diameter"], "Distance between the axes"),
        ("Perpendicular axis theorem applies to:", ["Planar (laminar) bodies", "3D bodies", "All bodies", "Point masses"], "Planar (laminar) bodies"),
        ("Perpendicular axis theorem: I_z = :", ["I_x + I_y", "I_x - I_y", "I_x·I_y", "√(I_x²+I_y²)"], "I_x + I_y"),
        ("Radius of gyration k is defined by:", ["I = Mk²", "k = I/M", "k = I·M", "I = M/k²"], "I = Mk²"),
        ("A torque produces:", ["Linear acceleration", "Angular acceleration", "Both", "Neither"], "Angular acceleration"),
        ("MOI depends on:", ["Mass distribution and axis", "Mass only", "Axis only", "Neither"], "Mass distribution and axis"),
        ("Kinetic energy of rotation equals:", ["½Iω²", "½mv²", "Iω", "mω"], "½Iω²"),
        ("Work done by torque = :", ["τ·θ", "τ·t", "τ·ω", "τ/θ"], "τ·θ"),
        ("Power in rotation P = :", ["τ·ω", "τ/ω", "τ·θ", "τ+ω"], "τ·ω"),
    ],
    20: [  # Rolling, Theorems
        ("A body rolling without slipping has v_cm equal to:", ["Rω", "R/ω", "R·ω²", "R+ω"], "Rω"),
        ("KE of a rolling body:", ["½Mv² + ½Iω²", "½Mv²", "½Iω²", "Mv²+Iω²"], "½Mv² + ½Iω²"),
        ("For a ring rolling, fraction of KE in rotation:", ["½", "⅓", "⅖", "⅕"], "½"),
        ("For a solid disc rolling, KE_rot / KE_total:", ["⅓", "½", "⅖", "⅕"], "⅓"),
        ("For a solid sphere rolling, KE_rot / KE_total:", ["2/7", "⅖", "½", "3/7"], "2/7"),
        ("In rolling without slipping, friction does:", ["No work", "Positive work", "Negative work", "Infinite work"], "No work"),
        ("The direction of friction in pure rolling on horizontal surface is:", ["Zero (static friction adjusts)", "Forward", "Backward", "Depends"], "Zero (static friction adjusts)"),
        ("A solid sphere, hollow sphere, disc, and ring roll down an incline. Which reaches first?", ["Solid sphere", "Hollow sphere", "Disc", "Ring"], "Solid sphere"),
        ("Acceleration of solid sphere rolling down incline θ:", ["(5/7)g sinθ", "g sinθ", "(2/3)g sinθ", "(3/5)g sinθ"], "(5/7)g sinθ"),
        ("Acceleration of disc rolling down incline θ:", ["(2/3)g sinθ", "g sinθ", "(5/7)g sinθ", "½g sinθ"], "(2/3)g sinθ"),
        ("Acceleration of ring rolling down incline θ:", ["½g sinθ", "g sinθ", "(2/3)g sinθ", "(5/7)g sinθ"], "½g sinθ"),
        ("In pure rolling, contact point has velocity:", ["Zero", "v", "2v", "½v"], "Zero"),
        ("Top of a rolling wheel has velocity:", ["2v", "v", "Zero", "½v"], "2v"),
        ("Parallel axis theorem gives MOI about a parallel axis distance d from COM axis:", ["I_cm + Md²", "I_cm - Md²", "Md²", "I_cm/d²"], "I_cm + Md²"),
        ("MOI of rod of length L about axis through one end (M=mass):", ["ML²/3", "ML²/12", "ML²/6", "ML²"], "ML²/3"),
        ("MOI of disc about a tangent in plane:", ["(5/4)MR²", "½MR²", "MR²", "(3/2)MR²"], "(5/4)MR²"),
        ("MOI of disc about diameter:", ["¼MR²", "½MR²", "MR²", "⅖MR²"], "¼MR²"),
        ("MOI of ring about diameter:", ["½MR²", "MR²", "¼MR²", "⅖MR²"], "½MR²"),
        ("Rolling KE of ring = Translational KE × :", ["1", "2", "½", "¼"], "1"),
        ("Total KE of rolling sphere = Translational KE × :", ["7/5", "5/7", "3/2", "2/3"], "7/5"),
        ("Condition for pure rolling:", ["v = Rω", "v > Rω", "v < Rω", "v = R/ω"], "v = Rω"),
        ("A hoop (ring) and disc roll down same incline. Which is faster at bottom?", ["Disc", "Ring", "Both same", "Cannot say"], "Disc"),
        ("MOI of solid cylinder about its axis (M=mass, R=radius):", ["½MR²", "MR²", "⅖MR²", "⅓MR²"], "½MR²"),
        ("A rolling body's total KE is shared between translation and rotation. For ring ratio is:", ["1:1", "2:1", "1:2", "3:1"], "1:1"),
        ("Perpendicular axis theorem for disc: I_z (through centre ⊥ plane) = :", ["I_x + I_y where both = ¼MR², so ½MR²", "¼MR²", "MR²", "⅓MR²"], "I_x + I_y where both = ¼MR², so ½MR²"),
    ],
    21: [  # Gravitation — Universal Law, g
        ("Newton's law of gravitation: F = :", ["Gm₁m₂/r²", "Gm₁m₂/r", "Gm₁m₂·r²", "Gm₁+m₂/r²"], "Gm₁m₂/r²"),
        ("Value of gravitational constant G:", ["6.67 × 10⁻¹¹ N·m²/kg²", "9.8 m/s²", "1.6 × 10⁻¹⁹ C", "6.02 × 10²³"], "6.67 × 10⁻¹¹ N·m²/kg²"),
        ("Unit of G:", ["N·m²/kg²", "N·m/kg²", "N/kg²", "N·m/kg"], "N·m²/kg²"),
        ("Dimensions of G:", ["[M⁻¹L³T⁻²]", "[MLT⁻²]", "[ML²T⁻²]", "[M⁻¹L²T⁻¹]"], "[M⁻¹L³T⁻²]"),
        ("Gravitational force is always:", ["Attractive", "Repulsive", "Both", "Zero"], "Attractive"),
        ("Acceleration due to gravity g at Earth's surface:", ["GM/R²", "GM/R", "G/R²", "GM·R"], "GM/R²"),
        ("Value of g at Earth's surface (approx):", ["9.8 m/s²", "6.67 m/s²", "32 m/s²", "10⁻¹¹ m/s²"], "9.8 m/s²"),
        ("g at height h above surface (h<<R):", ["g(1 - 2h/R)", "g(1 + 2h/R)", "g(1 - h/R)", "g(1 + h/R)"], "g(1 - 2h/R)"),
        ("g at depth d below surface:", ["g(1 - d/R)", "g(1 + d/R)", "g(1 - d²/R²)", "g·d/R"], "g(1 - d/R)"),
        ("g is maximum at:", ["Poles", "Equator", "Centre", "Moon's surface"], "Poles"),
        ("Variation of g at equator due to rotation:", ["Decreases", "Increases", "No change", "Zero"], "Decreases"),
        ("Value of g at centre of Earth:", ["Zero", "9.8 m/s²", "Maximum", "Infinite"], "Zero"),
        ("If Earth shrinks to half radius keeping mass same, g becomes:", ["4g", "2g", "g/2", "g/4"], "4g"),
        ("Gravitational force does not depend on:", ["Medium between masses", "Distance", "Masses", "None"], "Medium between masses"),
        ("Kepler's period law: T² ∝ :", ["r³", "r", "r²", "1/r"], "r³"),
        ("The Cavendish experiment measures:", ["G", "g", "M_Earth", "R_Earth"], "G"),
        ("A body's weight on Moon compared to Earth (approx):", ["1/6", "1/3", "6 times", "Same"], "1/6"),
        ("Mass of an object in space is:", ["Same as on Earth", "Zero", "Half", "Doubled"], "Same as on Earth"),
        ("Weight of a body at centre of Earth is:", ["Zero", "Maximum", "Half", "mg"], "Zero"),
        ("Acceleration due to gravity at Moon's surface is about:", ["1.62 m/s²", "9.8 m/s²", "3.7 m/s²", "6.67 m/s²"], "1.62 m/s²"),
        ("Inertial mass and gravitational mass are:", ["Equal (equivalence principle)", "Different always", "Equal only on Earth", "Related by G"], "Equal (equivalence principle)"),
        ("Weight of body at poles vs equator:", ["More at poles", "More at equator", "Same", "Depends"], "More at poles"),
        ("A man jumps higher on Moon because:", ["g is less", "Mass is less", "Weight is same", "Air resistance is zero"], "g is less"),
        ("If mass of Earth is doubled, keeping R same, g becomes:", ["2g", "g/2", "4g", "g"], "2g"),
        ("Two bodies of masses m and 2m are separated by distance r. Force on m:", ["2Gm²/r²", "Gm²/r²", "Gm²/(2r²)", "G(2m)²/r²"], "2Gm²/r²"),
    ],
    22: [  # Gravitational PE, Escape velocity, Orbital velocity
        ("Gravitational PE of a body at distance r from Earth's centre:", ["-GMm/r", "GMm/r", "mgh", "½mv²"], "-GMm/r"),
        ("Negative sign in gravitational PE indicates:", ["Attractive (bound) nature", "Error", "Repulsive", "Nothing specific"], "Attractive (bound) nature"),
        ("PE of a body at infinity is:", ["Zero", "Infinite", "Negative", "mgh"], "Zero"),
        ("Escape velocity from Earth's surface:", ["√(2GM/R)", "√(GM/R)", "√(GM·R)", "GM/R"], "√(2GM/R)"),
        ("Value of escape velocity from Earth:", ["11.2 km/s", "7.9 km/s", "9.8 km/s", "15 km/s"], "11.2 km/s"),
        ("Escape velocity in terms of g and R:", ["√(2gR)", "√(gR)", "√(gR/2)", "g·R"], "√(2gR)"),
        ("Escape velocity depends on:", ["Mass and radius of planet", "Mass of projectile", "Both", "Direction"], "Mass and radius of planet"),
        ("Escape velocity from Moon (approx):", ["2.4 km/s", "11.2 km/s", "5 km/s", "0.5 km/s"], "2.4 km/s"),
        ("Orbital velocity of a satellite at height h:", ["√(GM/(R+h))", "√(2GM/(R+h))", "GM/(R+h)", "√(gR)"], "√(GM/(R+h))"),
        ("Orbital velocity near Earth's surface:", ["7.9 km/s", "11.2 km/s", "9.8 km/s", "3.7 km/s"], "7.9 km/s"),
        ("Ratio of escape velocity to orbital velocity near surface:", ["√2", "2", "½", "1"], "√2"),
        ("Orbital period T for satellite at radius r:", ["2π√(r³/GM)", "2π√(r/GM)", "2π·r/GM", "2π·r²"], "2π√(r³/GM)"),
        ("A satellite in orbit has KE equal to:", ["½|PE|", "|PE|", "2|PE|", "Zero"], "½|PE|"),
        ("Total energy of satellite in orbit:", ["-GMm/(2r)", "-GMm/r", "GMm/(2r)", "Zero"], "-GMm/(2r)"),
        ("Binding energy of satellite at orbit = :", ["|Total energy|", "KE", "PE", "Zero"], "|Total energy|"),
        ("Escape velocity is independent of:", ["Direction", "Planet's mass", "Planet's radius", "All of above"], "Direction"),
        ("If escape velocity from a planet is v_e and radius R, GM = :", ["v_e²R/2", "v_e·R", "2v_e·R", "v_e²/R"], "v_e²R/2"),
        ("Speed needed for a body at height h to escape:", ["√(2GM/(R+h))", "√(GM/(R+h))", "√(2gR)", "gR"], "√(2GM/(R+h))"),
        ("For a satellite closer to Earth, orbital speed is:", ["Higher", "Lower", "Same", "Zero"], "Higher"),
        ("KE of satellite in orbit at radius r:", ["GMm/(2r)", "GMm/r", "-GMm/r", "Zero"], "GMm/(2r)"),
        ("PE of satellite in orbit at radius r:", ["-GMm/r", "-GMm/(2r)", "GMm/r", "Zero"], "-GMm/r"),
        ("Total energy of satellite is negative because:", ["It is bound", "It rotates", "It is in vacuum", "Always"], "It is bound"),
        ("For a satellite to go to infinity, its total energy must be:", ["≥ 0", "< 0", "Zero only", "Negative"], "≥ 0"),
        ("Escape speed at a height equal to Earth's radius (h=R):", ["√(GM/R)", "√(2GM/R)", "2√(GM/R)", "Zero"], "√(GM/R)"),
        ("If orbital speed is v, escape speed is:", ["v√2", "v/√2", "2v", "v"], "v√2"),
    ],
    23: [  # Kepler's Laws, Satellites, Geostationary
        ("Kepler's first law (law of orbits):", ["Planets move in ellipses with Sun at focus", "Orbits are circles", "Areal velocity is constant", "T² ∝ a³"], "Planets move in ellipses with Sun at focus"),
        ("Kepler's second law (law of areas):", ["Areal velocity is constant", "T² ∝ a³", "Equal times equal distances", "Orbits are elliptical"], "Areal velocity is constant"),
        ("Kepler's third law (law of periods):", ["T² ∝ a³", "T ∝ a", "T² ∝ a²", "T³ ∝ a²"], "T² ∝ a³"),
        ("Kepler's second law is a consequence of:", ["Conservation of angular momentum", "Conservation of energy", "Newton's third law", "Gravitational law"], "Conservation of angular momentum"),
        ("In elliptical orbit, planet is fastest at:", ["Perihelion", "Aphelion", "Midpoint", "Same throughout"], "Perihelion"),
        ("Planet is slowest at:", ["Aphelion", "Perihelion", "Midpoint", "Everywhere same"], "Aphelion"),
        ("A geostationary satellite has orbital period:", ["24 hours", "12 hours", "1 hour", "365 days"], "24 hours"),
        ("Height of geostationary satellite above Earth:", ["≈ 36,000 km", "≈ 300 km", "≈ 3600 km", "≈ 3,60,000 km"], "≈ 36,000 km"),
        ("Orbital radius of geostationary satellite (approx):", ["42,000 km", "36,000 km", "6,400 km", "1,00,000 km"], "42,000 km"),
        ("Geostationary satellite orbits in:", ["Equatorial plane", "Polar plane", "Any plane", "Inclined plane"], "Equatorial plane"),
        ("Direction of motion of geostationary satellite:", ["West to East (with Earth)", "East to West", "North to South", "Any"], "West to East (with Earth)"),
        ("Polar satellites have low heights and scan:", ["Entire Earth over time", "Only equator", "Only poles", "One hemisphere"], "Entire Earth over time"),
        ("Uses of geostationary satellite:", ["Communication, weather", "GPS only", "Military only", "None"], "Communication, weather"),
        ("A satellite's speed in orbit at radius r from Earth's centre:", ["√(GM/r)", "√(GM·r)", "GM/r", "r/GM"], "√(GM/r)"),
        ("Orbit at Earth's surface (ignoring atmosphere) is possible at:", ["7.9 km/s", "11.2 km/s", "3.0 km/s", "Not possible"], "7.9 km/s"),
        ("Kepler's third law for two planets: T₁²/T₂² = :", ["r₁³/r₂³", "r₁/r₂", "r₁²/r₂²", "√(r₁/r₂)"], "r₁³/r₂³"),
        ("A satellite revolves with T=2 hours at r=r₀. At r=4r₀, T is:", ["16 hours", "8 hours", "4 hours", "2 hours"], "16 hours"),
        ("Planets move around Sun due to:", ["Gravitational force", "Electromagnetic force", "Magnetic force", "Nuclear force"], "Gravitational force"),
        ("Areal velocity = dA/dt = :", ["L/(2m)", "L·m", "L/m", "L/(2r)"], "L/(2m)"),
        ("Eccentricity of a circular orbit:", ["Zero", "1", "Infinite", "0.5"], "Zero"),
        ("Eccentricity of parabolic orbit:", ["1", "0", "0.5", ">1"], "1"),
        ("Bound orbits have total energy:", ["Negative", "Positive", "Zero", "Either"], "Negative"),
        ("Unbound trajectories have total energy:", ["Positive", "Negative", "Zero only", "Infinite"], "Positive"),
        ("Two satellites revolve at r₁ and r₂=2r₁. Ratio of periods T₁:T₂:", ["1:2√2", "1:2", "1:4", "1:8"], "1:2√2"),
        ("Kepler's laws apply to:", ["All gravitational two-body systems", "Only planets", "Only satellites", "Only stars"], "All gravitational two-body systems"),
    ],
}

def main():
    d = json.loads(DATA.read_text())
    total = 0
    for wk, qlist in QS.items():
        assert len(qlist) == 25, f"Week {wk} has {len(qlist)} questions"
        week_entry = next(w for w in d["11"] if w["week"] == wk)
        new_qs = []
        for q, opts, ans in qlist:
            assert ans in opts, f"Week {wk}: answer '{ans}' not in options {opts}"
            new_qs.append({"question": q, "options": opts, "answer": ans})
        week_entry["questions"] = new_qs
        total += 25
    DATA.write_text(json.dumps(d, indent=2, ensure_ascii=False) + "\n")
    print(f"Replaced {total} physics/11 placeholder questions across {len(QS)} weeks: {sorted(QS.keys())}")

if __name__ == "__main__":
    main()
