#!/usr/bin/env python3
"""Replace placeholders in chemistry/11 weeks 40-52 (325 MCQs).

Coverage:
- wk40: Group 14 (Carbon family)
- wk41: Environmental – Air/water pollution, ozone depletion
- wk42: Environmental – Green chemistry, acid rain, greenhouse effect
- wk43: Revision – Basic concepts & atomic structure
- wk44: Revision – Periodic table & bonding
- wk45: Revision – Thermodynamics & equilibrium
- wk46: Revision – Redox reactions
- wk47: Revision – Organic basics & nomenclature
- wk48: Revision – Hydrocarbons
- wk49: Revision – States of matter & hydrogen
- wk50: Revision – s-block & p-block
- wk51: Mixed numerical problems
- wk52: Comprehensive revision
"""
import json, pathlib

PATH = pathlib.Path("src/data/chemistry-quizzes.json")

QS = {
40: [
 ("Group 14 elements:",
  ["C, Si, Ge, Sn, Pb","B, Al, Ga, In, Tl","N, P, As, Sb","O, S, Se, Te"],"C, Si, Ge, Sn, Pb"),
 ("Group 14 electronic configuration:",
  ["ns²np²","ns²np¹","ns²np³","ns²np⁴"],"ns²np²"),
 ("Common oxidation states of Group 14:",
  ["+4 and +2","+3 only","+5 and +3","+1 only"],"+4 and +2"),
 ("Inert pair effect causes Pb to prefer:",
  ["+2","+4","+3","0"],"+2"),
 ("Nature of elements down Group 14:",
  ["Non-metal (C) → metalloid (Si, Ge) → metal (Sn, Pb)","All metals","All non-metals","All metalloids"],"Non-metal (C) → metalloid (Si, Ge) → metal (Sn, Pb)"),
 ("Catenation order in Group 14:",
  ["C >> Si > Ge ≈ Sn > Pb","Pb > Sn > Si > C","All equal","Si > C"],"C >> Si > Ge ≈ Sn > Pb"),
 ("Allotropes of carbon:",
  ["Diamond, graphite, fullerene, CNT, graphene","Only diamond","Only graphite","Only fullerene"],"Diamond, graphite, fullerene, CNT, graphene"),
 ("Hybridisation of C in diamond:",
  ["sp³","sp²","sp","sp³d"],"sp³"),
 ("Hybridisation of C in graphite:",
  ["sp²","sp³","sp","sp³d²"],"sp²"),
 ("Diamond conducts:",
  ["Heat but not electricity","Both","Neither","Only electricity"],"Heat but not electricity"),
 ("Graphite conducts electricity because:",
  ["Delocalised π-electrons between layers","Ionic bonding","Free protons","H-bonding"],"Delocalised π-electrons between layers"),
 ("Fullerene C₆₀ shape:",
  ["Soccer ball (20 hexagons + 12 pentagons)","Cube","Sphere smooth","Flat disc"],"Soccer ball (20 hexagons + 12 pentagons)"),
 ("CO₂ is:",
  ["Linear, non-polar","Bent, polar","Trigonal planar","Tetrahedral"],"Linear, non-polar"),
 ("CO is a:",
  ["Strong reducing agent and toxic","Base","Acid","Inert"],"Strong reducing agent and toxic"),
 ("CO is toxic because:",
  ["Binds to haemoglobin forming carboxyhaemoglobin","Dissolves in water","Burns","Expands"],"Binds to haemoglobin forming carboxyhaemoglobin"),
 ("SiO₂ structure:",
  ["3D network of SiO₄ tetrahedra","Discrete molecules like CO₂","Linear","Layered only"],"3D network of SiO₄ tetrahedra"),
 ("Silicones are:",
  ["Organosilicon polymers (R₂SiO)ₙ","Silicates","Carbides","Borides"],"Organosilicon polymers (R₂SiO)ₙ"),
 ("Silicates contain:",
  ["SiO₄⁴⁻ tetrahedra","CO₃²⁻","NO₃⁻","SO₄²⁻"],"SiO₄⁴⁻ tetrahedra"),
 ("Zeolites are:",
  ["3D aluminosilicates used as catalysts and ion exchangers","Metals","Pure SiO₂","Clays only"],"3D aluminosilicates used as catalysts and ion exchangers"),
 ("Producer gas contains:",
  ["CO + N₂","CO + H₂","CO₂ + H₂","CH₄ + H₂"],"CO + N₂"),
 ("Water gas contains:",
  ["CO + H₂","CO + N₂","CO₂ + H₂","CH₄ + H₂"],"CO + H₂"),
 ("CO₂ + H₂O ⇌ ?",
  ["H₂CO₃ (carbonic acid)","CO + H₂","CH₄","HCO⁻"],"H₂CO₃ (carbonic acid)"),
 ("PbO₂ + HCl gives:",
  ["PbCl₂ + Cl₂ + H₂O","PbCl₄ only","Pb + HCl","No reaction"],"PbCl₂ + Cl₂ + H₂O"),
 ("SnCl₂ is a:",
  ["Reducing agent","Oxidising agent","Neutral","Inert"],"Reducing agent"),
 ("Glass is a:",
  ["Amorphous supercooled liquid (silicate)","Crystalline solid","Metal","Ionic solid"],"Amorphous supercooled liquid (silicate)"),
],
41: [
 ("Major air pollutants:",
  ["CO, NOₓ, SO₂, CO₂, particulates, hydrocarbons","Only CO₂","Only N₂","Only O₂"],"CO, NOₓ, SO₂, CO₂, particulates, hydrocarbons"),
 ("Main source of CO:",
  ["Incomplete combustion of fossil fuels","Photosynthesis","Plants","Oceans"],"Incomplete combustion of fossil fuels"),
 ("SO₂ comes mainly from:",
  ["Burning of sulphur-containing coal/oil","Plants","Volcanoes only","Refrigerators"],"Burning of sulphur-containing coal/oil"),
 ("NOₓ (NO + NO₂) comes from:",
  ["High-T combustion in vehicle engines","Plants","Oceans","Refrigerators"],"High-T combustion in vehicle engines"),
 ("Photochemical smog forms by:",
  ["NOₓ + hydrocarbons + sunlight → ozone, PAN","CO₂ + water","SO₂ + water","Only pollen"],"NOₓ + hydrocarbons + sunlight → ozone, PAN"),
 ("PAN stands for:",
  ["Peroxyacetyl nitrate","Polyaromatic nitrogen","Primary ambient nitrogen","None"],"Peroxyacetyl nitrate"),
 ("Classical (London) smog is rich in:",
  ["SO₂ + smoke (sulphurous smog)","O₃","NOₓ","PAN"],"SO₂ + smoke (sulphurous smog)"),
 ("BOD stands for:",
  ["Biochemical oxygen demand","Biological organic density","Biotic oxygen drop","None"],"Biochemical oxygen demand"),
 ("High BOD indicates:",
  ["High organic pollution","Clean water","High DO","Low bacteria"],"High organic pollution"),
 ("Eutrophication is caused by:",
  ["Excess nutrients (N, P) causing algal bloom","High DO","Low T","Low CO₂"],"Excess nutrients (N, P) causing algal bloom"),
 ("Major water pollutants:",
  ["Heavy metals (Pb, Hg, Cd), pesticides, nitrates, sewage","Only water","Only sand","Only CO₂"],"Heavy metals (Pb, Hg, Cd), pesticides, nitrates, sewage"),
 ("Minamata disease caused by:",
  ["Hg poisoning (organic mercury)","Pb","Cd","As"],"Hg poisoning (organic mercury)"),
 ("Itai-itai disease caused by:",
  ["Cd poisoning","Hg","Pb","As"],"Cd poisoning"),
 ("Blue baby syndrome caused by:",
  ["High nitrates in water (methaemoglobinaemia)","Pb","Hg","CO₂"],"High nitrates in water (methaemoglobinaemia)"),
 ("Stratospheric ozone (O₃) absorbs:",
  ["UV-B and UV-C","IR only","Visible only","X-rays only"],"UV-B and UV-C"),
 ("Ozone layer is in:",
  ["Stratosphere (15-35 km)","Troposphere","Mesosphere","Thermosphere"],"Stratosphere (15-35 km)"),
 ("CFCs deplete ozone by:",
  ["Releasing Cl radicals which catalyse O₃ destruction","Direct reaction with O₂","Absorbing UV","Forming O₂"],"Releasing Cl radicals which catalyse O₃ destruction"),
 ("Chain reaction for O₃ depletion by Cl:",
  ["Cl + O₃ → ClO + O₂ ; ClO + O → Cl + O₂","Cl + O₂ → ClO₂","O₃ → O₂","Cl + O → ClO only"],"Cl + O₃ → ClO + O₂ ; ClO + O → Cl + O₂"),
 ("Ozone hole over:",
  ["Antarctica (discovered 1985)","Equator","Arctic only (before 2020)","Pacific"],"Antarctica (discovered 1985)"),
 ("Montreal Protocol (1987) controlled:",
  ["CFCs and ozone-depleting substances","CO₂ only","SO₂","Methane"],"CFCs and ozone-depleting substances"),
 ("Kyoto Protocol (1997) targets:",
  ["Greenhouse gases (CO₂, CH₄, N₂O, etc.)","CFCs","SO₂","NOₓ"],"Greenhouse gases (CO₂, CH₄, N₂O, etc.)"),
 ("DO (dissolved oxygen) at 20°C saturation ≈",
  ["9 ppm","0 ppm","100 ppm","50 ppm"],"9 ppm"),
 ("Respirable suspended particulates (RSPM) size:",
  ["< 2.5 μm (PM2.5) or < 10 μm (PM10)","> 100 μm","> 1 mm","Visible only"],"< 2.5 μm (PM2.5) or < 10 μm (PM10)"),
 ("Smog word origin:",
  ["Smoke + fog","Smoke + oxygen","Smoke + gas","Sulphur + fog"],"Smoke + fog"),
 ("Major vehicular pollutant reduced by catalytic converter:",
  ["CO → CO₂, NOₓ → N₂, HC → CO₂ + H₂O","Only CO₂","Only SO₂","Only H₂O"],"CO → CO₂, NOₓ → N₂, HC → CO₂ + H₂O"),
],
42: [
 ("Green chemistry principles include:",
  ["Atom economy, safer reagents, renewables, waste prevention","Maximum waste","Toxic solvents","Non-renewable feedstock only"],"Atom economy, safer reagents, renewables, waste prevention"),
 ("Atom economy measures:",
  ["% atoms of reactants in final product","Cost per atom","Number of reactions","Yield of heat"],"% atoms of reactants in final product"),
 ("Ideal reaction for green chemistry:",
  ["High atom economy, water or solvent-free, catalytic","Low yield","High waste","Multi-step with waste"],"High atom economy, water or solvent-free, catalytic"),
 ("Acid rain has pH:",
  ["< 5.6","> 7","= 7","= 10"],"< 5.6"),
 ("Main causes of acid rain:",
  ["SO₂ and NOₓ → H₂SO₄ and HNO₃","CO₂ only","CH₄ only","O₃"],"SO₂ and NOₓ → H₂SO₄ and HNO₃"),
 ("Effects of acid rain:",
  ["Damages buildings, forests, aquatic life","Improves crops","Clears air","Heats atmosphere"],"Damages buildings, forests, aquatic life"),
 ("Marble cancer is due to:",
  ["Acid rain reacting with CaCO₃ in marble monuments","CO₂","Ozone","Heat"],"Acid rain reacting with CaCO₃ in marble monuments"),
 ("Greenhouse effect means:",
  ["Trapping of IR by GHGs (CO₂, CH₄, N₂O, H₂O vapour) in atmosphere","Heating Earth's surface by direct UV","Cooling","Photosynthesis"],"Trapping of IR by GHGs (CO₂, CH₄, N₂O, H₂O vapour) in atmosphere"),
 ("Main anthropogenic GHG:",
  ["CO₂ (from fossil fuels)","O₂","N₂","Ar"],"CO₂ (from fossil fuels)"),
 ("Global warming potential (GWP) of CH₄ vs CO₂ (100-yr):",
  ["~28× CO₂","Equal","Less than CO₂","0"],"~28× CO₂"),
 ("Major consequence of global warming:",
  ["Rising sea level, extreme weather, glacier melt","Colder winters only","Nothing","Photosynthesis increase"],"Rising sea level, extreme weather, glacier melt"),
 ("CO₂ concentration (current, ppm) is roughly:",
  ["~420 ppm","50 ppm","1000 ppm","10 ppm"],"~420 ppm"),
 ("Biodegradable waste means:",
  ["Decomposed by microbes naturally","Persists forever","Radioactive","Metallic"],"Decomposed by microbes naturally"),
 ("Non-biodegradable includes:",
  ["Plastics, glass, DDT, heavy metals","Paper","Food","Leaves"],"Plastics, glass, DDT, heavy metals"),
 ("Three Rs of waste management:",
  ["Reduce, Reuse, Recycle","Remove, Replace, Resell","Read, Write, Rest","Run, React, Reset"],"Reduce, Reuse, Recycle"),
 ("Dry cleaning uses liquid CO₂ because:",
  ["Non-toxic alternative to tetrachloroethene (greener)","Cheaper","Faster","Larger scale"],"Non-toxic alternative to tetrachloroethene (greener)"),
 ("H₂O₂ is preferred in green bleaching because:",
  ["Decomposes to H₂O + O₂ (no toxic residue)","Non-reactive","Leaves chloride","Cheap only"],"Decomposes to H₂O + O₂ (no toxic residue)"),
 ("Sustainable development means:",
  ["Meeting needs now without compromising future","Maximum consumption","No technology","No waste ever"],"Meeting needs now without compromising future"),
 ("Green synthesis example: ibuprofen (BHC route) replaces:",
  ["6-step with 40% atom economy → 3-step with 77%","5-step → 100% waste","No change","Inert"],"6-step with 40% atom economy → 3-step with 77%"),
 ("Carbon footprint measures:",
  ["Total GHG emitted by an activity","Size of forest","Solar flux","Pure CO₂ only"],"Total GHG emitted by an activity"),
 ("Renewable energy sources:",
  ["Solar, wind, hydro, biomass, geothermal","Only coal","Only oil","Only nuclear fission"],"Solar, wind, hydro, biomass, geothermal"),
 ("Ozone depleting substances (ODS) include:",
  ["CFCs, halons, CCl₄, methyl bromide","CO₂","CH₄","N₂"],"CFCs, halons, CCl₄, methyl bromide"),
 ("HFCs replaced CFCs but:",
  ["Are still potent GHGs (global warming)","Are inert","Are cheaper only","Are natural"],"Are still potent GHGs (global warming)"),
 ("Paris Agreement (2015) aims to limit warming to:",
  ["Well below 2°C, preferably 1.5°C","5°C","10°C","0°C"],"Well below 2°C, preferably 1.5°C"),
 ("Best practice for reducing carbon footprint at home:",
  ["Use energy-efficient appliances, public transport, LED","Drive more","Heat more","Buy more"],"Use energy-efficient appliances, public transport, LED"),
],
43: [
 ("Mole concept: 1 mole =",
  ["6.022 × 10²³ particles","10²³","100","1000"],"6.022 × 10²³ particles"),
 ("Avogadro's number is defined by the number of atoms in:",
  ["12 g of ¹²C (exact now)","1 g of H","22.4 L","100 g"],"12 g of ¹²C (exact now)"),
 ("Molar mass of water:",
  ["18 g/mol","16","20","2"],"18 g/mol"),
 ("Molarity (M) =",
  ["mol solute / L solution","g solute / L","mol / kg solvent","mass fraction"],"mol solute / L solution"),
 ("Molality (m) =",
  ["mol solute / kg solvent","mol / L","g / L","% by mass"],"mol solute / kg solvent"),
 ("Mole fraction (X_A) =",
  ["n_A / (n_A + n_B)","mol/L","mol/kg","g/L"],"n_A / (n_A + n_B)"),
 ("Normality (N) × equivalent mass =",
  ["g/L","mol/L","mol/kg","%"],"g/L"),
 ("Empirical formula represents:",
  ["Simplest whole-number ratio of atoms","Actual number of atoms","Molar mass","Structure"],"Simplest whole-number ratio of atoms"),
 ("For C₂H₄ empirical formula is:",
  ["CH₂","C₂H₄","CH","C₂H₂"],"CH₂"),
 ("Stoichiometry is based on:",
  ["Balanced chemical equation","Mass only","Volume only","Temperature"],"Balanced chemical equation"),
 ("Limiting reagent:",
  ["Consumed first, limits product","Consumed last","Excess","Catalyst"],"Consumed first, limits product"),
 ("% yield = ?",
  ["(Actual / Theoretical) × 100","Actual × Theoretical","Actual + Theoretical","100 only"],"(Actual / Theoretical) × 100"),
 ("Cathode rays are:",
  ["Electrons","Protons","Neutrons","Photons"],"Electrons"),
 ("Charge of electron:",
  ["−1.6 × 10⁻¹⁹ C","+1.6 × 10⁻¹⁹ C","0","2e"],"−1.6 × 10⁻¹⁹ C"),
 ("Mass of electron:",
  ["9.1 × 10⁻³¹ kg","1.67 × 10⁻²⁷ kg","0","1 g"],"9.1 × 10⁻³¹ kg"),
 ("Proton mass:",
  ["1.67 × 10⁻²⁷ kg","9.1 × 10⁻³¹","2.5 × 10⁻²⁷","0"],"1.67 × 10⁻²⁷ kg"),
 ("Isotopes have same Z but:",
  ["Different A","Different Z","Same A","Different charges"],"Different A"),
 ("Isobars have:",
  ["Same A, different Z","Same Z, different A","Same electrons","Same neutrons"],"Same A, different Z"),
 ("Bohr radius (n=1, H):",
  ["0.529 Å","1 Å","2 Å","0.1 Å"],"0.529 Å"),
 ("Energy of H (n=1):",
  ["−13.6 eV","+13.6 eV","0","−1.6 eV"],"−13.6 eV"),
 ("Photoelectric effect proves:",
  ["Particle nature of light","Wave nature","Neither","Both equally"],"Particle nature of light"),
 ("De Broglie wavelength:",
  ["λ = h/mv","λ = h·mv","λ = mc²","λ = nh"],"λ = h/mv"),
 ("Heisenberg uncertainty: Δx·Δp ≥",
  ["h/4π","h","h/2","1"],"h/4π"),
 ("Number of orbitals in f subshell:",
  ["7","5","3","9"],"7"),
 ("Maximum electrons in M-shell (n=3):",
  ["18","8","32","2"],"18"),
],
44: [
 ("Dobereiner proposed:",
  ["Triads","Octaves","Periodic law","Modern PT"],"Triads"),
 ("Mendeleev arranged elements by:",
  ["Atomic mass","Atomic number","Density","Size"],"Atomic mass"),
 ("Modern periodic law based on:",
  ["Atomic number","Atomic mass","Density","Valency"],"Atomic number"),
 ("Period 2 elements:",
  ["Li to Ne","H to He","Na to Ar","K to Kr"],"Li to Ne"),
 ("Group 17 is:",
  ["Halogens","Alkali","Alkaline earth","Noble gases"],"Halogens"),
 ("Atomic radius along period:",
  ["Decreases","Increases","Unchanged","Zero"],"Decreases"),
 ("IE down the group:",
  ["Decreases","Increases","Unchanged","Zero"],"Decreases"),
 ("EA along period:",
  ["Generally increases (more negative)","Always decreases","Zero","Unchanged"],"Generally increases (more negative)"),
 ("Electronegativity highest in:",
  ["F","Cl","O","N"],"F"),
 ("Most metallic element:",
  ["Cs (or Fr)","Na","Li","K"],"Cs (or Fr)"),
 ("Ionic bond formed between:",
  ["Metal and non-metal","Two metals","Two non-metals","Noble gas pair"],"Metal and non-metal"),
 ("Covalent bond formed by:",
  ["Sharing of electrons","Transfer only","Proton exchange","Metallic sea"],"Sharing of electrons"),
 ("Lattice energy of NaCl:",
  ["−787 kJ/mol (high magnitude = stable)","0","−10 kJ","+100 kJ"],"−787 kJ/mol (high magnitude = stable)"),
 ("VSEPR shape of NH₃:",
  ["Trigonal pyramidal (bond angle 107°)","Tetrahedral","T-shape","Square planar"],"Trigonal pyramidal (bond angle 107°)"),
 ("VSEPR shape of H₂O:",
  ["Bent (104.5°)","Linear","Tetrahedral","Pyramidal"],"Bent (104.5°)"),
 ("Hybridisation of C in CH₄:",
  ["sp³","sp²","sp","sp³d"],"sp³"),
 ("Hybridisation of B in BF₃:",
  ["sp²","sp³","sp","sp³d"],"sp²"),
 ("Hybridisation of S in SF₆:",
  ["sp³d²","sp³","sp³d","sp"],"sp³d²"),
 ("Bond order of O₂:",
  ["2","1","1.5","3"],"2"),
 ("Bond order of N₂:",
  ["3","2","1","0"],"3"),
 ("O₂ is:",
  ["Paramagnetic","Diamagnetic","Neither","Ionic"],"Paramagnetic"),
 ("H-bonding strongest with:",
  ["F, O, N","C, H","Metals","Noble gases"],"F, O, N"),
 ("Ice is less dense than water because:",
  ["Open H-bonded lattice","Trapped air","Lower mass","More protons"],"Open H-bonded lattice"),
 ("Fajan's rule: covalent character increases with:",
  ["Small cation, large anion, high cation charge","Large cation, small anion","Equal sizes","No effect"],"Small cation, large anion, high cation charge"),
 ("MO bond order formula:",
  ["(N_b − N_a)/2","(N_a − N_b)/2","N_b + N_a","N_b × N_a"],"(N_b − N_a)/2"),
],
45: [
 ("First law of thermodynamics:",
  ["ΔU = q + w","ΔS > 0","ΔG = 0","H = U + PV"],"ΔU = q + w"),
 ("State function example:",
  ["U, H, S, G","q","w","Path"],"U, H, S, G"),
 ("Enthalpy definition:",
  ["H = U + PV","H = q/T","H = U − TS","H = ΔG"],"H = U + PV"),
 ("Hess's law:",
  ["ΔH path-independent (sum of steps)","ΔH = q only","ΔH depends on path","ΔH zero"],"ΔH path-independent (sum of steps)"),
 ("Exothermic reaction has:",
  ["ΔH < 0","ΔH > 0","ΔH = 0","ΔG > 0"],"ΔH < 0"),
 ("Standard enthalpy of formation of element:",
  ["0 (in standard state)","Depends on compound","Always negative","Always positive"],"0 (in standard state)"),
 ("Second law expression:",
  ["ΔS_universe > 0 for spontaneous","ΔH < 0","ΔG > 0","Always ΔS = 0"],"ΔS_universe > 0 for spontaneous"),
 ("Gibbs free energy:",
  ["G = H − TS","G = U + PV","G = TS","G = q/T"],"G = H − TS"),
 ("Spontaneity criterion:",
  ["ΔG < 0","ΔG > 0","ΔG = 0","ΔH > 0"],"ΔG < 0"),
 ("At equilibrium:",
  ["ΔG = 0","ΔG < 0","ΔG > 0","q = 0"],"ΔG = 0"),
 ("ΔG° = −RT ln K (equilibrium).",
  ["True","False","Only at STP","Only for solids"],"True"),
 ("For spontaneous at all T:",
  ["ΔH < 0, ΔS > 0","ΔH > 0, ΔS < 0","ΔH > 0, ΔS > 0","ΔH < 0, ΔS < 0"],"ΔH < 0, ΔS > 0"),
 ("For non-spontaneous at all T:",
  ["ΔH > 0, ΔS < 0","ΔH < 0, ΔS > 0","ΔH > 0, ΔS > 0","ΔH < 0, ΔS < 0"],"ΔH > 0, ΔS < 0"),
 ("Kp and Kc related by:",
  ["Kp = Kc(RT)^Δn","Kp = Kc","Kp = Kc/RT","Kp = Kc×T"],"Kp = Kc(RT)^Δn"),
 ("If Q < K, reaction:",
  ["Forward direction","Reverse","At equilibrium","Stops"],"Forward direction"),
 ("Le Chatelier: increasing pressure favours:",
  ["Side with fewer moles","Side with more moles","No effect","Catalyst"],"Side with fewer moles"),
 ("Adding catalyst:",
  ["Does not change K or position of equilibrium","Shifts forward","Shifts reverse","Increases K"],"Does not change K or position of equilibrium"),
 ("pH = 3 means [H⁺] =",
  ["10⁻³ M","10⁻¹¹ M","3 M","0.3 M"],"10⁻³ M"),
 ("Ka × Kb =",
  ["Kw = 10⁻¹⁴","1","0","Kp"],"Kw = 10⁻¹⁴"),
 ("Buffer at pH = pKa when:",
  ["[A⁻] = [HA]","[A⁻] >> [HA]","[HA] >> [A⁻]","Only acid"],"[A⁻] = [HA]"),
 ("Ksp for AgCl:",
  ["s²","s³","4s³","s"],"s²"),
 ("Ksp for CaF₂:",
  ["4s³","s²","27s⁴","s"],"4s³"),
 ("Common ion effect:",
  ["Decreases solubility","Increases","No effect","Only at low T"],"Decreases solubility"),
 ("Buffer equation (Henderson-Hasselbalch):",
  ["pH = pKa + log([A⁻]/[HA])","pH = pKa","pH = Kw","pH = 7"],"pH = pKa + log([A⁻]/[HA])"),
 ("Le Chatelier for exothermic reaction: increasing T",
  ["Shifts backward (K decreases)","Shifts forward","No effect","K increases"],"Shifts backward (K decreases)"),
],
46: [
 ("Oxidation is:",
  ["Loss of electrons / increase in oxidation number","Gain of electrons","No change","Loss of protons"],"Loss of electrons / increase in oxidation number"),
 ("Reduction is:",
  ["Gain of electrons","Loss of electrons","Loss of protons","No change"],"Gain of electrons"),
 ("Oxidation number of H in NaH:",
  ["−1","+1","0","+2"],"−1"),
 ("Oxidation number of O in H₂O₂:",
  ["−1","−2","+2","0"],"−1"),
 ("Oxidation number of Mn in KMnO₄:",
  ["+7","+4","+2","+6"],"+7"),
 ("Oxidation number of Cr in K₂Cr₂O₇:",
  ["+6","+3","+7","+4"],"+6"),
 ("Oxidation number of S in H₂SO₄:",
  ["+6","+4","+2","+8"],"+6"),
 ("Oxidation number of N in HNO₃:",
  ["+5","+3","−3","+1"],"+5"),
 ("Disproportionation reaction:",
  ["Same element oxidised and reduced","Only oxidised","Only reduced","No redox"],"Same element oxidised and reduced"),
 ("Example of disproportionation:",
  ["2H₂O₂ → 2H₂O + O₂","NaCl + AgNO₃","HCl + NaOH","Zn + HCl"],"2H₂O₂ → 2H₂O + O₂"),
 ("Standard hydrogen electrode potential:",
  ["0.00 V","1.00 V","−0.76 V","0.34 V"],"0.00 V"),
 ("E° of Zn²⁺/Zn:",
  ["−0.76 V","0","+0.34 V","+0.76 V"],"−0.76 V"),
 ("E° of Cu²⁺/Cu:",
  ["+0.34 V","−0.34 V","0","+0.76"],"+0.34 V"),
 ("Daniell cell EMF:",
  ["+1.10 V","0","−1.10","+0.76"],"+1.10 V"),
 ("Galvanic cell converts:",
  ["Chemical → electrical","Electrical → chemical","Heat → electrical","Light → chemical"],"Chemical → electrical"),
 ("At anode (Galvanic cell):",
  ["Oxidation","Reduction","No reaction","Both"],"Oxidation"),
 ("At cathode (Galvanic cell):",
  ["Reduction","Oxidation","Ionisation","No reaction"],"Reduction"),
 ("Nernst equation (25°C, 1 bar):",
  ["E = E° − (0.0591/n) log Q","E = E° + RT","E = RT/nF","E = 0"],"E = E° − (0.0591/n) log Q"),
 ("ΔG° =",
  ["−nFE°","+nFE°","E°/F","F/E°"],"−nFE°"),
 ("Faraday's constant F =",
  ["96500 C/mol","6.022e23","1.6e-19","8.314"],"96500 C/mol"),
 ("Balancing redox in acidic medium uses:",
  ["H⁺ and H₂O","OH⁻ and H₂O","Only H⁺","Only H₂O"],"H⁺ and H₂O"),
 ("Balancing redox in basic medium uses:",
  ["OH⁻ and H₂O","H⁺ and H₂O","Only OH⁻","Only H₂O"],"OH⁻ and H₂O"),
 ("n-factor of KMnO₄ in acidic medium:",
  ["5","3","2","1"],"5"),
 ("n-factor of K₂Cr₂O₇ in acidic medium:",
  ["6","3","2","1"],"6"),
 ("Cell reaction Zn + Cu²⁺ → Zn²⁺ + Cu has:",
  ["ΔG° < 0, spontaneous","ΔG° > 0","ΔG° = 0","Not spontaneous"],"ΔG° < 0, spontaneous"),
],
47: [
 ("IUPAC name for (CH₃)₃CH:",
  ["2-methylpropane","isobutane (common)","Trimethylmethane","n-butane"],"2-methylpropane"),
 ("IUPAC name for CH₃CH=CHCH₃:",
  ["but-2-ene","but-1-ene","butane","but-1-yne"],"but-2-ene"),
 ("IUPAC name for CH₃-C≡C-CH₃:",
  ["but-2-yne","but-1-yne","butene","butane"],"but-2-yne"),
 ("IUPAC name for CH₃CHO:",
  ["Ethanal","Methanal","Propanal","Acetaldehyde (common)"],"Ethanal"),
 ("IUPAC name for CH₃COCH₃:",
  ["Propan-2-one","Propanone","Acetone (common)","Butanone"],"Propan-2-one"),
 ("IUPAC name for CH₃COOH:",
  ["Ethanoic acid","Methanoic acid","Propanoic acid","Acetic acid (common)"],"Ethanoic acid"),
 ("IUPAC name for CH₃OH:",
  ["Methanol","Ethanol","Methanol acid","Formaldehyde"],"Methanol"),
 ("Functional group priority (decreasing):",
  ["−COOH > −CHO > >C=O > −OH > −NH₂","−OH > −COOH","−NH₂ > −COOH","All equal"],"−COOH > −CHO > >C=O > −OH > −NH₂"),
 ("General formula of alkanes:",
  ["CₙH₂ₙ₊₂","CₙH₂ₙ","CₙH₂ₙ₋₂","CₙH₂ₙ₊₁"],"CₙH₂ₙ₊₂"),
 ("General formula of alkenes:",
  ["CₙH₂ₙ","CₙH₂ₙ₊₂","CₙH₂ₙ₋₂","CₙH₂ₙ₊₁"],"CₙH₂ₙ"),
 ("General formula of alkynes:",
  ["CₙH₂ₙ₋₂","CₙH₂ₙ","CₙH₂ₙ₊₂","CₙH₂ₙ₊₁"],"CₙH₂ₙ₋₂"),
 ("Structural isomers of C₄H₁₀:",
  ["n-butane, isobutane","1","3","4"],"n-butane, isobutane"),
 ("Chain isomers differ in:",
  ["Carbon skeleton","Position of group","Functional group","Space"],"Carbon skeleton"),
 ("Position isomers differ in:",
  ["Position of substituent","Skeleton","Functional group","Space"],"Position of substituent"),
 ("Functional isomers differ in:",
  ["Functional group (e.g., ether vs alcohol)","Skeleton only","Space only","None"],"Functional group (e.g., ether vs alcohol)"),
 ("Tautomers:",
  ["Functional isomers in rapid equilibrium (keto-enol)","Geometrical","Optical","Chain"],"Functional isomers in rapid equilibrium (keto-enol)"),
 ("Geometrical isomers require:",
  ["C=C with different groups on each C","Chiral C","Single bond rotation","Same groups"],"C=C with different groups on each C"),
 ("Optical isomers differ in:",
  ["Rotation of plane-polarised light","Boiling point","Colour","Solubility"],"Rotation of plane-polarised light"),
 ("Chiral centre:",
  ["C with 4 different groups","3 same groups","2 substituents","Any C"],"C with 4 different groups"),
 ("Meso compound is:",
  ["Optically inactive with chiral centres (internal mirror)","Chiral active","No stereocentres","Racemic"],"Optically inactive with chiral centres (internal mirror)"),
 ("Racemic mixture:",
  ["50:50 enantiomers (optically inactive)","Pure R","Pure S","Meso"],"50:50 enantiomers (optically inactive)"),
 ("Enantiomers are:",
  ["Non-superimposable mirror images","Identical","Same molecule","Geometrical"],"Non-superimposable mirror images"),
 ("Diastereomers are:",
  ["Stereoisomers, NOT mirror images","Enantiomers","Same compound","Identical"],"Stereoisomers, NOT mirror images"),
 ("Homologous series:",
  ["Same general formula, same functional group, differ by CH₂","Different formulas","Random","Different FGs"],"Same general formula, same functional group, differ by CH₂"),
 ("Free radicals are:",
  ["Species with unpaired electron","Ion with charge","Lone pair","Salt"],"Species with unpaired electron"),
],
48: [
 ("Wurtz reaction uses:",
  ["2R-X + 2Na → R-R + 2NaX","R-OH + Na","R-X + HCl","R + O₂"],"2R-X + 2Na → R-R + 2NaX"),
 ("Kolbe electrolysis gives:",
  ["Alkane from R-COONa","Alkene","Ester","Alcohol"],"Alkane from R-COONa"),
 ("Methane halogenation uses:",
  ["Free-radical chain","SN1","SN2","E1"],"Free-radical chain"),
 ("Markovnikov's rule applies to:",
  ["HX addition to unsymmetrical alkene","Alkane halogenation","Alkyne polymerisation","Benzene"],"HX addition to unsymmetrical alkene"),
 ("Peroxide effect gives:",
  ["Anti-Markovnikov product with HBr","Markovnikov","No product","Alkane"],"Anti-Markovnikov product with HBr"),
 ("Baeyer's reagent for alkene:",
  ["Cold dilute alkaline KMnO₄","Conc. H₂SO₄","HCl","NaOH"],"Cold dilute alkaline KMnO₄"),
 ("Alkene + cold dilute KMnO₄ gives:",
  ["cis-diol","Aldehyde","Ketone","Carboxylic acid"],"cis-diol"),
 ("Alkene + hot KMnO₄ gives:",
  ["Carboxylic acids (cleavage)","Diol","Alcohol","Ether"],"Carboxylic acids (cleavage)"),
 ("Ozonolysis of alkene (Zn/H₂O) gives:",
  ["Aldehydes/ketones","Carboxylic acids","Alcohols","Ethers"],"Aldehydes/ketones"),
 ("Ozonolysis of alkyne (Zn/H₂O) gives:",
  ["Carboxylic acids","Aldehydes","Alcohols","Ethers"],"Carboxylic acids"),
 ("Acidic hydrogen in alkyne:",
  ["Terminal ≡C-H","Internal CH","Any CH","CH₂"],"Terminal ≡C-H"),
 ("Tollens test identifies:",
  ["Terminal alkyne (silver acetylide white ppt)","Alkene","Alcohol","Ether"],"Terminal alkyne (silver acetylide white ppt)"),
 ("Lindlar's catalyst gives:",
  ["Cis-alkene from alkyne","Trans-alkene","Alkane","No reaction"],"Cis-alkene from alkyne"),
 ("Na/liq NH₃ reduction of alkyne gives:",
  ["Trans-alkene","Cis-alkene","Alkane","Carboxylic acid"],"Trans-alkene"),
 ("Benzene molecular formula:",
  ["C₆H₆","C₆H₁₂","C₆H₁₀","C₆H₁₄"],"C₆H₆"),
 ("Benzene is:",
  ["Aromatic, planar, 6 delocalised π-e⁻","Aliphatic","Cyclic saturated","Amorphous"],"Aromatic, planar, 6 delocalised π-e⁻"),
 ("EAS electrophile for nitration:",
  ["NO₂⁺","NO⁻","HNO₂","Cl⁺"],"NO₂⁺"),
 ("EAS electrophile for sulphonation:",
  ["SO₃/HSO₃⁺","SO₂","SO₄²⁻","H⁺"],"SO₃/HSO₃⁺"),
 ("Friedel-Crafts alkylation uses:",
  ["R-X + AlCl₃","R-OH","R-NH₂","R + Na"],"R-X + AlCl₃"),
 ("Friedel-Crafts acylation uses:",
  ["RCOCl + AlCl₃","R-X + Na","RCOOH","Mg"],"RCOCl + AlCl₃"),
 ("Activating group is:",
  ["−OH (o/p directing)","−NO₂","−CN","−SO₃H"],"−OH (o/p directing)"),
 ("Deactivating group is:",
  ["−NO₂ (m directing)","−CH₃","−OH","−OR"],"−NO₂ (m directing)"),
 ("Carcinogenic polycyclic aromatic:",
  ["Benzo[a]pyrene","Benzene only","Toluene","Naphthalene only"],"Benzo[a]pyrene"),
 ("Octane number of iso-octane:",
  ["100","0","50","200"],"100"),
 ("Petrol is a mixture of:",
  ["C5-C12 hydrocarbons","Only methane","Only benzene","Only alkynes"],"C5-C12 hydrocarbons"),
],
49: [
 ("At STP (0°C, 1 atm), 1 mole gas occupies:",
  ["22.4 L","24.79 L","10 L","100 L"],"22.4 L"),
 ("Ideal gas equation:",
  ["PV = nRT","PV = RT","P/V = nRT","PT = nRV"],"PV = nRT"),
 ("Dalton's law of partial pressures:",
  ["P_total = ΣP_i","P_total = P₁·P₂","P_total = 0","P_total = R·T"],"P_total = ΣP_i"),
 ("Graham's law:",
  ["Rate ∝ 1/√M","Rate ∝ M","Rate ∝ √M","Rate ∝ 1/M²"],"Rate ∝ 1/√M"),
 ("u_rms =",
  ["√(3RT/M)","√(2RT/M)","√(8RT/πM)","√(RT/M)"],"√(3RT/M)"),
 ("u_mp =",
  ["√(2RT/M)","√(3RT/M)","√(8RT/πM)","RT/M"],"√(2RT/M)"),
 ("Van der Waals equation:",
  ["(P + an²/V²)(V − nb) = nRT","PV = nRT","P + V = nRT","PV = 0"],"(P + an²/V²)(V − nb) = nRT"),
 ("'a' constant in vdW represents:",
  ["IMF","Molecular volume","T","P"],"IMF"),
 ("Z = PV/nRT; Z=1 for:",
  ["Ideal gas","All gases","Only H₂","Only noble gases"],"Ideal gas"),
 ("Critical T of CO₂:",
  ["31.1°C","0°C","100°C","−273°C"],"31.1°C"),
 ("Vapour pressure of liquid increases with:",
  ["T","Volume","Amount","Area"],"T"),
 ("Boiling point of water at sea level:",
  ["100°C","0°C","25°C","50°C"],"100°C"),
 ("Surface tension of water (20°C):",
  ["72.8 mN/m","100","10","1"],"72.8 mN/m"),
 ("Viscosity of liquids with T:",
  ["Decreases","Increases","Unchanged","Zero"],"Decreases"),
 ("Density of water max at:",
  ["4°C","0°C","100°C","25°C"],"4°C"),
 ("Isotopes of H:",
  ["¹H, ²H, ³H","¹H only","²H only","³H only"],"¹H, ²H, ³H"),
 ("Water gas:",
  ["CO + H₂","CO + N₂","CO₂ + H₂","CH₄ + H₂"],"CO + H₂"),
 ("Hardness due to:",
  ["Ca²⁺, Mg²⁺","Na⁺","K⁺","Cl⁻"],"Ca²⁺, Mg²⁺"),
 ("H₂O₂ is:",
  ["Oxidising and reducing","Only oxidising","Only reducing","Inert"],"Oxidising and reducing"),
 ("H₂O₂ stored in:",
  ["Wax-lined dark bottles","Clear sun","Metal","Open"],"Wax-lined dark bottles"),
 ("Heavy water (D₂O) used as:",
  ["Moderator in nuclear reactors","Fuel","Coolant only","Electrolyte"],"Moderator in nuclear reactors"),
 ("Permanent hardness removed by:",
  ["Ion-exchange / washing soda","Boiling","Filtration","Adding CaCl₂"],"Ion-exchange / washing soda"),
 ("Temporary hardness removed by:",
  ["Boiling","Ion-exchange","Adding CaCl₂","Filtering"],"Boiling"),
 ("Ionic hydrides formed by:",
  ["s-block (except Be, Mg)","Non-metals","Noble gases","Halogens"],"s-block (except Be, Mg)"),
 ("BOD means:",
  ["Biochemical oxygen demand","Biological overall density","Biotic oxygen drop","None"],"Biochemical oxygen demand"),
],
50: [
 ("Group 1 e⁻ config:",
  ["ns¹","ns²","ns²np¹","ns²np⁵"],"ns¹"),
 ("Group 2 e⁻ config:",
  ["ns²","ns¹","ns²np¹","ns²np²"],"ns²"),
 ("Flame colour of Na:",
  ["Yellow","Red","Violet","Blue"],"Yellow"),
 ("Flame colour of K:",
  ["Violet","Yellow","Red","Green"],"Violet"),
 ("Flame colour of Ca:",
  ["Brick red","Yellow","Violet","Green"],"Brick red"),
 ("Flame colour of Ba:",
  ["Apple green","Red","Yellow","Blue"],"Apple green"),
 ("Diagonal relationship:",
  ["Li↔Mg, Be↔Al","Na↔Mg","K↔Ca","Cs↔Ba"],"Li↔Mg, Be↔Al"),
 ("Alkali metals stored in:",
  ["Kerosene","Water","Alcohol","Air"],"Kerosene"),
 ("Alkali metals + H₂O:",
  ["MOH + H₂","MO + H₂","No reaction","M₂O + H₂"],"MOH + H₂"),
 ("Solvay process produces:",
  ["Na₂CO₃","NaOH","NaCl","KNO₃"],"Na₂CO₃"),
 ("Quicklime:",
  ["CaO","Ca(OH)₂","CaCO₃","CaSO₄"],"CaO"),
 ("Slaked lime:",
  ["Ca(OH)₂","CaO","CaCO₃","CaSO₄"],"Ca(OH)₂"),
 ("Plaster of Paris:",
  ["CaSO₄·½H₂O","CaSO₄·2H₂O","CaSO₄","CaO"],"CaSO₄·½H₂O"),
 ("Gypsum:",
  ["CaSO₄·2H₂O","CaSO₄·½H₂O","CaSO₄","CaO"],"CaSO₄·2H₂O"),
 ("Limestone:",
  ["CaCO₃","CaSO₄","CaCl₂","Ca(OH)₂"],"CaCO₃"),
 ("Boron family:",
  ["Group 13","Group 14","Group 15","Group 16"],"Group 13"),
 ("Most abundant metal in earth's crust:",
  ["Al","Fe","Na","K"],"Al"),
 ("Bauxite ore of:",
  ["Al","Fe","Cu","Zn"],"Al"),
 ("Hall-Héroult process:",
  ["Electrolysis of Al₂O₃ in molten cryolite","Smelting of Al","Bessemer process","Reduction with C"],"Electrolysis of Al₂O₃ in molten cryolite"),
 ("Cryolite:",
  ["Na₃AlF₆","AlF₃","Al₂O₃","AlCl₃"],"Na₃AlF₆"),
 ("B₂H₆ (diborane) has:",
  ["3c-2e bridge bonds","Normal covalent","Ionic","Metallic"],"3c-2e bridge bonds"),
 ("Borax formula:",
  ["Na₂B₄O₇·10H₂O","NaBO₂","B(OH)₃","BF₃"],"Na₂B₄O₇·10H₂O"),
 ("Graphite conducts due to:",
  ["Delocalised π-electrons","Ionic bonds","Free protons","H-bonds"],"Delocalised π-electrons"),
 ("Diamond has hybridisation:",
  ["sp³","sp²","sp","sp³d"],"sp³"),
 ("Silicones are:",
  ["Organosilicon polymers","Pure Si","Silicates","Carbides"],"Organosilicon polymers"),
],
51: [
 ("5 g of NaOH in 500 mL solution; molarity:",
  ["0.25 M","0.5","0.125","1"],"0.25 M"),
 ("Moles in 44 g CO₂:",
  ["1 mol","2","0.5","10"],"1 mol"),
 ("Mass of 0.5 mol H₂O:",
  ["9 g","18","36","4.5"],"9 g"),
 ("Molecules in 2 mol O₂:",
  ["1.2044×10²⁴","6.022×10²³","3.011×10²³","1.2×10²³"],"1.2044×10²⁴"),
 ("Volume of 2 mol CO₂ at STP:",
  ["44.8 L","22.4","11.2","67.2"],"44.8 L"),
 ("pH of 0.01 M HCl:",
  ["2","1","12","14"],"2"),
 ("pH of 0.01 M NaOH:",
  ["12","2","14","7"],"12"),
 ("[H⁺] in solution of pH 3:",
  ["10⁻³ M","10⁻¹¹","10⁻⁷","3"],"10⁻³ M"),
 ("Ka of acid (Ka=10⁻⁵) and 0.1M acid, [H⁺] ≈",
  ["10⁻³ M","10⁻⁵","0.1","10⁻⁷"],"10⁻³ M"),
 ("Ksp of AgCl = 1.8×10⁻¹⁰; solubility:",
  ["~1.34×10⁻⁵ M","1.8×10⁻¹⁰","1×10⁻⁵","10⁻⁷"],"~1.34×10⁻⁵ M"),
 ("ΔH = −100 kJ, ΔS = −200 J/K at 300 K; ΔG:",
  ["−40 kJ","−100","+40","0"],"−40 kJ"),
 ("Bond energy: H-Cl 431, H-H 436, Cl-Cl 242 kJ/mol; ΔH of H₂+Cl₂→2HCl:",
  ["−184 kJ","+184","−92","+92"],"−184 kJ"),
 ("2 mol ideal gas at 300 K, 2 atm; V:",
  ["24.6 L","12.3","49.2","22.4"],"24.6 L"),
 ("Kc = 4 for A⇌B at T; at equilibrium [A]=0.5, [B]:",
  ["2","0.125","4","0.5"],"2"),
 ("Half-life of first-order reaction with k=0.1/s:",
  ["6.93 s","10 s","0.1","100"],"6.93 s"),
 ("Enthalpy of neutralisation of strong acid + strong base:",
  ["−57.1 kJ/mol","−100","0","+57.1"],"−57.1 kJ/mol"),
 ("Equivalent mass of H₂SO₄:",
  ["49","98","196","24.5"],"49"),
 ("n-factor of KMnO₄ in acidic medium:",
  ["5","3","2","1"],"5"),
 ("1 mole electron = charge:",
  ["96500 C (1 F)","6.022e23 C","1 C","10 C"],"96500 C (1 F)"),
 ("Atoms in 24 g Mg (M=24):",
  ["6.022×10²³","1.2×10²⁴","3×10²³","2×10²³"],"6.022×10²³"),
 ("Molality of 1 m NaCl in 1 kg water means:",
  ["1 mol NaCl per kg water","1 mol per L","1 g per L","1 mol per mol"],"1 mol NaCl per kg water"),
 ("% by mass of NaCl in 5 g NaCl + 95 g water:",
  ["5%","95%","10%","1%"],"5%"),
 ("Normality of 0.5 M H₂SO₄:",
  ["1 N","0.25","0.5","2"],"1 N"),
 ("Mole fraction of water in 18 g H₂O + 46 g C₂H₅OH:",
  ["0.5","0.25","1","0.75"],"0.5"),
 ("For reaction 2A+B→C, if rate=k[A]²[B], order is:",
  ["3","2","1","0"],"3"),
],
52: [
 ("Most electronegative element:",
  ["F","Cl","O","N"],"F"),
 ("Bond order of O₂:",
  ["2","3","1","0"],"2"),
 ("O₂ molecular magnetism:",
  ["Paramagnetic","Diamagnetic","Ferromagnetic","Non-magnetic"],"Paramagnetic"),
 ("Hybridisation of C in diamond:",
  ["sp³","sp²","sp","sp³d"],"sp³"),
 ("Hybridisation of C in graphite:",
  ["sp²","sp³","sp","sp³d"],"sp²"),
 ("pH of pure water at 25°C:",
  ["7","0","14","1"],"7"),
 ("At equilibrium ΔG =",
  ["0","<0",">0","∞"],"0"),
 ("Standard enthalpy of formation of element:",
  ["0","Depends","Always negative","Always positive"],"0"),
 ("Ideal gas: molar volume at STP:",
  ["22.4 L","24","10","100"],"22.4 L"),
 ("Avogadro number:",
  ["6.022×10²³","10²³","10²⁴","6×10¹⁰"],"6.022×10²³"),
 ("Catalyst changes:",
  ["Rate, not equilibrium position","Equilibrium position","Only ΔH","Only K"],"Rate, not equilibrium position"),
 ("Increasing T for exothermic forward reaction:",
  ["K decreases, shifts backward","K increases","No effect","Shifts forward"],"K decreases, shifts backward"),
 ("Redox agent that itself reduces:",
  ["Reducing agent","Oxidising","Amphoteric","Catalyst"],"Reducing agent"),
 ("Na + H₂O gives:",
  ["NaOH + H₂","Na₂O + H₂","Na + OH","No reaction"],"NaOH + H₂"),
 ("Mg + N₂ gives:",
  ["Mg₃N₂","MgN","MgN₃","No reaction"],"Mg₃N₂"),
 ("Solvay process produces:",
  ["Na₂CO₃","NaOH","NaCl","KNO₃"],"Na₂CO₃"),
 ("Hall-Héroult process extracts:",
  ["Al","Cu","Fe","Na"],"Al"),
 ("Alkyne acidity is due to:",
  ["sp hybridised C-H","sp³","sp²","sp³d"],"sp hybridised C-H"),
 ("Markovnikov product of HBr + propene:",
  ["2-bromopropane","1-bromopropane","1,2-dibromopropane","propanol"],"2-bromopropane"),
 ("Benzene nitration electrophile:",
  ["NO₂⁺","NO₃⁻","HNO₂","NO"],"NO₂⁺"),
 ("H-bonding strongest in:",
  ["HF","HCl","HBr","HI"],"HF"),
 ("Most stable carbocation:",
  ["3° > 2° > 1° > CH₃⁺","CH₃⁺ > 1° > 2° > 3°","1° > CH₃⁺","All equal"],"3° > 2° > 1° > CH₃⁺"),
 ("Diamond conducts:",
  ["Heat only","Electricity only","Both","Neither"],"Heat only"),
 ("Graphite conducts:",
  ["Both heat and electricity","Heat only","Electricity only","Neither"],"Both heat and electricity"),
 ("Al₂O₃ nature:",
  ["Amphoteric","Only acidic","Only basic","Neutral"],"Amphoteric"),
],
}

def main():
    d=json.loads(PATH.read_text())
    total=0
    for wk,qs in QS.items():
        assert len(qs)==25, f"wk{wk}: {len(qs)}"
        week=next(w for w in d["11"] if w["week"]==wk)
        new=[]
        for i,(q,opts,ans) in enumerate(qs,1):
            assert len(opts)==4
            assert ans in opts, f"wk{wk} Q{i}"
            new.append({"id":i,"question":q,"options":opts,"answer":ans})
        week["questions"]=new
        total+=len(qs)
    PATH.write_text(json.dumps(d,indent=2,ensure_ascii=False)+"\n")
    print(f"Replaced {total} chemistry/11 placeholder questions across {len(QS)} weeks: {sorted(QS.keys())}")

if __name__=="__main__":
    main()
